### ISSUE TITLE
Future plans for mobile

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#1]
Just to sum up the discussion we had via email on the plans for mobile:

We do it step by step:
1. [x] Server app should be responsive and work on mobile (we need this anyway for share links)
2. [x] Integration into mobile app via webview
3. [x] (Possible desktop integration via webview)
4. [ ] Estimate native mobile integration, maybe something with the Android Notes app?
5. [ ] (Possibility to join shared documents without an account via the app, similar to proposal for Talk: https://github.com/nextcloud/talk-android/issues/261 – only makes sense once there is native mobile integration)

cc @rullzer @tobiasKaminsky @juliushaertl

**Comment by jancborchardt** [comment]
Point 1 is basically done since it indeed works nicely on mobile – further improvements at **Viewer enhancements #82** 

For more native integration, is this something which could be doable with the Android Notes app by @stefan-niedermann and the iOS Notes app by @phedlund? :)

**Comment by tobiasKaminsky** [comment]
It should also be default edit option in Nextcloud Files if text is not downloaded, same like office documents (opened via collabora) is done.

**Comment by tobiasKaminsky** [comment]
We are testing this right now :)

**Comment by jancborchardt** [comment]
@tobiasKaminsky yep, and that's why it's good we went with the editor embed getting the full screen – that's the way to go here too. :)

**Comment by tobiasKaminsky** [comment]
Ref: https://github.com/nextcloud/server/issues/16132

**Comment by tobiasKaminsky** [comment]
Shut up, bot ;-)

**Comment by brainchild0** [comment]
> Estimate native mobile integration, maybe something with the Android Notes app?

Does this item mean trying to unify the editing experience for notes, compared with files from regular client application?

**Comment by stefan-niedermann** [comment]
> Does this item mean trying to unify the editing experience for notes, compared with files from regular client application?

This is a possible future. If text is performant enough for 10k-character texts on smartphones and [provides a good user experience](https://github.com/nextcloud/text/issues/819) i will consider to use text as editor for the Android Notes app.


There are also [plans to consider it's usage in the Deck Android App](https://github.com/stefan-niedermann/nextcloud-deck/issues/452) (which i would prefer as a test balloon before including text into Notes).

@brainchild0 maybe you are interested in contributing there? 🙂 🚀

**Comment by brainchild0** [comment]
@stefan-niedermann: Thanks for the information. In fact, my question was more general in scope. I was not specifically suggesting that Notes mobile open the Text web application, only that some overall user experience apply equally in the case of notes and files. 

Issue nextcloud/android#126 points to the need for some means of editing offline (even if with an external editor), and then uploading asynchronously.  

As it seems that currently it is not planned to merge the offline and collaborative pathways, it would seem that support for both is needed.  

(I can't help but to ask how hard it would be to run the text app from an offline instance included in the mobile app, which could operate with or without a server connection.)

**Comment by max-nextcloud** [comment]
@jancborchardt, @juliushaertl I'm tempted to close this issue:
We do have the first three steps plus a webview implementation that's working pretty well.
The next step from my point of view would be a native android / ios app. And from my point of view that's an entirely different project. We might be able to reuse code etc. But I don't see this as part of this repository.

What do you say?
