### ISSUE TITLE
Store last_contact in memcache

### ISSUE THREAD

**Issue by rullzer** [nextcloud/text#1005]
I noticed on some systems people keep text files open all the time. Hence there is a lot of traffic to the session table. Because we keep updating the last contact timestamp.

If we have a memcache available we should utilize this to store the last contact time. That way we could reduce the write load of the system quite a bit.

@juliushaertl as discussed.

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/text/pull/1026/files
