### ISSUE TITLE
Not possible to edit .md files as simple text files anymore

### ISSUE THREAD

**Issue by StCyr** [nextcloud/text#1028]
**Describe the bug**
Workarounds described in https://github.com/nextcloud/text/issues/439 to edit .md files as simple text files don't seem to work anymore with NC20.

Plain text editor app seems incompatible with NC20 (despite https://github.com/nextcloud/text/issues/939). However, I could simply not download it anymore due to a deprecated certificate

As others point out already, this is needed to create websites using the Pico SMS app.

**Expected behavior**
There should always be a way to edit files as regular text files, without having nextcloud attempt to format them.

**Text app version:** (see Nextcloud apps page)
3.1.0

**Nextcloud version:** (see Nextcloud admin page)
NC20beta2

**Comment by StCyr** [comment]
Ok, I've succeeded installing the Plain Text Editor manualy (git clone in the app folder) but I don't see how to make all those things (Text, Plain Text Editor, Mardown Editor) work together?!?

**Comment by juliushaertl** [comment]
I'll do another release of files_texteditor for 20 soonish.

> I don't see how to make all those things (Text, Plain Text Editor, Mardown Editor) work together?!? 

Well if both are installed then you can open files with the plain text editor with right click or though the actions menu.

Closing since it is not a text app issue.
