### ISSUE TITLE
Bracket parentheses escaped with backslashes

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#103]
Because I need the Markdown file in plaintext, I download it / open it in files_texteditor. Since I used the `[ ]` syntax for checkboxes to use on Github, I’m facing this issue:

Shows correctly:
![checkbox formatting](https://user-images.githubusercontent.com/925062/60116565-94cf6400-9778-11e9-9030-2b5ca8da7717.png)

In the text the brackets are backslash escaped:
```
## 👩‍🏭 Installation

* \[ \] Finish button not visible on some screens – possibly sticky, or make warning wider

* \[ \] **Missing loading feedback on installation, should have a spinner**
```

**Comment by juliushaertl** [comment]
I'll look into a hotfix for this for 1.0.1 and as we will implement checkbox support properly with #110

**Comment by ainola** [comment]
I'm experiencing this issue on 1.1.0, though only with certain lines.

The following lines will all trigger the bug:

```
Asdf [asdf asdf](asdf asdf) asdf asdf asdf asdf asdf asdf asdf asdf asdf)

* [asdf asdf asdf/asdf](Asdf Asdf)

* asdf asdf asdf [a--f asdf asdf](a--f Asdf Asdf)

* [Asdf asdf asdf asdf asdf asdf](Asdf asdf)
```

I saved this locally on my machine (vimwiki), opened it up in Text, changed a char, closed, then reloaded in vim. All brackets had escape chars.

**Comment by juliushaertl** [comment]
@ainola Thanks for providing an example. I've moved this to a new issue #325
