### ISSUE TITLE
Checkmark icon is missing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#1033]
![image](https://user-images.githubusercontent.com/3404133/92568556-a0c11c00-f27f-11ea-9e4c-ff0a06ea26e6.png)

**Comment by juliushaertl** [comment]
Works fine it seems

**Comment by VanguardAX1** [comment]
I come with a similar problem with v22. In my situation every icon in that line (**except** the icon-checkmark) is missing.
Their `data:image/svg+xml;base64` codes not in `icons-vars.css` file.
