### ISSUE TITLE
NC 19 release not shown in Appstore

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/text#1063]
Hello,
I am confused. Will this app work in Nextcloud 19?

Appstore says no, latest release is for nc 18 https://apps.nextcloud.com/apps/text

Releases - last is v1.0.2 which was released 12 Aug 2019 https://github.com/nextcloud/text/releases/tag/v1.0.2

But in milestones it looks like  NC 19 is supported 
https://github.com/nextcloud/text/milestones?state=closed

I am very worried about updates breaking basic functionality since the photos app has been abandoned and many users didnt know, and downgrade is not possible.

Thanks.

**Comment by juliushaertl** [comment]
The app is released as part of the main server release.

**Comment by alexanderdd** [comment]
> The app is released as part of the main server release.

@juliushaertl can you adjust this page https://apps.nextcloud.com/apps/text so it reflects this?

**Comment by juliushaertl** [comment]
Yes, makes sense. I'll see if we can just remove it from the app store then.
