### ISSUE TITLE
Add support for Wiki links

### ISSUE THREAD

**Issue by Nebucatnetzer** [nextcloud/text#1065]
There a currently a lot of note taking applications getting made which are inspired by the Zettelkasten method.
A lot of those apps started adopting the wiki link format to link notes together. `[[Note Name]]`
I'm currently using Obsidian.md on the desktop to work with my notes but on the go I'm using Nextcloud Notes.
Therefore I have a lot of notes with links to each other but the links aren't working in the Android application or the web application.
Nextcloud Notes plans to use Nextcloud Text in the future and because of that it would make more sense to implement this feature directly in Nextcloud Text.

Describe the solution you'd like
Add support for the Wiki link, link format. So that one can use:
`[[Note Name]]` to link to a file
and
`[[Note Name#Heading]]` to link to a heading.

I originally reported this feature request in the Nextcloud Notes app.
https://github.com/nextcloud/notes/issues/616

**Comment by DarkknightAK** [comment]
With NC 20 easier link's to files are added, but compare to the suggestion here you need the filedId so for example:
[User Manual](/Nextcloud%20Manual.pdf?fileId=5945777)

move the file somewhere else didn't work (should work, cause the fileId didn't change). Move to an specific #Heading would be awesome (didn't work for now).

**Comment by Nebucatnetzer** [comment]
The links need to be in Wiki format otherwise they wouldn't work with the other applications.
In Obsidian they usually link to a file in the same directory.

**Comment by juliushaertl** [comment]
Are there any other markdown apps that support this? I'm not aware of anythink like `[[FileName]]` being part of any markdown semi-standard.

**Comment by spitlo** [comment]
On macos, [nvAlt](https://brettterpstra.com/projects/nvalt/) and the upcoming [nvUltra](https://nvultra.com/) supports it. And as mentioned, use of this type of link is also widespread in the [Zettelkasten](https://zettelkasten.de/) community.

There is some more context in this closed issue in the repo for the NC Notes Android app:
https://github.com/stefan-niedermann/nextcloud-notes/issues/954

**Comment by Nebucatnetzer** [comment]
[Zettlr](https://www.zettlr.com/) supports it as well.

**Comment by Nebucatnetzer** [comment]
And there is an issue open at the [Marktext](https://marktext.app/) repository https://github.com/marktext/marktext/issues/2329

**Comment by juliushaertl** [comment]
I'm still a bit hesitant of adding such markdown features that are not part of commonmark or a standardized extension, especially when they are not supported by a major chunk of markdown editors. Therefore I'll close this for now. Whenever this becomes more widely adopted we can re-evaluate.

**Comment by Nebucatnetzer** [comment]
I'm sad to see this go as I think it would have been an innovative feature.
But I understand that you don't want to support exotic features.

**Comment by xplosionmind** [comment]
If I may, I'd like to support the wiki-like links implementation. To me, it's the main and fundamental way of linking notes. I believe that right now it may be a quite unpopular feature, but I read on every single forum of Markdown apps which don't currently support it (such as [Joplin](https://joplinapp.org) and [Typora](https://typora.io)) that soon they'll implement it. It's the future of internal linking, and I believe starting to develop it now would make Nextcloud Text cutting edge in the near future

**Comment by einalex** [comment]
@juliushaertl this could be implemented using the "link" feature of the commonmark specification https://spec.commonmark.org/0.29/#links.
the link destination is a URI, so one could use relative references as the URI https://pretty-rfc.herokuapp.com/RFC3986#relative-ref
In practice this would look like this: (NoteTitle)[Category/NoteTitle] or this [Category/NoteTitle] (Github does this for example)
One downside is that it would add some computational overhead when moving a note from one category to another. One would have to update all the references.
