### ISSUE TITLE
text app makes integrity check fail

### ISSUE THREAD

**Issue by s0ftcorn** [nextcloud/text#1067]
Going to the adminoverview to update Nextcloud 16 to 17 and i see a failed integrity check. Caused by the text-plugin.
Seems like the whole repository got copied though i am not sure what i can delete and what not.

<details>
<summary>Server details</summary>

**Text app version:** 1.1.1

**Operating system:** Ubuntu 18.04.05

**Web server:** Apache 2.4.29

**Database:** mariadb 1:10.1.44

**PHP version:** php7.2

**Nextcloud version:** Nextcloud 17.0.9

</details>

<details>
<summary>Logs</summary>
[nc16integrity.txt](https://github.com/nextcloud/text/files/5307410/nc16integrity.txt)

</details>

**Comment by a4bits** [comment]
more details
seems like path 
`/index.php/apps/text/session/create?fileId=<ID>&filePath=<FILE>&guestName=null&forceRecreate=false`
either takes very long to load or comes out with error

`"An exception occurred while executing 'INSERT INTO `oc_text_documents` (`id`, `last_saved_version_time`, `last_saved_version_etag`, `base_version_etag`) VALUES(?, ?, ?, ?)' with params [<ID>, 1601478775, \"be32176e6f31380889fc6f9462c2422e\", \"be32176e6f31380889fc6f9462c2422e\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<ID>' for key 'PRIMARY'"`

**Comment by juliushaertl** [comment]
Maybe there was something wrong with the update, for a clean install of the text app you can remove the text folder in your app directory and copy the fresh one from the 17.0.9 server bundle.

**Comment by s0ftcorn** [comment]
this will remove all user data, right?

**Comment by juliushaertl** [comment]
No, if you just replace the text app directory it will only update the code that is used to run the app.

**Comment by gityeti** [comment]
Same problem. Update from 17.0.8 to 17.0.10. Integrity check error with text:

> Technical information
> 
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> 
> - text
> 	- EXTRA_FILE
> 		- l10n/br.json
> 		- l10n/br.js

So I removed text in nextcloud/apps folder and installed the last release
https://github.com/nextcloud/text/releases/tag/v1.0.2

But integrity check error for text remains the same.

**Comment by s0ftcorn** [comment]
Think you need to use the release shipped with your nextcloud version. I did that and the integrity check succeded.

**Comment by juliushaertl** [comment]
Yes, pleased use the one from the server tarball. We also removed the old releases now from the app store to avoid confusion.
