### ISSUE TITLE
loading file with error

### ISSUE THREAD

**Issue by a4bits** [nextcloud/text#1069]
**Bug**
Sometimes when I open text file it opens quickly, but sometimes it opens very slow or not at all - gets blocked loading with error from console:

`/index.php/apps/text/session/create?fileId=<ID>&filePath=<FILE>&guestName=null&forceRecreate=false`
`
"An exception occurred while executing 'INSERT INTO oc_text_documents (id, last_saved_version_time, last_saved_version_etag, base_version_etag) VALUES(?, ?, ?, ?)' with params [<ID>, 1601478775, \"be32176e6f31380889fc6f9462c2422e\", \"be32176e6f31380889fc6f9462c2422e\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<ID>' for key 'PRIMARY'"`

of course <ID> and <FILE> are placement here :-)

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 81
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:**
3.0.1

**Operating system:**
Debian Linux 10

**Web server:**
Apache 2.4.38

**Database:**
MariaDB 10.3.23

**PHP version:**
 7.4.10

**Nextcloud version:** 
19.0.3
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log 
empty, no errors reported there... (?!)

#### Browser log
![image](https://user-images.githubusercontent.com/40560367/94807803-73840b80-03f0-11eb-9327-a71bbdf15cd3.png)
![image](https://user-images.githubusercontent.com/40560367/94808248-1e94c500-03f1-11eb-8c78-2939227262b7.png)

and sometimes it goes good but with very long wait
![image](https://user-images.githubusercontent.com/40560367/94815366-bc40c200-03fa-11eb-9a9c-f80730bb6f75.png)

</details>

**Comment by juliushaertl** [comment]
We might need some more sane handling in case the file operation is blocked for longer due to reasons like the antivirus scanning.

**Comment by juliushaertl** [comment]
We improved the error behavior quite a bit in the meantime and this also seems to be the only report, so closing this, but feel free to comment if this still is an issue for anyone.
