### ISSUE TITLE
Outline view of headings for quick navigation (table of contents)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#107]
Here’s some examples of how other apps use headings to automatically create an outline for quick navigation. This is always shown on the left and we could do that too.

## Dropbox Paper
Very nicely designed, non-obtrusive by default, with h1 and h2 levels highlighted on the left:
https://blog.dropbox.com/topics/product-tips/paper-hidden-gems
![dropbox](https://user-images.githubusercontent.com/925062/60253644-ca856180-98cc-11e9-8b5d-48bb86029fb9.gif)

--------------------

## Google Drive
h1 and h2 are shown normally, and it seems starting with h3 they are indented:
![google docs outline](https://user-images.githubusercontent.com/925062/60253643-ca856180-98cc-11e9-9778-0df7fb147367.jpg)

--------------------

## [FoldingText](http://www.foldingtext.com/)
![foldingtext outline](https://user-images.githubusercontent.com/925062/60253645-ca856180-98cc-11e9-8f49-536f1553763c.png)

**Comment by thorsten-panknin** [comment]
I was just looking around for an issue mentioning a better overview of headlines and stumbled over this. Great idea!

**Comment by feutl** [comment]
like this too!

**Comment by b3** [comment]
Any idea if this still considered and how one can try to help?

**Comment by biva** [comment]
This idea would be great and would make the Collectives app even better!

As a complement (or maybe it would be a workaround?), it would be great to make sections collapsible (https://github.com/nextcloud/text/issues/1841)

**Comment by rinurinu** [comment]
I would love seeing this feature implemented. I use nextcloud text a lot and this would help declutter long notes.

**Comment by rotdrop** [comment]
We can actually add any mature Wiki-Software to the list of apps which have this feature, including Gitlab markdown-pages and perhaps Github. Comparison with Wiki-Software is perhaps a bit unfair if we look at the text-app alone. However, as the Nextcloud-Wiki app, which calls itself "collectives", is using "text"-app as backend it seems that many features yet missing from the collectives can only be implemented if they are also present in the text app. Besides TOC and general inter-page links (links to headings in the same document and to headings in other documents) also foot-notes come into my mind.

**Comment by b3** [comment]
Comparison with wiki may be unfair, but comparison with other collaborative editing tools may not be that unfair.
This features (TOC visibility and direct access to section through it) is a very common and almost essential features of any collaborative editing tool such as [Hedgedoc](https://hedgedoc.org), OnlyOffice or Collabora Online.

As I said I really think this feature is a must-be and I would like to help it exist.

Any idea where to begin?

**Comment by rotdrop** [comment]
> Comparison with wiki may be unfair, but comparison with other collaborative editing tools may not be that unfair. This features (TOC visibility and direct access to section through it) is a very common and almost essential features of any collaborative editing tool such as [Hedgedoc](https://hedgedoc.org), OnlyOffice or Collabora Online.

I also would very much like to have such a feature. I like the integration of kind-of-a-wiki into Nextcloud, and of course also the collaborative features. It is little bit sad that inter-page linking is not yet implemented.

I wonder if it would maybe easier to start with linking to headings inside pages and build the automatic TOC on top of that? Clearly the TOC wants to link to the headings in the document, so it needs support for hyper-links pointing to anchors in the same document. If these inside-page links are there (including of course that the editor jumps to the linked-to heading) then building the top would just be a matter of parsing the document and collecting the headings.

I am not involved in the development of "text", so I do not really no where to start.

**Comment by rotdrop** [comment]
> Comparison with wiki may be unfair, but comparison with other collaborative editing tools may not be that unfair. This features (TOC visibility and direct access to section through it) is a very common and almost essential features of any collaborative editing tool such as [Hedgedoc](https://hedgedoc.org), OnlyOffice or Collabora Online.

I also would very much like to have such a feature. I like the integration of kind-of-a-wiki into Nextcloud, and of course also the collaborative features. It is little bit sad that intra-page linking is not yet implemented. Actually, linking to headings inside documents, including the current one, i.e. linking to HTML-anchors (ok, its markup, but when it is finally rendered in the web-browser the task is to  link to HTML anchors)

I wonder if it would maybe easier to start with linking to headings inside pages and build the automatic TOC on top of that? Clearly the TOC wants to link to the headings in the document, so it needs support for hyper-links pointing to anchors in the same document. If these inside-page links are there (including of course that the editor jumps to the linked-to heading) then building the TOC would just be a matter of parsing the document and collecting the headings.

I am not involved in the development of "text", so I do not really no where to start.

**Comment by juliushaertl** [comment]
> As I said I really think this feature is a must-be and I would like to help it exist.
> Any idea where to begin?

Contributions in this area are of course very welcome. Let me try to summarise the necessary steps there a bit:

As we recently switched to tiptap v2 as the library being used for the editor, I think having a first look at the table of contents implementation in the documentation would be a good start:

https://tiptap.dev/guide/node-views/examples#table-of-contents

This should be adaptable to the text app, to be more specific in https://github.com/nextcloud/text/blob/master/src/components/EditorWrapper.vue where the actual editor instance is being used.

UI wise this would need to be implemented a bit differently, so that there is not a TOC node at the beginning of the document but it is a separate UI element next to the actual content.

If you have any further questions or need additional help, let us know.

**Comment by Bronson-Brown-deVost** [comment]
Seems like this is highly desired right now. Is anyone currently working on a branch for this? If not, I am willing to tackle #2173 first over the weekend, then perhaps this issue as well.

**Comment by ElaineCBaker** [comment]
Was this implemented?  It would be such a useful feature to have an outline view to be able to easily navigate through long documents using the headings, as you can do in MS Word and Google Docs.  I see it was marked done but I can't seem to find the option to display the outline view anywhere?

**Comment by mejo-** [comment]
@ElaineCBaker yes it was implemented. You find the toggle to turn it on and off in the headings menu in the editor menubar.

**Comment by ElaineCBaker** [comment]
Thanks, I don't seem to see a "headings" menu and not sure what the editor menu bar is?  This is what I see 
![Image](https://github.com/user-attachments/assets/713c8030-1063-4dbe-a4f4-40c8e6cd8700) 

Sorry I am new to Next Cloud just finding my way around.

**Comment by b3** [comment]
@ElaineCBaker what you show is not the [Text application](https://github.com/nextcloud/text) which this issue is about but rather [Nextcloud Office](https://apps.nextcloud.com/apps/richdocuments).

In Text toggling the table of contents is done as @mejo writes in one step : 

![Image](https://github.com/user-attachments/assets/c3458053-b1c6-4bd5-9d78-2c331ff205b2)

After that you get something like that: 

![Image](https://github.com/user-attachments/assets/7059ecd9-8008-45bf-a6cf-8dd6984d797b)

**Comment by ElaineCBaker** [comment]
Oh sorry I didn't realise I am in the wrong place so.  Do you know if this feature is in NextCloud office - RichDocuments app?  I can't seem to find this feature there, and I also can't seem to find a github issue for it?

**Comment by ElaineCBaker** [comment]
It's ok I found it with help from someone with Next Cloud experience.  Posting here in case others also have trouble finding it.  You click sidebar icon 

![Image](https://github.com/user-attachments/assets/85c6584e-e9f9-413f-bacb-afe0248ef871) and then navigator icon 

![Image](https://github.com/user-attachments/assets/10a50cf7-44d1-408c-9866-fd0b7a124232)

**Comment by Dan-Sun** [comment]
Is it possible to show the outline mode (TOC) all the time?
