### ISSUE TITLE
Deep Link to open the Editor immeditately 🥰

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/text#1070]
**Is your feature request related to a problem? Please describe.**
I have some bookmarks to some Text files i would love to edit directly.
At the moment i always have to click on the file in the filelist again and cannot create a valid bookmark directly to the editor. 

**Describe the solution you'd like**
It would be great to be able to directly visit ones files in the editor e.g.
nextcloud/index.php/apps/files/?dir=/PoiPoi&fileid=124604#editor which triggers the editor immediately

**Describe alternatives you've considered**
none 😞

Thank you for your great work!! 🥰

**Comment by juliushaertl** [comment]
This will be part of Nextcloud 20, where opening a file in the viewer changes the url to /index.php/apps/files/?dir=/&openfile=17163 where the openfile triggers the opening after loading the page when using this url.
