### ISSUE TITLE
Text-Files not loading when Theming-App is deactivated

### ISSUE THREAD

**Issue by gamebrina** [nextcloud/text#1084]
**Describe the bug**
A clear and concise description of what the bug is. I already found the error:
This part in Viewer.vue line 458 is broken and needs a Null-Check on OCA.Theming:
```
		updateTitle(fileName) {
			document.title = `${fileName} - ${OCA.Theming.name}`
		},
```
Because it throws
`TypeError: Cannot read property 'name' of undefined`
if Theming App is deactivated.

**To Reproduce**
1. Deactivate Theming App
2. Try to open / edit any text file
3. See black page with loading circle animation and wait forever

**Expected behavior**
Text editor should have loaded the file

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version:  86.0.4240.75

<details>
<summary>Server details</summary>

**Text app version:** 3.1.0

**PHP version:** 7.4

**Nextcloud version:** 20.0

</details>

<details>
<summary>Logs</summary>

#### Browser log
```
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at a.updateTitle (Viewer.vue:458)
    at Viewer.vue:336
    at l (ncvuecomponents.js:320)
    at Generator._invoke (ncvuecomponents.js:320)
    at Generator.forEach.t.<computed> [as next] (ncvuecomponents.js:320)
    at ae (viewer-main.js?v=ae45706f:403)
    at a (viewer-main.js?v=ae45706f:403)
    at viewer-main.js?v=ae45706f:403
    at new Promise (<anonymous>)
    at viewer-main.js?v=ae45706f:403
```

This part is broken and needs a Null-Check on OCA.Theming:
		updateTitle(fileName) {
			document.title = `${fileName} - ${OCA.Theming.name}`
		},

</details>

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/viewer/pull/631
