### ISSUE TITLE
Todo List Checkboxes

### ISSUE THREAD

**Issue by sunjam** [nextcloud/text#110]
![1561646005](https://user-images.githubusercontent.com/1787238/60274972-ef1e1100-98ad-11e9-93e6-eed93517615d.png)

**Is your feature request related to a problem? Please describe.**
Todo lists are supported in tiptap [as described here on their website](https://tiptap.scrumpy.io/todo-list).

**Describe the solution you'd like**
Todo checkboxes are an important inclusion for the Text app, as a Markdown shortcut, and as part of the WYSIWYG editor menu.  Thanks!

**Comment by jancborchardt** [comment]
@juliushaertl is this a duplicate of #93? :)

**Comment by juliushaertl** [comment]
@jancborchardt Yes. Let's close this in favor of #93
