### ISSUE TITLE
Markdown : Display non-formated

### ISSUE THREAD

**Issue by Sirr-Al-Asrar** [nextcloud/text#1101]
Hi,
As a simple syntax for publish on the web, markdown provide an easy formatting but a good visibility too when is not formatted.
Use a keyboard short-cut or a button to switch to formatted or non-formatted display can be consistant with markdown philosophy and it can be great for [front-matter usages](https://github.com/nextcloud/text/issues/145#issue-465414071), or for modify syntax instead of the content, ...

Thanks for the work. This collaborative editor is awesome 🥇

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/text/issues/439 which will not happen any time soon due to the way our collaborative editing is implemented. (see also https://github.com/nextcloud/text/issues/323#issuecomment-538461645 for some additional details)

**Comment by Sirr-Al-Asrar** [comment]
Ok, thanks

**Comment by claell** [comment]
Duplicate of #123
