### ISSUE TITLE
Share and allow editing not possible

### ISSUE THREAD

**Issue by hoergen** [nextcloud/text#111]
**Describe the bug**
I created a textfile and want to share it to not logged in users that can edit the text. But when I click in the share link dialog "allow edit" there is an error message "Unable to toggle this option"  . I can share it, but people can just read, but not edit it.

**Expected behavior**
On my other Nextcloud .. a similar installation, everything works like expected and "anonymous users" can edit the textfiles.

**Screenshots**
![00_temp](https://user-images.githubusercontent.com/24474762/60287291-ccbddf00-9911-11e9-9470-629e5648fbec.jpg)

**Comment by jancborchardt** [comment]
This issue seems like it’s rather related to the server core (file sharing) than the Text app specifically. Can you confirm if you encounter this problem with other file types too, and also with the Text app disabled?

If so, I would transfer the issue to the server repository but we also need more info like browser console, server log etc to be able to debug. :)

**Comment by hoergen** [comment]
You are right I tried to enable editing on other files (even it doesn't make sense) and got the same issue. It would be great if you could transfere it to the correct team. Thank you 🌻

**Comment by hoergen** [comment]
Oh.... I think I found it ... because of security reasons I deactivated in the settings "File Sharing" the option "allow public uploads".  As soon I checked that option it worked like a charm. Didn't do the connection between "uploads" and "editing".

Maybe put that detail on a more prominent location in the description of the app.

Thanks again and this issue can be closed.

**Comment by jancborchardt** [comment]
> Oh.... I think I found it ... because of security reasons I deactivated in the settings "File Sharing" the option "allow public uploads". As soon I checked that option it worked like a charm. Didn't do the connection between "uploads" and "editing".

Hmm, is this intentional @rullzer @nextcloud/sharing?

**Comment by SevenBlocks** [comment]
"allow public uploads" really needs to be renamed or have some parenthetical explanation that it's required for editing of documents. I spent weeks trying to figure out why link sharing was always read-only.

**Comment by lamixer** [comment]
This actually still needs fixing, in Nextcloud 21.0.3. I just embarrassed myself by asking someone to upload to a shared folder via link (ok, I should have tested it first).

If the Admin setting for 'allow public uploads' is unchecked, and you create a folder, then share the folder, then go back and look at the share details, there is a check box for "Allow editing" which you CAN check! But if you close that and return to it later, the box will be unchecked (and of course, functionally it doesn't work). The box should either not be shown at all, or should be greyed out so you can't check it.

If you then switch on 'allow public uploads' in Settings > Admin > Sharing > Allow Users to share via link > Allow public uploads things change. 

Go back to the folder you have shared, now it looks different: there are radio buttons to pick from "Read only", "Allow upload and editing", "File drop".

Probably the best UI would be the latter is always shown (the three radio button options) but if "Allow public uploads" is not enabled in settings, the options besides 'Read only" are greyed out / not selectable.

I will cross post this to the server core issues area.
