### ISSUE TITLE
Support printing notes (first print CSS, then export to PDF)

### ISSUE THREAD

**Issue by rkaraba** [nextcloud/text#112]
Please add PDF export because people sometimes need print their notes.

**Comment by jancborchardt** [comment]
@juliushaertl what do you think? Does this require some PDF generation library?

Another thing we can do is look at a proper print stylesheet which hides the top bar and adjusts some other things. @rkaraba would that solve the problem?

**Comment by juliushaertl** [comment]
Maybe we can use https://github.com/MrRio/jsPDF to build the pdf file, but that needs a deeper look.

I agree that a proper print sylesheet work actually be a good first step.

**Comment by rkaraba** [comment]
@jancborchardt 
Your solution is better than nothing so yes it will help

**Comment by nicostuhlfauth** [comment]
I already worked with jsPDF before. It's very easy to use, well documented and performant.

**Comment by jancborchardt** [comment]
@nicostuhlfauth cool, do you want to help implement this? :)

@juliushaertl maybe also helpful: for the Mail app @sourenaraya implemented a print stylesheet, and PDF export can then be done through the browsers/OS own "Print as PDF" functionality: https://github.com/nextcloud/mail/pull/1804

**Comment by juliushaertl** [comment]
Did not make it for 18

**Comment by Jab2870** [comment]
Is this still on your radar? Printing would be excellent, printing to pdf is (IMO) secondary.

**Comment by jancborchardt** [comment]
@Jab2870 yes, are you interested in contributing a fix?

See https://github.com/nextcloud/mail/pull/1804 where @sourenaraya implemented a print stylesheet for the Mail app. This could be done just the same here. :)

**Comment by joshdmwood** [comment]
Hi, just wanted to add that I encountered this issue today when attempting to print my markdown document. I could not a find working md-to-pdf or print from md feature within nextCloud that actually worked and I was not able to get the pdf flow working either. just wanted to thank you in advance for making this possible and keeping the beautiful css of nextCloud while printing. Thanks!

**Comment by ImaCrea** [comment]
Hello ! It'd be very helpful to be able to print or export as pdf notes. I see the discussion here stopped a while ago. Is there any chance we see that feature shipped at some point please? 🙏

**Comment by WilliamDEdwards** [comment]
In NextCloud, notes are stored as - and therefore also accessible as - regular files. To print a note before this issue is solved, without having to copy + paste it to some application manually, you could download the file from the file browser, or open it from your NextCloud client, and print it using your text editor.

**Comment by ImaCrea** [comment]
> In NextCloud, notes are stored as - and therefore also accessible as - regular files. To print a note before this issue is solved, without having to copy + paste it to some application manually, you could download the file from the file browser, or open it from your NextCloud client, and print it using your text editor.

Sure, this is I do at the moment. Thanks for pointing out that solution but it's also important to realize this is not as trivial is it sounds for many users (no opinion here, just what I observe).

**Comment by EricKerby** [comment]
> In NextCloud, notes are stored as - and therefore also accessible as - regular files. To print a note before this issue is solved, without having to copy + paste it to some application manually, you could download the file from the file browser, or open it from your NextCloud client, and print it using your text editor.

When text files / notes are in markdown *.md format, keep in mind most users don't have a MarkDown-compatible text editor installed locally, so printing outside the nextcloud web app isn't necessarily an easy workaround.

**Comment by susnux** [comment]
> PDF export can then be done through the browsers/OS own "Print as PDF" functionality: [nextcloud/mail#1804](https://github.com/nextcloud/mail/pull/1804)

Sadly this feature does not exist on mobile browsers (firefox mobile removed that feature one or two years ago).

**Comment by szaimen** [comment]
> Sadly this feature does not exist on mobile browsers (firefox mobile removed that feature one or two years ago).

They are working on a successor IIRC.

**Comment by Uatschitchun** [comment]
@susnux @vinicius73
Is there a regression in NC 27? When trying to print a md file from within my browser (opera), I only see one page to print?!

**Comment by juliushaertl** [comment]
Can you open a new issue for this please?

**Comment by Uatschitchun** [comment]
> Can you open a new issue for this please?

Done, see https://github.com/nextcloud/text/issues/4536

**Comment by geonom** [comment]
Is this still being worked on? Cannot see a workaround - copying the contents to Word works for the text but the images do not show up. Printing does not work beyond the first 1.5 pages. And there is no export or convert button to be found. Confused and feels like .md files are a lock in right now.
