### ISSUE TITLE
Add Text to Transifex

### ISSUE THREAD

**Issue by rkaraba** [nextcloud/text#113]
Please add this app to Transifex so users can help translate it.

**Comment by jancborchardt** [comment]
You’re absolutely right! cc @juliushaertl @rullzer @MorrisJobke

**Comment by MorrisJobke** [comment]
Added and deployed: https://github.com/nextcloud/docker-ci/commit/909467a0a5b182cb8cfd2ca3bebc6367612be91a

**Comment by juliushaertl** [comment]
Thanks a lot :+1:

**Comment by MorrisJobke** [comment]
Was wondering, why it didn't showed up - it overwrote the social translations :/ https://github.com/nextcloud/text/commit/5727f0a29ba896c6c5d9930e263e58e36a4b1f3b

**Comment by juliushaertl** [comment]
Sorry about that :/ I guess we need to revert https://github.com/nextcloud/social/commit/3b01776a5cd539a03c50eb3cea8f645e7b9c5749 then as well?

**Comment by MorrisJobke** [comment]
> Sorry about that :/ I guess we need to revert [nextcloud/social@3b01776](https://github.com/nextcloud/social/commit/3b01776a5cd539a03c50eb3cea8f645e7b9c5749) then as well?

Doesn't matter, because it is already deleted on transifex and getting from our own file format back to PO files is quite some hassle :/

Good thing is, that the old translations are still in the suggestions 😉
