### ISSUE TITLE
open text files in new tab(s)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/text#117]
The editor is great.
Is it possible the open a file in a new browser tab?

**Comment by juliushaertl** [comment]
This is more a server related issue, once we have https://github.com/nextcloud/server/issues/14593 we can also support opening the current active file action in a new tab, so let's close that an try to have a solution working for all apps.

**Comment by jancborchardt** [comment]
Yep, and @jakobroehrl just in case the question is how to bring up the browser native right-click menu over the Nextcloud right-click, you need to press `Shift` and then right-click.

As soon as the nextcloud/server#14593 @juliushaertl mentioned is fixed, the "Open in new tab" action could open the Text app in a new tab. :)
