### ISSUE TITLE
App corrupts existing .md and txt files

### ISSUE THREAD

**Issue by untilbit** [nextcloud/text#118]
**Describe the bug**
Installed the app on my Nextcloud 16.

The app shows a blank editor/screen when opening existing markdown (.md) or text files (.txt) and after closeind the editor window, the file can no longer be downloaded nor opened with the previous text editor app. It shows the file no longer exists error.

**To Reproduce**
1. Install app in Nextcloud 16
2. Open existing md/txt file
3. No content loaded
4. Close editor
5. Disanle Text app and enable text editor
6. Open same file.
7. The file can no longer be opened and file no longer exists error is shown.

**Expected behavior**
At leas .md files should be opened and also existing files should not be corruopted.

**Screenshots**

**Client details:**
 - OS: Linux
 - Browser: Firefox 67 on Linux/Android
 - Version: 16
 - Device: Desktop / Android phone

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** Latest of v. 16

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Does that happen for any file? Could you please fill out the issue template, especially the browser/nextcloud log?

**Comment by korelstar** [comment]
Maybe this is related to https://github.com/nextcloud/text/issues/122 ?

**Comment by korelstar** [comment]
Effectively, it looks that Text doesn't work as intended with NC16.0.0 but requires at least 16.0.1. This should be reflected by `appinfo/info.xml` in order to prevent frustrated users.

**Comment by jancborchardt** [comment]
@korelstar oh oh, good find. @juliushaertl @rullzer what’s our course of action here? Is it even possible to do min-version things with dot-releases?
