### ISSUE TITLE
 Integration into mobile app via webview

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#119]
From #1:

Proposal to provide direct editing 

## Mobile flow

To enable text editor into a client there are a few things that need to be care off.

### 1. Check for support

Check the capabilities API

`<server>/ocs/v2.php/cloud/capabilities`

If this contains a text section then mobile editing is supported.
There is a list of mimetypes that can be edited with text supplied.

### 2. Open a file with a fileid

This returns an URL that you have to open in a full screen webview.
Be sure to have javascript enabled.

This API is used to obtain a link for a document to load from mobile apps

Creating the link
<server>/ocs/v2.php/apps/text/api/v1/document
A POST request to this endpoint with the fileid parameter will preprare the server to serve this document.

The returned xml or json will has an url to open in a webview.

## 3. Interacting with the document

The text app looks for a javscript handler that the client can
register. This is: `TextMobileInterface`

It expects the following functions:

### close()

This closed the webview.

### share()

opens the share sidebar for the current file

### insertGraphic()

open a filepicker to select a file from your nextcloud.

Then the client has to call the function (on the webui):
`OCA.Text.Mobile.postAsset(filename, filePath)`

This will make sure the assets is added to the document.

I'll work on the server implementation and @tobiasKaminsky will look into the Android side once I have a working branch.

cc @tobiasKaminsky

**Comment by jancborchardt** [comment]
Also cc @marinofaggiana for iOS.

**Comment by tobiasKaminsky** [comment]
@juliushaertl ping me when I can test something :-)

**Comment by juliushaertl** [comment]
Hm seem the stale bot config doesn't work as expected

I'll keep you updated @tobiasKaminsky Planned for next week

**Comment by elpraga** [comment]
Are there any news here?

**Comment by tobiasKaminsky** [comment]
Yes, work is in progress and it will be in one of the next releeases :-)

**Comment by elpraga** [comment]
Great! That is certainly something to look forward to! Thank you!

**Comment by Araly** [comment]
Has this gotten any changes ? when I try to edit a md file on android, it loads forever, but I'm not sure Text here is the guilty part

**Comment by juliushaertl** [comment]
Already implemented, @Araly let's continue with your issue in https://github.com/nextcloud/text/issues/742
