### ISSUE TITLE
Missing all database tables for activation

### ISSUE THREAD

**Issue by Ang3er** [nextcloud/text#1203]
After upgrading to the latest stable version of nextcloud (20.0.2) I tried to activate all shipped apps, as well the app "text".
Currently Iam facing the issue of missing tables in my database (why no clue), does the upgrade not check if all required tables are there in place.

Could somebody please provide me the sqls for creating all needed tables for the app.
Further question, is there a "standard" approach to check all tables, if they are in the correct structure. (In earlier days I had a similar issue, but of course I could not just build up my complete database in new as I would lose all User data etc.)

Thanks in advance
Dominik

**Comment by juliushaertl** [comment]
The updater should check this. Can you check the output of `occ migrations:status text` and paste the output here?

**Comment by Ang3er** [comment]
![image](https://user-images.githubusercontent.com/12126245/100325174-89fdac00-2fc8-11eb-929d-5ee7d711828d.png)
Thats my output.
I fixed my problem temporarily by disabling text app for the upgrade.
Could you maybe just give me the original structure of the three text tables?

**Comment by juliushaertl** [comment]
So the migrations have been ran successfully meaning from a Nextcloud perspective the tables should be there.

You can manually reset this and retrigger the migration by running the following sql query and occ command:
```
MariaDB [nextcloud]> delete from oc_migrations where app = 'text';

occ migrations:migrate text
```

**Comment by Raudius** [comment]
I think this can be closed. Question was answered and relates to an unsupported NC version.
