### ISSUE TITLE
Search in text file

### ISSUE THREAD

**Issue by Gatak** [nextcloud/text#121]
It would be great if searching in the opened text file was possible. Especially in large text files this is needed since a browser only searches visible text and not text outside the text window.

**Comment by juliushaertl** [comment]
Which browser are you using? For me using the browser search works for all the content of the text app, even if it is hidden somewhere else, which requires scrolling.

**Comment by Gatak** [comment]
Mobile browser such as Opera.

**Comment by jancborchardt** [comment]
Thanks for the clarification :) closing.
