### ISSUE TITLE
sync causes conflict even if no edits have occurred

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/text#1212]
If a file is open in the editor, but has not been changed, and if an updated version is pushed from a client through file synchronization, then the editor reports a conflict, instead of simply loading the new version pushed from the client.

Worse, the same behavior occurs even when the editor is active in  viewing mode, as for a read-only public share.

The following steps will reproduce the issue:
1. Create a file in  a synchronized folder. Be sure that the desktop client is running and that synchronization is enabled.
1. Open the file in the editor. Make no changes.
1. Open the file in an editor running locally on the client system. Make changes and save. Allow the file to synchronize with the server.
1. Return to the editor in the browser.

Then the editor in the browser should simply refresh the content from the local changes.

Presently, the editor reports a conflict, and asks the user to choose between the two versions to resolve the conflict. (In viewing mode, the editor simply continues to display the outdated version.)

------

**Text app version:** 3.1.0
**Operating system:**  Linux
**Web server:** Apache
**Database:** MariaDB
**PHP version:**  7.3.24
**Nextcloud version:** 20.0.2

**Comment by arnowelzel** [comment]
I can confirm this, happens here as well.

**Comment by juliushaertl** [comment]
Thanks for your bug report. Please fill out the issue template to provide some more information about your setup and possible errors in the logfiles.

**Comment by claell** [comment]
This might be caused by #593.

**Comment by Ellpeck** [comment]
Is there any update on this?

This issue makes it pretty much impossible to use Text's preview feature to share documents with other people if they're being edited locally. I'd love to use the Text preview to share some of my notes with other people, but because I edit them on my computer rather than on Nextcloud, I keep having to go there to resolve conflicts, even though I never actually edit the file in Text.

**Comment by Raudius** [comment]
If I am understanding the issue correctly this sounds like a feature request for syncing text sessions with external changes.

This might be possible when opening files read-only. If a conflict occurs we can reload the document from server as the read-only session is not making changes anyway.
