### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/text#122]
**Describe the bug**
Getting a white screen when opening the file.

**To Reproduce**
1. Create "New text document"
2. It automatically tries to open it, get kind of white screen
3. Open the file manually, also get a whitescreen

**Expected behavior**
Getting an empty document and a toolbar I guess from the screenshots of the app in the appstore

**Screenshots**
![test4md](https://user-images.githubusercontent.com/34820982/60335192-8dd56b00-999d-11e9-9ebe-d7ba9a3cefa6.png)

**Client details:**
 - Browser: Firefox 67.0.4 (64-bit), Iron 66.0.3450.0 (Offizieller Build) (32-Bit)

<details>
<summary>Server details</summary>

**Text app version:**   1.0.0 (In your bug-template it says Social app version)

**Database:** mysql 10.2.24

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.0

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```{"reqId":"yP60sLrQB3bnSjeFcDdb","level":0,"time":"2019-06-28T09:50:51+00:00","remoteAddr":"77.179.108.215","user":"StefanS","app":"files_markdown","method":"GET","url":"\/cloud\/index.php\/apps\/files\/","message":"Could not find resource file \"\/cloud\/apps\/files_markdown\/css\/..\/build\/styles.css\"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3450.0 Iron Safari\/537.36","version":"16.0.0.9"}```

#### Browser log
```
Insert your browser log here, this could for example include:

Firefox Console in files app
```Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
The resource from “https://qqq.de/cloud/index.php/apps/files/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
files
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
OCA.Viewer initialized Viewer.js:37:10
New search handler registered search.js:67:12
The following handler is already registered 
Object { id: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, group: Getter & Setter, … }
Viewer.vue:339
    registerHandler Viewer.vue:339
    beforeMount Viewer.vue:178
    beforeMount Viewer.vue:177
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:30:10
The select2 library is deprecated! It will be removed in nextcloud 19.
globals.js:30:10
The humanFileSize library is deprecated! It will be removed in nextcloud 19.
globals.js:30:10
```

Firefox Console while opening
```Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://sozis-tiere.de/cloud/apps/deck/js/build/collections.js
Source Map URL: Modal.js.map

The escapeHTML library is deprecated! It will be removed in nextcloud 19.
```

After deactivating deck I don't get a error in console at this moment.

```

</details>

**Comment by juliushaertl** [comment]
Hm, this might be caused by not being on the latest Nextcloud 16 release. Can you update your instance to the latest release? Otherwise you could for testing disable the viewer app and try if it works to open the file then?

**Comment by Dubidubiduu** [comment]
Text works for me with nc 16.0.0 and without viewer app and with nc 16.0.1 and viewer app activated. Thank you. Have a great weekend!

**Comment by jancborchardt** [comment]
@Dubidubiduu you have a great weekend too! :)
