### ISSUE TITLE
Remember the last opened folder

### ISSUE THREAD

**Issue by gerroon** [nextcloud/text#1220]
**Is your feature request related to a problem? Please describe.**
I love the image inserting function but the issue is that it never remembers the last opened folder, so for every image that needs to be added one has to find that particular folder from  other directories.

**Describe the solution you'd like**
The image insertion browser should either remember the last opened folder, if not at least it should open the folder of the where that .md document is.

thanks

**Comment by vinicius73** [comment]
We already open file picker using the current location of `md`  file.
