### ISSUE TITLE
Images in shared md/txt don't show for other users

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/text#124]
**Describe the bug**
Images added to a text/markdown file shared by user a with b do not show when user b displays the text/markdown file.

**To Reproduce**
Share a file, add picture, watch shared file with other account.

**Expected behavior**
Shared pictures should either be automatically shared OR user is prompted if he wants to share the picture.

**Comment by jancborchardt** [comment]
@ho1ger @juliushaertl this is a duplicate of https://github.com/nextcloud/text/issues/54, right? :)

**Comment by ho1ger** [comment]
I guess so, yes. Didn't find it.

**Comment by jancborchardt** [comment]
@ho1ger right – I adjusted the title of the other issue. Thank you! :)
