### ISSUE TITLE
Changing the max-width

### ISSUE THREAD

**Issue by Larsene** [nextcloud/text#125]
It could be useful to be able to remove or tweak the max-width CSS for the text. At my taste, a full width feature is better.

Or, where can i change/remove the  max-width: 670px; from  .editor__content ?

For example, the stackedit.io editor width is better.

**Comment by jancborchardt** [comment]
The width is set to be roughly 80 chracters so it accomodates a recommended reading width of not much more than 75 characters (see https://baymard.com/blog/line-length-readability) and at the same time satisfies people who are used to 80 characters per line from their various editors.

If you want to use the full width, you can use the [Custom CSS app](https://apps.nextcloud.com/apps/theming_customcss) and this piece of CSS:
```
.editor__content {
    max-width: 100vw !important;
}
```

**Comment by sthyregod** [comment]
Hey, sorry for bumping an old thread. I've been pretty bugged by the line length. 80 chars is the lower end of the allowed range, some style guides has recommendations for 120 as line length (but very rarely above that).

But given that this is a text editor and not an IDE, is there any reason to physically limit the with? Even IDEs span as much as wanted, but usually just places a small line to indicate the desired max line width. Wouldn't it be much better to not limit the width and implement a 'max line width "line" ' as IDEs do it if some people want to know the limit for various programming-esque stuff? That way you could adjust the placement of the line at 80, 100, 120, or other place of personal preference or completely remove it if your tasks does not involve programming.

**Comment by abradshaw** [comment]
I agree - the width is FAR too narrow, can we please have a way to change it (I installed Custom CSS app but I have no idea where to add the snippet)

**Comment by codereptile** [comment]
> I agree - the width is FAR too narrow, can we please have a way to change it (I installed Custom CSS app but I have no idea where to add the snippet)

For you and others: Admin Settings -> Theming -> Custom CSS (text window). Paste your css there. You can also change the %, for example, I use 90% (cause no borders looks a bit weird):
```css
.editor__content {
    max-width: 90vw !important;
}
```
