### ISSUE TITLE
Nextcloud Text image support in QOwnNotes

### ISSUE THREAD

**Issue by pbek** [nextcloud/text#127]
I'm not sure if this is the right place to post this...

I've added Nextcloud Text image support to [QOwnNotes](https://www.qownnotes.org) 19.7.0 in https://github.com/pbek/QOwnNotes/issues/1226 in case anyone wants to test and comment on it.

**Comment by jancborchardt** [comment]
@pbek very cool! Will you also come to the Nextcloud Conference in Berlin? https://nextcloud.com/conf

I'd be happy to give feedback on the QOwnNotes design and work with you on improving it then. :)

**Comment by pbek** [comment]
Thank you, @jancborchardt. :) Currently I'm not much into traveling. :)

**Comment by juliushaertl** [comment]
@jospoortvliet How about asking for some testing of the integration of this on twitter?

@pbek Thanks for looking into the integration. Since there is nothing to handle on the code side, I'll close this for now.

**Comment by pbek** [comment]
Thank you
