### ISSUE TITLE
Shared notes containing Code Blocks are not responsive

### ISSUE THREAD

**Issue by broslavski** [nextcloud/text#1298]
**Describe the bug**
Shared notes created with a Text and containing Code Blocks breaks the adaptive layout on the smartphone resolution.

**To Reproduce**
1. Create a new note
2. Open Text and add Code Blocks to the note
3. Wait until the note is saved
4. Create a shared note
5. Open the shared note on the iPhone or another smartphone.
6. Shared note template is loaded outside the screen boundaries.

**Expected behavior**
The note template must be adaptive on all mobile device resolutions, regardless of the content of the note.

**Screenshots**
- [iPhone X](https://share.getcloudapp.com/YEuQBPeN)
- [iPhone 6/7/8 Plus](https://share.getcloudapp.com/X6u088rQ)

**Comment by vinicius73** [comment]
It was already solved.

![image](https://user-images.githubusercontent.com/1561347/196285390-424cf649-2792-4e16-a036-feda4e55b1b1.png)
