### ISSUE TITLE
Support plain text files

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#13]
The app should also support editing plain text files without formatting.

**Comment by agru** [comment]
This app already takes precedence over the normal text editor included to Nextcloud. So a file with the extension *.txt is opened in the Text app. But the formatting of text should then be disabled by default. Otherwise users will add Markdown-code to plain text files. # #

**Comment by jancborchardt** [comment]
@agru that's exactly the plan as described in the first post :)

> The app should also support editing plain text files _without formatting_.

**Comment by Gatak** [comment]
Just noticed this when switching to this app. IMO it should not be called text editor, but rather markdown editor, document editor, or some such until it can support plain text files without formatting. What happen if one open a text file, edit it and saves. It would ruin the file with md syntax in it. Perhaps removing important data.

**Comment by juliushaertl** [comment]
@jancborchardt maybe there was a misunderstanding then on my side, because I thought you mentioned to even render markdown for .txt files? I fully agree with @agru that it should not render markdown syntax in that case.

**Comment by agru** [comment]
Hi @jancborchardt - as @juliushaertl mentioned there is a slight difference between "should support" and "should not". In my opinion it is already a problem at the moment that the app "Text" takes precedence in editing *txt files. If they are clicked they are opened in "Text" if this app is installed and there is no possibility to open them in the normal core app "Text editor". And the same problem exists for Markdown-files. I also have the app "Markdown editor" from Robin Appelman installed. "Text" also takes precedence over this app.

**Comment by Gatak** [comment]
I would not mind this taking precedence over the normal core Text app as long as it has a plain mode that doesn't add markdown or other styles to the file as it would ruin the file.

Perhaps a config option to what files should be opened in this app would be useful, if possible?

**Comment by jancborchardt** [comment]
@juliushaertl I don’t remember exactly. Let’s go with what @agru and you say and _don’t_ render Markdown for plain text .txt documents. :) And also don’t show the formatting controls.

Then it’s also fine that it takes precedence over the files_texteditor since then it’s exactly the same, but with possibility of collaboration.

**Comment by claell** [comment]
Just to clarify, this issue as I understand it is not about switching to plain text mode for any document (like Markdown, right)? At least this is how I understand #129.

Else #123 would be a duplicate of this issue for example.
