### ISSUE TITLE
URLs are escaping improprly

### ISSUE THREAD

**Issue by shushugah** [nextcloud/text#1314]
When submitting a Wikipedia url, which contains two underscores for example https://en.wikipedia.org/wiki/Amazon_worker_organization, linking instead to https://en.wikipedia.org/wiki/Amazon

it renders (without space) as https://en.wikipedia.org/wiki/Amazon _worker_ organization

<img width="559" alt="Screenshot 2021-01-03 at 16 30 34" src="https://user-images.githubusercontent.com/7111514/103482403-06ae5200-4de1-11eb-8bdb-04ddcd2bc483.png">

**Comment by XueSheng-GIT** [comment]
Duplicate of https://github.com/nextcloud/text/issues/806?

**Comment by shushugah** [comment]
yes duplicate of #806, happy to close this in favor of that
