### ISSUE TITLE
[BUG] Faulty .json file reading

### ISSUE THREAD

**Issue by teemue** [nextcloud/text#1315]
### Steps to reproduce
1. Have a .json file uploaded
2. Open file in web nextcloud web interface

### Expected behaviour
Show actual content of .json file.

### Actual behaviour
When opening .json file, content is not shown, only `[object Object]`

## Server configuration detail

**Operating system:** Linux 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.27

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [ocm-provider/nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                    [ocs/nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => 11789d9f21c7784a303a30e31e14d2a7b849b9585e6cb2fa40f499e46004eb3879fbedf7c0d3a57f73692cc6e3b38fd02d5eff0f86601e18c23a9672c27cd033
                        )

                    [nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => 74250c408f40ecd6d755aa8a0ee90cd223cbe7a4bf20667f1db6cf4455a1f499d75bd3e00f1a40e02d0a948fa0525b28d6e50d77b4401ee5fb506f63193bd235
                        )

                    [core/ajax/nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => fbda71b3f12897968037cbbaa47d108d7da31f631b23dc757706668283995151cc00b50ef91e5af8ef1fd37aa93674bb9311c0a73409a1e3c4210b88d4dd2f83
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - apporder: 0.11.0
 - bookmarks: 4.0.5
 - breezedark: 20.0.2
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - contacts: 3.4.3
 - cookbook: 0.7.6
 - dashboard: 7.0.0
 - dav: 1.16.2
 - extract: 1.3.0
 - federatedfilesharing: 1.10.2
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - integration_github: 0.0.16
 - integration_google: 0.1.4
 - integration_reddit: 0.0.9
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - metadata: 0.12.0
 - news: 15.1.1
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.1
 - previewgenerator: 102.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - theming_customcss: 1.8.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - comments
 - contactsinteraction
 - encryption
 - external
 - federation
 - files_external
 - firstrunwizard
 - nextcloudpi
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "5": "nextcloudpi.local",
        "7": "nextcloudpi",
        "8": "nextcloudpi.lan",
        "11": "80.220.197.176",
        "1": "192.168.1.40",
        "12": "kitkis.duckdns.org"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.4.0",
    "overwrite.cli.url": "https:\/\/192.168.1.40\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "overwriteprotocol": "https",
    "loglevel": "2",
    "log_type": "file",
    "logfile": "nextcloud.log",
    "maintenance": false,
    "theme": "",
    "app_install_overwrite": [
        "previewgenerator",
        "drawio"
    ],
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "data-fingerprint": "703f54782b0e47b14b4408a9e473d962"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Operating system:** macOS 10.15.7

**Comment by juliushaertl** [comment]
Already fixed with https://github.com/nextcloud/text/pull/1223 for the next release.
