### ISSUE TITLE
Clicking a link in richEditor downloads the entire folder.

### ISSUE THREAD

**Issue by szche** [nextcloud/text#1355]
**Describe the bug**
Clicking a file link within the richEditor leads to download of the whole folder.

**To Reproduce**
1. Create a new folder and a Readme.md file inside it
2. Upload a new file to that folder
3. Add file link to that file in Readme and click the link in richEditor
4. The browser will open a new window and download the whole folder zipped as 'download.zip'

Please note that this bug doesn't happen if you open the Readme.md in editor first, then click the link. 
The bug doesn't also affect the "home" folder - works fine there.

**Expected behavior**
Clicking the link should open the file in a viewer app

**Client details:**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Microsoft Edge
 - Version: Nextcloud 20.0.5
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.1.0

**Operating system:** Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** MySql

**PHP version:** v7.4.13

**Nextcloud version:** 20.0.5

</details>

**Comment by szche** [comment]
Seems the issue is with the markdown link parsing inside richEditor. To test it out, I compared the `<a href>` fields generated in viewer app and in richEditor:
Viewer app: `/index.php/apps/files/?dir=/TestFolder&openfile=XXXXXXX#relPath=Image.png`
richEditor: `/index.php/apps/files/?dir=&openfile=XXXXXXX#relPath=Image.png`
As you can see, richEditor link doesn't include the folder name (**TestFolder**) in it's path so Nextcloud tries to locate the file in the home directory. 
Should be a relatively easy fix.

**Comment by vinicius73** [comment]
I could not reproduce this error in the recent versions of text.
If this bug persists, please open a new issue.
