### ISSUE TITLE
Use relative image paths for better rendering in 3rd party apps

### ISSUE THREAD

**Issue by matthijsbro** [nextcloud/text#1368]
**Is your feature request related to a problem? Please describe.**
When I open .md files on my laptop images don't render unless I manually change the image url to a relative path. 
Example: My document is in /Document/Example.md and includes an image: /Photos/Frog.jpg

**Describe the solution you'd like**
In the above example the image is put in as:
`![Frog.jpg](Photos/Frog.jpg)`
This could be:
`![Frog.jpg](../Photos/Frog.jpg)`

In the last case it renders proper online, as well as in a Markdown editor/viewer on my laptop.

**Describe alternatives you've considered**
Move the image to the folder of the .md file. That seem rendundant copying, however.

**Additional context**
<img width="958" alt="Screenshot 2021-01-20 at 15 01 59" src="https://user-images.githubusercontent.com/803217/105185426-cb29bc80-5b30-11eb-9f84-8904ff533df4.png">
<img width="729" alt="Screenshot 2021-01-20 at 15 04 08" src="https://user-images.githubusercontent.com/803217/105185446-cfee7080-5b30-11eb-86cd-4b8a47019b18.png">

**Comment by 13hannes11** [comment]
In general proper support for relative paths would be great as currently locally edited markdown files don't show the images included.
And usually my folder structure is something like:

- project
  - something.md
  - img
    - img1.png

**Comment by mejo-** [comment]
Images uploaded to Text use relative paths nowadays (to the `.attachments.$fileId/` folder). The way we handle images changed a lot starting with Nextcloud 24, so closing this issue as completed.
