### ISSUE TITLE
Text stopped wrapping text with .txt files 

### ISSUE THREAD

**Issue by lunar-debian** [nextcloud/text#1407]
## Summary

When using plain text files users should be able to decide if they want lines to be wrapped or not. This should be implemented using a toggle. The toggle state could be remembered in the browser storage.

<details>
 <summary>Initial summary (as before the issue discussion)</summary>

**Describe the bug**
Nextcloud Text can be used to open `.txt` files. But word-wrapping is not enabled and that makes it not very usable.

I've just upgraded the server from Nextcloud 18. It used to work fine.

**To Reproduce**
Create a new file ending in`.txt`. Open it with Text. Type a line too long to fit on the screen. It will not be wrapped and requires horizontal scrolling.

**Expected behavior**
Words should be wrapped, just like they are with rich text.

The issue can be fixed by adding the following CSS snippet using the custom CSS app.
```
#editor-wrapper:not(.richEditor) .ProseMirror pre {
  white-space: pre-wrap;
}
```

**Screenshots**
![Video demonstrating the bug](https://user-images.githubusercontent.com/24840614/106590600-3027de00-6545-11eb-8d2f-89883d0503f7.mp4)

<details>
<summary>Server details</summary>

**Text app version:** 3.1.0

**Nextcloud version:** 20.0.6 - 20.0.6.1

</details>

</details>

**Comment by sushifrick** [comment]
Same problem here with Nextcloud 20.0.8 and text 3.1.0. I did not realize it until one of our users asked for an option to anable word wrap today.

Could you please provide a fix for this, or at least say something to the proposed "fix" by @lunar-debian . Is is "save" to use it os is there any other parts of the editor that are affected in an unwanted way by this?

**Comment by RussianNeuroMancer** [comment]
https://github.com/nextcloud/text/issues/1006

**Comment by dave-kennedy** [comment]
This has been "fixed" in Nextcloud 23, i.e. lines are wrapped by default when viewing plain text files. Depending on the file, sometimes I want lines to wrap and sometimes not. It'd be nice if there was a button in the toolbar to toggle this behavior.

**Comment by ed-ud** [comment]
I find the opposite extreme case - we see it show the file in the center third of the window (and it wraps the lines of text) and there are huge areas of empty white space on the left/right of that.  I'd like to TURN OFF line wrapping or have it use the entire available width of the window before wrapping...

**Comment by juliushaertl** [comment]
@jancborchardt @nimishavijay @max-nextcloud What do you think about this. I see that with either wrapping or not wrapping will not work for everyone or every file type / content. Having a toggle is quite common for a text editor, but I fear we start overcomplicating the UI.

**Comment by ed-ud** [comment]
I tried this CSS snippet via the "Custom CSS" app, and it seems to work fairly well to stop the line wrapping when we view text files:

#editor-wrapper:not(.richEditor) .ProseMirror pre {
  white-space: pre;
}

**Comment by max-nextcloud** [comment]
Since this is just for plaintext and code editing we do not have the menubar. So the ui is not so cluttered anyway. I'd be okay with adding a toggle or so. Maybe even one for full width of the editor and one for line wrapping.

**Comment by nimishavijay** [comment]
Great idea! Agreed, word wrap toggle is there in every other editor so we should include it for sure for `.txt` files. For `.md` I don't think we need to include it as `.md` files are usually used for readable content as it has formatting, bullet points, etc :)

**Comment by juliushaertl** [comment]
Thanks for the input everyone, I've updated the issue description accordingly.

**Comment by max-nextcloud** [comment]
Okay... so this issue is getting somewhat mixed up. Initially it was about wrapping not working anymore in NC20. This is fixed with Nextcloud 23 and there is a [workaround](https://github.com/nextcloud/text/issues/1407#issuecomment-1093077356) available for earlier versions.

**Comment by juliushaertl** [comment]
@max-nextcloud Yes, good take, lets track the enhancement separately then in #2290

**Comment by max-nextcloud** [comment]
@juliushaertl I copied over your new summary and reverted this so the two are easier to destinguish / understand.

**Comment by pdwalker** [comment]
> #editor-wrapper:not(.richEditor) .ProseMirror pre {
> white-space: pre;
> }

I also added a heavy handed ".editor__content { max-width:revert!important; }" to the custom css.  I may refine it further if i find it causing problems elsewhere.
