### ISSUE TITLE
Toggle full list to checkboxes doesn't work

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#1408]
Only the first element gets converted as reported by @jancborchardt

**Comment by XueSheng-GIT** [comment]
Duplicate?
https://github.com/nextcloud/text/issues/903

**Comment by jancborchardt** [comment]
Duplicate indeed, didn’t see that, sorry! And thanks @XueSheng-GIT :) Closing in favor of https://github.com/nextcloud/text/issues/903 then
