### ISSUE TITLE
No preview of embedded images

### ISSUE THREAD

**Issue by zenzc** [nextcloud/text#1420]
Images who add per Drag'n'Drop into the editor will not been previewed.
This issue is in NC 20.0.7, at NC 19.0.1 it will previewed.
If i close the editor and download the .md file, the image is correct embedded (data:image/png;base64,...)

**To Reproduce**
1. Go to 'Files' tab
2. Add 'New text document'
3. Click in the opened editor
4. Drag and drop an image from the host to the editor-page
5. There are only an icon, no preview of the image

**Screenshots**
![image](https://user-images.githubusercontent.com/78602558/107043840-d123cc80-67c3-11eb-9aae-9df24a40e8ab.png)

**Expected behavior**
Display of the embedded image, testet on NC 19.0.1 (https://nextfiles.de/de/demo/)
![image](https://user-images.githubusercontent.com/78602558/107047127-bf442880-67c7-11eb-9df4-d4153ab61efd.png)

**Client details:**
 - OS: Windows 10 Edu, build 1904
 - Browser: Chrome Version 88.0.4324.104 and Firefox 85.0 (64-bit)
 - Device: Desktop

**Server details:**
 - OS: Ubuntu 20.04 Server

**Text app version:** 3.1.0

**Web server:** apache 2.4.41

**Database:** MariaDB 10.3.25

**PHP version:** 7.4.3

**Nextcloud version:** 20.0.7, deb package

**Comment by vinicius73** [comment]
This process of upload have changed.
Now drag'n'drop is fully supported, not only images also another type of files.
