### ISSUE TITLE
Paste images

### ISSUE THREAD

**Issue by zenzc** [nextcloud/text#1421]
It would be nice for documentations when it is possible to paste images (screenshots) from the clipboard into the text.
The images should be embbeded into the .md file.
Today is only possible to save the screenshot and drag'n drop then the image-file.
Much obliged!

**Comment by archont00** [comment]
Wouldn't be a designated folder within user accessible files a better option?
With the possibility to rename (or even move elsewhere) the linked file from the editor directly  - when the user feels the need to have things organised.

P.S. I use screenshots a lot.

**Comment by zenzc** [comment]
I think it's great for documentation when images are embedded directly in the md-file (base64 encoded). This makes collaboration and exchange easier. This also increases acceptance. I know that it doesn't quite match the markdown idea. The nextcloud/text editor supported it up to version 19.0.1 with drag n drop images. In the current version (NC 20.0.7) there is a issue with the preview of embedded images. https://github.com/nextcloud/text/issues/1420

**Comment by crobarcro** [comment]
I came to also request this feature, but would also prefer images to just go in same directory as md, by default, or that you can choose a location. 

But ability to paste images would be really excellent!

**Comment by lars-becker** [comment]
PS: Typora has a nice drag and drop implementation which could be used as a model.

**Comment by juliushaertl** [comment]
Storing images would be fairly easy now with the recent work by @eneiluj on https://github.com/nextcloud/text/pull/1900

**Comment by lars-becker** [comment]
> Storing images would be fairly easy now with the recent work by @eneiluj on #1900

Wow. That's really great and would be a **huge** leap for the utility of collectives. Thanks. Will it be released with the next version of text or do we have to wait for the next Nextcloud release? :)

**Comment by ya-d** [comment]
Maybe the recent PR #2264 helps implementing this feature as well? 😊 Really looking forward to these image handling enhancements and table support. Thanks a lot guys.

**Comment by juliushaertl** [comment]
Yes, this was actually implemented by @eneiluj in #2264 right away 🚀
