### ISSUE TITLE
Lists have too much space

### ISSUE THREAD

**Issue by andrewmcguinness** [nextcloud/text#143]
I use text files a lot for lists, and bulleted md lists are fine, but the rendering in this app spaces list items out like paragraphs, which I find a bit too much vertical space.

That's a matter of opinion. I don't know if it's feasible to identify some "user-customizable" styling parameters like paragraph spacing for different elements. Presumably I could hack the css myself but that might have knock-on effects.

**Comment by juliushaertl** [comment]
I think the default list spacing is just fine, as a bigger space helps separating items from each other, so as long as there is no design reasoning behind such a change, I'd keep it like that for now. In case you use .txt files, we will have a proper plain text editing in the next release with #129 which has a more condensed line spacing and doesn't add additional padding to elements like lists.

Apart from that it should work just fine if you add a custom css rule for the editor  with the theming_customcss app e.g.
