### ISSUE TITLE
Up/down arrows don’t work to switch between list items

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#1450]
The up and down arrow buttons don’t work to skip between list points or todo list items, like in other text editors.

This comes up for example if you want to change something in all points of a list, like capitalize the first letter, or remove spaces. You can not skip

**Comment by juliushaertl** [comment]
Seems to only affect checkboxes, not bullet or numbered list items for me.

**Comment by juliushaertl** [comment]
Works as expected with the latest release
