### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by zonky2** [nextcloud/text#1489]
It would be nice to be able to display the line numbers - with Etherpad this was standard.

When editing together, it's nice to be able to say "look at line 42" in the chat instead of "look at the third paragraph before the bulleted list...".

**Comment by marcelklehr** [comment]
> When editing together, it's nice to be able to say "look at line 42" in the chat instead of "look at the third paragraph before the bulleted list...".

I think for this particular use case live carets are more handy.

Generally, line numbers feel more relevant for code editing than for normal text editing and make the editor appear very technical.
