### ISSUE TITLE
PROPFIND with Depth "0" 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/text#1507]
The PROPFIND with the Depth "0" on directory return richWorkspace always NULL 

Sorry if this is not the right place where write the this issue. (Was better the Server ?)

**Comment by marinofaggiana** [comment]
@juliushaertl any fix here ?

**Comment by juliushaertl** [comment]
@marinofaggiana Feel free to give https://github.com/nextcloud/text/pull/1590 a spin for that.
