### ISSUE TITLE
Toggeling checkboxes is still possible during idle timeout

### ISSUE THREAD

**Issue by scaredmushroom** [nextcloud/text#1525]
**Describe the bug**
When the session timed out due to inactivity, it is still possible to toggle the checkboxes of checklists.
Because it will not sync these changes users get confused and their changes get lost on resync.

**To Reproduce**
1. Open a text file
2. Create a checklist
3. Wait until idle timeout
4. Toggle checkboxes

**Expected behavior**
On timeout the checkboxes should be read-only.

**Comment by marcelklehr** [comment]
Confirmed with Nextcloud 25
