### ISSUE TITLE
No way to remove formatting. Must delete text and retype. 

### ISSUE THREAD

**Issue by plutocrat** [nextcloud/text#1528]
**Describe the bug**
No way to remove formatting. Must delete text and retype. eg You accidentally backspace, and an entire paragraph becomes H1. You can put in a line break, but the paragraph remains as H1 FOR EVER. Need to delete entire paragraph. Or, cut, paste into external text editor, cut from there, and paste back into App. 

Needs Remove formatting button. 

**Client details:**
Firefox Linux Latest

**Comment by susnux** [comment]
I think with the current version (NC24) this is possible, except for links.

**Comment by marcelklehr** [comment]
With the latest version I can remove a link using the menu bubble and all other attributes using the menu. Closing for now, feel free to shout this is being closed in error.
