### ISSUE TITLE
Clicking on a linked document or website ... does nothing. 

### ISSUE THREAD

**Issue by plutocrat** [nextcloud/text#1529]
**Describe the bug**
Clicking on a linked document or website ... does nothing. You might expect, after 20 or 30 years of clicking on links, that they might do something. Instead, you need to right click and open the link in a new tab. 

I was considering using Nextcloud for some wiki-like documentation. Clearly its not up to the job. 

**Browser **
Firefox Linux latest.

**Comment by martinkoutecky** [comment]
Same here, NC21. Pretty annoying :(

**Comment by martinkoutecky** [comment]
Seems fixed in NC 21 RC1, but there's another problem - there's no way to go back.

**Comment by juliushaertl** [comment]
Fix will be part of the next release with https://github.com/nextcloud/text/pull/1419

**Comment by martinkoutecky** [comment]
@juliushaertl Thanks. I want to ask though, it seems #1419 fixes the "click does nothing" bug, but doesn't fix "after clicking a link, there's no way to go back" problem. Should I open a new report for it, or am I missing something else?

**Comment by juliushaertl** [comment]
> @juliushaertl Thanks. I want to ask though, it seems #1419 fixes the "click does nothing" bug, but doesn't fix "after clicking a link, there's no way to go back" problem. Should I open a new report for it, or am I missing something else?

Yes, a separate issue would be appreciated with some detailed steps to reproduce.
