### ISSUE TITLE
l10n: Author colors

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/text#1545]
Could you describe this feature in more detail:
https://github.com/nextcloud/text/blob/38e37b234170c473e784f567fa3e70d4fe5004f5/src/components/SessionList.vue#L67-L69

Function description:

- Author colors are only shown until everyone has closed the document.

In my opinion it is a bit vague.

As for the author colors only visible when editing the file, why isn't it a description like this:

- Author colors are only shown when editing the document.

**Comment by juliushaertl** [comment]
I think the current version makes it more clear that the author colors are not persisted, but I also agree that the wording isn't the best there yet.


> Author colors are only shown when editing the document.

Doesn't make it clearer in my oppinion. The main point here is that if all users close the document the author information will be gone and if the file is reopened a fresh tracking of authors will start.

cc @jancborchardt

**Comment by juliushaertl** [comment]
🏓 @jancborchardt @nimishavijay

**Comment by marcelklehr** [comment]
How about

> Author colors will be lost after everyone has closed the document

**Comment by jancborchardt** [comment]
Great suggestion @marcelklehr, let’s do it like that! :)

**Comment by max-nextcloud** [comment]
We still need to bring author colors back after the y.js rework. So I'm removing this from the list of good first issues as it's currently blocked.

**Comment by juliushaertl** [comment]
Let's close this as currently we don't have author colors as a feature
