### ISSUE TITLE
2 Readme files created

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/text#1546]
When I create a readme file with the rich workspaces feature, it results in 1 file on the file system (when the file system is case sensitive) but 2 files in the webinterface:

![grafik](https://user-images.githubusercontent.com/7354506/113917276-4f5f1800-97e1-11eb-9e3a-312a2af871e4.png)

**To Reproduce**
1. Click in the empty area and create a new readme.md

**Expected behavior**
Only 1 readme file created

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7354506/113917342-64d44200-97e1-11eb-8097-6cd5d8f79810.png)

**Client details:**
 - OS: Nextcloud on Ubuntu with snap, based on ZFS fs below
 - Browser: all
 - Version: nextcloud 20

<details>
<summary>Server details</summary>

**Text app version: 3.1.0** (see Nextcloud apps page)

**Operating system: Ubuntu 20.04 with nextcloud snap and ZFS as underlying file system**

</details>

**Comment by XueSheng-GIT** [comment]
I have the same issue when using rich workspaces on an external samba mount (nextcloud 23.0.2). Just wondering whether this should haven been covered by https://github.com/nextcloud/text/pull/834.

**Comment by JMoVS** [comment]
@XueSheng-GIT this was fixed in my case by switching to a case-sensitive file system as the underlying fs.

**Comment by XueSheng-GIT** [comment]
I double checked my samba config and "case sensitve" was not set (defaults to "auto"). After explicitly setting case sensitive = yes, the issue (multiple readme files) seems to be gone.

Still wondering whether there's an issue that nextcloud created multiple readme files with different upper/lower cases. I assume in my case this is related to the smbclient implementation and not a general issue.

**Comment by marcelklehr** [comment]
Could not reproduce this anymore with text master and NC master, and samba set to case sensitive = no
