### ISSUE TITLE
Nesting checkbox/tickbox/task list item in unordered list turns entire UL into checkbox after reopening

### ISSUE THREAD

**Issue by ndroftheline** [nextcloud/text#1566]
### Steps to reproduce
1. Create or open text file using Nextcloud Text
2. Create unordered list and nest a task list item in it. example screenshot:
![image](https://user-images.githubusercontent.com/4163695/115291740-370bd780-a1a9-11eb-81c4-65747d5c9e7b.png)

3. Close and reopen the file twice
4. Observe that all the task list item's parents have now been changed to task list items. example screenshot:
![image](https://user-images.githubusercontent.com/4163695/115291839-54d93c80-a1a9-11eb-8745-808b78b1bc3a.png)

### Expected behaviour
List items remain the type specified

### Actual behaviour
List items are displayed as task list items when they have task list item children, even if the list items are supposed to be unordered list items instead

## Server configuration detail

**Operating system:** Linux 5.3.18-3-pve #1 SMP PVE 5.3.18-3 (Tue, 17 Mar 2020 16:33:19 +0100) x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.4.18

**PHP version:** 

7.4.15
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, standard, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, imap, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.9 - 20.0.9.1

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** linuxserver.io nextcloud

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - bruteforcesettings: 2.1.0
 - calendar: 2.2.0
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.5.1
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - drawio: 1.0.0
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_snapshots: 1.0.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.9.5
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.17
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - auto_mail_accounts
 - encryption
 - files_external
 - notes
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.mounga.eco\/",
    "overwritehost": "nextcloud.mounga.eco",
    "overwriteprotocol": "https",
    "0": [
        "192.168.11.60:42477",
        "nextcloud.mounga.eco"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.11.60:42477",
        "nextcloud.mounga.eco"
    ],
    "dbtype": "mysql",
    "version": "20.0.9.1",
    "installed": true,
    "maintenance": false,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "loglevel": 0,
    "theme": "",
    "encryption.legacy_format_support": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0

**Operating system:** Docker on debian (OpenMediaVault) 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by ndroftheline** [comment]
hey all, just curious if someone can replicate this behaviour or if it's just me

**Comment by thomas-mc-work** [comment]
Yes, same problem here on Nextcloud `22.2.3` and Text `3.3.0`. Very annoying.

**Comment by marcelklehr** [comment]
In NC 25 you can no longer mix normal lists and task lists, so this issue was fixed by becoming invalid. Thank you for your feedback nonetheless. :hearts:
