### ISSUE TITLE
ResourceLocator can not find a web root

### ISSUE THREAD

**Issue by the-sane** [nextcloud/text#157]
**Describe the bug**
I'm seeing the following error in my logs:

`ResourceLocator can not find a web root (root: /var/snap/nextcloud/14306/nextcloud/extra-apps/text, file: index.php/css/text/47cd-d800-icons.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)`

I have nextcloud installed via snap.  This issue has been discussed on their github (https://github.com/nextcloud/nextcloud-snap/issues/902), where the snap maintainer has stated it is not a problem with the snap but rather an extension making assumptions about the server's configuration.  See, specifically, his comment here: https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-472981857

**To Reproduce**
Open Nextcloud in a browser and navigate to the Files app to cause the error to be thrown.

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version 67.0.4
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:**
Text v1.0.0

**Operating system**:
Ubuntu Server 18.04

**Web server:**

**Database:**
mysql 5.7.26

**PHP version:**
7.2.19

**Nextcloud version:** (see Nextcloud admin page)
16.0.2 installed from snap

</details>

**Comment by juliushaertl** [comment]
This is not an app issue as described in https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-510387708 the app just has the files in place and the server is trying to resolve them and seems to have issues here with the snap using a app path outside of the regular web root.
