### ISSUE TITLE
l10n: No translated text string

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/text#1573]
No translated text strings for:
https://github.com/nextcloud/text/blob/7653189a351215fa2b3763681aa325ba7267a393/src/components/MenuBubble.vue#L49

![obraz](https://user-images.githubusercontent.com/47037905/116093390-e7487700-a6a6-11eb-95af-d4a852bdd108.png)

![obraz](https://user-images.githubusercontent.com/47037905/116093694-2ecf0300-a6a7-11eb-958f-2ec92378bc5e.png)

In Transifex and in l10n files there is only a text string:

- Add Link

However, there is no text string to translate:

- Update Link

App:
Nextcloud 21.0.0
Text 1.0.2

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/text/commit/e1287a74dc9faed27c8178dea1376ab955c3350d
