### ISSUE TITLE
Readme.md still not compatible with NC 21

### ISSUE THREAD

**Issue by eehmke** [nextcloud/text#1595]
**Describe the bug**
The updater tells: for Readme.md no actual version available

**To Reproduce**
With NC 20, open the web updater

**Expected behavior**
all apps should have actual versions for NC

**Client details:**
 - OS: Debian 10.9 on the server

**Comment by juliushaertl** [comment]
Readme.md is an 3rdparty app, please head over to https://gitlab.univ-nantes.fr/uncloud/files_readmemd/ for reporting this.
