### ISSUE TITLE
Text size is a bit small

### ISSUE THREAD

**Issue by gcala** [nextcloud/text#162]
**Is your feature request related to a problem? Please describe.**
In a laptop with a 13.3" screen and 1080p resolution text is a bit tiny for my taste.

**Describe the solution you'd like**
A button opening viewer options like that in firefox:

![Firefox-Reader-view](https://user-images.githubusercontent.com/153917/61069997-1a9c1200-a3fd-11e9-8308-ea0a88a2342c.png)

This way should be possible to customize font size, text width, row height and backgroud. 

Thanks

**Comment by WunderWaffla** [comment]
Yes please. I can zoom in browser but then top panel and headings get too big. It'll be awesome to have an option to change font size

**Comment by jancborchardt** [comment]
We could also think about increasing the base font size in general. Currently it’s set to be the same as the Nextcloud interface font size, but possibly makes sense to increase the size there, especially on desktop.

Maybe it’s even good to base it on the screen size with `vw`/`vh` as we have the 80 characters width limit too.

**Comment by jancborchardt** [comment]
We could also think about increasing the base font size in general. Currently it’s set to be the same as the Nextcloud interface font size, but possibly makes sense to increase the size there, especially on desktop.

Maybe it’s even good to base it on the screen size with `vw`/`vh` as we have the 80 characters width limit too.

**Comment by brainchild0** [comment]
I'm not sure how popular it would be, but for me it is helpful to be able to change to a serif font (such as in the example menu in the original post), in addition to making adjustments to the font size, as I find it much easier to read through longer sequences of text in a serif typeface.

**Comment by jancborchardt** [comment]
For the next version of Nextcloud (18) we increased the base font size from 12.8 to 14, so this should improve it already.

For the rest, the interface is perfectly zoomable with the browser zoom, that is also Ctrl+scroll or Ctrl+ +/-.

Putting in more configuration for font size or type would increase our testing matrix too much for our resources. But you could just change the font that is used with the [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) app.

**Comment by jancborchardt** [comment]
Sorry, didn’t see this was in Text and thought it was in the server core.

Reopening, but still we have other things with more priority and we need to see how to make this not a time sink of configuration. ;)

**Comment by Nyco** [comment]
To me, the editor font size should be the same as the rendered text font size (no heading), and the same as in the URL bar.
![Nextcloud Text](https://user-images.githubusercontent.com/25348/110615632-ec537480-8193-11eb-9aa3-2d67fabc8059.png)

**Comment by juliushaertl** [comment]
@Nyco That is a different app ;) https://github.com/nextcloud/files_texteditor + https://github.com/icewind1991/files_markdown

**Comment by max-nextcloud** [comment]
I played a bit with this and for me `2vmin` looked pretty good. I also tried it in the rich workspace and when changing the window size it works really well.

However `2vmin` seems very flexible. So instead I tried `calc(7px + 1vmin)` and that also worked well.

## `1920x1080` screen.

So `2vmin` should be approx 20px.

The resulting line height with `7px + 1vmin` is 25px - so font size is approx 16px.
The resulting line height with `2vmin` is 29px so font size is approx 20px - matching the expectation.

Using halve the screen width (960) fonts become slightly smaller.

## really small screen size 

`2vmin` does not work so well - `7px + 1vmin` is a lot better i think:
![Bildschirmfoto vom 2022-11-08 15-26-23](https://user-images.githubusercontent.com/97337118/200591299-266a14b4-c491-49e5-a2fd-4b3b548e006a.png)
![Bildschirmfoto vom 2022-11-08 15-26-40](https://user-images.githubusercontent.com/97337118/200591310-d299e579-37ed-4d47-9550-81eeef749b5e.png)

**Comment by max-nextcloud** [comment]
What would need to be done:
- [ ] figure out what size to use for fonts
- [ ] figure out heading sizes (they should also be adjusted)
- [ ] maybe also make the width of the entire file flexible.

The flexible width might be required if we want to make sure we can display 80 chars.

**Comment by max-nextcloud** [comment]
I think this might be an interesting issue for a design call.

**Comment by max-nextcloud** [comment]
@jancborchardt @nimishavijay Would you have a look at this and play with the numbers some?

We need some values that work both in the workspace and in the viewer. On small and large screens.

**Comment by juliushaertl** [comment]
Should we maybe collect design call topics with a label as I feel we currently don't have a large thing to review but might well catch up on some smaller ones in a mixed call?

**Comment by jancborchardt** [comment]
Considering this issue is already quite old – back then we had a lower general font site, like 13 or 14 px. These days we have 15px (and could increase to 16 at some stage).

In any case, I think the Text app body text having the same size as the default Nextcloud text size is what we should do.

**Comment by max-nextcloud** [comment]
Closing as the we now use a larger font in general. :smiley:
