### ISSUE TITLE
Just upgraded and lost rendering and toolbar

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/text#166]
**Describe the bug**
Text is displayed as text the way a Notepad type program would display it, and the toolbar for easy markup is missing from the app.

**To Reproduce**
1. Open a text type file.
2. Notice it's wrong.

**Expected behavior**
Markup patterns should render text in various ways according to the Markup Language.

**Screenshots**
![Screenshot from 2019-07-14 13-54-43](https://user-images.githubusercontent.com/28640985/61187451-3a227d00-a63f-11e9-9b0b-f36014c965f8.png)

**Client details:**
 - OS: Ubuntu 18.04 Workstation
 - Browser: Both Chrome and Firefox
 - Version: Latest versions on Ubuntu 18.04
 - Device: Desktop

<details>
<summary>Server details</summary>

Link: [https://cloud.ruppssites.com/index.php/s/GBb6PKdmHJKYAfe](https://cloud.ruppssites.com/index.php/s/GBb6PKdmHJKYAfe)
Password: `2fQZ3pT4rpOrq+qnskBA`

**Social app version:** 0.2.6 (um, but why?)
**Text app version:** 1.0.1

**Operating system:** Ubuntu 18.04.1

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.26

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.3

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No log entries happen when opening the text type file (*.txt).
```

#### Browser log
```
What? Where do I get this?
```

</details>

**Comment by WNYmathGuy** [comment]
Um, not sure if this helps or makes me look dumb, but I see that if I rename a *.txt to *.md, then refresh the browser it opens correctly.
![Screenshot from 2019-07-14 15-08-50](https://user-images.githubusercontent.com/28640985/61188173-562b1c00-a649-11e9-87e6-b17ffe1cdba3.png)

**Comment by jancborchardt** [comment]
It is intentional that plain text files like `.txt`are not rendered as markdown since it could lose characters when copying (e.g. backticks are not shown, or `#` signs starting a line, etc). Related issues:

- Support plain text files #13
- Markdown only view #123
- Bugfix/plaintext editing #129

**Comment by WNYmathGuy** [comment]
Thanks, @jancborchardt I was just confused because the *.txt files were being interpreted by the new app prior to the recent update.

**Comment by jancborchardt** [comment]
@WNYmathGuy yep, thought so. :) Sorry about changing stuff around, and thanks for the early testing! Don’t hesitate to open further issues for things you run into.
