### ISSUE TITLE
Lost edit after going offline and coming back online

### ISSUE THREAD

**Issue by PVince81** [nextcloud/text#1667]
**To Reproduce**
1. Open the text editor
2. Type some text "first line"
3. Wait for save
4. Type some text "second line" and quickly disable the laptop's wifi before it saves.
5. Wait for about a minute
6. Bring back the wifi
7. Click the button "reconnect"

**Expected behavior**
The line "second line" is still there and saved.

**Actual behavior**
After going offline and after some delay, a spinner appears instead of the text editor.
Two error messages appear about being offline.
One of them has a button to reconnect.
After reconnecting the wifi, the "second line" is gone and the file has an older state with only "first line".

**Client details:**
 - Browser: Firefox
 - Version: 89
 - Device: Laptop with openSUSE Tumbleweed

<details>
<summary>Server details</summary>
See c.nc.com

**Text app version:** the one from c.nc.com

#### Browser log
<img width="509" alt="image" src="https://user-images.githubusercontent.com/277525/122527576-b9830d00-d01b-11eb-9732-d3a347cc5a34.png">

</details>

**Comment by max-nextcloud** [comment]
Other bugs in the area:
* #3374
* #3404 

Will add to the board with high priority.

For this issue in particular I think the steps in question might not have been send yet. So we need to keep them around and try resending them once the reconnection succeeds.

**Comment by juliushaertl** [comment]
Might be something interesting to retest after the recent changes with y.js and session handling.
