### ISSUE TITLE
Issue when opening files that contain links

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#1676]
![image](https://user-images.githubusercontent.com/3404133/122979770-3d305700-d398-11eb-934c-aab9597952d2.png)

**Comment by azul** [comment]
Looks like the accessor to state was removed from the Viewer api:
https://github.com/nextcloud/viewer/commit/dbfa6bc8ead717530001a981b7d442510bf8d897#diff-c29528ea58a2d0307765d4357b88c9a469c148ccca2d82b653dbb97290ab6ab1L52-L63
and replaced with separate getters:
https://github.com/nextcloud/viewer/commit/dbfa6bc8ead717530001a981b7d442510bf8d897#diff-c29528ea58a2d0307765d4357b88c9a469c148ccca2d82b653dbb97290ab6ab1R79-R81

So we need to replace `OCA.Viewer.state.file` with `OCA.Viewer.file`.
