### ISSUE TITLE
Multiuser editing does not work for files on External Storages in NextCloud

### ISSUE THREAD

**Issue by pfaf** [nextcloud/text#1686]
**Describe the bug**
Multiuser editing does not work for files on External Storages in NextCloud

**Expected behavior**
In NextCloud v21.0.2 I have created a group folder and shared it with group Sales.
If two users that belong to the group Sales edit a file in the Group Folder, then one can see the other editing the file, that is ok, it works. This should also work for files on External Storages, no?

**To Reproduce**
I have also created an External Storage folder location called SMBSales of type SMB/CIFS with authentication type "Log-in credentials save in session", to another server with connected users using LDAP to the Samba4 share.
When both users try to access the same file, the NextCloud Notes application does not report that both are editing the specific file, they do not have any way of knowing that the other is also accessing the file at that time, neither can see the edits that the the other user does to the text file.

**Client details:**
 - OS: Windows
 - Browser: Chrome and Firefox
 - Version: 89.0.1
 - Device: desktop PC

**Text app version:** Notes v4.0.4
**Operating system:** Debian Buster v10.8
**Web server:** NGINX  v1.14.2
**Database:** MariaDB v10.3.27
**PHP version:** php v7.3.27
**Nextcloud version:** v21.0.2

#### Nextcloud log (data/nextcloud.log)
_(No relative reports there, they are very old)_

**Comment by juliushaertl** [comment]
This is currently by design of the external storage with user credentials, see https://github.com/nextcloud/server/pull/21049#issuecomment-632730210 for further details on the technical limitations, so this is not related to text as it happens with any collaborative file editing app.

**Comment by taaaaaaaaaaaaame** [comment]
[nextcloud/server#21049](https://github.com/nextcloud/server/pull/21049) was rejected.
