### ISSUE TITLE
Collaborator avatars blurry on high-dpi display

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#171]
We should probably request double the resolution for the avatars as currently they are blurry on high-dpi displays (or when zoomed slightly):
![Text app high dpi avatars blurry](https://user-images.githubusercontent.com/925062/61301260-deddbf80-a7e3-11e9-9271-4293cf5628d9.png)

@juliushaertl this seems like a great first issue – could you post the spot where this would need to be adjusted?

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/text/blob/1231cae02746d23c92a8460bc76fbf7de37f0164/src/components/SessionList.vue#L79

**Comment by rullzer** [comment]
I think I even added code to the vue-components for an avatar thingy that automatically does the src-set. So then it autoscales :wink:

**Comment by rullzer** [comment]
See https://github.com/nextcloud/nextcloud-vue/pull/526 :wink:

**Comment by juliushaertl** [comment]
Should be fine after 65ce04f
