### ISSUE TITLE
error when issuing the make command 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/text#178]
**Describe the bug**
I get these errors
rm -f js/*
rm: cannot remove 'js/highlight': Is a directory
Makefile:61: recipe for target 'clean' failed
make: *** [clean] Error 1

**To Reproduce**
1. cd /var/www/nextcloud/apps/
2. git clone https://github.com/nextcloud/text.git
3. cd /text/
4. sudo make
5 see error

Make is installed. 

Ubuntu 18.04
Nginx

**Comment by juliushaertl** [comment]
Issue introduced in #169 

Please pull again, fixed with https://github.com/nextcloud/text/commit/c6592686b2c764713f3cd3d4f2352b1d196ead31

**Comment by rollanders** [comment]
I noted that I can install from within NC. So no need to use make and so forth

**Comment by juliushaertl** [comment]
Ok, thanks for reporting anyway :+1:
