### ISSUE TITLE
A .txt text file is difficult to read without line breaks in the TEXT editor

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/text#1817]
A .txt text file is difficult to read without line breaks in the TEXT editor.
Long paragraphs go beyond the boundaries of the visible part of the editor, and the presence of many lines in the text makes horizontal scrolling at the bottom useless. The horizontal scrolling touchpad doesn't help.
Plain text editor displays text with line breaks. But it's not in the mainstream, and co-editing not supported.
The markdown format is great, but users aren't ready for it yet.
If I provide a test file with long paragraphs and many lines, it’s easier for the user to download it to see it.

[example](https://cloud.mpda.ru/s/TXTz9MoYs3aEczQ)

This leads to despair.
Can you do something about it?

**Comment by dave-kennedy** [comment]
This has been "fixed" in Nextcloud 23, i.e. lines are wrapped by default when viewing plain text files. Depending on the file, sometimes I want lines to wrap and sometimes not. It'd be nice if there was a button in the toolbar to toggle this behavior.

**Comment by juliushaertl** [comment]
Yes, lets close this in favour of #1817
