### ISSUE TITLE
Author colors are the same for different authors

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/text#1818]
**Describe the bug**
The author colors of the written texts are the same.

**To Reproduce**
1. Create a file
2. Share it (directly or via link)
3. Write and let others write
4. Different authors have the same color (in my and my colleagues case blue)

**Expected behavior**
It looks like the color is derived/somehow depended on the user name. 

**Client details:**
 - OS: Ubuntu, Arch
 - Browser: Firefox, Brave
 - Version: 90.0.2, 1.27.111
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.2.0

**Operating system:** Ubuntu 20.04

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.4

**Nextcloud version:** 21.0.3

</details>

**Comment by juliushaertl** [comment]
Yes, colors are generated from the display name to match the color of the avatar placeholder: https://github.com/nextcloud/server/blob/9124c69cf6ca7cf7551112f19a9e5431f9cb6f13/lib/private/Avatar/Avatar.php#L292-L319

While I agree that a different color per connected user would be good it would then no longer fit the avatar if no custom avatar is set. Though we could certainly do this for guest user sessions.

**Comment by q-wertz** [comment]
Thanks for the information.

We had the problem that 3 users had the same color (which is quite surprising) and first I thought I misconfigured something. 

Would really be good if the highlighting colors are spread over the color range as far as possible.

**Comment by max-nextcloud** [comment]
I remember that colors used to be blue more often then anything else.
My understanding is that this was fixed in the meantime for avatars and colors are now more evenly distributed.
@juliushaertl , @jancborchardt you might remember this.
I'll close this issue. Please reopen if this has not been fixed.

**Comment by q-wertz** [comment]
I cannot confirm that this is fixed.

First author color (me) and second one who joined are both blue.

Text version: 3.5.1

**Comment by susnux** [comment]
It looks like the color calculated here: https://github.com/nextcloud/text/blob/5aeca92a5817fcc817fc9174f45f7e4031cd8ef8/src/extensions/UserColor.js#L37

So it is derived from the clientId which is the current session id. It is a somewhat pseudo random function, e.g. the first 100 values would look like this:
![user colors 1 to 100](https://user-images.githubusercontent.com/1855448/203061186-61a28b53-9604-4b3f-9c46-bd8f15b7fda4.png)

As you can see there are some cases where two users might get the same color.

**Comment by q-wertz** [comment]
Do you remember with which release this fix was published?

Can I find out what the `clientID` is? According to juliushaertels comment above it was derived from the display name. `sessionID` sound like something that changes with every login.

A third user now has a slightly different color (but also blueish)

**Comment by mejo-** [comment]
I'll close this as we no longer have author colors in Text.
