### ISSUE TITLE
Use NC Search for link to calender, tasks, chat rooms, ...

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/text#1822]
If you have a look at github it's very easy to link between all different stuff link issues, pull requests, users, ...

What if text (and richdocument) can access nextcloud stuff like use the NC search.

### Example: meeting_minutes.md

Project:
- #NC project
- #NC label
hover will show other linked project items or documents with the same label

Location:
- #NC calendar entry
- #NC talk channel
hover will show the calendar entry or the last text from the talk channel 

Attendees:
- @peter
- @robert
hover will show the contact card (with user status, phone, chat, e-mail, ...)

Agenda items:
- #NC deck card 1
- #NC deck card 2
hover will show the card (with owner, status, deadline, )

Files
- #NC file link's
- #NC folder
hover will show an preview, would be very useful for images, videos, ... files within the folder

**Comment by Andreas-Kainz** [comment]
What would be needed is an insert command to richdocument editors to start the search so stuff can be added and an global hover rendering which show an html "link preview".

And for .md files an specific character (like @ and #)

**Comment by max-nextcloud** [comment]
We started working on this towards the 25 release. We have something for attached files, user mentions, and links to urls. The idea is to embed more things.

We also briefly discussed using search to autocomplete what people type.

**Comment by juliushaertl** [comment]
Coming up with 26: #3700
