### ISSUE TITLE
Cannot view or edit .md

### ISSUE THREAD

**Issue by shgysk8zer0** [nextcloud/text#186]
### Steps to reproduce
- Create "New text document" or open existing

### Expected behaviour
It should open and be viewable and editable

### Actual behaviour
Either a spinner over a black screen appears or a pure white popup appear. Neither display any content or allow editing.

## Server configuration detail

**Operating system:** Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (fpm-fcgi)

**Database:** mysql 10.1.40

**PHP version:** 

7.2.19-0ubuntu0.18.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

    [news] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/arthurhoaro/favicon/resources/cache/url35582f5ff98475df1002b230d045bc0d] => Array
                        (
                            [expected] => 
                            [current] => ca7bc83d1d8d607eee91f1e6c4cd3467f5e6225a11db6a85d004a33c45f687466bcc716692972594f7730a357a6841055b10d766519de5e62a32ea56368187e8
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url74eb9f6c458097e269b7e3775c5af6d5] => Array
                        (
                            [expected] => 
                            [current] => 28d9c4c3e4c02421a7e239170f503d07da4c3abcfb41c0ff6e080c5e710fe34d96217ede6b11e708ce00ff66e911c16b425faafbd53fd266fb4a5204c73676ac
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url03f2eb192df2ddda43946eb98e7002f4] => Array
                        (
                            [expected] => 
                            [current] => d7e3fa89d58ad0102064b81549cb965f1cca545777651121368d8080633e27c75ed8ddb57c9c047b531c8b3cd246be6d1d7c5b90abf3d313efd26d3d570cd8cb
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url9315f7ec77801f9dabf5f7a57c81bc3d] => Array
                        (
                            [expected] => 
                            [current] => aa8b1b0eb44d4f9e23056c47710c07295d83d9f9a9d36b9f27c3258ff6eba244842afa121d2b0ff470b4e9e36c1bde9f374e0e868300bc0faa16bb7ceeeda28d
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url5d889366413cc76e9b690d513b91cf71] => Array
                        (
                            [expected] => 
                            [current] => 187aaaedd1f3514de3b9b3dd7ff0640f79ec56d4ad869c6b5fcc61c13263685caf11dfff194225c63f7f0aa0136f89dac93507c01ac97bb150d275f232dbf2fa
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url32c5feb1a3ca2cd066b5faaacb118ac0] => Array
                        (
                            [expected] => 
                            [current] => 9642146c1ae4a2c15b6d8747a177cc8bd911766dc639d3ea842eeddd56c7066f0d89cdb17d041d62a902adc679f82c1d4e2ec310aa3d3f506ef79ab96a4de1aa
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlad6d52d3b86566dd3cfed6a16af5a290] => Array
                        (
                            [expected] => 
                            [current] => ea4bf9885b8825c46a1bd02d30a17a2ec76b3de7bef7c066ac0aea014cac11d178446cb687b1fabc094bef94c54e368c665921c75d22b505f19ddab262adf2eb
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbe8b09f7f1f66235a9c91986952483f0] => Array
                        (
                            [expected] => 
                            [current] => 3b05fb034d64c5be6ff1cd53c300d673ac4534ba181b186a648ccb53f16b54aa2f5ea27803be34e05b94392050bc37e017672ff0161fff1b1acbdb5abf6df42d
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6e2aa22c629b6ec17bfbb9718222c357] => Array
                        (
                            [expected] => 
                            [current] => d2e3576065e1bbcba4dfa9ab0e490a347ec008afe506046673b5bc761c60337a2cf7956147f58e8472914b098d066ce0bb3cd13c2456059d0f9b2bd81e52fd57
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6963ec6d8bea30a6f4c2be1c2874ed89] => Array
                        (
                            [expected] => 
                            [current] => 4433c6d8cf24ee8e11723f133387b99a8628e08d602e8c028d1021b1f3176893a696005dd3af44779052d426b1dfd4e367082051ea3582fc51279a89151f1915
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url8ffdefbdec956b595d257f0aaeefd623] => Array
                        (
                            [expected] => 
                            [current] => 468c9ccd06fb8480c509e06f0fcd77102e7b4b4828cb00ffc59278987e121c5bcc53f0dce9de84041662625d737dd7f1cce5f514e5de6d5880c93ea7deff7c7b
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url3097fca9b1ec8942c4305e550ef1b50a] => Array
                        (
                            [expected] => 
                            [current] => 07cb5698227798458dd8855a4f39c8ad9c770105cba9e4538a1babf08de083fe747252e9806b142e7c6b5f167b48a5cd58e909aa03aa5a71a99de0769d11b177
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urld245406cb6c9f36be9064c92c34e12e1] => Array
                        (
                            [expected] => 
                            [current] => db19d1de3fdf1bf9ad3619bc42010e761e2e9fe5aeac33720338e36d78da0187b48797dc89e5cce1f30e6179718cb889777cb4209ee6dc2887ec0ed607897541
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url82274bb7cf5b45a96513333999ccfc53] => Array
                        (
                            [expected] => 
                            [current] => 171796bc8ab59f9a562714850af3ca442ad890290ab468e7207b26dcf4d707bd1be52286c258f69b75d93e128a18e27b63a897c1956c05bbfb18c0433341e2d2
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url9464b52de3caaa57ba15982102ffabd4] => Array
                        (
                            [expected] => 
                            [current] => f41130278acb51b49e6785b2b7458aa019e04fbe63313a36aa6c1714f3e4eba696bed8685ea806d23fbf5f154594b6a8f96ceccfbd9be394e8551843eaf9b276
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url06cda0335c4acf2cd6035a1c46478678] => Array
                        (
                            [expected] => 
                            [current] => aa5153befa5f7937f1746be201dd96ec9e187d74cd7b5817ff469105bbd68a2829cdaf2949fb15d68ca10946c505090fe0fa40b04f04d36bbd9bfdde6b10f2a3
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlb83879a97344ff58537620a675ad21a8] => Array
                        (
                            [expected] => 
                            [current] => b19d960fb348c176647dba77006537b39226148a023acdf3cf870bf08ff92e56dab18bf965efa8732a86daf9f2c4f60e6fa594f7c174df2c7a6d231134f86224
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urle7cb411788255e0b0143e487bd756835] => Array
                        (
                            [expected] => 
                            [current] => dd29f9d675081ccde7ee92a660a057c43f703f412fe3b3f64ef69d2e43bb0af3656c2e2f7e9cd2d397cada3035dab29767c7fb8e458748b34c0c951190a32fe5
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf7f4be827fc1618353cbcafd1d0fdd86] => Array
                        (
                            [expected] => 
                            [current] => 0a801cc2d9fe408665533448f2c42e47a39e6d2792dc00087f919ed7566c68afb23bfb9f01f46747ddd3250e5ae19081359eb49c759351576f9dfbe7295cef65
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urla5b72ef1388db778357626a9ba812218] => Array
                        (
                            [expected] => 
                            [current] => af2d64732cc28afb9e3e7429a6f4a9b100719003f639cb34fd82ef2a8fa4fc9b8a9dbfab625a575c8a2019250f02210dccc09851903700ce73269a53dc870215
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url679e8eaa3d6b38d49190dfb1c8c230d3] => Array
                        (
                            [expected] => 
                            [current] => 6c24afaa94a34a9d367d5f9ff41b32fd1ccbc5f25dc2926df04db88441e20d39cfa1df8c891e432da85424814dc9bd5d51b8657440319c0bd5ef6a4385679e4e
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url63551d588ab3f634b44a462fbd6d2d1e] => Array
                        (
                            [expected] => 
                            [current] => 0737e9b2d97e7cc243253685d65aec01788ab895a4d43fc749619e462619da730cf5d4a60e761283997b70cb6617d815854b26123b4c22edd7acb1cbfda3df05
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url021f2c63a7228de83d5ef5c0ee4ca329] => Array
                        (
                            [expected] => 
                            [current] => 98462f0fb85db1b9ce804785a1ae8d3abd9c488283f5c28b61646da82221c7c71c1b137157152fe444228772e5da72e7d19ea936b52aaa1232fcdaa84016ee16
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - audioplayer: 2.7.2
 - audioplayer_editor: 0.0.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - checksum: 0.4.3
 - circles: 0.17.5
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - cospend: 0.1.0
 - dav: 1.9.2
 - deck: 0.6.4
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_automatedtagging: 1.6.0
 - files_frommail: 0.3.0
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.1.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - groupfolders: 4.0.4
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.7.2
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - ransomware_protection: 1.4.0
 - registration: 0.4.6
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - social: 0.2.6
 - sociallogin: 1.16.3
 - socialsharing_diaspora: 1.0.4
 - socialsharing_email: 1.0.5
 - socialsharing_facebook: 1.0.4
 - socialsharing_twitter: 1.0.4
 - spreed: 6.0.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.0
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.2
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 3.0.0
 - twofactor_webauthn: 0.0.1
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - files_markdown
 - files_texteditor
 - guests
 - photosphereviewer
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.kernvalley.us"
    ],
    "htaccess.RewriteBase": "\/",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/cloud.kernvalley.us",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "America\/Los_Angeles",
    "log_rotate_size": 2097152,
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_sendmailmode": "smtp",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mysql.utf8mb4": true,
    "app_install_overwrite": []
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** Fedora 29

## Logs

<details><summary>Web server error log</summary>

```
Nothing relevant
```
</details>

<details><summary>Nextcloud log</summary>

```
Nothing relevant
```
</details>

<details><summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
OCA.Viewer initialized viewer.js:154:262
New search handler registered search.js:67:12
The following handler is already registered 
Object { id: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, group: Getter & Setter, … }
viewer.js:132:5276
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
The select2 library is deprecated! It will be removed in nextcloud 19. main.js:750:58
The select2 library is deprecated! It will be removed in nextcloud 19. main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 3 main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 6 main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 11 main.js:750:58
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 6 main.js:750:58
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 6 main.js:750:58
Source map error: request failed with status 404
Resource URL: https://cloud.kernvalley.us/js/spreed/merged-files.js?v=258a2518-55
Source Map URL: backbone.marionette.min.js.map
The humanFileSize library is deprecated! It will be removed in nextcloud 19. main.js:750:58
Unhandled promise rejection TypeError: "h.read is not a function"
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:45
    D https://cloud.kernvalley.us/core/js/dist/main.js?v=258a2518-55:230
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:45
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:52
    o https://cloud.kernvalley.us/core/js/dist/main.js?v=258a2518-55:230
    H https://cloud.kernvalley.us/core/js/dist/main.js?v=258a2518-55:230
    u https://cloud.kernvalley.us/core/js/dist/main.js?v=258a2518-55:235
main.js:230:27763
```
</details>

## Screenshot
- A basic README  
![A basic README](https://i.imgur.com/cIEVNik.png)
- A "New text document" (empty)  
![A "New text document"](https://i.imgur.com/fBtYxbH.png)

**Comment by OlivierNicole** [comment]
I just installed Text and encountered the same problem.

**Operating system:** Linux 4.14.12
**Webserver:** Apache/2.4.39
**Database:** MariaDB 10.3.14
**PHP version:** 7.3.5
**Nextcloud version:** 16.0.0
Updated from an older Nextcloud or fresh install: updated
**Where did you install Nextcloud from:** Arch Linux package repository
**Are you using an external storage:** No
**Are you using encryption:** No

## Client configuration
**Browser:** Firefox 67.0.4
**Operating system:** Arch Linux

**Comment by juliushaertl** [comment]
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

Besides that could you also extend the following line in your htaccess file:
```
- RewriteCond %{REQUEST_FILENAME} !\\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg)
+ RewriteCond %{REQUEST_FILENAME} !\\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg|map)
```

This will allow your browser to access the source maps so the console log output should be a bit more helpful to see where this is actually breaking. After doing that, please share the browser console error again.

**Comment by shgysk8zer0** [comment]
## Screenshot
![screenshot](https://i.imgur.com/1r9WzXMh.png)

## HAR (*I guess you can drag it into network panel in Chrome [cookies, etc. removed]*)
[`cloud.kernvalley.us_Archive [19-07-21 10-33-53].har`](https://cloud.kernvalley.us/s/JmDjspAA6Q92bfx)

## Console
```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 files:1:1
The resource from “https://cloud.kernvalley.us/apps/files/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). files
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
OCA.Viewer initialized viewer.js:154:262
New search handler registered search.js:67:12
The following handler is already registered 
Object { id: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, group: Getter & Setter, … }
viewer.js:132:5276
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
Source map error: request failed with status 404
Resource URL: https://cloud.kernvalley.us/js/spreed/merged-files.js?v=258a2518-55
Source Map URL: backbone.marionette.min.js.map
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 20 main.js:750:58
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://cloud.kernvalley.us/apps/deck/js/build/collections.js?v=258a2518-55
Source Map URL: Avatar.js.map
Unhandled promise rejection TypeError: "h.read is not a function"
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:45
    S https://cloud.kernvalley.us/apps/guests/dist/main.js?v=258a2518-55:271
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:45
    exports https://cloud.kernvalley.us/apps/text/js/files.js?v=258a2518-55:52
    D https://cloud.kernvalley.us/apps/guests/dist/main.js?v=258a2518-55:271
    D https://cloud.kernvalley.us/apps/guests/dist/main.js?v=258a2518-55:271
    l https://cloud.kernvalley.us/apps/guests/dist/main.js?v=258a2518-55:271
main.js:271:30662
```

**Comment by shgysk8zer0** [comment]
After viewing in Chrome  (which I guess handles mapping in console), it appears to be an error on
`/node_modules/axios/lib/adapters/xhr.js:100` loading cookies:

```
     var cookies = require('./../helpers/cookies');

      // Add xsrf header
      var xsrfValue = (config.withCredentials || isURLSameOrigin(config.url)) && config.xsrfCookieName ?
        cookies.read(config.xsrfCookieName) :
        undefined;

      if (xsrfValue) {
        requestHeaders[config.xsrfHeaderName] = xsrfValue;
      }
```

To my understanding, `Unhandled promise rejection TypeError: "h.read is not a function"` is the call to `cookies.read`.

**Comment by shgysk8zer0** [comment]
**Update**

Seeing the relation to cookies had me think to check my content / tracking blocking settings in Firefox and Privacy Badger add-on.

@OlivierNicole Check your privacy settings & add-ons. I hope this resolves it for you as well.

Firefox was set to strict content blocking but did not report anything blocked.

Privacy Badger showed that it blocked tracking cookies for some images from Imgur, but nothing else.

Setting Firefox to standard protection and disabling Privacy Badger resolved my issue. Even working when restoring their settings, so I'm pretty confused by that.

I'm going to mark this as closed. I would open something for false flags for certain privacy settings, but have so little info as to be useless and extremely difficult to reproduce.

**Comment by OlivierNicole** [comment]
@shgysk8zer0 Setting Firefox Privacy Settings to Standard and disabling uBlock Origin did not solve the problem for me.

**Comment by juliushaertl** [comment]
Hm that line also looks a bit strange: 

    S https://cloud.kernvalley.us/apps/guests/dist/main.js?v=258a2518-55:271

Let me reopen to check if the guest app somehow interferes with our code.

**Comment by tlinna** [comment]
I'm also having this problem intermittently (often it starts working after a couple of refreshes, but auto-saving the file also seems to be, well, delayed or intermittent), and I'm also using README.md app. I'll try and see if disabling it helps.

**Comment by Omaha2002** [comment]
Having the same issue thinking it was README.md related I posted an issue at Gitlab: 

https://gitlab.univ-nantes.fr/uncloud/files_readmemd/issues/30

Response from Matthieu, the maker of README.md was:

"This is definitely a an issue with with the text app !
There is a error in the console which belong to text app.
Can you please open an issue in the text app github and quote this one, I'll try to work with them."

**Comment by juliushaertl** [comment]
Hm still cannot reproduce this with guests/files_readmemd enabled :/

**Comment by juliushaertl** [comment]
Maybe someone who has that failure, could send me some credentials to a test account? That could help to have a more detailed look what is going wrong there.

**Comment by Omaha2002** [comment]
Julius, I've send you a mail witjh credentials for a test account

**Comment by juliushaertl** [comment]
So this might be related to multiple webpack entryfiles with the same jsonpFunction name being loaded on the same page together with async import. https://github.com/webpack/docs/wiki/configuration#outputjsonpfunction I'll see if I can reproduce that locally tomorrow, since maybe it only affects running the production build.

**Comment by HieronymusCH** [comment]
Good morning
I still have to refresh and trying to open it more than 10 times until the toolbar and the content load.
Even with completely disabled uMatrix, uBlock Origin and Privacy Badger. They are all off.

System:
Ubuntu 19.10
Firefox 71.0 (64-Bit) canonical - 1.0
NextCloud 17.0.2
Text 1.0.2

**Comment by juliushaertl** [comment]
@HieronymusCH Your text app version seems outdated and not the one shipped with the server release. It should actually be 1.1.1 Please check that you don't have an old version installed in a separate app directory.

**Comment by HieronymusCH** [comment]
I just cloned it with "git clone https://github.com/nextcloud/text.git".
- master -> changelog.md -> 1.0.2
- stable17 -> changelog.md -> 1.0.2
- stable17-sync -> changelog.md -> 1.0.2

Am I holding it wrong?

live long & prosper
  Hieronymus

Am 23.12.19 um 16:14 schrieb Julius Härtl:
