### ISSUE TITLE
Enabling the dark theme through Accessibility Settings hides the buttons

### ISSUE THREAD

**Issue by szaimen** [nextcloud/text#187]
**Describe the bug**
Enabling the dark mode through Accessability Settings hides the buttons

**To Reproduce**
1. Open the acessibility settings 
2. Enable dark theme
3. Create a new text-file or open an existing one.
4. The buttons are not visible.

**Expected behavior**
The buttons should be visible.

**Client details:**
 - OS: Android 9 (Pie)
 - Browser Chromium-based Browser (in Mobile View and in Desktop-View)
 - Version 75
 - Device: Samsung Galaxy S10E

**Server Details:**
I am running Nextcloud Snap 16.0.3 on Ubuntu 18.04 LTS and the latest version of the text-app.

**Comment by jancborchardt** [comment]
Which buttons are you referring to? It all shows fine here:
![Markdown dark theme](https://user-images.githubusercontent.com/925062/61726630-3c3cb800-ad72-11e9-8798-93388290a407.png)


If you are referring to the header bar with title and the buttons for Close and Sidebar, they are currently fading out, set to be fixed in the next version, tracked in **Viewer enhancements #82**

**Comment by szaimen** [comment]
No, that isn't working:
![image](https://user-images.githubusercontent.com/42591237/61748131-cd765380-ad9f-11e9-82ff-b20e2281eafc.png)
The icons are also not visible in mobile view.

**Comment by jancborchardt** [comment]
Handing over to @juliushaertl then.

@szaimen I guess a server log might be useful here, and the full URL of one of the icons – e.g. do you have `/index.php/` in your path or not?

**Comment by juliushaertl** [comment]
This is most likely an issue of the server in combination with the snap: https://github.com/nextcloud/server/issues/13556

**Comment by szaimen** [comment]
`{"reqId":"qBOfaFwWw1UH3TZT8r0i","level":3,"time":"2019-07-24T09:35:20+00:00","remoteAddr":"141.23.155.119","user":"admin","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/14795\/nextcloud\/extra-apps\/text, file: index.php\/css\/text\/3acc-d459-icons.css?v=e5a3815d156a10062d0d3a1450cc937d, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/75.0.3770.142 Safari\/537.36","version":"16.0.3.0"}`
That is just one of many error messages in the server log.

The URL of one of the missing icons looks like this:
![image](https://user-images.githubusercontent.com/42591237/61783286-d4d14780-ae07-11e9-91c7-1b1320ec325d.png)

**Comment by juliushaertl** [comment]
Yes, look very much like the same error. Let's close this issue then, since there is nothing we can do on the text app side about this.

**Comment by szaimen** [comment]
Please reopen the Issue.
Maybe there is something you can do  on the text app side about this:
After a few hours of trial and error I found out, that `https://domain/extra-apps/tasks/img/tasks.svg` just works fine. If that also works with other installations e.g. from @jancborchardt (just open that link on your installation) you could bypass the Server error.

**Comment by juliushaertl** [comment]
We cannot workaround that because the apps directory depends on the server configuration. You might have apps-extra where the text app is located but others might have it in the regular apps or an apps2 folder. The issue here is that the server cannot find the folder, since it is not inside of the nextcloud folder when using the snap.

**Comment by szaimen** [comment]
> The issue here is that the server cannot find the folder, since it is not inside of the nextcloud folder when using the snap.

If that is really true, I wonder why the default path: 
"https://domain/index.php/svg/files/public" also cannot be found but 
"https://domain/apps/files/img/recent.svg" can?
And I am sure, that the files app is located inside the nextcloud folder.

**Comment by juliushaertl** [comment]
https://domain/index.php/svg/files/public is a dynamic endpoint (which is handled by the Nextcloud server code) that looks for the apps folder of the files app and returns the image. (this is what fails on your setup) https://domain/apps/files/img/recent.svg will be served by your webserver so Nextcloud is not involved there.

**Comment by szaimen** [comment]
Okay, thank you for sharing your knowledge!

**Comment by the-sane** [comment]
@szaimen You might want to comment about this over in the mentioned server issue, https://github.com/nextcloud/server/issues/13556; maybe someone will finally take notice.  Everyone who uses the snap or a nonstandard server configuration is affected by this and similar issues.

**Comment by szaimen** [comment]
Out of curiosity:
When I understand the icon-loading correctly, the dark and the white icons should get loaded from the same path, and the browser applies a color afterwards.
So what is the normale mode doing differently than the dark mode, so that the icons get loaded there correctly?

**Comment by the-sane** [comment]
Just noting that the toolbar buttons are absent for me in both the default and dark themes.  I have 16.0.3 installed via snap.
