### ISSUE TITLE
Fix editing filename below pictures

### ISSUE THREAD

**Issue by biva** [nextcloud/text#1890]
I'm using Collectives and I see the filename below each picture that I insert. Most of the time, this is disturbing and makes the reading of the article weird. Would it be possible to remove this title? Sorry if it's a Collective issue, I'm not sure where to report this :/

I give an example below:

![image](https://user-images.githubusercontent.com/9964305/136633784-003ac485-0dbc-40f4-b5ad-2913ae2271c9.png)

**Comment by biva** [comment]
Thanks, and can I totally remove the image description?

**Comment by juliushaertl** [comment]
Yes, that should also work fine.

**Comment by max-nextcloud** [comment]
Editing the filename has been broken for a while - at least since 24 - probably longer.

**Comment by max-nextcloud** [comment]
Closing this as #2250 has a more recent discussion about this. It's on our board for things to fix next.
