### ISSUE TITLE
Pasting text

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/text#1922]
## Steps to reproduce

1. Create a text file via Files.
2. Open the file via Files.
3. Paste the text into a text file.

Unable to paste text into a text file. It is possible only after we enter at least one character from the keyboard.

## Server

- Notes app version: 3.3.0
- Nextcloud version: 22.2.0
- PHP version: 7.3.25
## Client

- Browser (incl. version): Firefox 92.0.1
 - OS: Win10

**Comment by juliushaertl** [comment]
I cannot reproduce this issue here. Is there any error reported in the browser console when pasting the text?

**Comment by Valdnet** [comment]
There is no error.

**Comment by juliushaertl** [comment]
Can you also reproduce that on different browsers and in a private browser window in firefox?

**Comment by Valdnet** [comment]
The problem is also present on a different version of Firefox. Also in a private private browser.

Exactly you need to create a new text file with the extension `txt`, for example: `test.txt`. The file must be created empty with no value, ie 0 bytes. Then try to paste the text via the right mouse button or via Ctrl + C.

**Comment by susnux** [comment]
I tried to reproduce this, but had no luck. For me this works on NC 23 and on current master as it should.

Tested with Firefox 101 and Firefox 102 on Linux.
