### ISSUE TITLE
Document markdown syntax and keyboard shortcuts

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#1941]
The options to directly type markdown syntax and use keyboard shortcuts in order to format your text are currently hidden to new users. I wonder whether it would be a good thing to document these features and that way make them more accessible to users.

One option would be to describe markdown syntax and keyboard shortcuts (if applicable) in menubar icon tooltips. That's e.g. how the Github, Gitlab and Etherpad editors do it. I read in #1075 though that you decided to remove tooltips altogether from the menubar icons. What was the reasoning behind that?

Cc @jancborchardt :wave:

**Comment by jancborchardt** [comment]
For keyboard shortcuts: Yep, let’s do that for sure! :) Putting it in the tooltips is a good call too, so like "Bold (Ctrl+B)" and "Underline (Ctrl+U)".

For Markdown syntax I’m less sure, what we could do is have one last entry with an `icon-info` which opens a modal explaining Markdown syntax quickly?

**Comment by mejo-** [comment]
> For keyboard shortcuts: Yep, let’s do that for sure! :) Putting it in the tooltips is a good call too, so like "Bold (Ctrl+B)" and "Underline (Ctrl+U)".

I opened a PR to do this: #1963

**Comment by mejo-** [comment]
So @nimishavijay and me brainstormed a bit how the formatting help modal could look like. That was great fun and @nimishavijay's input helped a lot to develop a proper concept here :ok_hand: 

Idea is basically to have
1. Some short introductionary text that explains the fact that markdown formatting syntax exists
2. A table with styles, their markdown syntax and (if not on mobile) keyboard shortcuts
3. A list of examples that show how the styles are actually rendered

For the examples we ideally reuse existing CSS so we don't have to update the examples if we ever change something in the text styling. Another reason is that custom theming will apply automatically that way.

Please excuse my ugly drawing, but that's a first mockup:

![formatting_help_mockup](https://user-images.githubusercontent.com/3582805/144244266-6bedf436-9a81-487b-9d14-204ff2b50d7d.jpeg)

**Comment by mejo-** [comment]
First ugly screenshots:

![Screenshot 2021-12-07 at 15-23-43 Readme md - Nextcloud](https://user-images.githubusercontent.com/3582805/145046580-db8fcb59-863a-46e7-a686-ad86a836ee08.png)

![Screenshot 2021-12-07 at 15-22-25 Readme md - Nextcloud](https://user-images.githubusercontent.com/3582805/145046575-77a9e852-41b4-416d-b381-8fc6a28c38a0.png)

**Comment by mejo-** [comment]
Here's a PR to add the formatting help modal: #2001
