### ISSUE TITLE
Right-click on link opens the link immediately

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#195]
If you right-click a link for whatever reason, it seems to treat it as if it was a left click.

The same issue seems to happen on the tiptap page: https://tiptap.scrumpy.io/

Instead, it should simply show the browser menu so people can copy, etc.

**Comment by filisko** [comment]
I think this only happens wity Firefox, with Chromium seems to be ok

**Comment by nina-py** [comment]
It's been a while since this was raised and I think it's no longer an issue - I can't reproduce it with Firefox. Chrome also works fine.
