### ISSUE TITLE
Improve handling of mobile icon overflow

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#1958]
As per recent discussion, the current way of overflowing icons has the problem that icons triggering a submenu might then create a two level submenu. Currently this is avoided by just always showing the emoji picker.

**Comment by mejo-** [comment]
Suggestion from @jancborchardt: The emoji picker could replace the action menu, then it is not as weird.

**Comment by juliushaertl** [comment]
Not sure I get that fully, the action menu would still be needed for the formatting actions that don't fit the width, or?

**Comment by mejo-** [comment]
> Not sure I get that fully, the action menu would still be needed for the formatting actions that don't fit the width, or?

Sure. I think he meant to close the action menu once emoji picker is clicked and only display the emoji picker?

**Comment by juliushaertl** [comment]
Closing as a duplicate of https://github.com/nextcloud/text/issues/2836 which contains more details about the mobile menu bar redesign
