### ISSUE TITLE
"Link file" button is displayed in Android client

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/text#1975]
"Link file" button is displayed when selecting some text in NC Android client. Clicking on this button does not do anything because it's not supported at the moment.

**To Reproduce**
* Edit a markdwon document in NC Android client
* Select some text
* Click on "Link file"

Maybe we should just not render this button in the MenuBubble component when Text is displayed in the Android app. I don't know if Text's Vue components can check if they are rendered in the Android app.
`isMobile` mixin is off-topic here :grin:.

@juliushaertl @mejo- @azul @luka-nextcloud Any idea?

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/text/issues/1170 is there for the actual implementation, but of course we should hide it as it is not avilable yet. :+1:

**Comment by mejo-** [comment]
The Android app has a custom UserAgent string and probably the easiest is to detect it that way?

I talked to Tobi and he pointed me to https://github.com/nextcloud/server/blob/master/lib/public/IRequest.php#L68 - so simply copying this regex should work :blush: 

See https://stackoverflow.com/a/21742107 on how to get the UserAgent string in JavaScript.

Maybe a small mixin to be reused later would be nice (e.g. `isAndroidClient`), just like we have the `isMobile` mixin?

**Comment by juliushaertl** [comment]
To also cover other apps that use direct editing, I'd just make use of the initial state value we have in place to determine that the "direct editing mode" is used: https://github.com/nextcloud/text/blob/8cdb2d22fc42c60e03f480b1ddecfe328dbaaf42/lib/DirectEditing/TextDirectEditor.php#L161 and hide the element if that is present. Then this will also work on iOS or desktop.

**Comment by eneiluj** [comment]
@mejo- @juliushaertl Thanks for the suggestions.

I went with the one covering the most use cases: To use the initial state.
