### ISSUE TITLE
Cypress test always fails in pull requests

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/text#2004]
I only updated a single CSS property on a PR but it cannot pass the cypress test.
Seems like it happens to all PRs now, something might has happened to cypress?

Please check this bug: https://github.com/nextcloud/text/runs/4447871861?check_suite_focus=true

**Comment by juliushaertl** [comment]
As discussed in the call might be related to the server change and could be fixed by https://github.com/nextcloud/text/pull/1999

**Comment by max-nextcloud** [comment]
Looks like #1999 did the trick for text and https://github.com/nextcloud/server/issues/30278 fixed the underlying issue in the end.
