### ISSUE TITLE
To-do-list: Icons inline with other lists and wrong indication

### ISSUE THREAD

**Issue by ya-d** [nextcloud/text#2018]
**Is your feature request related to a problem? Please describe.**
The icon for to-do-lists doesn’t match other list types. If you create a to-do-list it is marked as unordered list.

Currently if a to-do-list is enabled there is no indication that you have to click on the checkmark again to change list types. Clicking other list types unordered / ordered either has no visible effect at all or removes the list completely.

**Describe the solution you'd like**
The icon should follow other list types, you could probably use `mdiOrderBoolAscendingVariant`.

To-do-lists should be properly indicated as such and handled as a proper list type. Cycling through list types should change them accordingly.

**Additional context**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/30781876/146674852-16a5534e-77a6-4ce4-8bab-66650765b937.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/30781876/146674861-57e1967f-11e6-43b8-bdc7-2c317e58359e.png">

Related to #1075

**Comment by juliushaertl** [comment]
@nextcloud/designers This is a nice enhancement for the icon I'd say :+1:
