### ISSUE TITLE
files app creating 404s for directories

### ISSUE THREAD

**Issue by timreeves** [nextcloud/text#2025]
I'm running 22.2.3 on Debian 10, so configured that the self test has zero complaints.

I'm monitoring all webserver logs using fail2ban, to keep my server secure. So I have to keep looking at them, and correct any "false positives" which might lead to real users getting banned. What I've noticed with Nextcloud is like this:

"GET /ocs/v2.php/apps/text/workspace?path=%2F HTTP/2.0" 404   (%2F = "/")

"GET /ocs/v2.php/apps/text/workspace?path=%2FDocuments HTTP/2.0" 404   (/Documents")

"GET /ocs/v2.php/apps/text/workspace?path=%2FTim HTTP/2.0" 404   (/Tim)

These are folders in my file workspace. Why on earth a 404?

Would be grateful for feedback / fix.

Thanks for all the good work!

**Comment by juliushaertl** [comment]
From the context the 404 is the most fitting response code as the client requests a file and the server either returns it or a 404 if it is not found. I also don't think that a fail2ban rule on 404 responses is drastically improving the security of a system.

Note that this behaviour is the same on other endpoints, e.g. when the files app fetches a preview which is not available for a file.

**Comment by timreeves** [comment]
Yes, I've been seeing the 404s for non-available file previews as well. I understand what you write, I'm just not very happy with it. I indeed had to give up on the idea of having fail2ban monitor 404s, but I do have it monitor all the other 4xx codes. So fail2ban is permanently scanning all the log files, and in the case of Nextcloud it has to keep reading all those "expected" 404s, while looking for new "real" problems. As I've blogged [here](https://timreeves.de/internet-technologie/nginx-konfiguration-optimieren-und-geld-sparen/) and [here](https://timreeves.de/internet-technologie/plesk-wordpress-fail2ban-jails-fuer-nginx/), with the right techniques one can halve the load on a server and thus downsize it, saving money and resources. Saving resources is something I personally find is my duty towards coming generations - that's my motivation.

**Comment by juliushaertl** [comment]
I'm totally with you not that motivation. 😉 Maybe for some more background, when an external user (who is not logged in with a user session) you would get a different response code anyways. Either 401 or a 3xx for a redirect to the login page, so for detecting cases where the 404 is not necessary those might probably be the more impact status codes, though with the redirect you might also run into blocking actual guest user requests.
