### ISSUE TITLE
Author color shows as background color of inserted image even if author colors are disabled

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#2051]
**Describe the bug**
If you insert an image, it will have a colorized background around it, which is your author color, even if that feature is disabled.

**Expected behavior**
There’s no author color background on inserted images if the author colors checkbox is not checked.

**Screenshots**
See the screenshots in these pull requests :)
- https://github.com/nextcloud/text/pull/2002
![](https://user-images.githubusercontent.com/89908051/145087545-ec7ae1cc-56e2-4906-947b-0d8836240c6b.png)

- https://github.com/nextcloud/text/pull/1900
![](https://user-images.githubusercontent.com/11291457/138112774-8dcb9f11-792d-40b0-9379-e20453acd43e.gif)

**Comment by juliushaertl** [comment]
Has been fixed by https://github.com/nextcloud/text/pull/1888 already and I also can no longer reproduce this on master or Nextcloud 23. Backport is pending for 22/21.
