### ISSUE TITLE
Up and down arrow key behavior in lists

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#2096]
The up and down arrow buttons don’t work to skip between list points or todo list items. The caret either is set to the end of the next line, or skips to the next list block.
![caret list](https://user-images.githubusercontent.com/925062/149318131-f93a8f81-8175-46be-9a7e-d4a81bab37fd.gif)
 
This comes up for example if you want to change something in all points of a list, like capitalize the first letter, or remove spaces. It works perfectly in normal text, moving the caret exactly down.
![caret normal text](https://user-images.githubusercontent.com/925062/149318117-6d9dc367-6f8e-4866-a467-b994df093741.gif)

**Comment by juliushaertl** [comment]
Works fine in tiptop v1 so I guess it is something related to our way of implementing todo lists.

**Comment by max-nextcloud** [comment]
In [tiptap v2 demo](https://tiptap.dev) it always jumps to the end of the next todo entry.

**Comment by juliushaertl** [comment]
Seems fixed on master after tiptap v2 and #2188
