### ISSUE TITLE
Add support for autolink (tiptap v2)

### ISSUE THREAD

**Issue by ya-d** [nextcloud/text#2097]
[Tiptap v2 adds support for autolink](https://github.com/ueberdosis/tiptap/issues/2087) and creates hyperlinks automatically when URLs are inserted by typing oder pasting. 

It would be nice if Text would support that as well. Thanks for considering!

Related to #1906 #1981

**Comment by mejo-** [comment]
Interesting, this should be enabled per default with tiptap v2 (see https://tiptap.dev/api/marks/link#autolink), but for some reason it doesn't work in latest Text :thinking:

Seems like our custom `addProseMirrorPlugins()` in https://github.com/nextcloud/text/blob/master/src/marks/Link.js#L55 overwrites the default plugins autolink, onOpenClick and linkOnPaste. For linkOnPaste, this probably even is a regression in Nextcloud 24.

**Comment by vinicius73** [comment]
Yes @mejo- , we must fix it.
I will work on it.
