### ISSUE TITLE
 Error with position of "add/edit link - file" button on selected text when note is scrolled down

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/text#2111]
## Steps to reproduce
1. scroll down in your note
2. select some text

### Expected behaviour
I should be able to see the contextual button "add link / file"

### Actual behaviour
I can't see it, unless I scroll back up which is not usable. (many users here think the feature is just gone. it's only eventually by chance that one can't notice it can be found upper)

### Screenshots

https://user-images.githubusercontent.com/764332/149632336-e600eb6b-e4c5-465c-b4c9-7dfeb60567e1.mov

## Server
Please complete the following information.

- Notes app version: 4.2
- Nextcloud version: 21.0.7

## Client
Please complete the following information.

- Browser (incl. version):  Firefox 96
 - OS: MacOS Mojave

**Comment by XueSheng-GIT** [comment]
Wasn't this fixed by https://github.com/nextcloud/text/pull/1903?
Maybe your text app version is too old and does not include this fix!?

**Comment by mejo-** [comment]
There were several related fixes recently, see #1903, #2019 and #2113.

There will be Nextcloud 22 and 23 point releases the following days which will include the relevant fixes. So your best bet is to upgrade to Nextcloud 22 and wait for the next point release. Afterwards the issue should be fixed for you.

**Comment by ImaCrea** [comment]
thanks :)
