### ISSUE TITLE
Missing close icon for modals

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2130]
The close icon of all our modals is missing since we [upgraded to `vue-material-design-icons` 5.0.0](https://github.com/nextcloud/text/pull/1872/commits/182d4d1edd86b81c1d6600bc98d5b24e08fcd6f7).

* When opening a text document in a public folder share
* When opening the help modal from within a text document

After some debugging it seems like the [icon slot of ActionButton](https://github.com/nextcloud/nextcloud-vue/blob/7e6418ca80c9fa75eafb97b0d6804b0f54caca6c/src/components/ActionButton/ActionButton.vue#L91-L96), as [used by the `@nextcloud/vuejs` Modal component](https://github.com/nextcloud/nextcloud-vue/blob/0fb30b40ae6c07acc68cbddb2a4486116f555da9/src/components/Modal/Modal.vue#L124-L132), is empty for some reason.

Downgrading `vue-material-design-icons` to 4.12.0 brings back the Close icon, but I honestly don't understand what's happening there.

**Comment by juliushaertl** [comment]
We should check if this is still an issue now that `@nextcloud/vue@5.0.0` is used where the upgrade of vie-material-design-icons was also included https://github.com/nextcloud/nextcloud-vue/pull/2385/commits/44a46890a3d59fea07327b7ae170c32655d7580e

**Comment by szaimen** [comment]
I think the close button it is missing everywhere (whenever a modal is opened after the 5.0 upgrade)

**Comment by juliushaertl** [comment]
@vinicius73 Looked into that at https://github.com/nextcloud/nextcloud-vue/issues/2529

Possible fix is waiting for a review in https://github.com/nextcloud/nextcloud-vue/pull/2532

**Comment by mejo-** [comment]
This got fixed in @nextcloud/vue 5.1.1, which we're using since 9f8bfc927a12f0fac768e35e866243a8174c12e6.
