### ISSUE TITLE
Adjust code to suppress `_italic_`

### ISSUE THREAD

**Issue by pat-githubber** [nextcloud/text#2132]
**Problem**
I name my PDF files according to `Author_Year_Title.pdf`. When I copy-paste this file name into NextCloud Markdown, it converts `_Year_` to italics as seen in the image below instead of `Author_Year_Title`.

![image](https://user-images.githubusercontent.com/87087327/150994314-47f0b479-dfe4-4c1a-a141-863a7481b429.png)

**Need**
I am able to access the Text App in the terminal using:
```
sudo -i 
cd /var/www/nextcloud/apps/text
```
Can I delete or change something in the code, so that `_Year_` does not generate an italic text? 
Of course, I should be still able to use `*italics*` for italics text.

**Related issues**
The related posts did not help me:(
https://github.com/nextcloud/text/pull/1913
https://github.com/nextcloud/text/issues/75

**Comment by max-nextcloud** [comment]
Hi @pat-githubber

Thanks for your report.
Which version of nextcloud are you using?
I think @mejo- fixed something like this fairly recently. It might only be released with the next point release coming in the next weeks though.

**Comment by mejo-** [comment]
Indeed, this got fixed by https://github.com/nextcloud/text/pull/1964, which will be part of the upcoming Nextcloud 22 and 23 point releases (scheduled for the following days).

@pat-githubber would you mind testing the new point release once it's out and reopening this issue if the problem still exists afterwards?

**Comment by pat-githubber** [comment]
Hi @max-nextcloud, @mejo- 

**My Version** (sorry, I forgot to state that - noob)
NextCloudPi 22.2.3
Text App 3.3.0 

Thank you a lot! Yes, I will test and report, @mejo-!!
