### ISSUE TITLE
Revitalize the Changelog

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/text#2133]
**Is your feature request related to a problem? Please describe.**

Neither the https://github.com/nextcloud/text/blob/master/CHANGELOG.md nor [the release notes in the releases section](https://github.com/nextcloud/text/releases) are maintained. Is there a reason for it?

**Describe the solution you'd like**

Having the changes documented in either of both locations. With *changes* in terms of a high level description, not a list of the containing commits.

**Comment by juliushaertl** [comment]
Since the text app is bundled with the server release, the changelog is maintained at https://nextcloud.com/changelog/

We currently have no plans to maintain a separate one.
