### ISSUE TITLE
The app has no icon

### ISSUE THREAD

**Issue by tanghus** [nextcloud/text#214]
The app is downloaded and enabled in admin, but the app icon never shows up anywhere in the top menu bar or drop down menu.

**To Reproduce**
Download and enable the app from `/settings/apps/office/text`
Go to the Nextcloud root.
**Expected behavior**
The app should be available from the top menu bar or drop down menu.
I then figured, that maybe one should just select a file like with the text- or MarkDown editors, but that just prompts to open a local text editor.

**Screenshots**
![nextcloud_no_text_app](https://user-images.githubusercontent.com/533222/62364271-55d3c180-b521-11e9-8cfe-7092438d26e9.png)

**Client details:**
 - OS: Kubuntu 19.04
 - Browser: Firefox
 - Version: 68.0.1
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

I'm on a shared hosting, so I don't have all info

**Text app version:** 
1.0.1

**Operating system:** 
`uname -a` says: `Linux ngcobalt83.example.com 4.19.46 #1 SMP Wed May 29 12:40:11 CEST 2019 x86_64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz GenuineIntel GNU/Linux`
No idea which distro.

**Web server:**
Some Apache version

**Database:**
MySQL or MariaDB. Not sure

**PHP version:**
7.1

**Nextcloud version:**
16.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
I have no idea what to include from that file..?
```
Insert your Nextcloud log here
```

#### Browser log
There's really nothing here that seems relevant. Please ask specifically what to look for.

</details>

**Comment by tanghus** [comment]
I also followed [this](https://help.nextcloud.com/t/nextcloud-introduces-collaborative-rich-text-editor/55605/6?u=tanghus) advice, and an app opens, but there's just a never ending spinner.

**Comment by juliushaertl** [comment]
Can you check the browser logs when opening the text file?

**Comment by tanghus** [comment]
And as it often happens: Now it works :P

Look good - I'll do some testing. First thing I noticed, is that it can be a bit difficult to see "where you are" in Dark Mode (from Accessibility).

**Comment by scheinercc** [comment]
@juliushaertl not sure if you want me to open a new ticket or rather reopen this one. I was also confused after installation as there was no App (still isn't). Following the link above I now finally found the one way to create a text document (Files > "+" button in the breadcrumbs list).  Maybe that is something which could be added to the `README` maybe!? Thanks for this cool tool ;)

**Comment by juliushaertl** [comment]
@jancborchardt Not sure if we need to communicate a bit better that the text app is a file editor and doesn't provide its own app icon? This is probably also less relevant since it is shipped by default with 17 and not installed manually by admins though the app store.

**Comment by jancborchardt** [comment]
> This is probably also less relevant since it is shipped by default with 17 and not installed manually by admins though the app store.

@juliushaertl yes, tend to agree with this. Lots of other apps are also not necessarily showing an icon, and it would become a mess if they did. E.g. Viewer, PDF viewer, Collabora etc.

We should maybe have a good .md file in the example files starting for 17 then?

**Comment by scheinercc** [comment]
As mentioned, if there would be a clear guide showing how to create a new file, that would be great. The entry point doesn't have to be an app icon, that was just what I was looking for as I wasn't sure in which other app and area that app could be accessed from otherwise.

**Comment by juliushaertl** [comment]
Contributions to the readme file are very welcome :wink:
