### ISSUE TITLE
Translation "rich workspaces" -> DE "Umfangreiche Arbeitsbereiche" is really misleading

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/text#2165]
Ok, one can argue about correct translations. However, English "rich workspace" means something like "enhanced", or "enriched", "with surplus features". But it does not mean "large", "bulky", "wide", "big" which would be the translation for the German word "umfangreich".

Maybe not so important, but ...

The full to-be-translated phrase is "Show rich workspaces".

**Comment by juliushaertl** [comment]
Yes, that translation can certainly be improved, though I don't have a good idea immediately. Maybe @jancborchardt or @max-nextcloud @mejo- ? In general I think "rich workspaces" is also quite non-descriptive for the feature. Maybe we should consider to switch to something more obvious like "Folder notes"?

**Comment by juliushaertl** [comment]
cc @jospoortvliet as well as I remembered you were also involved in the initial naming from the marketing perspective.

**Comment by luka-nextcloud** [comment]
It doesn't seem to be a bug to me, but we still need to discuss it.

**Comment by juliushaertl** [comment]
@jancborchardt As due to the discussion in https://github.com/nextcloud/text/issues/3209 should we rename this feature to "Folder description"? We can probably use just description in general but in some cases it might be needed to make it more explicit on what the description is aimed at.

**Comment by juliushaertl** [comment]
@szaimen @jancborchardt Any objections against renaming "Rich workspaces" to "Folder description" across all places?

**Comment by szaimen** [comment]
For me "Folder description" makes sense 👍

WDYT @nimishavijay @marcoambrosini ?

**Comment by marcoambrosini** [comment]
I agree with @mejo-: "Folder notes" is most appropriate because that's a space where I can write anything, not necessarily a description of the folder.
I'm strongly in favor of changing "rich workspaces" to that.

**Comment by jancborchardt** [comment]
Since we call it "Add description" in the menu which is nice and succinct, I would just say we call the setting "Show folder description". @juliushaertl good with you?
Also, this is less confusing than "Add note" or "Add folder note" cause it can be confused with Notes.

**Comment by juliushaertl** [comment]
> Since we call it "Add description" in the menu which is nice and succinct, I would just say we call the setting "Show folder description". @juliushaertl good with you?

Yes, that sounds good 👍
