### ISSUE TITLE
Auto preview embeg image

### ISSUE THREAD

**Issue by kyhuynhduc** [nextcloud/text#217]
**Describe the bug**
Auto preview embeg image

**To Reproduce**
1. create .md file
2. insert image form current directory 
3. close file
4. reopen .md file

**Expected behavior**
auto show image 

**Screenshots**
![image](https://user-images.githubusercontent.com/36893030/62419552-d2df7200-b6ac-11e9-9afe-53c1fcd8ac5c.png)

**Client details:**
 - OS: MAC OS
 - Browser: chrome
 - Version: NC 16.0.1
 - Device: desktop

**Comment by juliushaertl** [comment]
I cannot reproduce that. Can you share the markdown content of the file by download it? What image format is it?

**Comment by juliushaertl** [comment]
Closing due to no response, if you can still reproduce the issue, feel free to reopen with the requested information.
