### ISSUE TITLE
Feature-request: inter-page links

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/text#2173]
**Is your feature request related to a problem? Please describe.**
Trying to convert pages from DokuWIki: inter-document links do not seem to be supported by NC text app?

**Describe the solution you'd like**
Link to a header in the same document  like
```
See below [LinkText](#heading-text)
...
#### Heading Text
Blah blah.
```
The link should be followed by scrolling down to the linked header. This is BTW supported on Github, I think.
**Describe alternatives you've considered**
Do not use Nextcloud collectives and text-app, stick to DokuWiki

**Comment by juliushaertl** [comment]
Related to https://github.com/nextcloud/text/issues/107 as we'd need the anchors then anyways which would easily allow to link to them.
