### ISSUE TITLE
Files with hash in filename (#) can not be edited

### ISSUE THREAD

**Issue by MelBourbon** [nextcloud/text#218]
**Describe the bug**
Any file with a hash in the filename can not be edited. I use the hash symbol in combination with terms as surrogate to tags.

**To Reproduce**
1. Create a MD file with a hash in the filename, for example by using the nextcloud notes app
2. Click on the file to open it with text
3. File will not open

**Expected behavior**
File should be opened with text to edit.

**Client details:**
 - OS: Windows 7
 - Browser: Chrome Browser

**Text app version:** 1.0.1
**Operating system:** Ubuntu 18.04
**Web server:** Nginx
**Database:** MariaDB
**PHP version:** 7.2
**Nextcloud version:** 16.0.3

**Comment by juliushaertl** [comment]
This is a bug in the viewer app, that will be fixed in the next release https://github.com/nextcloud/viewer/pull/191
