### ISSUE TITLE
Improve read only performance when just displaying rich workspace

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2183]
In most cases the rich workspace area is probably not edited, so we should think about having a more sane process for opening up a read only editor and just kicking of the heavy sync parts and session setup when starting to edit.

**Comment by max-nextcloud** [comment]
I profiled the workspace loading some and it turns out rendering the menubar is surprisingly expensive.
I experimented some with it and we can postpone that until the content has been rendered. In theory this would reduce the time till the content is displayed by 600-800ms. In practice it's still hard to measure.

**Comment by ImaCrea** [comment]
Great idea :) It's very disturbing when I'm ready to click on a file and then everything scrolls down because finally the editor is loaded.

**Comment by tcitworld** [comment]
The PR from @max-nextcloud doesn't really answer the original issue, may this be reopened to avoid loading sync & session until the workspace is actually opened?

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/text/pull/4776 also contributed to that by showing the content already before the session is opened but what would be missing is a read only and just open the session once clicked option

**Comment by elzody** [comment]
Notes from meeting with @marcoambrosini:

- [ ] Suggestion buttons row should not be displayed there 
- [ ] When we navigate to a folder, the rich workspaces section should not be in "edit" mode, and thus the file should not be locked
- [ ] Cursor becomes pointer when hovering the inactive text input. Clicking on it activate the text area and locks the file
- [ ] Clicking outside saves and disables edit mode again
- [ ] Little scrolling arrows should not be shown
- [ ] Plus button should not be cut off
