### ISSUE TITLE
Callout box support

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2184]
Callout boxes with different styles might be useful for documentation and knowledge base purposes.

This is for example what is available in http://bookstackapp.com

![Screenshot 2022-02-16 at 09 45 27](https://user-images.githubusercontent.com/3404133/154228074-4426019e-7709-467b-997a-3610e340c972.png)

Open topics to investigate:
- [ ] How can we represent this in markdown files?

**Comment by max-nextcloud** [comment]
We could use https://www.npmjs.com/package/@gerhobbelt/markdown-it-container which defaults to:
```
::: info
Here's an infobox
:::
```

That seems somewhat sane to me.
`markdown-it-container` will turn that into `<div class="info">Here's an infobox</div>`. Classes are not hardcoded so people could add their own which we might want to prevent so they cannot use classes with different meaning from our css.
