### ISSUE TITLE
some modals broken after vue 5.0 update (and after vue 5.0 merge in the viewer app)

### ISSUE THREAD

**Issue by szaimen** [nextcloud/text#2203]
need to verify that all modals work on desktop and mobile after vue 5.0 updates. If not need to make it work.

- [ ] Helpmodal
- [ ] PublicFilesEditor
- [ ] EditorWrapper?
- [ ] ViewerComponent?
- [ ] else?

<details>
<summary>For easy testing</summary>

```
docker run -it \
-e VIEWER_BRANCH=master \
-e TEXT_BRANCH=master \
-p 127.0.0.1:8443:443 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

Feel free to ping me if you should need help on fixing this!

**Comment by juliushaertl** [comment]
Is there any specific issues you see in regards to the modal? From my quick tests this works fine on master of viewer/server/text.

**Comment by szaimen** [comment]
Did you test mobile too?

**Comment by szaimen** [comment]
Some examples:
| 1 | 2 | 3 |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/156678899-684b0a1c-30b6-4e46-91fe-8b918c0506bd.png) | ![image](https://user-images.githubusercontent.com/42591237/156679114-57633ffb-72c2-4f61-8be5-1cd3b224bea1.png) | ![image](https://user-images.githubusercontent.com/42591237/156679035-eba647c6-77ff-4006-b83f-927769f18b6c.png) |
