### ISSUE TITLE
✨📱 Text app review: Mobile focus

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#2211]
(Notes from first review on 2020-10-06 in issue at https://github.com/nextcloud/text/issues/1075 )

## Header bar https://github.com/nextcloud/text/issues/2440 https://github.com/nextcloud/text/pull/2441

* [x] Make backgound solid var(--color-main-background)
* [x] Add small blue flavor bar on the top like in Nextcloud Office
* [x] Bold the filename / title

## Toolbar

* [x] The 3-dot menu wraps into the next line, but all toolbar entries should always be on the same row (with "Saved" indicator" and people menu) https://github.com/nextcloud/text/issues/1186 https://github.com/nextcloud/text/pull/2294
* [ ] #2606 https://github.com/nextcloud/text/pull/2611
   * In the long run, we could group the items into few menus: Formatting, headings, etc – however we might not have enough space
   * Possibly think about moving the formatting bar to the bottom on mobile
* [x] #2607 https://github.com/nextcloud/text/pull/2627
   * [x] use primary for active icons, primary-light for the background
   * [x] raise opacity for all buttons by default
   * [x] current opacity for the disabled buttons
   * [x] Remove blue circle below active icon

## Collaborators https://github.com/nextcloud/text/issues/2449 https://github.com/nextcloud/text/pull/2450

* [x] "Saved" text is too wide
  * [x] Could be combined with participants, showing a circle indicator on unsaved changes, and in the participants menu we can show extra text for "Last saved x minutes ago" on top of the participant list → **let’s do this one**
    * [x] Adjust behavior on desktop, but keep "Saved" text as additional info
  * Could collapse into a checkmark icon on mobile, could even be actionable to save
  * Could show asterisk next to filename, but filename is not present on mobile
  * Could be in a subline below the title, but filename is not present on mobile
* [x] People avatars could be a bit smaller → from 44px to e.g. 36px
* [x] Avatars should move a bit closer together to save space
* [x] Author color borders could be var(--color-main-background) when author colors are not enabled so there is separation, and when author colors are not enabled the colors don’t make sense yet anyway.
* [x] Always show all participants in dropdown (including yourself so you know your own color)

## Content

* [ ] If possible, cursor of other collaborators could show (there is a tiptap component) #90

**Comment by juliushaertl** [comment]
@jancborchardt If I remembered correctly we also talked about getting rid of the menu bubble for links and move that to the menu bar, right? Then I'll add that as well

**Comment by juliushaertl** [comment]
@nextcloud/office Adding this to the 24 milestone, feel free to pick some low hanging fruits for some polishing during the beta phase.

**Comment by szaimen** [comment]
Maybe this should be added to the list as well?
https://github.com/nextcloud/text/issues/2203

**Comment by luka-nextcloud** [comment]
@jancborchardt @juliushaertl 
`Author color borders could be var(--color-main-background) when author colors are not enabled so there is separation, and when author colors are not enabled the colors don’t make sense yet anyway.`
If colors are not enabled, we still need a way to distinguish ownership, and we can do it by giving border color.
Is that correct?

**Comment by luka-nextcloud** [comment]
@jancborchardt 
`Author color borders could be var(--color-main-background) when author colors are not enabled so there is separation, and when author colors are not enabled the colors don’t make sense yet anyway.`

Do we want to always show author border?
If enabled -> border color = author color
If not enabled -> border color = var(--color-main-background)

**Comment by juliushaertl** [comment]
Closing as remaining points have separate tickets.
