### ISSUE TITLE
Click on website link does nothing

### ISSUE THREAD

**Issue by robeke** [nextcloud/text#2213]
**Describe the bug**
Left mouse-click to open a correctly formatted website link (hyperlink) in the markdown document does nothing.  Right-click on a correctly formatted website link will open the website in a new browser tab but also opens the right-click context menu in the new tab.

**To Reproduce**
1. Insert a correctly formatted website link in a markdown document
2. Hover over the link to verify it is what you expect and note that the cursor changes to a hand indicating a clickable link
3. Attempt to open the website with a left mouse-click on the link and note that it does not open
4. Attempt to open the website with righ mouse-click on the link and note that is opens in a new tab but also opens the right-click context menu

**Expected behavior**
If hovering over a link changes the cursor to a hand, a left mouse-click on the link should then open the hyperlink. Another option would be to require a press of the CTRL key to change the cursor to a hand and enable the left mouse-click to open the hyperlink (as is the case in LibreOffice).  If opening the hyperlink in a new tab using the right mouse-click is an intentional feature, it should not also open the right-click context menu forcing the user to take an extra step to hide/close this menu.

**Client details:**
 - OS: Manjaro Linux and Windows 10
 - Browser: Vivaldi
 - Version: 5.1.2567.49 (Chrome 98.0.4758.105)
 - Device: Desktop

**Server**
 - Text app version:  3.2.0
 - Operating system:  CentOS 7.9.2009
 - Web server: Apache 2.4.6
 - PHP version: 7.3.29
 - Nextcloud version: 21.0.9.1

**Comment by mejo-** [comment]
This is fixed with latest Text in Nextcloud 24.

**Comment by robeke** [comment]
Thanks.  FYI, I have not yet upgraded to Nextcloud 24 but with 22.2.9 which includes Text 3.3.1, the undesireable behaviour described above has not changed when using the Vivaldi browser.  However, in Firefox 101.0.1, a single left click on a link opens that link in a new tab correctly as expected.  I will hopefully be able to verify the fix using Vivaldi with Nextcloud 24 in the near future.
