### ISSUE TITLE
Can't use editing tools in rich workspace editor when text selected

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/text#2237]
The "add link" bubble goes on top and make it impossible (for people not using markdown, which is most of the people) to properly set styling.

https://user-images.githubusercontent.com/764332/158260471-823c3eaa-4ed6-46b8-9e04-1129b16df494.mp4

**Comment by juliushaertl** [comment]
This should be fixed with the latest release, can you fill out the issue template so that we know which version you are currently using?

**Comment by max-nextcloud** [comment]
Looks like Nextcloud 21 to me. We did not backport the fix to 21 - all later versions will show the link menu below the text instead.

**Comment by ImaCrea** [comment]
this is fixed with nc21 in deed. Thank you !
![Capture d’écran 2022-05-20 à 10 57 41](https://user-images.githubusercontent.com/764332/169493252-c5ca82dd-1ee4-42d6-b8c5-b1da24e7e3d4.png)
