### ISSUE TITLE
[Question] How disable auto text wraping?

### ISSUE THREAD

**Issue by stormenergy91** [nextcloud/text#2280]
Hi, I updated my Nextcloud to last release with Text version 3.3.1. I notice that now in all my .md files, inside the code widget, long lines of text now are automatic wraped. 

There is any way to disable this new feature and leav long text inline?

Reading codes is more confusing in this way, for me was better to scroll. 

Thanks

**Comment by juliushaertl** [comment]
Closing this as a duplicate. Feel free to follow https://github.com/nextcloud/text/issues/1407 for the discussion.
