### ISSUE TITLE
Scrollbars showing in mobile view

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#2295]
**Describe the bug**
With current master when opening a text in a small screen such as a mobile there are two scrollbars showing at the right.
This also leads to the menubar overflowing again.

**To Reproduce**
1. Open a text file
2. Set your browser dev tools to use pixel 5 screen size
3. enter halve a page - maybe a bit more
4. See two scrollbars at the side.

**Expected behavior**
The content should fit the screen.

**Screenshots**
![Bildschirmfoto von 2022-04-13 11-52-00](https://user-images.githubusercontent.com/97337118/163152611-53e1c0cb-eb7c-458d-80b9-8aa09ec4fa52.png)

**Client details:**
 - OS: linux
 - Browser: chromium with dev tools set to mobile view of pixel 5
 - Version: NC 24
 - Device: desktop

**Comment by szaimen** [comment]
Related: https://github.com/nextcloud/text/issues/2203#issuecomment-1058722666
