### ISSUE TITLE
Previews in Files don’t reflect view of rendered Markdown

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#23]
So now that we have this fancy WYSIWYG editor, we have kind of a problem with our default previews:
![markdown preview](https://user-images.githubusercontent.com/925062/57707076-4605b900-7667-11e9-8f6c-52e2044e71a8.png)

If you just created a document and used some headings and it looked nice, you will be confused when you see that.

Anything we can do there? Like a markdown renderer for the preview generator? cc @rullzer maybe?

**Comment by jakobroehrl** [comment]
It would be nice, if containing images are shown up, too

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/25212
