### ISSUE TITLE
Performance issue with fast typing within viewer

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2323]
**To Reproduce**
1. Open a text file in the viewer
3. Insert a table
4. Do some quick typing

**Actual behaviour**
Typing seems to lack behind and feels slow. 

- Seems to only happen in the viewer, not in rich workspace single file share links
- A quick profile didn't show anything obvious to me, but might need a deeper look again

**Expected behavior**
Typing should be fast and responsive

**Screenshots**

**Client details:**
Reproduced with Firefox and Chromium

As a sidetone this does not seem to happen

**Comment by juliushaertl** [comment]
@max-nextcloud Any idea how tables could cause that? I wouldn't expect that to be much different from the other nodes.

**Comment by max-nextcloud** [comment]
@juliushaertl I don't really have an idea. One issue might be that tables use NodeViews to render the additional buttons (add column, etc.). Right now i don't think there are other elements that use vue NodeViews and allow editing the content.

**Comment by vinicius73** [comment]
I was not able to reproduce the issue faithfully.
I've cold crashed the app only one time when I've run profiling.

Now I'm changing some potential performance issues and I will try profiling again.
