### ISSUE TITLE
Use setContent for collision resolution

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#233]
Since tiptap 1.23.2 setContent will dispatch a transaction, so we could preserve the collaboration history with that even when we apply changes from the file from outside:

https://github.com/scrumpy/tiptap/releases/tag/tiptap%401.23.2

**Comment by juliushaertl** [comment]
@max-nextcloud This would be interesting to reevaluate with the ongoing y.js work if we can resolve the manual file overwrite outside of text more nicely by applying the new document on top of the existing editing session.

**Comment by max-nextcloud** [comment]
Just talked about this with @juliushaertl. Some points to note:
* if we make locking mandatory (maybe including the locking app in server by default) there would be no need for collision resolution anymore.
* we could improve collision resolution by having one party handle it while the others keep editing using `setContetn` if the server side version is chosen
* The current version is currently mostly made read only to prevent overwriting the server side file. We could keep the editing alive if we managed to save the conflicting files in different places.

**Comment by juliushaertl** [comment]
Was done with https://github.com/nextcloud/text/commit/7512ef2ed051fa8aa7c5a4a92119de14c4050081
