### ISSUE TITLE
Don't prepend timestamp to image filename

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2338]
When a new image gets added to the document, we shouldn't prepend filename with a timestamp. Instead, filename conflicts should be resolved by appending ` (2)` etc. when a file already exists.

As discussed in the design review call, see https://gitlab.com/collectivecloud/collectives/-/issues/322 for details.

**Comment by susnux** [comment]
Looks like this is fixed with https://github.com/nextcloud/text/pull/2376 ?

**Comment by mejo-** [comment]
Yes, indeed. Thanks for checking @susnux :heart:
