### ISSUE TITLE
Allow to upload non-image files

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2339]
We want to extend the functionality to upload images (either via toolbar or via drag&drop) to allow uploading non-image attachments.

When uploading a non-image attachment, a link to it should be added to the document.

As discussed in the design review call, see https://gitlab.com/collectivecloud/collectives/-/issues/322 for details.

**Comment by eneiluj** [comment]
Hey, so how do we want to make that happen exactly?

* How should other file types be displayed in Text? Generic type icon or preview if available?
* Do we want to open the viewer on click for compatible file types like PDFs or videos?

More questions will come during the implementation :grin:.

**Comment by mejo-** [comment]
In a private discussion with @juliushaertl, we came to the conclusion that it might be rather confusing to allow non-image attachments in the standalone text editor. The most common usecase for standalone text is probably that it's launched from the Files app, and there people expect to have "control" over their files.

So it might not be the best UX to expose a feature that allows to upload files which then disappear in a hidden folder and are removed automatically once their reference is removed from the markdown file. Especially as there's no interface to list the attachment files in standalone text.

The situation is different if the Collectives app is the primary user interface. There, users will have an attachments list to browse the attachments, and the attachments are tied to a page UI-wise.

IIRC, our idea implementation-wise was to alllow non-image attachment uploads in the Text backend, but only expose the feature in the UI when inside a collective.

@juliushaertl please add if I missed something from our brainstorming :wink:

This is all not set in stone and I'd like to hear other opinions on it :speech_balloon:

**Comment by mejo-** [comment]
This already got implemented in #2378 thanks to gorgeous @julien-nc :blush:
