### ISSUE TITLE
JSON files are evaluated

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/text#236]
**Describe the bug**

Opening a raw JSON file results in the display of `[object Object]`.

**To Reproduce**
1. Create a file with `{}` as its content
2. Open it with Text
3. Experience bug

**Expected behavior**
JSON is displayed as plain text.

**Screenshots**
Content in former editor:
![Screenshot](https://cloud.teutsch.me/s/H4TFMbomjGGfQxj/download)
Content in Text:
![Screenshot](https://cloud.teutsch.me/s/96xabekM5sHspj2/download)
**Client details:**
 - OS: Windows 10 1809
 - Browser: Chrome
 - Version: 76
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 1.0.2

**Operating system:** Armbian Stretch

**Web server:** Apache2 2.4.25

**Database:** MariaDB 10.1.38

**PHP version:** 7.3.7

**Nextcloud version:** 16.0.3

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No log entries
```

#### Browser log
```
The escapeHTML library is deprecated! It will be removed in nextcloud 19.

```

</details>

**Comment by juliushaertl** [comment]
Thanks for reporting, I could reproduce that. Seems that axios is doing some magic here.

**Comment by karottenbaum** [comment]
It seems this is occuring again with 3.1.0, NC 20.0.3

**Comment by juliushaertl** [comment]
Oh that seems to be indeed a regression of https://github.com/nextcloud/text/pull/1187. Thanks for the notice :+1: 

Fix is in https://github.com/nextcloud/text/pull/1223
