### ISSUE TITLE
feature request: direct "save as" option for markdown text files

### ISSUE THREAD

**Issue by viisauksena** [nextcloud/text#2363]
Many Groups use Nextcloud in Handling Protocolls of Meetings,

it would be great to have a "save as" option directly out of the markdown editor. 
We use a template for collecting new topics for our next meeting, and fill them in as the meeting goes. 
at the end it would be great to simply **save as** the document ind still go on using the template.

the template is important since it contains many infos in the header which stay the same and also is shared and linked multiple times.

**Comment by mejo-** [comment]
Just a question @viisauksena: have you taken a look at the [Nextcloud Collectives app](https://apps.nextcloud.com/apps/collectives)? Collectives has support for page templates.

Inside your collective, add a new page "Meeting notes" and create a template inside this page. Afterwards, every new subpage of "Meeting notes" will use your template.

Collectives is basically a wrapper around the Text app that allows to organize your documents and shared knowledge.

The option to add a template for subpages of a page can be found in the three-dot-menu next to the page title.

**Comment by viisauksena** [comment]
thx @mejo . from my understanding it lacks the consitency of the shared link to non cloud users.

**Comment by mejo-** [comment]
Dear @viisauksena,

If I understand your request correctly, then you're currently using a normal text document as template by copying and afterwards editing it, right? Nextcloud already has a template feature for this. You should have a template folder inside your home directory. Place your template text document there (call it e.g. "Protocol Template.md"). Afterwards, when creating a new text document with the "+" Icon on top of the file list, you should see a modal where you can select between your templates and "empty file".

This should fit your usecase, no?

Regarding Collectives: collectives can be shared with a public link just like text files. It's not possible though to share single pages inside a collective. Just the collective as a whole can be share. If this is sufficient for you, I recommend that you look into the collectives app. It's developed with usecases like protocols and meeting notes in mind :relaxed:
