### ISSUE TITLE
Removing an image from a page does not delete it in files.

### ISSUE THREAD

**Issue by Fran6nd** [nextcloud/text#2364]
**Describe the bug**
Removing an image from a page does not delete it in files. So if we are not carefully, we fill the server with useless content.

**To Reproduce**
1. Upload an image.
2. Delete it from the text app.
3. See it does still exist in files (show hidden folders)

**Expected behavior**
When a pic is removed from all pages, it should be removed from the server?

 - OS:  iOS
 - Browser: safari
 - Version: 25
 - Device: Mac

Thank you guys.

**Comment by mejo-** [comment]
Hey @Fran6nd,

actually, the image file should be deleted when you remove it from your text file. But it only happens after you close all open editor sessions for that text document - or if you just close the tab without properly closing the editor - when the garbage collector job runs.

Could you verify that you closed all sessions of the text document? Is the image file still there in the attachments folder afterwards?

**Comment by vinicius73** [comment]
There is the Cleanup cron process, which is responsible to delete attachments.

https://github.com/nextcloud/text/blob/ab7dcc2b607c00b56a044e8a9a36a999eeb36e80/lib/Cron/Cleanup.php#L80

If the attachment is deleted at the same time when you remove it from the document you can't und it.
