### ISSUE TITLE
Store uploaded images in a more intuitive place.

### ISSUE THREAD

**Issue by Fran6nd** [nextcloud/text#2365]
**Is your feature request related to a problem? Please describe.**

* If one day we need to migrate from next cloud to something else, having an intuitive file location system would ease a lot any migration. 

* When I want to delete a MD file, I want to delete all the images/files it contains. So I need to find where they are. But it's a big mess when with have a lot of files.

**Describe the solution you'd like**
I would like that when I create a Text file `textfile` and upload an image in it, it creates a `textfile_content` folder in the same place and store all the file's content in here so, in case of a problem, it will be more "human friendly". Currently attachments are stored in folders like `.attachments.1213` which is confusing a lot.

Hope it's clear.

Thank you guys.

**Comment by vinicius73** [comment]
> When I want to delete a MD file, I want to delete all the images/files it contains. So I need to find where they are. But it's a big mess when with have a lot of files.

When you delete a markdown file, an event handler will be responsible to remove the attachments.

https://github.com/nextcloud/text/blob/ab7dcc2b607c00b56a044e8a9a36a999eeb36e80/lib/Listeners/BeforeNodeDeletedListener.php#L46

**Comment by mejo-** [comment]
As described by @vinicius73, you don't have to manually delete uploaded image files after removing it from the markdown document. So this issue should be solved for you, right?
