### ISSUE TITLE
Require optional CI checks to succeed

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#2372]
Github can only require CI checks to always succeed. If they do not run because a path filter is in effect the merge will be blocked.

https://github.com/dorny/paths-filter#conditional-execution could enable conditionally running actions and still require them.

**Comment by vinicius73** [comment]
For reference:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks

**Comment by mejo-** [comment]
Given that we still have flaky Cypress tests from time to time, I'm not sure whether we want to make them mandatory in the first place :thinking:
