### ISSUE TITLE
Focus order issues with viewer modal

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2387]
When opening a text file in viewer, focus remains in the background and the user needs to tab through all the contents in the background without seeing what they’re doing to get to the modal.

**Comment by vinicius73** [comment]
Scheduled to v5.3.2 https://github.com/nextcloud/nextcloud-vue/milestone/77

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/text/pull/2794
