### ISSUE TITLE
Markdown tables release

### ISSUE THREAD

**Issue by ocervell** [nextcloud/text#2413]
Is the markdown table support added by #114 included in the latest release ? I can't see them being rendered in the editor.

I can't build from `master` on my instance (lots of issues with `make` when I run it related to versions incompatibilities and such) and to my knowledge it is not included in the latest tag `v24.0.0`.

**Comment by juliushaertl** [comment]
Tables is part of 24. Please make sure to use the files from the official server releases as master will not work together with 24.
