### ISSUE TITLE
Image handling with pasted content

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2418]
- Paste a formatted text from other source (handbook)
- The content has a remote image

- Only the image node label shows (expected due to CSP)
- 🐛 It is not possible to remove the image node

**Comment by mejo-** [comment]
I'm no longer able to reproduce this bug @juliushaertl. When pasting copied content that contains remote images, the image gets displayed as broken (expected), but I'm still able to remove the image node. Please reopen if I missed something.
