### ISSUE TITLE
Add buttons to change list indentation level

### ISSUE THREAD

**Issue by flueders** [nextcloud/text#2438]
**Is your feature request related to a problem? Please describe.**
When I tried to create (un-)ordered lists with more than one level, I couldn't find an intuitive way to do this (since there is also no way to change to code view). My first workaround was to edit the file in an external editor, but this is no good solution, I think.

After some research, I discovered the "official" way of indenting list entries: pressing the tab key. However, there was [this issue ](https://github.com/nextcloud/text/issues/601) which added additional problems.

And, by the way, I still don't know how to decrease the list indention level using the keyboard.

**Describe the solution you'd like**
I would like to have a button to easily change a list entry's level. This could also be a drop-down underneath the list buttons.

**Describe alternatives you've considered**
As written before: using external editors or the tab key. There is also the [markdown editor app](https://github.com/icewind1991/files_markdown), which handles this problem by offering a code view.

**Additional context**
Maybe related to https://github.com/nextcloud/text/issues/234

**Comment by juliushaertl** [comment]
I think especially on mobile such buttons would generally make sense, where I also run into this from time to time. Would be interesting to see how other editors and mobile apps handle this, as adding just more icons to the menubar is nothing we can do any longer, as is is already really crowded now that we added more general formatting options.

One option might be a contextual toolbar that only displays relevant actions based on the content type, maybe at the bottom of the screen? Or a floating menu before or after the content https://tiptap.dev/api/extensions/floating-menu

cc @nimishavijay @jancborchardt @max-nextcloud @vinicius73

**Comment by nimishavijay** [comment]
> One option might be a contextual toolbar that only displays relevant actions based on the content type

This sounds good! I like the idea of having formatting options in the bottom of the screen since the top is getting crowded now.

> Or a floating menu before or after the content

Floating menu can cover the content of the document which can be a bit frustrating in my experience. 

This is how Google does it: When you select a bullet list, some of the formatting options (text and highlight color) are hidden and new options to increase and decrease indent as well as a check list toggle are shown. We could do something similar with the increase and decrease indent buttons
| No formatting | Bullet list |
|--|--|
|![image](https://user-images.githubusercontent.com/52440189/169866914-ebc14743-bada-4355-ac12-6b543845b690.png) | ![image](https://user-images.githubusercontent.com/52440189/169867004-12ffcd8f-ff4a-4eee-ab0e-4410841a1382.png) |

**Comment by flueders** [comment]
Thank you for your reactions!

@nimishavijay @juliushaertl I also really like the idea of having a contextual toolbar. Nevertheless, I suggest considering the screen size for the toolbar's placement. On large screens, it perhaps would make sense to just add a second row below the top menu, whereas on smaller devices, the "split" between top menu and (contextual) bottom menu is more convenient.

**Comment by susnux** [comment]
The floating menu looks ok, but I fear it might get messy like the MenuBubble for links (bad UX).
The idea of hiding stuff might be nice and simple, as some features are useless when editing lists:
- Bockquotes do not work
- Callouts do not work
- Codeblocks do not work

That are more than 2 buttons which would need to be replaced for the indention buttons :)

**Comment by max-nextcloud** [comment]
#2836 talks about the menu bar redesign. It will hopefully allow for adding these buttons.

**Comment by maximelehericy** [comment]
can confirm that decreasing the indent is impossible to do at the moment.... 😥

**Comment by max-nextcloud** [comment]
@maximelehericy 

> can confirm that decreasing the indent is impossible to do at the moment.... disappointed_relieved

Did you try `shift+tab`? - that just did the trick for me.
What type of list are you working on?

**Comment by susnux** [comment]
> Did you try `shift+tab`? - that just did the trick for me. What type of list are you working on?

On mobile, where you do not have a shift key, there is indeed no way to change the indention level

**Comment by maximelehericy** [comment]
> Did you try `shift+tab`? - that just did the trick for me.
> What type of list are you working on?

Hmmm, now shift+tab works to decrease the indentation, but tab stopped working to increase it 😑🙂

**Comment by JKBWP** [comment]
> Hmmm, now shift+tab works to decrease the indentation, but tab stopped working to increase it 😑🙂

Same here, but it's a bit strange: in the Text app, the menu catches focus when pressing tab, so it's not possible to increase the indentation level. But in the Collectives app (which uses the Text app afaik), it works.

**Comment by Pilzinsel64** [comment]
Oh yes, this is very strange. Need to download the file and raw edit it.

**Comment by Pilzinsel64** [comment]
> Hmmm, now shift+tab works to decrease the indentation, but tab stopped working to increase it 😑🙂

> Same here, but it's a bit strange: in the Text app, the menu catches focus when pressing tab, so it's not possible to increase the indentation level. But in the Collectives app (which uses the Text app afaik), it works.

Oh yes, this is very strange. This can't be excpected, especially because Shift+Tag still works.
Want to mentoin that before nc25.0.2 get released. Hope the ping is ok. @juliushaertl

**Comment by Pilzinsel64** [comment]
@JKBWP @maximelehericy 
This comment might help you: https://github.com/nextcloud/text/issues/3493#issuecomment-1328763115

**Comment by daFreeMan** [comment]
Editing a `.md` document in Firefox on a Win10 machine, I can use `TAB` and `SHIFT-TAB` to indent and outdent with no problem.

However, there's no tab button on the soft keyboard on my Android phone. That definitely needs to be added!

**Comment by jancborchardt** [comment]
@max-nextcloud @mejo- what do you think about making the "Lists" action a menu? It could be this – with the indentation entries disabled unless you focus a list:

> - Bulleted list
> - Numbered list
> - Checklist
> ---
> - Increase indentation
> - Decrease indentation

This is probably nice as grouping anyway to keep the amount of icons in the toolbar in check and prevent overflow to the 3-dot menu.
