### ISSUE TITLE
Trigger event on content change in syncService

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2462]
For Collectives, it would be very nice if Text could trigger an event when the content changed in syncService.

This way, we could update the page content that we pass into the [RichText component][https://gitlab.com/collectivecloud/collectives/-/blob/main/src/components/Page/RichText.vue] in realtime when the [Editor component](https://gitlab.com/collectivecloud/collectives/-/blob/main/src/components/Page/Editor.vue) is loaded (and has the up-to-date content from syncService anyway).

This would make life easier and we could avoid a `setInterval` loop in https://gitlab.com/collectivecloud/collectives/-/merge_requests/533/diffs#4ce2ff67d66d8af017006277e1e4338890fccb1b_192_192

**Comment by vinicius73** [comment]
Now, Editor triggers 4 events (without payload).

```
sync-service:idle
sync-service:save
sync-service:error
sync-service:sync
```
