### ISSUE TITLE
Unreadable link color when primary color is bright

### ISSUE THREAD

**Issue by scheinercc** [nextcloud/text#248]
**Describe the bug**
Links are currently displayed almost white on white for me.
See - "This is the link text" in the screenshot below

**To Reproduce**
It seems that `var(--color-primary)` is derived from  `/index.php/settings/admin/theming`
"Color". This value is in my instance currently set to `#F1F1F1`. As the background of the text editor is (obviously) white, it makes the text barely readable.

**Expected behavior**
I would expect links to be simply in the text color, just underlined, or alternatively to have the option to adjust text colors individually - if that is actually possible:
https://stackoverflow.com/questions/35465557/how-to-apply-color-in-markdown#35485694

**Screenshots**
<img width="648" alt="image" src="https://user-images.githubusercontent.com/817856/63343569-9b9de000-c391-11e9-94bd-322ff3bba6e4.png">

**Client details:**
 - OS: macOS 10.14
 - Browser: Firefox Nightly
 - Version: 70
 - Device: MBP

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)
 2.8.0

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Yes we should use --color-primary-element there which has a fallback for bright colors.
