### ISSUE TITLE
number removed during save / load when list item starts with number and a dot

### ISSUE THREAD

**Issue by BugerDread** [nextcloud/text#2480]
**Describe the bug**
I want to make a list like this:
![image](https://user-images.githubusercontent.com/26651175/172022740-9cf678c7-8896-4d60-b45f-23451253a15a.png)

... but when saved and opened again I get this:
![image](https://user-images.githubusercontent.com/26651175/172022760-8ce62c93-0828-47e9-9eb3-36ef9b4a8142.png)

... all the numbers where there is a dot and space after the number are lost during save / load.

**To Reproduce**
-  create new file
-  create list with item with number ending with dot as I did
- save / close it
- open it again
- numbers are missing

**Expected behavior**
Numbers stays there during save / load.

**Screenshots**
Provided at the top.

**Client details:**
 - OS: Ubuntu 20.04
 - Browser: firefox
 - Version: 100.0.2 64bit
 - Device: desktop PC

<details>
<summary>Server details</summary>

**Text app version:** 
3.4.1

**Operating system:**
Ubuntu 20.04

**Web server:**
apache

**Database:**
mysql

**PHP version:**
Version: 7.4.3

**Nextcloud version:**
Nextcloud Hub II - 23.0.5

</details>

**Comment by susnux** [comment]
This is an upstream issue of the `prosemirror-markdown` project: https://github.com/ProseMirror/prosemirror-markdown/issues/75

**Comment by mejo-** [comment]
Thanks. This was fixed upstream in https://github.com/ProseMirror/prosemirror-markdown/commit/0a7a13137fd23ce1e87564aca390b39e690b19d8 and wil be fixed when upgrading to the next prosemirror-markdown release.

**Comment by susnux** [comment]
1.9.2 is released (including this fix), waiting for the dependabot 😉
