### ISSUE TITLE
install on armv7 arch

### ISSUE THREAD

**Issue by schmidchr** [nextcloud/text#259]
**Describe the bug**
make install on armv7 fails with 
> Error: Cannot find module '/var/www/nextcloud/apps/text/node_modules/node-sass/scripts/install.js'

**To Reproduce**
install npm Version: 3.5.2-0ubuntu4 (no warnings or errors)
`apt-get install npm`
install dependencies and build the Javascript
`make`

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)
github 22|08|2019

**Operating system:**
 Ubuntu 18.04.3 LTS
 
**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7.2.21

Python 2.7.15+
openjdk 11.0.4 2019-07-16

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

</details>

<details>
<summary>Logs</summary>
  [npm-debug.log](https://gist.github.com/schmidchr/784d858e947e2b4e493ffb2bb5ee2eed)

</details>

**Comment by juliushaertl** [comment]
If you are just installing the app please use the release bundles. No npm should be needed then. If you want to start developing and building the app on ann arm plattform you will need to rebuild node-sass yourself as there are no binary releases done as described here: https://github.com/sass/node-sass/issues/1609
