### ISSUE TITLE
Emoji picker and "Insert image" should go into the overflow menu

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/text#2606]
Emoji picker and "Insert image" should go into the overflow menu
- In the long run, we could group the items into few menus: Formatting, headings, etc – however we might not have enough space
- Possibly think about moving the formatting bar to the bottom on mobile

**Comment by juliushaertl** [comment]
Closing as a duplicate of https://github.com/nextcloud/text/issues/2836 which contains more details about the mobile menu bar redesign
