### ISSUE TITLE
Missing/Wrong text for new text file (if German "Persönlich: Du" is chosen)

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/text#2613]
**Describe the bug**
Creation of new text file shows wrong text entry (see screenshot), if German language with "Persönlich: Du" is chosen.
![New Text](https://user-images.githubusercontent.com/4077683/175386474-ba12fb64-46fd-4081-8827-dddf2aa8c695.png)

**To Reproduce**
1. Got to Settings and choose "German (Persönlich: Du)" as language.
2. Go to 'Files'
3. Click on '+' to open menu for creation of new files

**Expected behavior**
Correct entry "Neue Textdatei" for new markdown files should be shown. This is actually shown if German "Formell: Sie" is chosen as language instead of "Persönlich: Du".
![New Text_correct](https://user-images.githubusercontent.com/4077683/175388023-82e7532d-b609-4e0e-8eff-b871654f52cb.png)

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 101.0.1
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.5.1

**Operating system:** Ubuntu 20.04

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.4

**Nextcloud version:** 24.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
n/a
```

#### Browser log
```
Insert your browser log here, this could for example include:

n/a
```

</details>

**Comment by susnux** [comment]
Already fixed for master: https://github.com/nextcloud/text/commit/1a793f006133f515a83b147d56b62ddc0c22bdcd
