### ISSUE TITLE
Remove the blue border around the textarea

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#2671]
Since https://github.com/nextcloud/server/pull/31584 was merged the text editor has a blue border.

Let's remove it.

> Just what's the blue border around the textarea, that shouldn't be there. :)

_Originally posted by @jancborchardt in https://github.com/nextcloud/text/issues/2627#issuecomment-1171536095_

**Comment by juliushaertl** [comment]
@jancborchardt This was added on purpose to indicate the keyboard focus better, could you confirm that we shall force-remove it on text?

**Comment by jancborchardt** [comment]
Yes, I mean this makes sense for general inputs and textareas, but e.g. in Word, Google Docs or apps like that you also don’t have a frame around the entire page. So in Text, this border should not exist.

cc @nextcloud/accessibility
