### ISSUE TITLE
Issue pasting certain tables

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2708]
- Save the following table as table.html
- Open it in the browser
- Copy it and paste it into text

```
<table>
<tr style="height: 63px;">
<th style="width: 15.8024%; height: 63px;">
Country
</th>
<th style="width: 31.7902%; height: 63px;">
Partner / Service Providers
</th>
<th style="width: 26.8211%; height: 63px;">
Website
</th>
<th style="width: 10.0771%;">
Type
</th>
<th style="width: 16.8673%;">
Customer type
</th>
</tr>
<tr>
<td style="width: 15.8024%;">Australia</td>
<td style="width: 31.7902%;">Foo</td>
<td style="width: 26.8211%;"><a href="http://www.nextcloud.com.com/">http://www.nextcloud.comm/</a></td>
<td style="width: 10.0771%;">VAR</td>
<td style="width: 16.8673%;">&nbsp;</td>
</tr>
</table>
```

![Screenshot 2022-07-12 at 08 15 46](https://user-images.githubusercontent.com/3404133/178421566-4f15664e-9a8c-4cc0-b17d-e0f7dd415fa7.png)

**Comment by juliushaertl** [comment]
More simplified repro:

```
<table>
<tr>
<th>Country</th>
<th>Partner</th>
<th>Website</th>
<th>Type</th>
<th>Customer</th>
</tr>
<tr>
<td>Australia</td>
<td>Foo</td>
<td>dfg</td>
<td>VAR</td>
<td>sdf</td>
</tr>
</table>
```

![Screenshot 2022-07-12 at 08 26 35](https://user-images.githubusercontent.com/3404133/178423160-610092c7-e3c5-4e34-bf76-73486c9b9265.png)

**Comment by juliushaertl** [comment]
@max-nextcloud Any idea on why that could happen?

**Comment by max-nextcloud** [comment]
I don't get it. This looks pretty much just like our table definition.

**Comment by juliushaertl** [comment]
Seems that browsers add a tbody to the Dom automatically:
![Screenshot 2022-07-13 at 06 54 50](https://user-images.githubusercontent.com/3404133/178653667-4fdd6ef6-d1d1-43ff-bba3-a27168066b25.png)

**Comment by max-nextcloud** [comment]
We should also have a rule for that:
```
{ 
  tag: 'table tbody :first-child th',
  priority: 60
}
```

The second query you tried looks more flexible and also very good. The first-child might be a `tbody`, `thead` or `tr`. One problem would be nested tables - as in a table nested in the first element inside another table all cells would fullfill the second query. But we don't support those anyway.

**Comment by max-nextcloud** [comment]
I can still reproduce this. I created a test that loads a table with that structure and that works just fine.

Maybe it's about pasting the structure.
