### ISSUE TITLE
Menu bar entries barley visible in dark mode

### ISSUE THREAD

**Issue by susnux** [nextcloud/text#2710]
**Describe the bug**
If the browser requests a dark color theme the menu bar entries are barley visible,
except the "add image", "heading" and "formatting help" buttons all other buttons are black on dark grey (while those three work and are shown as white on dark grey).

**Screenshots**
![screenshot of the editor](https://user-images.githubusercontent.com/1855448/178462100-4a5d400e-d773-4dbe-9237-1c4398c5fadd.png)

**Client details:**
 - Browser: Firefox 101
 - Version: NC @ master, text @ master branch

**Comment by juliushaertl** [comment]
Seems to come from 37fef5d91, will push a fix.
