### ISSUE TITLE
Feature request: Autolink feature should be optional

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/text#2723]
**Is your feature request related to a problem? Please describe.**
Our users reports, that the autolink feature is annoying, e.g. if the destination link does not exist or if the user accidentally did not put a space after a dot/period (see screenshot).

![2fadc8c7-0855-402f-9783-e367f2943f0f](https://user-images.githubusercontent.com/100593683/179351026-158fbf5e-ae6a-41dc-8359-e2c4cb9d073f.PNG)

**Describe the solution you'd like**
Give the user the choice to enable/disable the autolink feature and/or introduce a setting to enable/disable autolink feature systemwide.

**Comment by susnux** [comment]
I guess this can be easily implemented after https://github.com/nextcloud/text/pull/2718 is merged

**Comment by juliushaertl** [comment]
I'd say we should just finetune the autolinker to not convert things like example.com for the false positive cases instead of another config option. Or we try to only match links if they are surrounded by spaces.

**Comment by susnux** [comment]
> I'd say we should just finetune the autolinker to not convert things like example.com for the false positive cases instead of another config option.

The links created in the report are all fine and they are all valid, as `.md` is a valid TLD (it the TLD of Moldova).

> Or we try to only match links if they are surrounded by spaces.

That would also result in false positives: `... please create a readme.md file` will be automatically linked to `https://changelog.md/`.

I guess it is only safe to auto-link if a protocol is given (`http`, `https`...)

**Comment by juliushaertl** [comment]
Right, then I'd say it makes sense to only do this with for links that actually have a protocol set.

Should be fairly straight forward with https://tiptap.dev/api/marks/link#validate
