### ISSUE TITLE
Collaborator menu focus looks odd in dark mode

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2731]
<img width="210" alt="Screenshot 2022-07-20 at 08 16 14" src="https://user-images.githubusercontent.com/3404133/179910246-d1706833-02d0-4bdb-810e-7393c6d2ef22.png">

**Comment by vinicius73** [comment]
Non directly related: We are facing infinity loop errors from `focus-trap` when we interact with this element inside `viewer` 

Waiting to viewer update to the new version of `@nextcloud/vue`
https://github.com/nextcloud/nextcloud-vue/pull/3347
https://github.com/nextcloud/viewer/pull/1428
https://github.com/nextcloud/viewer/pull/1429

**Comment by juliushaertl** [comment]
Pushed a fix to #2757
