### ISSUE TITLE
Buttons do not have an accessible name

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2737]
- [ ] Close button is addressed in the next component release https://github.com/nextcloud/nextcloud-vue/blame/master/src/components/Modal/Modal.vue#L402-L404
- [x] Add proper label to the session list #2763 

![Screenshot 2022-07-20 at 20 41 57](https://user-images.githubusercontent.com/3404133/180182021-7ca0d138-ac1a-4033-b859-e596066b90b4.png)

**Comment by vinicius73** [comment]
Waiting for https://github.com/nextcloud/nextcloud-vue/issues?q=milestone%3A5.3.2

**Comment by juliushaertl** [comment]
Filed https://github.com/nextcloud/nextcloud-vue/issues/2907 to discuss how we handle potential patch releases as currently everything just went to master for 6.0.0

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/text/pull/2794
