### ISSUE TITLE
Black screen - 403 vendors~editor.js

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/text#274]
![TextNotLoading](https://user-images.githubusercontent.com/34820982/64077505-6bc7d400-ccd1-11e9-97bf-f8c7fe2ae5e0.png)
**Describe the bug**
Wanna open or create a file, get a black screen instead. Seems not all resources (vendor.js) get transferred.

**Expected behavior**
I get the interface and can start to edit my textfile.

**Client details:**
 - Browser: [e.g. chrome, safari] FF 68.0.2 (x64), Iron 66.0.3450.0 (x32)

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)  1.0.2

Nextcloud 16.0.4

Version: 16.0.4.1

Apps installed: 56

Apps updates available: 0
PHP

Version: 7.3.8

Memory Limit: 1 GB

Max Execution Time: 3600

Upload max size: 64 MB

Database

Type: mysql

Version: 10.2.26

Network log before clicking at the file
```
404 | GET | sozis-tiere.de | preview?fileId=347827&c=b6002f918bebe26a2d83a0796a2e30d2&x=273&y=273&forceIcon=0 | img | json | 1.11 KB | 2 B | 171 ms
-- | -- | -- | -- | -- | -- | -- | -- | --
404 | GET | sozis-tiere.de | preview?fileId=347831&c=0e6012b8c10d419ae8abbe6bc8b79617&x=273&y=273&forceIcon=0 | img | json | 1.11 KB | 2 B | 267 ms
404 | GET | sozis-tiere.de | preview?fileId=347829&c=08db9e35ee129c66956e8a06682e84f7&x=273&y=273&forceIcon=0 | img | json | 1.11 KB | 2 B | 187 m
```

Network log after clicking at the file
```200  | GET | sozis-tiere.de | vendor.js?v=147615ea1482658db3b5 | script | js | 33.88 KB | 94.58 KB | 88 ms
-- | -- | -- | -- | -- | -- | -- | -- | --
403 | GET | sozis-tiere.de | vendors~editor.js?v=0fbbe8d254d3b139328f | script | html | 916 B | 609 B | 88 ms
</details>
```

**Comment by juliushaertl** [comment]
> 403 | GET | sozis-tiere.de | vendors~editor.js?v=0fbbe8d254d3b139328f | script | html | 916 B | 609 B | 88 ms

Please check your webserver lconfig as the file should be served by that without any nextcloud code involved.

**Comment by Dubidubiduu** [comment]
Thanks again!

My Cloud runs in a subfolder and the .htaccess of the top-folder contained some stuff of my wordpress firewall (WP SECURITY)

Just deactivated "Avanced Character String Filter", "Bad Query Strings" functionality and another stuff in the .htaccess about ~ and it worked again.

Part of the .htaccess (actually already deleted the ~ in the snipped, but it was somewhere there)
```
# 6G:[REQUEST STRINGS]
<IfModule mod_alias.c>
RedirectMatch 403 (?i)([a-z0-9]{2000,})
RedirectMatch 403 (?i)(https?|ftp|php):/
RedirectMatch 403 (?i)(base64_encode)(.*)(\()
RedirectMatch 403 (?i)(=\'|=\%27|/\'/?)\.
RedirectMatch 403 (?i)/(\$(\&)?|\*|\"|\.|,|&|&amp;?)/?$
RedirectMatch 403 (?i)(\{0\}|\(/\(|\.\.\.|\+\+\+|\\"\\")
RedirectMatch 403 (?i)(`|<|>|:|;|,|%|\|\s|\{|\}|\[|\]|\|)
RedirectMatch 403 (?i)/(=|\$&|_mm|cgi-|etc/passwd|muieblack)
RedirectMatch 403 (?i)(&pws=0|_vti_|\(null\)|\{\$itemURL\}|echo(.*)kae|etc/passwd|eval\(|self/environ)
RedirectMatch 403 (?i)\.(aspx?|bash|bak?|cfg|cgi|dll|exe|git|hg|ini|jsp|log|mdb|out|sql|svn|swp|tar|rar|rdf)$
RedirectMatch 403 (?i)/(^$|(wp-)?config|mobiquo|phpinfo|shell|sqlpatch|thumb|thumb_editor|thumbopen|timthumb|webshell)\.php
</IfModule>
```

Guess it's somehow neccessary to use this filename?!
