### ISSUE TITLE
l10n: Understanding issue of "Front matter"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/text#2768]
https://github.com/nextcloud/text/blob/4b5848104a02d4bdc8e1e933e5eae1a5a2acf2d7/src/nodes/FrontMatter.js#L13

What is "Front matter"?

Should this string appear at Transifex?

**Comment by susnux** [comment]
> What is "Front matter"?

Some kind of metadata of the file, probably in most languages the translation for *metadata* would be better than the translation of *front matter*.

> Should this string appear at Transifex?

It was asked for a translatable heading.
Personally I do not think translating is that useful, as it is a technical term / proper name. ( https://github.com/nextcloud/text/pull/2751#discussion_r929749274 ).
