### ISSUE TITLE
Missleading keyboard behaviour in emoji picker

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2785]
**Describe the bug**
There's room for improvement in the keyboard navigation in emoji picker:

* [ ] When emoji picker is open, <kbd>Esc</kbd> should only close emoji picker, not the full editor modal
* [ ] <kbd>Tab</kbd> should insert the selected emoji
* [ ] When emoji picker is open, <kbd>Esc</kbd> followed by <kbd>Return</kbd> inserts the last selected emoji. This should not happen. It's only reproducible in public shares or Collectives right now, due to the fact that <kbd>Esc</kbd> closes the whole editor modal in other cases.

**Comment by PVince81** [comment]
unclear whether this needs a fix in the emoji picker or on the text app side (ex: prevent event bubbling) ?

for emoji picker issues specifically, please raise in the [nextcloud-vue repo](https://github.com/nextcloud/nextcloud-vue)

**Comment by mejo-** [comment]
Upstream issue regarding the unexpected behaviourt with <kbd>Esc</kbd> followed by <kbd>Return</kbd>: https://github.com/ueberdosis/tiptap/issues/3063
