### ISSUE TITLE
"Add link" popup dialog always displayed in first screen

### ISSUE THREAD

**Issue by Nyco** [nextcloud/text#279]
**Describe the bug**
_A clear and concise description of what the bug is._
The "Add link" popup dialog is always displayed in first screen, meaning when you scroll down from the top, this dialog is not in your screen but you have to scroll back up

**To Reproduce**
1. Type a long document that makes a scroll bar appear (twice of three time your browser window height)
2. Move to top
3. Select text in the window, the "Add link" popup dialog appears right above
4. Scroll down and select text in the second or third window, the "Add link" popup dialog appears in the first part

**Expected behavior**
_A clear and concise description of what you expected to happen._
GIVEN I have typed a long text that is larger that the browser windows content height
WHEN I click on text that is not in first part of text (scrolled up to top)
THEN the "Add link" popup dialog appears right above the selected text (expected result)
BUT the "Add link" popup dialog appears in first part of text (viewed when scrolled up to top) (actual result)

**Client details:**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 76.0.3809.132
 - Device: MacBook Air

> Some more information :
> 
> **Webserver:** Apache/2.4.6 (CentOS)
> 
> **Database:** mysql 5.5
> 
> **PHP version:** 7.2
> 
> **Nextcloud version:** 16.0.4
> 
> **Updated from an older Nextcloud/ownCloud or fresh install:** regularly updated since ownCloud 8
> 
> **Where did you install Nextcloud from:** tar.gz from Nextcloud web site
> 
> **Are you using encryption:** no

**Screenshots**

1. Input lots of text
![Capture d’écran 2019-09-04 à 13 41 42](https://user-images.githubusercontent.com/25348/64252019-20eccd00-cf1a-11e9-9b65-d8231c2791fa.png)

2. Select text
![Capture d’écran 2019-09-04 à 13 41 48](https://user-images.githubusercontent.com/25348/64252029-277b4480-cf1a-11e9-8f80-bbfe32bb2236.png)

3. Input URL
![Capture d’écran 2019-09-04 à 13 42 06](https://user-images.githubusercontent.com/25348/64252035-2ba76200-cf1a-11e9-8eb8-d88c98ad5224.png)

4. Enter
![Capture d’écran 2019-09-04 à 13 42 10](https://user-images.githubusercontent.com/25348/64252048-3104ac80-cf1a-11e9-9117-5d4ccc8f22ff.png)

5. Select text within the current top view
![Capture d’écran 2019-09-04 à 13 42 16](https://user-images.githubusercontent.com/25348/64252059-35c96080-cf1a-11e9-8f43-2be62d04f7a7.png)

6. Do not deselect, scroll down a bit
![Capture d’écran 2019-09-04 à 13 42 23](https://user-images.githubusercontent.com/25348/64252071-38c45100-cf1a-11e9-844e-6813cb776276.png)

7. Select new text below: popup is not located right above selected text
![Capture d’écran 2019-09-04 à 13 42 33](https://user-images.githubusercontent.com/25348/64252086-3eba3200-cf1a-11e9-847c-85a88e5484ff.png)

8. Scroll down to bottom of document and select text: popup seems not to be displayed at all
![Capture d’écran 2019-09-04 à 13 42 43](https://user-images.githubusercontent.com/25348/64252094-44177c80-cf1a-11e9-8a85-e67cbf70725b.png)

9. Do not deselect, scroll up to top: the popup is here!
![Capture d’écran 2019-09-04 à 13 42 47](https://user-images.githubusercontent.com/25348/64252100-48439a00-cf1a-11e9-8c2d-3e2feb3485d4.png)

**Comment by Zakkob** [comment]
Reproduced at:

**Client configuration**
- Browser: Chrome 77.0.3865.90
- Browser: Microsoft Edge 44.18362.329.0
- OS: Windows 10

**Server configuration:**
- Nextcloud version: 17.0.0
- Webserver: nginx/1.17.4
- Database: mysql 10.4.8
- PHP version: 7.3.10
- Updated from an older Nextcloud/ownCloud or fresh install: fresh install
- Where did you install Nextcloud from: docker pull nextcloud:latest
- Are you using encryption: no
