### ISSUE TITLE
Error 500 on PUT index.php/apps/text/session/create

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/text#2806]
**Describe the bug**
TXT and MD files can't be opened or displayed, I only get an empty screen. Preview in the Details tab works. 

readme.md is not shown in folder view, there's just a hypno wheel.

All worked fine until I upgraded to NC 24 and got a hard error in ExceptionSerializer at login. I restored all the files in webroot, restored the database and deleted the whole appdata.foobar folder. Everyting works fine except text app. Error in browser console is a 500 at PUT .../apps/text/session/create

Integrity check is ok.
I've run every repair, check and scan command on commandline.

Don't have a clue what might have caused this. No chance to delete/reinstall this app because it's part of NC core and delivered with the core. already tried disable/enable the app, didn't help.

**To Reproduce**
1. Go to any folder
2. Click on any .md oder .txt file

**Expected behavior**
File should be opened in Markup-Editor

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34368929/185071767-976c0280-9e14-4c84-9097-5c27323cb89a.png)

**Client details:**
 - OS: Linux, Windows
 - Browser: Chrome, Chromium, Firefox, Edge

<details>
<summary>Nextcloud Hub II (23.0.2)</summary>

**Text app version:** 3.4.0

**Operating system:** openSUSE

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.4.25

</details>

**Comment by Volker-K** [comment]
Ok, seems this error wasn't caused by rolling back to a previous release. 
As if by magic, it works again since today. I guess it had to do with network components (proxy, load balancer), existed for a few days and only after the rollback someone noticed.
Tonight someone changed something on other components that made it work again.

**Comment by itcihef** [comment]
I think this has to be handled because I have the same exact problem after I upgraded Nextcloud from 2.2.10 to 23.0.12 then to 24.0.8. Nothing went wrong during upgrades. Apache conf wasn’t modified in the process.

**Server:** Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux.

**Comment by juliushaertl** [comment]
@itcihef Please check your logs and file a new report with a filled out issue template if you still see this issue.
