### ISSUE TITLE
Disable text app fetching if switching to other lists (Recents)

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#2807]

**Comment by marcelklehr** [comment]
@juliushaertl Can you elaborate what this is about?

**Comment by juliushaertl** [comment]
Sure, sorry forgot to fill that out:

If you have a folder with a rich workspace open, which produces regular sync api requests, and then switch to the recent files list, the text session is still running in the background and the API request continue, even though the rich workspace is not visible anymore.
