### ISSUE TITLE
Author color is cleared when accent is added

### ISSUE THREAD

**Issue by drebs** [nextcloud/text#2871]
**Describe the bug**

If an accent is inserted in the end of a line colored with an author color, that line's color is cleared out.

I could only reproduce in Firefox, and in Chromium the problem doesn't happen.

It seems related to dead keys, as the color is cleared after an accent key is pressed but before the next key (the one that will receive the accent) is pressed.

The color is only cleared "locally" (that is, someone else editing the same document will not see the issue manifest).

When the accent is inserted in the middle of the line, then the color is not cleared.

**To Reproduce**

1. Create a .mdwn document and open it for editing.
2. Enable "Show author color" in the top-right "Active people" menu.
3. Type some text without accents.
4. Try to add an accented letter in the end of the line (eg. á).
5. Witness the author color be cleared for that line.

**Expected behavior**

The author color for that line should not be cleared and remain the same.

**Client details:**
 - OS: Linux Debian 11 (Bullseye)
 - Browser: Firefox
 - Version: 91.12.0esr
 - Device: Desktop computer

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)

3.5.1

**Operating system:**

Linux Debian 11 (Bullseye)

**Web server:**

Nginx version 1.18.0-6.1+deb11u2

**Database:**

MariaDB version  1:10.5.15-0+deb11u1

**PHP version:**

PHP version 7.4.30-1+deb11u1

**Nextcloud version:** (see Nextcloud admin page)

24.0.4

</details>

#### Browser log

Nothing shows up in the console.

**Comment by mejo-** [comment]
Hey @drebs, thanks for your report. I can confirm that the bug still exists on latest development branch.

**Comment by mejo-** [comment]
So this happens with all dead keys like acute (`'`), backtick/grave, circumflex (`^`), cedilla (`¸`), etc.

When typing a dead key as first character in a new paragraph, the author color doesn't get applied until the second key that accompanies the dead key is typed (even though the diacrit is displayed already).

**Comment by mejo-** [comment]
I guess that we have to check for [editor.view.composing](https://prosemirror.net/docs/ref/#view.EditorView.composing) and only apply the transaction that sets the author colors if it's not true. See https://discuss.prosemirror.net/t/plugins-and-characters-with-a-diacritic/2674/3
