### ISSUE TITLE
User mentions: improve search results

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2905]
**Describe the bug**
There's two issues with the results provides by user mentions:
1. The current user is always listed additionally to the search results. When searching for 'admi' as user 'jane', I get 'jane' and 'admin' as results.
2. Exact matches seem to be missing. Searching for 'admi' still lists 'admin', but searching for 'admin' doesn't list it anymore.

@luka-nextcloud

**Comment by luka-nextcloud** [comment]
@mejo- I cannot reproduce the first issue.
