### ISSUE TITLE
Add new features to RichTextReader

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2919]
**Describe the bug**
We need to add the new Text features to RichTextReader in order to use them in read-only mode (e.g. in Collectives):

* [x] rendering of user mentions (#2970)
* [ ] rendering of file attachments
* [x] attributes for page anchor links (#3345)
* [x] Rich link previews
* [x] Allow toggeling outline

**Comment by juliushaertl** [comment]
Good catch, is there any way we can unify the implementation so that future features would be implemented right away?

**Comment by mejo-** [comment]
For now, the way to go is to implement them in `RichText.js` instead of `EditorFactory.js`. That way, they will be part of both `RichTextReader.vue` and `Editor.vue`. If they contain features that are only needed for the Editor though, we need to make sure that these parts are only loaded in `EditorFactory.js` and not in `RichText.js` (e.g. see `EditableTable.js` vs. `Table.js`).

I'm sure there's smarter solutions to this :blush:

**Comment by mejo-** [comment]
File attachments are rendered as images that were failed to load in `RichTextReader.vue` at the moment. The reason is that we don't pass the session as a property to [`AttachmentResolver` in Collectives](https://gitlab.com/collectivecloud/collectives/-/blob/59b177ed3ea34995b2f7d452b82737516f9c9df6/src/components/Page/RichText.vue#L98-103).

Images are still loaded because we have a fallback mechanism for them (they're requested via the DAV url if session is unset).

Maybe something to discuss next week @max-nextcloud @vinicius73 and @eneiluj.

**Comment by mejo-** [comment]
Heading anchor attributes will be fixed by https://github.com/nextcloud/text/pull/3345.

**Comment by juliushaertl** [comment]
Added https://github.com/nextcloud/text/pull/2977 to the list
