### ISSUE TITLE
Focus visible looks funny on headings

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#2921]
**Describe the bug**
When focusing a heading it has a box around it with a little square at the lower left to make room for the `#` anchor:

![Bildschirmfoto vom 2022-09-15 08-09-21](https://user-images.githubusercontent.com/97337118/190327581-2341e958-f229-41e8-b619-429af1c5a988.png)

**To Reproduce**
1. Go to a text file with headings
2. Focus one of the headings
3. See highlighting with funny shape

**Expected behavior**
I did not expect this to be highlighted at all - but i guess that's for accessibility reasons. If highlighted i would expect this to only have a clear rectangle around the heading itself.

**Comment by susnux** [comment]
Does this happens only in a specific browser? Because for me it looks correct using Firefox 104:
![Correct highlight of border](https://user-images.githubusercontent.com/1855448/190356251-a7aa1671-6007-4ee5-9769-8a11cdeca745.png)

**Comment by max-nextcloud** [comment]
Yes... I was seeing this in chrome as well. Thanks a lot for looking into this @susnux!
