### ISSUE TITLE
Sync issue in a loadbalanced setup

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/text#2984]
**Describe the bug**
We use a loadbalanced setup with 2 nodes. We noticed that changes in  files are not synced, when multiple persons editing the same file. The problem occurs only when the requests goes to different nodes. If the requests goes to one node, the changes are in sync.

**To Reproduce**
1. Create a file and share with other persons
2. Multiple persons open the file and start editing
3. Changes are not synchronized, when the requests got to different nodes 

**Expected behavior**
Changes are synced

**Client details:**
 - OS: Windows, Linux 
 - Browser: Firefox
 - Version: 104.0.2
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:**  3.5.1

**Operating system:** Debian 11

**Web server:** Apache 2

**Database:** MariaDB 10.5

**PHP version:** 8.0

**Nextcloud version:** 24.0.5

</details>

<details>

**Comment by pbek** [comment]
Some people often see the changes of other people, other people don't. If those other people write into the document changes are never actually written into the markdown file.

**Comment by juliushaertl** [comment]
I could not reproduce this issue on a clustered setup, so it might be related to some configuration issue. Therefore I'd like to ask you to either [raise a support ticket](https://nextcloud.com/de/enterprise/) in case you have an enterprise subscription or head over to the [forum to get help](https://help.nextcloud.com).
