### ISSUE TITLE
Links to sections?

### ISSUE THREAD

**Issue by jans23** [nextcloud/text#299]
**Describe the bug**
My Markdown file contains several sections and I want to link to those. Is this possible somehow?

**To Reproduce**
1. Add a section, say `# section1`
2. Add a link to this section: `[link](#section1)`

**Expected behavior**
When clicking the link, section 1 should be displayed.

**Actual behavior**
A new browser window opens showing the folder in which the Markdown file is stored.

**Client details:**
 - OS: Linux
 - Browser: latest Firefox

**Comment by sunjam** [comment]
Are you referring to Categories, which are literally defined as folders in [Nextcloud Notes](https://github.com/nextcloud/notes/issues).
