### ISSUE TITLE
Add support for cmd+s shortcut on MacOS

### ISSUE THREAD

**Issue by Shinokuni** [nextcloud/text#300]
**Is your feature request related to a problem? Please describe.**
Currently, cmd+s shortcut opens browser save page dialog.

**Describe the solution you'd like**
It would be nice to have this shortcut supported like ctrl+s.

**Describe alternatives you've considered**

**Additional context**

**Comment by juliushaertl** [comment]
If someone wants to look into that, the save shortcut is defined here: https://github.com/nextcloud/text/blob/master/src/components/EditorWrapper.vue#L290

**Comment by juliushaertl** [comment]
Seems to work fine after the tiptap v2 migration

**Comment by provokateurin** [comment]
@juliushaertl this should also work for Ctrl+S on Linux, right? Because it doesn't work for me (both in text and collectives).

**Comment by provokateurin** [comment]
From the issue description it seems like ctrl+s was supported, should I open a new issue?

**Comment by mejo-** [comment]
Yes, this seems to be a bug indeed. Please open a new issue. Thank you @provokateurin!
