### ISSUE TITLE
show display names instead of LDAP-UUID when hovering over elements in editor

### ISSUE THREAD

**Issue by Toraih** [nextcloud/text#3067]
**Describe the bug**
When hovering over text in editor, UUID of LDAP-users are shown instead of their names

**To Reproduce**
1. Login as an LDAP-user into Nextcloud
2. Create a text-document (e.g. Test.md)
3. Edit the document
4. Hover with mouse over text to show author's name
5. UUID instead of name is shown

**Expected behavior**
Show author's name instead of UUID

**Screenshots**
can supply if requested...

**Client details:**
not relevant

## Server details

**Operating system**:
Ubuntu Server 18 + 22

**Nextcloud version:**
24.0.4 (snap)
(All NC-apps are up2date: 2022-09-28)

**Version of the richdocuments app**
Text V3.5.1

**Comment by juliushaertl** [comment]
@nextcloud/designers We currently have a variety of ways how this is handled. Some server parts also show the lid as a tooltip, but maybe we should indeed not use that as all.

**Comment by juliushaertl** [comment]
Fixed by #2678
