### ISSUE TITLE
App does not recognize the owner of an file in filesystem correctly

### ISSUE THREAD

**Issue by cchartmann** [nextcloud/text#3075]
**Describe the bug**
When I set the permissions to -rw-r--r-- and the owner of the file to root the text app thinks there is a connection problem, but lets the user type text.
If I set the permissions to -r--r--r-- and the owner of the file to root then the text app knows it's not possible to write, the app displays the contents of the file the user can enter no text and there is no error message.
In both cases, the file is read-only, but only in the second case does the text app know this.

It seems that the talk app only checks the file owner's permissions and not the permissions that nextcloud actually has.

**To Reproduce**
find an markdown file that you can edit in Nextcloud
go to that file on the shell of the Nextcloudserver
chown root:root filename
chmod o-w filename
and try to acces the markdown file in Nextcloud

**Expected behavior**
The text app should recognize that the file is read-only for Nextcloud, even though the file owner can edit it.

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: i dont know
 - Device: Laptop using the Browser

<details>
<summary>Server details</summary>  

**Text app version:**
3.5.1

**Operating system:**
Rocky Linux 9

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
8.0

**Nextcloud version:**
24.0.5
</details>

**Comment by juliushaertl** [comment]
Changing files on the file system outside of Nextcloud is not supported by server. Any files inside of the data directory are supposed to be readable and writable by the web server.
