### ISSUE TITLE
Easily add links to other nextcloud files

### ISSUE THREAD

**Issue by Klakla2** [nextcloud/text#308]
**Is your feature request related to a problem? Please describe.**
Adding links to other files in my Nextcloud instance is tedious.

**Describe the solution you'd like**
Add an 'Add Nextcloud link' icon to the right of the current 'Add picture' icon to easily add a link to a file in your Nextcloud instance just how you do it to add a picture.

**Describe alternatives you've considered**
It is already possible to select a file using the 'Add picture' icon, but that one adds a big picture like rectangular shape and the link is not to the file itself, but to the directory in which it is contained. But the code should be very eaasy to adapt to add in this case a proper link to a file in my text.

**Additional context**
## Current tedious:

In order to add a link to another file in your Nextcloud you need to

 1. Have additional files tab open in your browser showing the files in Nextcloud

 2. Click on the files tab

 3. Go into the directory with the file to be linked

 4. In order to avoid spelling issues right-click the file and attempt to rename it

 5. Copy the name of the file to the clipboard

 6. Click on the text editor tab

 7. Paste the name of the file into your text editor

 8. Highlight the copied name

 9. Click on the files tab

10. Right-click the file to be linked again

11. Select Details

12. Click on the icon to do a direct copy of the Nextcloud Link to the clipboard

13. Click on the text editor tab

14. Paste  the Nextcloud Link as a link in the text editor

15. Done - you have a link like [NextcloudApps.md](https://cloud.adfc-berlin.de/index.php/f/193740)

## Proposed:

1. Click on the 'Nextcloud link' icon right to the current 'Add picture' icon

2. Select the file in that GUI as you would select a picture

3. Done - you have a link like [NextcloudApps.md](https://cloud.adfc-berlin.de/index.php/f/193740)

**Comment by juliushaertl** [comment]
Sounds like a nice idea, we probably could also add a file picker option when a text is selected in addition to the existing url field for adding a link.

**Comment by twkrol** [comment]
Great idea. An more, I would like to make a link to another nextcloud file, and when clicked to let it open the file automatically as I pointed to file, not a directory.

**Comment by gorn** [comment]
It would be great to be able to use relative links - this way the editor can turn your filesystem in a very basic wiki. Please add another option when a word is selected - currently there is "add link" only. Something like "link to nexcloud file". In line with wiki style it would be great if the file is red if it does not exist and by clicking on it you would created nex .md file.

**Comment by azul** [comment]
I'll start working on this. Will probably use relative links with fileid like i did for images (#504):
```
[relative link](../other_dir/file?fileid=123)
```

They work outside of nextcloud as relative links and can still be found if the directory structure changes or is different because of how files were shared.

So first goal is the original proposal with relative links.
Will see if i can also get to 
- [ ] file link option in tooltip when text is selected
- [ ] link that opens right away

**Comment by azul** [comment]
I will stay away from red links for missing files for now for two reasons:
* How do you select a file from the dialog that does not exist yet?
* I am not sure if this even is part of the scope for text app.

I'm working on a [wiki app](https://gitlab.com/collectivecloud/wiki) which does have this as part of it's scope.
