### ISSUE TITLE
When embedding an image, cannot remove caption containing file name

### ISSUE THREAD

**Issue by sunjam** [nextcloud/text#311]
When embedding an image in Nextcloud Text, I do not want to display the caption at the bottom containing the file name `mwt_pathfinder_open_reference.png`  Please consider adding an ability to embed the image while removing the file name, or the ability edit the file name into nothingness that will not be displayed.

![Screen Shot 2019-09-25 at 2 37 57 PM](https://user-images.githubusercontent.com/1787238/65641622-203bd980-dfa2-11e9-9a90-aab7f5ef2578.png)

**Comment by juliushaertl** [comment]
You should be able to edit and remove the text from the caption.

**Comment by sunjam** [comment]
> You should be able to edit and remove the text from the caption.

Ah, now I understand how to edit and remove the caption text.

This behavior of listing the file name as a caption is not something I'm used to from any text application or editor.  My recommendation is to not display a caption by default, and simply embed the image.  Thank you!
