### ISSUE TITLE
Suggestions list of user mentions has bright background in dark theme mode

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3140]
**Describe the bug**
When entering <kbd>@</kbd> in dark theme mode, the suggestion list for user mentions doesn't follow the dark mode pattern. Instead, it uses dark font on bright background:

**To Reproduce**
1. Make sure you use the dark theme
2. Open a Text document
3. Start mentioning a user by typing `@`

**Expected behavior**
Suggestion list should follow dark theme design.

**Screenshots**
![2022-10-10T17:32:04,504597349+02:00](https://user-images.githubusercontent.com/3582805/194903603-5ef6c24e-fcb5-473a-ab9e-a50478fa4eea.png)

@luka-nextcloud

**Comment by meonkeys** [comment]
I also noticed Markdown table backgrounds are dark and unreadable even in light mode. I can't find a combination of light/dark mode and background image/color that makes the tables readable. NC server version is 25.0.2.3 and text app version is 3.6.0.

Here's a screenshot. The header cell in the table is readable, but the cells below are not:

![Screenshot from 2022-12-15 10-38-24](https://user-images.githubusercontent.com/50639/207941164-d6573c8b-cd70-4af7-a46b-cb5e4a798fcf.png)

**Comment by juliushaertl** [comment]
Thanks for reporting, that is already tracked in #3369
