### ISSUE TITLE
Reuse NcAutoCompleteResult, remove code duplication

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3142]
**Describe the bug**
Instead of shipping our own copy of `NcAutoCompleteResult` [as `components/Mention/AutoCompleteResult.vue`](https://github.com/nextcloud/text/blob/13af71a20ec7f9843451351e3b662ba1c3b76e49/src/components/Mention/AutoCompleteResult.vue), we should reuse the [upstream one from `@nextcloud/vue`](https://github.com/nextcloud/nextcloud-vue/blob/c4271b1c47206588d5d5f2bb91ea8cf68caf4599/src/components/NcRichContenteditable/NcAutoCompleteResult.vue). Currently it's not possible as `@nextcloud/vue` doesn't export `NcAutoCompleteResult`.

@luka-nextcloud

**Comment by juliushaertl** [comment]
Pending release for the exported components: https://github.com/nextcloud/nextcloud-vue/pull/3480#pullrequestreview-1180864032
