### ISSUE TITLE
Wrong italian localization of default text filename

### ISSUE THREAD

**Issue by digitall-it** [nextcloud/text#316]
**Describe the bug**
When creating a new text document in italian, the default filename has a typo, so that the extension is not .md (with a dot) but ,md (with a comma). 

**To Reproduce**

1. Set language to italian
1. Click on the plus button on the website
1. Create a new text document
1. Accept the default
1. Check out the file name

**Expected behavior**
I expect the default filename to end in .md instead of ,md.

**Screenshots**
![Schermata 2019-09-30 alle 18 30 29](https://user-images.githubusercontent.com/3578378/65897803-6d5be900-e3b0-11e9-8a72-c06354b6578b.png)

**Client details:**
 - OS: Apple OSX v10.14.6 (18G103) 
 - Browser: Apple Safari
 - Version: 13.0.1 (14608.2.11.1.11)
 - Device: desktop Mac

**Text app version:** 1.1.0

**Operating system:** CentOS 7

**Web server:** Apache/Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 17.0

</details>

**Comment by digitall-it** [comment]
The wrong translation gets pulled from Transifex. I required access and fix it from there, then will solicit here an update.

**Comment by jancborchardt** [comment]
Oh … @juliushaertl should this actually be translatable at all? Feels like the `.md` should be hardcoded to prevent stuff like this?

**Comment by jancborchardt** [comment]
Also @digitall-it thanks for your help! Did you fix it in Transifex meanwhile?

**Comment by juliushaertl** [comment]
Yes, the .md should be hardcoded.

**Comment by digitall-it** [comment]
Seems like I could not save the string on transifex, maybe my account hasn't the rights to do so; however, it has been set as a "suggestion", amongst the others, in the italian translation of the text section of the Nextcloud organization.
