### ISSUE TITLE
Images in subfolder are not displayed

### ISSUE THREAD

**Issue by severin-lemaignan** [nextcloud/text#317]
Images in my markdown document are placed in a subfolder of the working directory, like:

```
./figs/fig1.png
./document.md
```

When inserting an image in the document, eg:
```
![my image](figs/fig1.png)
```

the image is not displayed.

Text version: 1.0.2

**Comment by juliushaertl** [comment]
Let's track this as an enhancement since relative paths in general are not supported at the moment.

**Comment by wenzhuoz** [comment]
+1

It's such a nice feature to have. Markdown Editor (files_markdown) supports relative paths. I use them a lot in my own markdown documents, e.g.

    ![Certificates on System Keychain](Screenshots/Keychain_Access_System_Certificates.png)

QOwnNotes also inserts images by copying them to the `Notes/media` folder and adds relative paths like:

    ![IMG_20160629_103917](file://media/4726.jpeg)
    ![Screenshot from 2019-04-15 15-48-05](../media/390017047.png)

**Comment by HappyClint** [comment]
looking forward to this feature.

**Comment by Zaxzeng** [comment]
Any progress on this really useful feature?

**Comment by azul** [comment]
#504 addressed this and has been merged.
It should fix this. Please reopen if it does not.
