### ISSUE TITLE
Width attribute for images should be handled

### ISSUE THREAD

**Issue by severin-lemaignan** [nextcloud/text#318]
It would be very useful to be able to specify the dimension of images.

`pandoc` supports a [markdown syntax to specify the width of images](https://pandoc.org/MANUAL.html#images):
```
![my fig](fig.png){width=50%}
```
This syntax is particularly easy to map to HTML.

It would be great if Nextcloud's text could properly handle those.

Text version: 1.0.2

**Comment by juliushaertl** [comment]
We currently try to align with the commonmark spec as much as possible, but I agree that this would probably be useful. 

Ref: https://talk.commonmark.org/t/support-for-image-dimensions/148/37

**Comment by juliushaertl** [comment]
We currently have no plans to implement this feature, however if you or someone is interested in contribution, it would be good to evaluate how this syntax is handled by other markdown editors, especially if image tags still work, so this would require some research before starting an implementation.

**Comment by rvjr** [comment]
Gitlab supports this in its MD markup since some time now, and I think it really helps readability in many cases if you can size images as intended.

See this close issue for reference: https://gitlab.com/gitlab-org/gitlab/-/issues/28118

**Comment by mejo-** [comment]
Let's continue the discussion here: https://github.com/nextcloud/text/issues/4556
