### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#32]
We should have the important backend functions covered with integration test, especially logic related to pushing steps and save collision handling.

**Comment by max-nextcloud** [comment]
I'm planning to write integration tests while writing the y.js rewrite of the API. I don't think there's a point in adding tests before hand.
Not sure about which test approach to use though:
* integration test with sth. like behat
* integration test from within cypress just triggering api requests.

**Comment by juliushaertl** [comment]
Sounds good, let's close this one then. I think cypress would be fine as I feel it has a lower barrier for running them locally and we don't have any behat tests so far anyways.

**Comment by juliushaertl** [comment]
Also for a API level test I don't see much benefit in using gherkin as a test description language.
