### ISSUE TITLE
Rich workspaces: If there is no Readme.md, don’t show editor placeholder but move into "+" menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#3209]
Currently, every folder has the empty "Add notes, lists or links …" on the top. This leads to various issues such as:
- Always uses a lot of vertical space, for every single folder
- People can accidentally click into it
- People end up finding the feature annoying and disabling it completely even though they might find it useful on a folder-by-folder basis

Instead, we should only show it directly on top of the file list if a Readme.md is present. If not, we show an entry "Add description" at the bottom of the "+ New" menu. (This entry of course does not need to show if a Readme.md is present.)

Before | After (if a Readme.md is present, of course still show it directly)
-|-
![image](https://user-images.githubusercontent.com/925062/189092679-ee99ff79-0d60-4c7e-aa44-fc6f3b6c7912.png)|![image](https://user-images.githubusercontent.com/925062/189093430-0a54fcda-63ed-4f8a-b89d-86d5cfe98508.png)

cc @eneiluj @mejo- @max-nextcloud @juliushaertl 

As discussed @karlitschek

**Comment by juliushaertl** [comment]
@jancborchardt If you can provide a example files Readme text, we can add that :)

Besides that should all be doable, but moving to 26 as we have final freeze for 25 today.

**Comment by juliushaertl** [comment]
- [ ] Register new file menu entry to add the description
  - [ ] Check if we can show/hide it depending on the current folder status. If not this may need some extension of the server api for the new files menu
  - [ ] Only show the rich workspace area if a file is present
- [ ] Rename from ui parts from rich workspace to description

FYI @tobiasKaminsky to align this on the Android and iOS apps as well.

**Comment by jancborchardt** [comment]
> @jancborchardt If you can provide a example files Readme text, we can add that :)

@juliushaertl how about this:

> # Welcome to Nextcloud! 📱☁💻
>
> Here you can add a description or any other info relevant for the folder. It will show as a "Readme.md" and in the web interface also embedded nicely up at the top.

**Comment by dartcafe** [comment]
Isn't it simply just a folder description? Common users may have a problem in understanding, what a "rich workplace" may be. It needs to be explained. Simply naming it to "Folder Description" seems to be more understandable and needs no further explanation.

**Comment by Tummerhore** [comment]
This issue still exists for me with Nextcloud 26.0.3 and NC Text 3.7.2 (even though now, it only shows whitespace instead of the hint "add notes..."). Tested with latest versions of Firefox and Chrome. A quick glance in the dom revealed that the whitespace container is indeed rich text workspace. Please reopen this issue.

![grafik](https://github.com/nextcloud/text/assets/45203603/399afa10-ea24-4887-ac89-dc88510e41e2)
![grafik](https://github.com/nextcloud/text/assets/45203603/ea5624a9-39eb-44c6-bfec-9aef29d56292)
