### ISSUE TITLE
Bracket escaping issue

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#325]
I'm experiencing this issue on 1.1.0, though only with certain lines.

The following lines will all trigger the bug:

```
(Asdf [asdf asdf](asdf asdf) asdf asdf asdf asdf asdf asdf asdf asdf asdf)

* [asdf asdf asdf/asdf](Asdf Asdf)

* asdf asdf asdf [a--f asdf asdf](a--f Asdf Asdf)

* [Asdf asdf asdf asdf asdf asdf](Asdf asdf)
```

I saved this locally on my machine (vimwiki), opened it up in Text, changed a char, closed, then reloaded in vim. All brackets had escape chars.

_Originally posted by @ainola in https://github.com/nextcloud/text/issues/103#issuecomment-538218183_

**Comment by joshp23** [comment]
I came here to report the same issue
`[1]` becomes `\[1\]` and so on.
