### ISSUE TITLE
Code linebreaks & editor width

### ISSUE THREAD

**Issue by Gmentsik** [nextcloud/text#326]
As mentioned in #320  there are line-breaks in the code-section. I'd prefer horizontal scrollbars instead because that's what most IDEs have as default setting and most devs are used to I guess.

I'm sure there are a lot of non-devs using this app, but having an option to switch between floating and fixed width (like eg. gitlab) would make working with code or tables also lot easier.

**Comment by ahstro** [comment]
Created a PR to use horizontal scrolling instead of wrapping. I can expand on it and add the ability to switch, but I'm not sure if that's a desirable feature? 😇
