### ISSUE TITLE
Make builds deteministic again

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3271]
**Describe the bug**
Currently local builds will differ from build in the CI.

**To Reproduce**
1. Check out any commit build on ci - such as the latest from main branch.
2. run `make dev-setup && make build-js-production`
3. run `git diff`
4. see diffs

**Expected behavior**
Local builds should be the same as in CI.

**Comment by max-nextcloud** [comment]
It looks like in `editor.js` the id used by webpack to identify the hightlight js related plugins differs:

```diff
< ;t.exports=it},46661:(t,e,n)=>{var r={"./1c":[73870,"highlight/1c"],
---
> ;t.exports=it},23506:(t,e,n)=>{var r={"./1c":[73870,"highlight/1c"],

```

Then this is referenced in other places.

```diff
< ;break}return t.prev=3,t.next=6,r(46661)("./"+e)
---
> ;break}return t.prev=3,t.next=6,r(23506)("./"+e)

```

Then `editor.js` has different checksums in other files:

```diff
< {vendors:"60cf33faeddb22bd7a16",editor:"997a3640478f6e15d18b","editor-rich":"6c7799cca3323bd17956",
---
> {vendors:"60cf33faeddb22bd7a16",editor:"37a91e51db0af1c37b2a","editor-rich":"6c7799cca3323bd17956",
```

**Comment by max-nextcloud** [comment]
Looks like highlight.js - or rather the way we bundle it creates the issue.
Inside js/editor.js.map you will find your local directory that you build text in.
It's inside a longer webpack expression related to highlight.js:
```
"webpack:///text/node_modules/highlight.js/lib/core.js","webpack:///text/node_modules/highlight.js/lib/languages|/home/runner/work/text/text/node_modules/highlight
.js/lib/languages|lazy|/^\\.\\/.*$/|chunkName: highlight/[request]|groupOptions: {}|namespace object"
```

It looks like the substitution of the absolute path with the relative path only occured on the first entry.
I don't understand yet what the `|` separated entries mean.

I have no idea how the key I mentioned in the comment above is computed but i suspect it might be based on the path or the entry in the map file.

**Comment by juliushaertl** [comment]
Works fine for me locally again :)

**Comment by mejo-** [comment]
Oh wow, really? What changed? For me it doesn't work yet. after running `npm ci && npm run build` on latest `main` branch, I still have diffs in the `js/*` files.

**Comment by juliushaertl** [comment]
Hm, not sure if related to the node/npm version in use (as it was sometimes in the past) but here is mine to compare:

```
~ ➜ node -v
v16.18.1
~ ➜ npm -v
8.19.2
```

**Comment by juliushaertl** [comment]
Also let me update and try with the latest ones...

**Comment by juliushaertl** [comment]
Also works with 

```
~/repos/nextcloud/server/apps/text main ➜ node -v
v16.20.0
~/repos/nextcloud/server/apps/text main ➜ npm -v
9.6.6
```

**Comment by mejo-** [comment]
Mine is

```
> node -v
v18.13.0
> npm -v
9.2.0
```

**Comment by juliushaertl** [comment]
Ok, then you're using a different node version than CI, might be the issue
