### ISSUE TITLE
Milestone 1.1.0 is closed yesterday, but cannot be found in https://apps.nextcloud.com/apps/text

### ISSUE THREAD

**Issue by Klakla2** [nextcloud/text#330]
Title should be self-explaining.
Still only milestone 1.0.2 there.

**Comment by juliushaertl** [comment]
1.1.0 is now shipped with nextcloud 17 so there won't be app store releases anymore.

**Comment by Klakla2** [comment]
Sorry, this app is supported in Nextcloud 16, which will be End of Life not before 2020-04. So I expect it to be in the app store until then.

**Comment by Klakla2** [comment]
Now I read in the code appinfo.xml, that the Release 1.1.0 has

`<nextcloud min-version="17" max-version="17"/>`

So we would have to upgrade to Nextcloud 17 to get it.

This was not clear to me when reading in current app description:

``
Nextcloud Text is available for Nextcloud 16 and will be part of Nextcloud 17 as the default text editor. To start editing just open an existing markdown or plaintext file or create a new one.
``

**Comment by juliushaertl** [comment]
1.1.0 is basically v1.0.2 but for Nextcloud 17. I might release another patch update for 16 if there are bugfixes needed, but nothing big came up until now.

> Sorry, this app is supported in Nextcloud 16, which will be End of Life not before 2020-04. So I expect it to be in the app store until then.

It will be in the app store, but note that new features will only land newer Nextcloud versions. Also the app is not part of the shipped bundle with 16 so it is not bound to the EOL dates at all.
