### ISSUE TITLE
[Music App] - Additional List View "Genre" | Edit Meta Data | Delete Song Files

### ISSUE THREAD

**Issue by MoritzDPTV** [nextcloud/text#3317]
Hello there,

As mentioned in the title, there are three requests that complete the music app smoothly:
1) Additional List View "Genre": The music provides a list view where songs are listed showing their Title, Artist, Album and Length. By now, any further information, like the genre, can be taken from the meta data. It would be very great to add "Genre" for this list view, as this is an important information.

2) Edit Meta Data: With the dots at the right hand side of each song, the meta data can be seen. A very nice feature would be to be able to edit this meta data (as in conventional music players like iTunes).

3) Delete Song Files: Having all the music there and being able to sort it and organize it, it would also be very handy and data-efficient to be able to delete song files. Maybe easy to add in the song's menu (the dots at the right hand side of each song).

Thanks for your great work anyway, the music app improved already alot!

Best,
Moritz

**Comment by mejo-** [comment]
Dear @MoritzDPTV, it seems like the feature request targets the [Music app](https://github.com/owncloud/music), but you submitted it in the Nextcloud Text app project. Please submit your feature requests over at https://github.com/owncloud/music/issues instead.
