### ISSUE TITLE
Mobile Nextcloud App: [Scan Feature] - Scan Documents from Files | Further Improvements

### ISSUE THREAD

**Issue by MoritzDPTV** [nextcloud/text#3318]
Hey there,

the Nextcloud mobile app already provides a feature to scan documents using the camera. It would be great, to be able to scan documents not only from the camera as source but also from existing images from files (as provided by Dropbox and other scan apps).

Further improvements for the scan feature:
a) When taking a photo, the area of interest can be adjusted by moving the corners of it. Therefore, a zoom of the position of the currently selected and moved corner is shown at the position of the corner. The zoom is very helpful, but unusable if it is shown at the position of the corner as the finger that is moving the corner is covering the zoom. The zoom should be displayed e.g. on the opposite side of the selected corner, such that the user can see what the zoom is showing (Dropbox handles it that way).
b) When scanning multiple pages (using the camera) there is a delay (up to 15 seconds!) after pressing the “save” button (seems to depend from the amount of scanned photos). There should be some kind of pop-up illustrating that the saving is in progress (and its progress), otherwise it may be hit again, which leads to a crash of the app and loss of taken photos for the scan! Alternatively, the save button could be deactivated or something.
c) When saving the scan, the settings used for the last saving could be kept (e.g. quality). This would be very user-friendly.
d) After saving, there is a pop-up appearing asking whether images should be kept or deleted. This pop-up could be replaced with another checkbox within the saving settings. Thereby, the whole process is shortened and facilitated.

Thanks and cheers,
Moritz

**Comment by mejo-** [comment]
Hey @MoritzDPTV, please submit your reature request regarding the Nextcloud mobile app over at https://github.com/nextcloud/android (if you mean the Android app) or at https://github.com/nextcloud/ios (if you mean the iOS app).
