### ISSUE TITLE
ETA for the next release?

### ISSUE THREAD

**Issue by xplosionmind** [nextcloud/text#3319]
It is a looooong time since the latest release of this app, and I wonder when it will be ready so that it can be used in production… it is so awesome and useful!

**Comment by mejo-** [comment]
Dear @xplosionmind. Nextcloud Text is shipped with server releases these days, we don't do isolated releases of the app anymore. So you should already use the latest version of Text if you run an up-to-date Nextcloud server release (i.e. 24.0.6 or even 25.0.0).

**Comment by xplosionmind** [comment]
Thanks a lot for clarifying, @mejo-!
