### ISSUE TITLE
New Line Bug | Conflict Handler Issues

### ISSUE THREAD

**Issue by MoritzDPTV** [nextcloud/text#3324]
Hello there,

some of the text editor related issues occur only in the mobile app, some appear in both the desktop browser and the mobile app.

1) New Line Bug: This bug only applies to the mobile app. When creating a new line, two lines are created.

2) Conflict Handler Issues: When there is a conflict due to simultaneously edited and opened (text) files, the two versions are displayed in text boxes on a vertically split screen. Each file version has its button at the bottom of the screen to be able to select the corresponding version to continue with.
a) This bug only applies to the mobile app. Having a conflict, when selecting the "current version", the current version is opened in the editor. Unfortunately, the same does not apply to the selection of the "saved version". When selecting the saved version, the current version disappears but the screen remains split and nothing happens (see image "2_a_conflict_handler_stuck.png"). Closing the file and/or the app and reopening the text file will lead again to the conflict handler. Via the browser, both selections work.
b) This bug applies for both the desktop browser and the mobile app. The text boxes of the two file versions are not aligned. Some sort of offset is used for the left text box. As a result, at the top side and at the very end of the left text box, there is some space. As there is no such offset for the right text box, the very end of it is covered by the corresponding selection button, which should be avoided in order to be able to read the whole file to differantiate between both file versions. Furthermore, the two buttons for the selection are no centered at each half side of the screen but rather shifted to the left. In the browser this shift has a stronger impact due to the large scale (see images "2_b_mobile_app_top.png", "2_b_mobile_app_bottom.png", "2_b_browser_top.png", "2_b_browser_bottom.png").

Thanks for your work! If you need further information, let me know.

Best,
Moritz

**File type:** .txt

**Text app version:** 3.5.1

**Browser:** Mozilla Firefox 106.0.2 (64-bit)

**Client operating system:** Ubuntu 22.04.1 LTS

**Nextcloud iOS app version:** 4.5.3.0

**Mobile iOS version:** iOS 15.6.1

**Server operating system:** Ubuntu 20.04.5 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.3

**Nextcloud version:** 24.0.6 (Stable)
![2_a_conflict_handler_stuck](https://user-images.githubusercontent.com/35461483/198407969-fa7f2be0-8f2c-4227-9a82-c5566a26185e.png)
![2_b_browser_bottom](https://user-images.githubusercontent.com/35461483/198407973-3d4f0e34-035d-4b08-97ff-f33db4f4b8f3.png)
![2_b_browser_top](https://user-images.githubusercontent.com/35461483/198407975-8e81d30f-c540-4a43-b947-0d020956ade7.png)
![2_b_mobile_app_bottom](https://user-images.githubusercontent.com/35461483/198407978-57dc8ffe-6aa9-4322-82a5-cf669f4b9dcf.png)
![2_b_mobile_app_top](https://user-images.githubusercontent.com/35461483/198407981-5b853475-aeb0-48cc-8817-7521749fcd8d.png)

**Comment by juliushaertl** [comment]
Was fixed with https://github.com/nextcloud/text/pull/3972
