### ISSUE TITLE
missing emojis

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3357]
**Describe the bug**
emojis' icons are missing in the pickup menu

![emojis](https://user-images.githubusercontent.com/59349105/200031137-eb0f6693-1b77-4591-90b8-4ca0cc94d8b4.png)

**To Reproduce**
1. Go to Text app
2. open a document
3. click the emojis menu to add one in your text
4. many icons are missing, showing a white frame

**Client details:**
 - OS: macosmojave
 - Browser: safari and chrome, same result
 - NC Version: 2407
 - Device: laptop

**Comment by susnux** [comment]
This looks like a font issue, all emojis missing for you are emojis added with Emoji 13.0 in mid 2020.

After some research, it seems that your OS is too old to render those new emojis, as Apple only added Unicode 13 support to macOS Big Sur and later: https://www.macworld.com/article/234408/apple-showcases-several-new-emojis-coming-later-this-year.html

**Comment by punkyard** [comment]
oh ok then

could you capture your emoji list, so i can see how the first missing one looks like please?

![Capture d’écran 2022-11-08 à 12 30 50](https://user-images.githubusercontent.com/59349105/200554069-6a24274a-147c-4dc7-814c-fea62ca056fb.png)
![Capture d’écran 2022-11-08 à 12 31 36](https://user-images.githubusercontent.com/59349105/200554093-51b262db-caed-4bdb-800a-c371821c79b8.png)

**Comment by mejo-** [comment]
Yes, this is a known issue with old operating systems and the emoji picker. Not sure whether there's a way to update the emoji fonts on your system, but definitely out of scope for our app :grimacing:

That's how the emoji picker looks for me:

![grafik](https://user-images.githubusercontent.com/3582805/200556685-5f830397-f382-4046-8e03-4d8fd7711e4c.png)

**Comment by susnux** [comment]
> i can see how the first missing one looks like please?

So the first two missing ones are `smiling face with tear` and `disguised face`:
https://emojipedia.org/emoji-13.0/

> Not sure whether there's a way to update the emoji fonts on your system, but definitely out of scope for our app

Sadly not, but if your mac is newer then 2012 you should be able to upgrade to at least macOS Big Sure.

**Comment by punkyard** [comment]
thanks for the answers
i'll think about the update then ^^
