### ISSUE TITLE
Reconnect after idle broken

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3374]
**Describe the bug**
When the session is idle after 30 minutes, reconnect function is broken. After hitting reconnect, the editor is empty.

**To Reproduce**
1. Open a Text document
2. Wait for 30 minutes
3. See the "Document idle, click to continue editing" message
4. Hit "reconnect", see the empty editor afterwards

**Expected behavior**
Reconnect should work :wink:

**Comment by max-nextcloud** [comment]
It also looks like the disconnected editor sends lots of sync requests. At least that's what i observed on my local machine.

**Comment by max-nextcloud** [comment]
As a starting point setting [`IDLE_TIMEOUT`](https://github.com/nextcloud/text/blob/a436756a4bcc1169c9a467c119457b88a93f68bd/src/services/SyncService.js#L43) to a low value might be good.

The reconnect button is rendered in `src/components/Editor/DocumentStatus.vue` and triggers a `reconnect` event that is [handled by the Editor](https://github.com/nextcloud/text/blob/a436756a4bcc1169c9a467c119457b88a93f68bd/src/components/Editor.vue#L434).

**Comment by max-nextcloud** [comment]
Looks like the reconnect works fine. It just does not cause any changes in the ui because `$editor` is not responsive and therefore the components based on it do not get rerendered.
