### ISSUE TITLE
Improve idle session handling

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3375]
Some ideas how to improve idle session handling:

* Only start idle timer when [page becomes invisible](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)
* Set session to idle after 30 minutes of page being invisible
* Reset timer once [page becomes visible again](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)
* Automatically reconnect once [page becomes visible](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) if session got idle in the meantime

**Comment by max-nextcloud** [comment]
closing as duplicate of #1715
