### ISSUE TITLE
EML Reader

### ISSUE THREAD

**Issue by feutl** [nextcloud/text#339]
I am archiving parts of my emails as EML files (thunderbird export) together with my finished projects in NC.

Sometimes it would be nice to simple open that EML file like any other TXT file. Could this be somehow integrated into the "text" app, because for me this seems like a somehow perfect fit.

**Comment by juliushaertl** [comment]
Contributions are very welcome, the mimetypes that are opened as plain text are specified here: https://github.com/nextcloud/text/blob/33bff1dcf20d18b03a3286f73ccc44e75894b599/src/helpers/mime.js#L27

**Comment by feutl** [comment]
cool, thanks, I gonna dig a little deeper to understand the EML format, but seems basically text :)
Thanks

**Comment by putt1ck** [comment]
We're working on an EML Viewer app (supports proper layout as email clients do) - and I say working on but more or less just waiting for approval for first release.

**Comment by juliushaertl** [comment]
Lets close this as editing EML files is likely out of scope and the viewing is possible with https://apps.nextcloud.com/apps/emlviewer
