### ISSUE TITLE
File is deleted when pressing Ctrl+Delete

### ISSUE THREAD

**Issue by PatrickJosh** [nextcloud/text#3391]
Hello,

Apparently, when you press ‘Ctrl+Delete’, the file you are currently editing is deleted. In my opinion, this is very unintuitive since ‘Ctrl+Delete’ is used to delete the word after the cursor in many other programs. The file can still be restored from the trash, but in my opinion it should not be deleted in the first place.

If it is relevant:
I am using Nextcloud 25.0.1, which runs on Fedora Server 36.
My browser is Firefox 106.0.3 on Fedora 36.

**Comment by juliushaertl** [comment]
I'm wondering where that behavior is coming from as we don't have any handling for deletion of a file in text, so maybe viewer or the files app

**Comment by liquidat** [comment]
I can confirm this behavior on an upgraded as well as on a fresh installation of 25, see #3459 for more details.

This does NOT happen with 24.x versions, which can be easily tested with:
`podman run -d --rm -p 8080:80 nextcloud:24-apache`
vs
`podman run -d --rm -p 8080:80 nextcloud:apache`

**Comment by juliushaertl** [comment]
Coming from https://github.com/nextcloud/viewer/blob/d49b84edc1eee607212b82039d41bb50884fd596/src/views/Viewer.vue#L799-L801 so we should catch and not propagate the keypress for that.
