### ISSUE TITLE
Handle inline images as inline images

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3429]
For a long time we used inline images but rendered them on their own line like a block node. With #3282 we now treat images as block nodes. New images will be inserted with a leading and a trailing newline so they live in their own paragraph. They will then be rendered as a block node.

However images still exist that were inserted before that change. So we also render inline images to look like block nodes just like we did in the past.

I think we should:
* [ ] start rendering inline images as such - but maybe still fairly big - so people notice the change but it does not completely break their content.
* [ ] allow to convert inline images into block images by putting them on a separate line.
* [ ] make sure the file resolution magic that block images use to resolve attachments etc still works for inline images.

_Originally posted by @max-nextcloud in https://github.com/nextcloud/text/pull/3282#pullrequestreview-1179697980_

**Comment by max-nextcloud** [comment]
[2f7ff70](https://github.com/nextcloud/text/pull/3282/commits/2f7ff70e525ba8f11b8a7988fa083782c2632a90) could serve as a starting point.

**Comment by mejo-** [comment]
We decided to close this issue for now. We didn't have inline-rendered images before and so far nobody complained. So let's rediscuss this once it's a real usability issue for somebody.
