### ISSUE TITLE
Preserve bullet used for lists (-, * or +)

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3478]
**Describe the bug**
There are different bullets chars that can be used to write lists in markdown. Preserve them when editing the file in text.

**To Reproduce**
1. Create a file containing a list using `-` chars as bullets.
2. Open the file in text.
3. Change and save the file.
4. Inspect the file. All bullets turned into `*`.

**Expected behavior**
Preserve the type of bullet used.

**Comment by max-nextcloud** [comment]
Text reads the markdown source and turns it into data structures for the tiptap editor.
When saving the file it serializes these data structures into markdown again.

In order to preserve properties of the initial markdown they need to be handled in each of the steps involved:
1. Parsing with `markdown-it` (md -> html)
2. Loading with tiptap (html -> tiptap nodes and marks)
3. Processing done by tiptap / prosemirror
4. Serializing with prosemirror-markdown (tiptap nodes -> md)

We already loose the information what bullet was used in 1.
You can try this on the [demo site of markdown-it](https://markdown-it.github.io/):
No matter which bullet you pick the html code always looks the same.
But the internal representation notes the bullet down:
<details><summary>debug view on demo site</summary>
```json
[
  {
    "type": "bullet_list_open",
    "tag": "ul",
    "attrs": null,
    "map": [
      0,
      2
    ],
    "nesting": 1,
    "level": 0,
    "children": null,
    "content": "",
    "markup": "-",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  },
...
]
```
</details>

So what it would take would be turning this `markup` property of the token into an html attribute such as in `<ul data-bullet='+'>`.

In 2. we'd than have to convert this into an `attr` on the tiptap list node. Tiptap and prosemirror should leave this alone in 3. and 4. would be [handled](https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/to_markdown.ts#L87-L89) by `prosemirror-markdown` if the bullet was stored in the `bullet` attribute of the ul node.

**Comment by susnux** [comment]
Keep in mind that all list items should use the same bullet, e.g. new created items should use the bullet of the previous item. The same is valid for TODO lists.

**Comment by max-nextcloud** [comment]
@jancborchardt pointed out in the design review:
> We can use `style="list-style-type:'-';"` with a string value in the HTML: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

**Comment by juliushaertl** [comment]
But in the rendering we actually want a unified look, right?

**Comment by max-nextcloud** [comment]
Frankly... i don't know. I'd be fine with both. Having different bullets might be confusing because there is no way of creating them (thus far) and to me it seems unnecessarily complex. Otoh if the rendered output closer matches the source might be nice.
