### ISSUE TITLE
NC25: Tab key shortcut broken - NO possibility increase list intentional level anymore

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/text#3493]
**Describe the bug**
- Since Nextcloud 25 it is not possible anymore to increase the intentional level of a list entry. Traditionally it gets done via the TAB key but since NC25 this TAB key points to the close button.
- There is no other option to increase the list intentional level
- The only workaround: Download the file, enter the TAB in the raw text file, upload the file again and continue work. This can be annoying when doing slightly bigger lists.

_(Not sure if this bug should be addresses to the viewer app instead, as some people mentoined the TAB key still works in Collective Apps that uses text.)_

**To Reproduce**
1. Open a (new) text file
2. Start a new list and write the first entry
3. Press enter to start the second point
4. Now press TAB on keyboard to increase the list intentional level because we want to add a sub-entry to the collection

**Expected behavior**
The intentional level of the second entry should get increased by one, like this (As of Nextcloud 24.0.7):
![grafik](https://user-images.githubusercontent.com/23138465/204206006-d6071692-1027-4903-9c47-8f143e9e1520.png)

**Screenshots**
Instead the close button get focused.
![grafik](https://user-images.githubusercontent.com/23138465/204205886-dda5a8f5-6013-4059-a450-1d491be569f9.png)

**Client details:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 107.0
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.6.0

**Operating system:** Ubuntu Server 22.04.1 LTS

**Web server:** Apache

**Database:** MySql (MariaDB)

**PHP version:** 8.0

**Nextcloud version:** 25.0.1 & 25.0.2 RC1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Pilzinsel64** [comment]
Another important notice:
- This happens only if there is NO headline in the document. It doesn't metter where that headline is, as soon as one headline is there, the TAB key works again.

**Comment by rba7sp** [comment]
I'm having the same issue and can confirm the workaround.

**Comment by BernhardBaumrock** [comment]
@Pilzinsel64 you are a genius, thank you!

**Comment by mejo-** [comment]
Another noticable difference: when logging the `keydown` and `keyup` events in Firefox Debugger, the parent element is `div.ProseMirror` in documents where tab indention doesn't work, but `div.ProseMirror.ProseMirror-focused` in documents where it works.

**Comment by mejo-** [comment]
This is still an issue and needs further debugging.
