### ISSUE TITLE
Text app Sidebar do not open in Nextcloud 25.0.1

### ISSUE THREAD

**Issue by NielBuys** [nextcloud/text#3494]
**Describe the bug**
When I open an txt or md file in my Nextcloud 25.0.1. The sidebar do not open. It looks like its opening but then the screen goes behind the text window. This worked in Nextcloud v24 before I upgraded.

**To Reproduce**
1. Go To an md or text file and open it.
2. Click on the 3 dots and press open sidebar
3. The sidebar do not open.

**Expected behavior**
I expect the sidebar to open

**Client details:**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 107.0
 - Device: Laptop

<details>
<summary>Server details</summary>

**Text app version:3.6.0** 

**Operating system:Ubuntu 20.04**

**Web server:Apache v2.4**

**Database:MySQL 8**

**PHP version:8.0**

**Nextcloud version:25.0.1** 

</details>

**Comment by juliushaertl** [comment]
Is the name or folder path containing any special characters or spaces? Then this would already be addressed with https://github.com/nextcloud/viewer/pull/1470

Please also report back if there are any javascript errors reported in the browser console

**Comment by NielBuys** [comment]
The name has spaces but no special characters. 
Screenshot of Name
![image](https://user-images.githubusercontent.com/8427483/204285278-bf212d83-7d87-49c3-a9b7-e929dd6be9be.png)

I removed the spaces in the name it did not help
![image](https://user-images.githubusercontent.com/8427483/204285525-385625b6-9e3b-4191-99e8-90f46897a6de.png)

Here is the errors in my browser console. The below error is repeated 2 times.
![image](https://user-images.githubusercontent.com/8427483/204284801-9bc25935-d0a6-427d-8b5f-265d78458d23.png)

Then this error also. But I don't think this error is needed for this Issue.
![image](https://user-images.githubusercontent.com/8427483/204284960-5c68ef72-a236-4d05-9404-f4cdf753e4de.png)

Thanks for reply

**Comment by juliushaertl** [comment]
Thanks, in that case this will be fixed in the upcoming 25.0.2 with the above mentioned viewer app pull request.
