### ISSUE TITLE
Cypress snapshots lose css formatting

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3499]
**Describe the bug**
When looking at a cypress snapshot in the list of tests run it's displayed without the css applied.
Going back to the current browser state css is also gone.

**To Reproduce**
1. Open Cypress
2. Run tests
3. Hover over previous steps

**Expected behavior**
The css should still be applied and the view should look like during the test run.

**Screenshots**

<details>
<summary>
After the test test everything is still good:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-31](https://user-images.githubusercontent.com/97337118/204515043-79272ffb-623c-4fc3-8601-53f6633bb189.png)

</details>

<details>
<summary>
Hovering over the test step:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-47](https://user-images.githubusercontent.com/97337118/204515046-96f0b219-0221-4a01-898d-fff89ea3f228.png)

</details>

<details>
<summary>
After hovering even the current state is broken:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-54](https://user-images.githubusercontent.com/97337118/204515050-9d596083-d625-498a-9a21-4836aace73e4.png)

</details>

- Browser: Chromium
- Text version: current master - but happens for a while.
- Cypress current (11.2.0) but also happens for a while.

**Comment by mejo-** [comment]
This seems to be a generic issue with Nextcloud Cypress tests - at least the same happens in Collectives Cypress tests as well.

**Comment by max-nextcloud** [comment]
https://github.com/cypress-io/cypress/issues/16066 seems to be the cypress issue in question.

![Bildschirmfoto vom 2022-11-29 19-39-48](https://user-images.githubusercontent.com/97337118/204618631-2ad04392-19cd-420c-8053-9be34e91e475.png)
Cypress snapshot on the left misses all the stylesheets that have a media attribute.

**Comment by luka-nextcloud** [comment]
I would close it as an upstream issue since there is nothing we can do about it for now.
