### ISSUE TITLE
hide images filename in text/collectives

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3506]
Hi
Filenames really kill the design, especially when not needed ^^
Could we see an evolution of an option that will show/hide images legend in text documents and Collectives?

Thans for the great job so far!

**Comment by susnux** [comment]
So this is about hiding the description or about not using the filename by default?
Until then: You can always remove the default description so no text is shown.

**Comment by punkyard** [comment]
> Until then: You can always remove the default description so no text is shown.

no i can't! that's my request :)
how do you do this? a setting i haven't seen yet?

**Comment by punkyard** [comment]
If i selected the text under the picture, and erased it, it came back automatically.

@susnux are you referring to another way to have the text not displayed?

**Comment by susnux** [comment]
> If i selected the text under the picture, and erased it, it came back automatically.

@punkyard you have to press `enter` after erasing it (the image description is only saved when pressing enter).

**Comment by punkyard** [comment]
génial !
that's what i needed to hear
thanks a lot @susnux

**Comment by juliushaertl** [comment]
Maybe we should consider making the input more obvious? By default we could also leave the alt text empty as the filename is probably not very helpful in most cases.

**Comment by mejo-** [comment]
In my opinion the situation improved vastly with your fix from #3631 @juliushaertl! People who are annoyed by the filename will click on it and either try to remove it or replace it with a proper description. And now this will work for users even if they don't press enter. So I would regard this issue as fixed :wink:
