### ISSUE TITLE
no horizontal bar in firefox

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3508]
Hi
with NC 24.0.7, Collectives and texts don't display their horizontal bars in 100.0 Firefox Release May 3, 2022.
This happens when there is only one bar. If I add a second bar, right after the first one, one of the two is displayed .. weird, no ?

just to let you know
have a great weekend everybody

**Comment by juliushaertl** [comment]
Can you post a screenshot on what bars you are referring to? I don't think I fully get your report.

**Comment by max-nextcloud** [comment]
My mention above was unrelated. Just so it does not confuse people.

I understood the bars as `<hr/>` tags added by pressing `---`. Haven't tested in NC24 yet. NC25 it works for me in Firefox.

**Comment by luka-nextcloud** [comment]
@punkyard It no longer happens with the latest firefox release.
