### ISSUE TITLE
Prefix heading ids to prevent naming conflicts

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#3513]
## This is a https://github.com/nextcloud/text/labels/good%20first%20issue if you...

* have a basic understanding of javascript.
* have a working nextcloud development environment to test your changes.

If you would like some guidance feel free to ping @max-nextcloud or join the [public text channel](https://cloud.nextcloud.com/call/9tq2th3p).

## Problem
If you enter the text "Nextcloud" and format as heading, it will be indented.
This is because css that targets `#nextcloud` is applied to it.

## Solution
* Add a `heading-` prefix to the id in html to avoid id naming conflicts in https://github.com/nextcloud/text/blob/main/src/nodes/Heading/HeadingView.vue#L22
* Make sure the links in the outline **do not** have the prefix and still work.

## To Reproduce
1. Create a new markdown file
2. Open the file in the text editor
3. Enter "# Nextcloud"
4. The word "Nextcloud" will be outpus as heading but also be indendet.

## Expected behavior
The word "Nextcloud" will just be a heading without indentation.

## Screenshots
![image](https://user-images.githubusercontent.com/6613614/205507777-005be970-4c9b-4c80-8381-27d0cef2fe54.png)

## Context
<details>
<summary>Client details</summary>
 - OS: Windows 10
 - Browser: Vivaldi 5.5.2805.50, Firefox 107.0.1
 - Device: desktop
</details>

 - Nextcloud version: 25.0.1

## Side note
https://github.com/nextcloud/text/issues/3513#issuecomment-1336485033 outlines a workaround which should be ignored for resolving the matter but can be used by anyone finding this issue and looking for a temporary solution until a fix is shipped with the test app itself.

**Comment by arnowelzel** [comment]
A workaround is to add the following CSS using the ["Custom CSS"](https://apps.nextcloud.com/apps/theming_customcss) app. It seems there is a global style for `#nextcloud` which adds a padding to the left for every element with the ID "nextcloud":

```
.text-editor__wrapper div.ProseMirror #nextcloud {
  padding-left: 0 !important;
}
```

**Comment by juliushaertl** [comment]
Thanks for reporting.

Seems we need some kind of prefix to avoid id naming conflicts in https://github.com/nextcloud/text/blob/master/src/nodes/Heading/extractor.js#L13

**Comment by max-nextcloud** [comment]
:clap: such a good catch! Congratulations.

**Comment by max-nextcloud** [comment]
In order to make sure this https://github.com/nextcloud/text/labels/good%20first%20issue is easy to parse I tried to provide all information needed in the issue description above.

If some aspects of it are still unclear please ask so i can clarify further.

If you think this should be done differently please open a new issue describing your solution. Let's keep this issue focused on the proposed solution to provide clarity for whoever wants to tackle it.
