### ISSUE TITLE
Format markdown code for tables

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3516]
## This is a challenging https://github.com/nextcloud/text/labels/good%20first%20issue if you...

* want to **learn about how text serializes its content** to markdown.
* **know your way around javascript** including functional programming styles.

If you would like some guidance ping @max-nextcloud or join the [public text channel](https://cloud.nextcloud.com/call/9tq2th3p).

## Problem
When creating a table the resulting markdown source is not aligned.

## Solution
Create pretty tables like https://www.tablesgenerator.com/markdown_tables

Currently tables are written to the markdown files like this:
```
| A | B | C |
|---|---|---|
| Columns | with long | text |
```

The goal of this issue would be to make sure the table is formatted in the markdown file like this:
```
| A       | B         |  C   |
|---------|-----------|------|
| Columns | with long | text |
```

<details>
<summary>Alternatives we considered</summary>

* We could also try to preserve the format of existing tables. However that seems tedious as every cell could have it's own spacing and then editing the content might need to change that as well.
* For some tables it may make more sense to drop alignment - for example if they include a single large cell that would spread the entire table over a multi screen width.
*For now we settled on creating nicely formatted tables. This could be changed in the future based on user feedback.*
</details>

### Testing

The existing [test for serializing tables](https://github.com/nextcloud/text/blob/main/src/tests/nodes/Table.spec.js#L64-L69) loads a [markdown input file](https://github.com/nextcloud/text/blob/main/src/tests/fixtures/tables/basic/table.md), serializes it and checks the output is the same as the input.
The table in the markdown file is currently not aligned. If you change it to be nicely formatted the test will fail because text currently does not serialize the table content that way. So now you have a failing test you can start from.

### Markdown rendering of tables

The `toMarkdown` functions in [the table nodes](https://github.com/nextcloud/text/tree/master/src/nodes/Table) define how to serialize the table to markdown.
Each file in that folder describes a node, which corresponds to an html element in the table. Rendering of the result starts with rendering the `Table` node, descends into to the `TableHeader` node, then further into the `TableHeadRow` and then `TableCell` and so on. Right now the `TableCell`s just start with a leading whitespace and end with a trailing one. In order to format the table nicely the number of whitespaces will have to depend on the largest cell in a given column.

### Computing the cell width

In order to compute the width of the columns the content of the entire table needs to be considered. The to markdown function gets arguments of the [following form](https://github.com/ProseMirror/prosemirror-markdown#MarkdownSerializer.nodes):
```
toMarkdown(state: MarkdownSerializerState, node: Node, parent: Node, index: number)
```
The `node` argument is a ProsemirrorNode and you can use [`descendants`](https://prosemirror.net/docs/ref/#model.Node.descendants) to iterate through all of the child nodes.
Starting from the `Table` itself, iterate through all of the children. We're only interested in the `TableCell`s here. The function handed to `descendants` will get the child node as a first argument. If it's not a `TableCell` just return true (so `descandents` continues to look for `TableCell`s inside the node in question. If it's a table cell you can use the index to identify the column this `TableCell` is in.

### Providing the cell width to the `TableCell` `toMarkdown` function

Markdown serialization happens based on `prosemirror-markdown`. [`MarkdownSerializerState`](https://github.com/ProseMirror/prosemirror-markdown#----class----markdownserializerstate) can be used to track the required width for each column.

## Additional context

Strictly speaking this is not part of perserving md source - still came up when discussing #593 .

**Comment by bronson** [comment]
You make a great point. When the WYSIWYG editor goes to modify a Markdown table, it's unclear whether it should preserve cell spacing or not. It could do one of three things (that I see):

1. Reformat the entire table by omitting unnecessary whitespace. This is the current behavior, which produces tables that can only be edited by GUI Markdown editors that support tables.
2. Reformat the entire table by justifying each cell. Some users may prefer this, some users may find it objectionable (and, as you say, user response might depend on the width of the user's screen).
3. Reformat just the cell that was edited, leaving the rest of the table alone. For occasional edits this might be preferable, but if the editor updates a lot of cells in the table, it quickly turns into #1.

It doesn't seem like any of these will work for every case. Options 1 and 3 are guaranteed to corrupt tables that weren't created with this Markdown editor, and Option 2 is likely to produce pathological files. Using a heuristic to decide between options 2 and 3 might be productive, or it might not make anyone happy.

The upside of `.md` files: they're super flexible! The downside of `.md` files: they're super flexible.

So, just to make sure I understand, you're suggesting someone implement #2, and then maybe use a heuristic to crunch down some cells if line widths are getting out of hand?

**Comment by max-nextcloud** [comment]
> So, just to make sure I understand, you're suggesting someone implement Option 2, and then maybe use a heuristic to crunch down some cells if line widths are getting out of hand?

Yes. Exactly. That seems the most promising approach so far to me.

From my understanding 3. is more difficult to implement as it would require extracting the information how much whitespace there is and keeping track of it during the editing. I agree that a heuristic combining 2 and 3 would be ideal.

**Comment by dacog** [comment]
Just as @bronson wrote, 

> The upside of .md files: they're super flexible! The downside of .md files: they're super flexible.

Given that, and that „It doesn't seem like any of these will work for every case“, would it make sense to make this a configurable setting to maintain that flexibility and give the users a choice?

That would mean there should be a decision on the default setting, and a couple of alternatives to choose from. 

https://www.tablesgenerator.com/markdown_tables also gives the user the choice to select how to format the table

![4156B647-5B4F-4703-AE71-5CD3F43F1454](https://user-images.githubusercontent.com/557703/210043990-231409c0-9815-4185-ad32-a163b5299d5b.jpeg)

Would something like this make sense?

**Comment by max-nextcloud** [comment]
> Given that, and that „It doesn't seem like any of these will work for every case“, would it make sense to make this a configurable setting to maintain that flexibility and give the users a choice?

Let me quote https://nextcloud.com/design/ here:

> * Software should get out of the way. Do things automatically instead of offering configuration options.
> * When people ask for a setting, find out what the root of the problem is and fix that instead.

@dacog Would you personally prefer a different algorithm than the default used by the tables generator you pointed to?
What are the tradeoffs involved here?

**Comment by susnux** [comment]
Also I do not think a per user setting is possible so you could only configure the behavior per nextcloud instance.
Consider two users sharing a file and having different settings, then the file is always completely converted and when one of those users downloads the file the content might be in the "wrong" format from their point of view.

**Comment by max-nextcloud** [comment]
In order to make sure this https://github.com/nextcloud/text/labels/good%20first%20issue is easy to parse I tried to provide all information needed in the issue description above.

If some aspects of it are still unclear please ask so i can clarify further.

If you think this should be done differently please open a new issue describing your solution. Let's keep this issue focused on the proposed solution to provide clarity for whoever wants to tackle it.

**Comment by juliushaertl** [comment]
I think there was a misunderstanding with the issue. It is about nicely formatting the actual markdown source code in.

Some example:

Currently tables are written to the file like this:

```
| A | B | C |
|---|---|---|
| Columns | with long | text |
```

The goal of this issue would be to make sure the table is formatted in the markdown file like this
```
| A       | B         |  C   |
|---------|-----------|------|
| Columns | with long | text |
```
