### ISSUE TITLE
export content

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/text#354]
would be very useful if the document could be also saved as pdf , ods, docx ...

**Comment by koying** [comment]
I agree. MD is not the most business-friendly format.
Maybe it's already on the roadmap (I guess it is), but an export to rtf or ods would make the app much more useful as a "notepad" app, whose content can be used as a base for more elaborate documents

**Comment by juliushaertl** [comment]
Related to https://github.com/nextcloud/text/issues/112 and https://github.com/nextcloud/text/issues/128 

Regarding ods/docx/rtf, i fear that this is nothing that can be easily implemented as my last research has not shown any existing library for converting to those formats in javascript. We could of course have a general markdown to document converter in the backend but this would be out of the scope of the text app and should be handled in a separate app i think. So closing this in favor of the other two tickets.
