### ISSUE TITLE
remove link menu

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3560]
when selecting text to add a link, a menu appears
the menu comes in the way of the lines below, which is not handy when setting several links in a row

![Capture d’écran 2022-12-11 à 13 45 16](https://user-images.githubusercontent.com/59349105/206904705-16fda626-8806-4af8-b1e0-2a71ca755417.png)

please, remove the pop-up menu, let user select the text and click in the icon menu to add a link
(as here in github text edition)

![Capture d’écran 2022-12-11 à 13 51 23](https://user-images.githubusercontent.com/59349105/206904684-6bd7ba52-af89-464c-afd8-8da3eb8134cb.png)

**Comment by mejo-** [comment]
Dear @punkyard, thanks for your report. The link actions menu bubble got removed in latest development branch of Nextcloud Text. It will be released as part of Nextcloud 26. We won't backport the change to Nextcloud 25 though.

PS: Please use the templates provided when creating a new Github issue and fill out at least information about the Nextcloud version you're running.

**Comment by punkyard** [comment]
I will ;)
thanks for your reply, we'll wait till 26 then
