### ISSUE TITLE
text app appears to not play nice with encryption

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/text#3574]
**Describe the bug**
When I create a new markdown file on my encrypted nextcloud, they render in the app as if they did not get decrypted.

**To Reproduce**
1. Ensure Nextcloud encryption is enabled.
2. In the Files app, press `+` to create a new file, and pick new text file (markdown).
3. Open the file, which opens it in the Text app.
4. Be met with content:
> HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5. Feel surprised by this behavior, try removing the unexpected content to use the editor as normal, but feel not confident the content still ends up encrypted (edit: it does).

**Expected behavior**
Using Text with encryption enabled gives a similar user experience as when encryption is disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/3059397/207614144-6d88b8d6-fc71-4f2d-b619-504870f6e692.png)

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 103.0.2 (64 bit)
 - Device: laptop

<details>
<summary>Server details</summary>

**Text app version:** 3.5.1

**Operating system:** Ubuntu 20.04.4

**Web server:** Apache

**Database:** PostgreSQL 12.12

**PHP version:** 8.0.16

**Nextcloud version:** 24.0.4

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"1FxZl7fxuD239dcZpReK","level":3,"time":"2022-12-14T14:07:28+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"jbGvNr8ndJlIeCokNtea","level":3,"time":"2022-12-14T14:07:34+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"gwNNHjAaZoW2x0TQjSWB","level":3,"time":"2022-12-14T14:07:42+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"wMyq4h73yvOtg4cFbGb6","level":3,"time":"2022-12-14T14:07:50+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"U465zqpU2AWqotONT21b","level":3,"time":"2022-12-14T14:07:55+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"K1QcG7s806zurLcA055p","level":3,"time":"2022-12-14T14:07:56+00:00","remoteAddr":"82.217.121.24","user":"kiara","app":"user_oidc","method":"PROPFIND","url":"/remote.php/dav/files/kiara/","message":"no OIDC providers","userAgent":"Mozilla/5.0 (Linux) mirall/3.5.4git (Nextcloud, arcolinux-5.19.2-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"YkJVLMRCy91uvGRKRWtv","level":3,"time":"2022-12-14T14:08:01+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"xg1jDq8NHGgj2LStDkFC","level":3,"time":"2022-12-14T14:08:11+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"kEmaX4Y8vfY0DUxIMYdw","level":3,"time":"2022-12-14T14:08:15+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"wAOuSLRkrPw9h5EGCN3M","level":3,"time":"2022-12-14T14:08:23+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"ZtuTsNiZ6Gmrw79TI9xG","level":3,"time":"2022-12-14T14:08:25+00:00","remoteAddr":"82.217.121.24","user":"kiara","app":"user_oidc","method":"PROPFIND","url":"/remote.php/dav/files/kiara/","message":"no OIDC providers","userAgent":"Mozilla/5.0 (Linux) mirall/3.5.4git (Nextcloud, arcolinux-5.19.2-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"jGm1jFrz8W6m9Xvi6DyZ","level":3,"time":"2022-12-14T14:08:29+00:00","remoteAddr":"86.88.14.135","user":"--","app":"user_oidc","method":"PROPFIND","url":"/remote.php/caldav/calendars/leon/ict_shared_by_kiara/","message":"no OIDC providers","userAgent":"Evolution/3.46.2","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"TbNbWP5dMtFPVjANmsrY","level":3,"time":"2022-12-14T14:08:29+00:00","remoteAddr":"86.88.14.135","user":"--","app":"user_oidc","method":"PROPFIND","url":"/remote.php/caldav/calendars/leon/personal/","message":"no OIDC providers","userAgent":"Evolution/3.46.2","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"BJepZOCykIUvQweI2TiP","level":3,"time":"2022-12-14T14:08:29+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
{"reqId":"EhpNR1AI6JLDP0GKFEsD","level":2,"time":"2022-12-14T14:08:32+00:00","remoteAddr":"82.217.121.24","user":"kiara","app":"files","method":"POST","url":"/ocs/v2.php/apps/files/api/v1/templates/create","message":"Controller OCA\\Files\\Controller\\TemplateController::create executed 155 queries.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.4.1","data":{"app":"files"}}
{"reqId":"4I4rnpyU2WMl8gM1IxDv","level":3,"time":"2022-12-14T14:08:37+00:00","remoteAddr":"82.217.121.24","user":"--","app":"user_oidc","method":"GET","url":"/remote.php/webdav/","message":"no OIDC providers","userAgent":"--","version":"24.0.4.1","data":{"app":"user_oidc"}}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [files](https://cloud.bij1.org/apps/files/)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 24 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 27 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 27 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 24 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 24 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 24 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 25 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 60 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 256 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 408 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
GEThttps://cloud.bij1.org/core/preview?fileId=-1&x=256&y=256&a=1
[HTTP/2 400 Bad Request 144ms]

jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 408 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
[DEBUG] files: Created new file 
Object { app: "files", uid: "kiara", basename: "test.md", etag: "06cb95fdbeab49ec2ca15b43863a6133", fileid: 63302, filename: "/test.md", lastmod: 1671026912, mime: "text/markdown", size: 0, type: "file", … }
[ConsoleLogger.js:29:8](webpack:///nextcloud/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
No new notification data received [App.vue:323](webpack:///notifications/src/App.vue)
Polling interval updated to 30000 [App.vue:355](webpack:///notifications/src/App.vue)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:127:11](webpack:///nextcloud/core/src/OC/util.js)
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment [util.js:139:11](webpack:///nextcloud/core/src/OC/util.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 14 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
[INFO] viewer: Opening viewer for file  
Object { app: "viewer", uid: "kiara", path: "/test.md" }
[ConsoleLogger.js:33:16](webpack:///viewer/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 436 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
[DEBUG] viewer: Fetching additional files... 
Object { app: "viewer", uid: "kiara" }
[ConsoleLogger.js:29:16](webpack:///viewer/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
Array []
[EditorFactory.js:68:9](webpack:///text/src/EditorFactory.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 420 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
No new notification data received [App.vue:323](webpack:///notifications/src/App.vue)
Polling interval updated to 30000 [App.vue:355](webpack:///notifications/src/App.vue)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
```

b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This should be fixed on the server repo with https://github.com/nextcloud/server/pull/35649

Maybe you can test the patch for Nextcloud 24 that can be found at https://github.com/nextcloud/server/pull/35657.patch

Details on how to apply a patch can be found at https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html

**Comment by juliushaertl** [comment]
Closing as fixed in server
