### ISSUE TITLE
Update the content when the file is opened

### ISSUE THREAD

**Issue by ChemBioScripting** [nextcloud/text#358]
**Is your feature request related to a problem? Please describe.**
Hi, I'm new to nextcloud. I installed the _Text_ application to enable the creation of a text file from the plus button and to be able to view and edit it, but I realized that, by making changes to the same file with another editor, they are not displayed in the nextcloud's _Text_ application. 

**Describe the solution you'd like**
The cause I believe depends on the intervals for the updates, which do not occur when the file is opened, but are later, keeping past versions in memory. I don't know if it can be connected to [cronjob interval configuration](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#cronjob-interval-configuration).

**Describe alternatives you've considered**
I wonder if it is possible to update the contents of the file when it is opened from the nextcloud's file manager, instead of keeping the previous version in memory. I tried to clear the browser cache to see an update of the contents, but an instant update would be convenient when the file is opened, thank you!

**Comment by WhoNeedszZz** [comment]
Can also confirm this behavior and was looking to see if it was mentioned yet. Thanks for writing it up for us!

**Comment by juliushaertl** [comment]
Is the file stored on some external storage? Could you fill out the bug report issue template to give some more details about your setup? In general we use the files etag to check if the underlying file has changed on the filesystem and show a conflict resolution dialog in those cases. I guess for some reason this doesn't work as expected on your system.

**Comment by juliushaertl** [comment]
Also could you enable debug logging on your instance, try to reproduce the behavior and share the browser and nextcloud logs?

**Comment by martin21** [comment]
I see exactly the same behavior with Nextcloud Text 2.0.0 on Nextcloud 18.

How to reproduce:

- Open a Markdown file in Nextcloud Talk
- Edit the file locally, for example with KWrite and have the updated version synchronized to Nextcloud
- There is no notification in the Nextcloud Text application that is still open
- Close Nextcloud Text
- Open the Nextcloud File application
- Verify that the file has been synchronized
- Open the file in Nextcloud Text
- Nextcloud Text shows the *old* content
- Log off and close the browser
- Log in and open the file again in Nextcloud Text
- Nextcloud Text still shows the old content
- Edit the file in Nextcloud Text
- Save the file in Nextcloud Text
- File content conflict dialog appears

Expected results: Nextcloud Talk notifies me about the changes in the text made by some other application.

Nextcloud 18 is running on Devuan Beowulf. Client is Debian Sid with with Nextcloud client 2.6.4-1. Nextcloud is running on a VMware based VM. Files are stored locally on a BTRFS filesystem.

Some details about my setup, taken from the system report:

```
Operating system: Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64

Webserver: Apache/2.4.38 (Debian) (fpm-fcgi)

Database: mysql 10.3.22

PHP version: 7.3.14-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

Nextcloud version: 18.0.4 - 18.0.4.2
```

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.0
 - end_to_end_encryption: 1.4.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_mindmap: 0.0.21
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - music: 0.14.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - audioplayer
 - encryption
 - files_external
 - user_ldap
```

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "[…]"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "[…]",
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "installed": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```

**Comment by martin21** [comment]
I changed log level to debug.

Nextcloud Text still does not notify me, but on re-opening the new content appears, unlike before.

Then I changed the file name of the file to be one with white space in it like `Some file.md`. Now the Text app still displays the old file content when opening it again. Hmm, okay, but this may be a timing issue, cause:

But when I then reload the Files app in the browser and then open Text app again it shows the added line.

Adding a fifth line I wait for a notification within Text for more than a minute. However it does not show. Nextcloud cron job `cron.php` is running as user `www-data` every 5 minutes. Still after waiting for more than 5 minutes there is no notification. However this cron job may be unrelated.

However after all of this, there is nothing in `nextcloud.log`. The file is empty. I truncated the file before and made sure it is owned by `www-data:www-data` again. I use `'loglevel' => 0,` as documented in https://docs.nextcloud.com/server/18/admin_manual/configuration_server/logging_configuration.html

So no idea how to debug this properly. Setting log level to warn again for now.

**Comment by juliushaertl** [comment]
Do you still see this issue on the most recent versions?

We made quite some improvements to the way changes are detected in https://github.com/nextcloud/text/pull/871 so I'll close this for now, but feel free to comment and reopen if the issue still exists.
