### ISSUE TITLE
Scrolling in heading outline

### ISSUE THREAD

**Issue by dragonwolfmastr** [nextcloud/text#3585]
**Is your feature request related to a problem? Please describe.**
When I create many headings in the Markdown text editor, the outline cannot scroll down to show all of them.

**Describe the solution you'd like**
Be able to scroll through the document outline when hovering over it with the mouse OR have a scrollbar on the side of the outline.

**Describe alternatives you've considered**
Make the outline text smaller or move its starting point upward, though this would be a less efficient method.

**Additional context**
![Screenshot from 2022-12-18 11-04-28](https://user-images.githubusercontent.com/120978423/208314844-983f740c-af16-4243-afb5-56b65fe187c9.png)

**Comment by mejo-** [comment]
@luka-nextcloud since I already looked into it briefly: I probably have to set `height` and `overflow-y: auto` for `.editor--toc`: https://github.com/nextcloud/text/blob/4d07cbd88f2b033f28b3ccd0c951227ac6166563/src/components/Editor/TableOfContents.vue#L68
