### ISSUE TITLE
 facilitate deep-linking

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/text#3587]
i'm using this app to make and preview markdown documents.
being familiar with github, i am used to seeing the headers from markdown documents used to facilitate deep-linking, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/3059397/207631706-f8d294c3-4306-4ab1-9866-88f710fcd890.png)

i feel it would be nice if markdown previews in nextcloud were to offer a similar feature.
(i'm not sure if this request should go here. i previously tried filing this [at prosemirror](https://github.com/ProseMirror/prosemirror/issues/1344), but they seemed under the impression this wasn't something on their end.)

**Comment by mejo-** [comment]
Hey @KiaraGrouwstra, thanks for your feedback. Which Nextcloud version do you run? Text in Nextcloud 25 and above already has support for heading anchor links. I'll close this issue as completed therefore. Feel free to comment and/or reopen if you think there's still something missing regarding this feature.

PS: It would help if you could use the templates to create a new issue. How did you end up writing this issue without using the template? Did you follow a link somewhere to create the issue? Or did you go to https://github.com/nextcloud/text/issues and select "New issue" there? I'm just curious how it comes that we often get issues that obviously aren't written using the template :wink:

**Comment by KiaraGrouwstra** [comment]
Hi there! Thanks for explaining and closing this.

I mostly copied my explanation over from my post over at the other issue. It hadn't come to mind for me the present version might already have addressed this (not having managed the update to Nextcloud 25 yet), so I got a bit lazy with the template. My apologies.
