### ISSUE TITLE
URL Preview is a Privacy Leak (and a major waste of screen space in most cases)

### ISSUE THREAD

**Issue by yuv** [nextcloud/text#3588]
**Describe the bug**
When user enters a URL into a Markdown file, a preview is automatically fetched and displayed under the URL.

**To Reproduce**
1. Go to files section
2. Create new text file
3. name it something.md
4. type in some text and a URL
5. press enter after the URL
6. watch your screen being used to display something you do not want/need to see

**Expected behavior**
- my preference: leave my text alone
- optional: have a global setting (per server instance) disabled by default, to show URL previews.
- nicer optional: have a per-user setting, still disabled by default 
- kind of good: a per-document setting, such as interpreted meta-data at the start of the document as used by a few smart editors to set things like tab widht. still disabled by default 
- wizard: automatically disable when on metered/slow bandwidth.  But still, disabled by default

**Client details:**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox
 - Version: 107
 - Device: desktop

**Text app version:** 3.6.0

**Operating system:** Ubuntu 22.04

**Web server:** nginx

**Database:** MariaDB 10.5.18

**PHP version:** 8.1.13 

**Nextcloud version:** 25.0.2

**Comment by nickvergessen** [comment]
> optional: have a global setting (per server instance) disabled by default, to show URL previews.

Add this to your config/config.php
```php
'reference_opengraph' => false,
```

Default disabled is not an option at the moment.

**Comment by yuv** [comment]
appreciate the quick and helpful reply, thanks!

The changed config leaves a little aesthetic defect: a "waiting wheel" is still displayed before things move on and the editor keeps working as expected.

**Default matter.**  Now that you have told me what the setting is, a little bit of search has brought me to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html and I can read myself into what else is going on.

Is anybody at NextCloud giving some thought to implement "privacy by design?"  And graceful change?

**Graceful change**:  new features should come disabled by default with an intro for admins explaining what the new feature is and how to enable it. 

**Privacy by design**:  an instance of a NextCloud server should not call external URLs, not even calling home (I know developers like telemetry and stats, but frankly if they come by default I am more inclined to disable them than if I am asked nicely to contribute).

I am shocked that default disabled is not an option.  Has the Silicon Valley culture polluted Germany?  I believe Germany is where NextCloud is mostly based, and from my experience (Sie koennen auch Deutsch mit mir schreiben) Germany has (or used to have?) a much higher respect of users' privacy and experience.

This feature specifically is not only terrible for privacy:  it is also bad for usability.  In the majority of conceivable scenarios, I can only see it as negative value:  eating away valuable display surface, bandwidth, battery/computing cycles.  In a few cases it may not be an annoyance, but for those cases I would rather have it as a bubble when the cursor hovers over the URL.  Only in static print, and as an option, would the frame insert as it shows up now make sense IMHO.  This is a general use editor tool, not social networking.

**Comment by juliushaertl** [comment]
Thanks a lot for your feedback on this. We discussed this matter internally and came to the conclusion that we will introduce a simple admin UI setting to disable the link preview feature and remote fetching for open graph data to make it more visible to admins and easier to configure. This will be tracked further in https://github.com/nextcloud/server/issues/35840

> **Graceful change**: new features should come disabled by default with an intro for admins explaining what the new feature is and how to enable it.
> **Privacy by design**: an instance of a NextCloud server should not call external URLs, not even calling home (I know developers like telemetry and stats, but frankly if they come by default I am more inclined to disable them than if I am asked nicely to contribute).

Feature development and picking sane defaults is always a compromise between usability, exposure of features and privacy. In this specific case we decided to still keep them enabled by default as it seemed to be the best balance between making the feature visible and privacy. Open graph data fetching is performed by the server itself, so individual users can not be tracked through that. There is also a caching layer so the request would only be issued once.

> This feature specifically is not only terrible for privacy: it is also bad for usability. In the majority of conceivable scenarios, I can only see it as negative value: eating away valuable display surface, bandwidth, battery/computing cycles. In a few cases it may not be an annoyance, but for those cases I would rather have it as a bubble when the cursor hovers over the URL. Only in static print, and as an option, would the frame insert as it shows up now make sense IMHO. This is a general use editor tool, not social networking.

Link previews give the reader of a document additional context without clicking on the link directly. From our perspective this is definitely a useful feature for lots of users, but we of course keep a close look on feedback. So far this issue is however the first negative one we received. Looping in @jancborchardt here as well for the UX feedback.

**Comment by yuv** [comment]
> we will introduce a simple admin UI setting to disable the link preview feature and remote fetching

Thanks

> Open graph data fetching is performed by the server itself, so individual users can not be tracked through that.

Privacy is not limited to individual user tracking.  I am trying to run a private NextCloud instance.

**Comment by max-nextcloud** [comment]
We've had this request in collectives again. I'll reopen and focus on the ui issue when turning of `reference_opengraph`.

**Comment by max-nextcloud** [comment]
Actually... let's make a new issue for the ui thing. This can still serve as documentation of how to turn off the link previews.

**Comment by juliushaertl** [comment]
Should we separate the UI config to make reference_opengraph only for the remote fetching and have a separate config for showing or not showing at all? Since previews can still be wanted just without external requests.

**Comment by max-nextcloud** [comment]
> Since previews can still be wanted just without external requests.

So then you'd only have previews for local content?

**Comment by mejo-** [comment]
I also got the feedback already that link previews can be annoying in certain situations (while they for sure are super useful in the majority of cases). That's why I still think that we should somehow allow to disable them *individually*. I think it would be great from a user perspective to decide per link whether a link preview is displayed or not - instead of just supporting to enable/disable it in document-wide, user-wide or even instance-wide scope.

**Comment by yuv** [comment]
@mejo- 
> decide per link whether a link preview is displayed or not - instead of just supporting to enable/disable it in document

not instead, in addition, and in lower priority to the implementation of the per server configurable default and per document switch.  if  you make it "instead," it becomes a quagmire of repeating the setting too many times when the user-intended behavior is different from the developer's default.

What you are suggesting is similar to what many in the cookies/spyware industry are doing to circumvent GDPR regulation asserting user's right to privacy: instead of letting the user exercise their right with one simple switch, they create multiple switches, first for classes of cookies, then for individual cookies, with the ultimate intention of causing decision-fatigue and bending users to operator's preferred default by attrition.  Not cool. 

> link previews [...] for sure are super useful in the majority of cases

Biased language.  Makes no difference if useful or "super" useful.  I agree they can be useful.  The "super" just shows where you are coming from and makes me doubt any other of your comments have any other intention but asserting your own opinion.  Provide evidence to prove your assertions?

Vocal majority?  Silent majority?  Majority of users in a specific country?  Actually irrelevant if you stop politicking and show respect for valid opinions that have the only drawback of being different than yours.  Wether they satisfy the needs of a majority, a plurality, or a minority:  as long as they satisfy those needs and can be implemented without fatal or critical consequences, they should.

I do accept that url previews are useful to some, useless to some, and detrimental to some.  I do not care whether some is a majority, a plurality, a minority.  I do care for good UX/UI design and that means to me making things useful for as many end-users as possible while staying out of their way, even if that means sacrificing the interests and wishes and views of the developer or of the operator.  To force a user to make a decision per link (i.e. the "instead" that you are suggesting) is exactly the opposite of staying out of user's way.

**Comment by yuv** [comment]
@max-nextcloud 
> We've had this request in collectives again.

Forgive my ignorance, what is "collectives?"

**Comment by yuv** [comment]
@max-nextcloud : can you please reopen this ticket and make it a feature request?

Use case: user starts MD file on a NextCloud instance with `reference_opengraph` set to false.  User copies MD file to a NextCloud instance with `reference_opengraph` set to true.  User's privacy is breached.  The worse part: the user does not know whether privacy is in jeopardy.

This is not a marginal case.  Any political or business-competitive side is negatively affected:  a dissident listing politically sensitive websites on a document;  a police investigator listing links to extremist organization websites;  a business analyst listing competitors' website while their startup is still under the radar.  All cases in which the leak is detrimental.  I am pretty confident that users in these situation do not reply to your objective and open minded surveys, @mejo- /s, how do you count (and weight) "cases?"

Suggestion for implementation: like other text editors do, interpret a sequence of characters in a comment as the switch to set/unset `reference_opengraph`, e.g.

```
<!-- URL Preview: no -->
- list of privacy sensitive URL's here
<!-- URL Preview: yes -->
- continue with list of non-privacy sensitive URL's here 
```

remains the question of the default, but on that one we can agree to disagree.

**Comment by arnowelzel** [comment]
JFTR: to turn hide the previews completely, I use the following CSS rule with [CustomCSS](https://apps.nextcloud.com/apps/theming_customcss):

```
.ProseMirror .widgets--list {
    display: none;
}
```
