### ISSUE TITLE
Treat newlines as hard linebreaks (not paragraph breaks) when pasting plaintext

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3598]
**Describe the bug**

Pasting plaintext currently transforms each newline into a paragraph break.

**To Reproduce**
1. Open a Text document
2. Copy some multi-line plaintext to the clipboard
3. Paste the plaintext into Text (<kbd>Ctrl</kbd>-<kbd>V</kbd> in Nextcloud 25 and below, <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>V</kbd> in Nextcloud 26)
4. See each newline being converted into a paragraph break.

**Expected behavior**
Newlines should be regarded as hard linebreaks.

**Comment by susnux** [comment]
Should every newline be converted to hard line breaks or should empty lines be converted to paragraph breaks?
E.g.:
```
Hello
world
```
being `<p>Hello<br>world</p>`
vs 
```
Hello

world
```
being `<p>Hello</p><p>World</p>` ?

BTW I think you meant <kbd>CTRL</kbd>+<kbd>V</kbd>?

**Comment by mejo-** [comment]
@susnux that's a good question. Empty newlines should probably be treated as paragraph breaks like in your example.

**Comment by mejo-** [comment]
@susnux @juliushaertl @max-nextcloud do you have an idea where to change this? I might take a look into it the next days but don't have a good idea where to start. So any hint would be appreciated :heart:

**Comment by juliushaertl** [comment]
I think it could basically use the same hook through clipboardTextParser as in https://github.com/nextcloud/text/pull/2716/files

Prosemirror splits them be newlines and wraps in paragraphs, so as soon as we return a slice there we can overrule the default behaviour. This we currently only do for the markdown paste but could easily be done for the plaintext paste with shift as well.

https://github.com/ProseMirror/prosemirror-view/blob/49903c758b510aa937e2f19d16e9ff4bc5bef4f8/src/clipboard.ts#L51-L61

The backportable fix would just skip the markdown conversion.

**Comment by susnux** [comment]
I think changing [Markdown.js#L85](https://github.com/nextcloud/text/blob/master/src/extensions/Markdown.js#L85) to something like this could fix it:
```js
clipboardTextParser(str, $context, _, view) {
	const parser = DOMParser.fromSchema(view.state.schema)
	const doc = document.cloneNode(false)
	const dom = doc.createElement('div')
	if (shiftKey) {
		dom.innerHTML = '<p>' + str.replace('\n', '<br />').replace('<br /><br />', '</p><p>') + '</p>'
	} else {
		dom.innerHTML = markdownit.render(str)
	}
	return parser.parseSlice(dom, { preserveWhitespace: true, context: $context })
},
```

**Comment by mejo-** [comment]
Thanks a ton @juliushaertl and @susnux. Your hints were really helpful and my implementation is pretty much what @susnux proposed: #3623
