### ISSUE TITLE
Outline functionality for the markdown editor in nextcloud

### ISSUE THREAD

**Issue by fermiongithub** [nextcloud/text#3645]
Imagine you have a markdown document with a dozen or more headings.

Let's assume that the document is longer than some screen areas.

To locate a passage further down, you have to scroll.
This is tedious and lengthy.

Suggestion:
Addition of a table of contents (Outline), which is automatically generated from the headings.
In the sidebar. As an option. Can be turned on and off.

The FOSS https://joplinapp.org/ provides a markdown editor that automatically generates such a table of contents. See screenshot. At the top right you can see the table of contents. The individual entries are clickable and act like a link to the respective heading.

![Bildschirm­foto 2023-01-05 um 09 55 57](https://user-images.githubusercontent.com/5146767/210977746-31d02537-4390-4aeb-be19-aac904333239.png)

Edit:
Now I noticed that there is already a similar proposal from 2019. I'm sorry.
https://github.com/nextcloud/text/issues/107

**Comment by mejo-** [comment]
Dear @fermiongithub, which version of Nextcloud do you run? Starting with Nextcloud 25, Text allows to display the document outline (table of contents). Take a look at the headings menu, there you have an option "show outline" :blush:
