### ISSUE TITLE
Text document shared via link has controls bar overlap sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#365]
See this when you share a Text document:
- The controls bar overlaps the sidebar on the right, including the call button. It is only needed in the content area and doesn’t need to extend further to the right.
- The action icons are not flush left with the text of the document, but I assume that’s directly related to the previous point.
- There’s a double scrollbar in the document?

![Shared text doc issues header bar scrollbar](https://user-images.githubusercontent.com/925062/66957833-40bdf780-f067-11e9-86aa-771b7ed81ea0.png)

--------------------------------

On mobile there’s some stuff too:
- The right sidebar does not collapse on mobile at all
- The title does not ellipsize (possibly core issue)
- Edit time doesn’t show, or there’s whitespace on the right of the controls bar for some reason

![shared text doc issues mobile no collapse](https://user-images.githubusercontent.com/925062/66957832-40bdf780-f067-11e9-8a54-645997349772.png)

cc @juliushaertl @skjnldsv

**Comment by juliushaertl** [comment]
How do you get the talk sidebar to show, doesn't work at all for me with talk installed on public pages :confused:

**Comment by juliushaertl** [comment]
cc @danxuliu

**Comment by juliushaertl** [comment]
Ah nevermind, needed to pull the talk app again :wink: I'l look into.

**Comment by danxuliu** [comment]
> See this when you share a Text document:
>
> - The controls bar overlaps the sidebar on the right, including the call button. It is only needed in the content area and doesn’t need to extend further to the right.
> - The action icons are not flush left with the text of the document, but I assume that’s directly related to the previous point.
> - There’s a double scrollbar in the document?

Known issues due to the hacks needed to add the Talk sidebar to the public share pages, see https://github.com/nextcloud/spreed/issues/2237#issuecomment-536204017

I took a look at fixing it, but I could not find a good way to do that yet. If you want to try please check too with large text documents, as there is were the fun starts due to the scrolling containers and the sticky header ;-)

> On mobile there’s some stuff too:
> - The right sidebar does not collapse on mobile at all

[Talk's fault](https://github.com/nextcloud/spreed/issues/2313), unrelated to Text ;-) I need to add a button to show the sidebar, although I do not know where... In the header seems out of place, and in the body it would take precious space from the content. But that is something to discuss elsewhere ;-)

> Ah nevermind, needed to pull the talk app again :wink: I'l look into.

Please note that Talk is broken in _master_ branch; you need to use _stable17_ ;-)

**Comment by jancborchardt** [comment]
> Talk's fault, unrelated to Text ;-) I need to add a button to show the sidebar, although I do not know where... In the header seems out of place, and in the body it would take precious space from the content. But that is something to discuss elsewhere ;-)

Just like it is placed in the Talk app, on the top right of the content area (excluding sidebar). :) In the case of the Text app this would mean as the rightmost item of the controls bar. Does that work @juliushaertl?

**Comment by jancborchardt** [comment]
> Then, when the sidebar is closed, there will still be a 44px white column to the right of the contents, which will be pretty noticeable for example with the PDF viewer. However, if that is acceptable, it should be easy to implement ;-)

No, of course it should show properly integrated. :) I guess for the Text app this is doable, for PDF viewer we might need to dig? But a white bar on the right is of course not really acceptable. A quick fix for the PDF viewer could be to just show the icon on the top right but _below_ the actions bar.

> Note that the icon will then appear to the right of the edit time, not as the last button.

Yes, that’s what I meant. Edit time and other editors are also items of the controls bar. :)

**Comment by juliushaertl** [comment]
@danxuliu Maybe you could just expose some JS methods on the public pages that allow toggling the talk sidebar? (As long as we do not have a regular files sidebar on public pages) We can then add the toggle button right into text/pdf_viewer, so it is integrated inside of the text app toolbar.

**Comment by juliushaertl** [comment]
This has been fixed quite some time ago.
