### ISSUE TITLE
Sub bullet list no more available

### ISSUE THREAD

**Issue by nomad-fr** [nextcloud/text#3677]
**Describe the bug**

When you are in edit mode on a markdown file (.md), you can't even do a sub bullet list. Normal bullet are avaible but when you are on a bullet list if you press tab it don't do a sub bullet anymore. It seems to appear in Nextcloud 25.0.2.

**To Reproduce**
1. in edit mode on a markdown file
2. create a bullet list
3. try to do a sub bullet list
4. tab swith to menu position

**Expected behavior**
Usualy when in edit mode of a markdown file if you are in a bullet list and press tab you shoud obtain a sub bullet to start a sub bullet list.

**Client details:**
 - OS: Ubuntu 22.04
  - Browser: Firefox 108.0.2  or Firefox ESR
 - Version: from 25.0.2 to 25.0.3
 - Device: dsktop

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)
3.6.0

**Operating system:**
Debian 10.13
FreeBSD 13.1 p5

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
php 8.1

**Nextcloud version:** (see Nextcloud admin page)
25.0.3 and 25.0.2

</details>

**Comment by Pilzinsel64** [comment]
Probably a duplicate, see here (workaround available): #3493
