### ISSUE TITLE
The text after a check box is set to strike through when the check box is checked

### ISSUE THREAD

**Issue by tigexplorer** [nextcloud/text#3689]
**Describe the bug**
The text after a check box is set to strike through when the check box is checked.

**To Reproduce**
1. Insert a checkbox with a line of text
2. Check the checkbox
3. The text is set to strike through

**Expected behavior**
The text should not be touched if the check box is ticked in the box.

**Screenshots**

![Bildschirmfoto vom 2023-01-21 17-18-32](https://user-images.githubusercontent.com/43775552/213876565-bb5f6535-94dc-46b4-a43b-b9b1debf0130.png)

**Client details:**
 - OS: ubuntu 22.4
 - Browser: Firefox
 - Version: 109.0
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:**  3.6.0

**Operating system:** Linux 4.19.0-23-amd64 x86_64

**Web server:**

**Database:** mysql Version: 10.3.36 

**PHP version:** 8.1.14

**Nextcloud version:** 25.0.3

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by susnux** [comment]
This is intentionally styled like this, see https://github.com/nextcloud/text/issues/886
