### ISSUE TITLE
Failed to load file

### ISSUE THREAD

**Issue by softweb-dev** [nextcloud/text#3690]
" Failed to load file,  This file cannot be displayed as download is disabled by the share " issue is showing if " hide download" is active.

**Comment by Pilzinsel64** [comment]
True, same here, I ad to update all my links.
Is that indeed or is that a bug?

**Comment by luka-nextcloud** [comment]
@softweb-dev I think the issue is not well explained, could you please elaborate?

**Comment by softweb-dev** [comment]
Its bug for shure. I have also tested with a fresh installation. Same issues. Its because old Javascript code inside the app. Developer will fix that next version.

**Comment by softweb-dev** [comment]
> True, same here, I had to update all my public links. Is that indeed or is that a bug?

Its Bug.

**Comment by luka-nextcloud** [comment]
@softweb-dev I cannot see the image.

![image](https://user-images.githubusercontent.com/89908051/214842741-628dfdbc-7044-4faf-a688-575cddac4f42.png)

**Comment by luka-nextcloud** [comment]
@softweb-dev I cannot reproduce as you can see from the video, could you share a screen recording?

https://user-images.githubusercontent.com/89908051/215489126-2bc7ac18-622c-433a-be27-715f2e6a2419.mov

**Comment by Pilzinsel64** [comment]
@luka-nextcloud You need to open the file via the public link:
https://user-images.githubusercontent.com/23138465/215696726-14624f4e-9800-4ea0-827b-5a7340fd8a71.mov

**Comment by Pilzinsel64** [comment]
Related: #3704

**Comment by whenthelight** [comment]
> @luka-nextcloud You need to open the file via the public link: https://user-images.githubusercontent.com/23138465/215696726-14624f4e-9800-4ea0-827b-5a7340fd8a71.mov
> 
> It worked just fine with v25.0.2 or v25.0.1 (not sure the last working version yet, probably I regoniced it too late).

Same Error @my Installation. V25.0.1 worked fine. 
After Update to V25.0.3 this Error happened. Another Instance with V25.0.2 also have this Error. Public Share with "Hide Download" and marked as editable.

**Comment by juliushaertl** [comment]
I've commented in https://github.com/nextcloud/text/issues/3704 with the reference on how this could be fixed. Will close this one as a duplicate of #3704
