### ISSUE TITLE
Links in Text files will open 2x

### ISSUE THREAD

**Issue by softweb-dev** [nextcloud/text#3691]
https://help.nextcloud.com/t/links-in-text-files-will-open-2x/149729/1

And also 

[linkissue.webm](https://user-images.githubusercontent.com/48855596/213891110-547f3b19-2d52-407a-bc48-7e4097ce77b0.webm)

**Comment by luka-nextcloud** [comment]
@softweb-dev I am not able to reproduce the first issue. Please take a look at the video:

https://user-images.githubusercontent.com/89908051/214514751-21f5a704-2ac7-49be-a80d-22f752fee98c.mp4

**Comment by softweb-dev** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Issue comes only on shared link. Bud share is now not more possible since latest version 25.0.3.

**Comment by luka-nextcloud** [comment]
@softweb-dev  In that case, we have nothing to fix.

**Comment by juliushaertl** [comment]
@luka-nextcloud Still needs to be fixed also if it is not working due to another bug ;)

@softweb-dev Please fill out the issue template so we know which version this happens with and which browser/OS you are using. Also knowing the exact steps taken for creating the share link would be good..

**Comment by juliushaertl** [comment]
I could not reproduce this issue anymore also not on share links. @softweb-dev Can you check this again with the latest release?

**Comment by softweb-dev** [comment]
https://eb12.de/2.webm
