### ISSUE TITLE
Since NC 25.02 update: publicly shared .md files need additional right for download in order to be displayed.

### ISSUE THREAD

**Issue by listeneroninterestingtopics** [nextcloud/text#3704]
**Describe the bug**

Since NC 25.02 update: publicly shared .md files need additional right for download in order to be displayed.

Before sharing the file with read only worked perfectly! In NC 25.02 and 25.03 (Text App always current:  3.6.0) read only produces bug "file not readable because right to download is blocked". After giving right to download it works. But read only is impossible like that.

**To Reproduce**
1. Share folder
2. In sharing options choose "hide download" (as we want read only)
3. Open shared link in private browser or after being logged out of NC

**Expected behavior**
.md files should be shared read only.

**Screenshots**

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: tested with firefox 108.0.2, current chromium ....
 - Version: 22.04
 - Device: Laptop

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)
3.6.0

**Operating system:**
NC 25.02 and NC 25.03

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
8.1

**Nextcloud version:** (see Nextcloud admin page)
NC 25.02 and NC 25.03
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This is actually caused by this line:
https://github.com/nextcloud/text/pull/2776/files#diff-2dc81f0bddfb02f0a6ba96048923dafeb718b07ccd10036e3004dff976411240R499

Hide download is not really well defined in what it should achieve, but I think it makes sense to revert this part of the change to still render hide download share links with text.

**Comment by max-nextcloud** [comment]
Removing the good first issue label as there's a pr open now.
