### ISSUE TITLE
Ability to rename Readme.md

### ISSUE THREAD

**Issue by summersab** [nextcloud/text#3720]
**Is your feature request related to a problem? Please describe.**
Readme.md is a very common file name for the tech-savvy and administrators. However, for the average user, it likely isn't the most obvious name for their default notebook.

**Describe the solution you'd like**
It would be nice to be able to change the name of the default notebook to something like Notes.md or Notebook.md. Allowing each user to rename their own default notebook would be ideal, but this would likely require a lot of reworking. A global setting that applies to all users would be an acceptable starting point.

**Describe alternatives you've considered**
I might be able to write a middleware to implement this feature, but providing it in the app itself would be helpful.

**Comment by mejo-** [comment]
Dear @summersab, thanks for your feedback. Using `Readme.md` for summaries in a directory is common in a lot of software solutions. At the same time, with the document being displayed automatically in the folder users don't have to care about the filename.

Making the filename customizable would be a lot of work and bring much complexity for very few gain in my eyes.

**Comment by max-nextcloud** [comment]
Dear @summersab 

I'm not sure i understand your usage scenario fully. We mostly use the Readme.md file to enable adding notes to folders  in the files app. For generic note taking i would recommend the notes app which these days also can use text as an editor.

Of course you're free to use the space above your own homefolder for your note taking and i actually do so too. My understaning is that we currently allow using translated names of Readme.md for the file that contains the folder summary. However Readme is really hard to translate - I think for german the translation for example is 'Anleitung'. If you want you can rename the readme file to the localized version in your language and it should still work.

However even this feature is hard to discover and even harder to explain. So I agree with @mejo- that the benefit from making the name customizable does not outweight the added complexity.
