### ISSUE TITLE
Syntax highlighting in plaintext files

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3768]
**Describe the bug**
When editing a `.txt` file words are rendered in green after the initial word on a line.

**To Reproduce**
1. Create a new file ending in `.txt`
2. Start typing some words on the same line
3. See the second and following words in green.

**Expected behavior**
Black font on white background

**Screenshots**
![grafik](https://user-images.githubusercontent.com/97337118/217013718-6650a69a-52da-45c9-8a49-1a0e90384da3.png)

Only happens with current main branch, stable25 is not affected.

**Comment by juliushaertl** [comment]
Might be related to https://github.com/nextcloud/text/pull/3688/files#diff-42c9a543a241dd3537586929537f7b73764d29b327137b9acad292df13a5844c which was the most recent change.
