### ISSUE TITLE
Hyperlink editing missing from documentation

### ISSUE THREAD

**Issue by life-on-mars** [nextcloud/text#3790]
I just spent a hours trying to find out how to add hyperlinks in the editor. Documentation is referring to markdown everywhere and the internal "formatting help" only contains shortcuts. 

I didn't expect a pulldown menu in something that presents itself as a keyboard-based plain text editor. 

As adding hyperlinks as markdown code does not work, I would like to suggest mentioning how to add links somewhere in the documentation, possibly in the formatting help.

**Comment by susnux** [comment]
This is only an issue for NC25, for the upcoming NC26 this is fixed by adding a menu bar entry instead of the floating menu.

**Comment by mejo-** [comment]
Given that Nextcloud 26 is about to be released in the next weeks, I'll close this issue.
