### ISSUE TITLE
Creating a heading unfocusses the editor

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3804]
**Describe the bug**
After clicking a heading button typing will not result in the heading being written

**To Reproduce**
1. Create a Heading by clicking a button in the H1 dropdown menu
2. Start typing right away
3. See no text showing up

**Expected behavior**
The text should show.

**Comment by juliushaertl** [comment]
@max-nextcloud I cannot reproduce this, can you check if this still occurs for you?

**Comment by max-nextcloud** [comment]
Nice.. yes. seems fixed. :)
