### ISSUE TITLE
`@tiptap/extension-collaboration` comes with its own history support

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3805]
**Describe the bug**
... and is not compatible with "@tiptap/extension-history". But we currently add the History extension in `RichText` which is also used in a collaborative context.

**To Reproduce**
1. Open browser developer tools
2. Open a markdown file in text
3. Toggle on warnings
4. See warning in console of developer tools

**Expected behavior**
No warning - we should only enable history when we do not enable collaboration.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/97337118/219741804-c2f31ab4-5ef9-4a1a-b4b2-9e25732d2ee9.png)

**Comment by mejo-** [comment]
This is still valid. We should only load `extension-history` if `extension-collaboration` is not loaded.

**Comment by max-nextcloud** [comment]
b9eab5ba403dea4f2e5ef31c85d9f700b346acdd fixed this alongside #4601
