### ISSUE TITLE
Desktop: Hide the close and share buttons in direct editing

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3819]
## This is a https://github.com/nextcloud/text/labels/good%20first%20issue if you...

* want to **learn how the text app is rendered in the desktop client**
* have some basic knowledge of **javascript and vue**

If you would like some guidance ping @max-nextcloud or join the [public text channel](https://cloud.nextcloud.com/call/9tq2th3p).

## Problem

When opening a direct editing link in the desktop it currently shows a close and share button that are not working.

## Solution

Integrate the sidebar properly and hide the close and share buttons.
This would go along well with #585 which redirects logged in users to the text view in files.

These buttons could be hidden on desktop here:
https://github.com/nextcloud/text/blob/ba1bc2cb2eef697252fa98b89b8d8321beda91d4/src/views/DirectEditing.vue#L31-L34

**Comment by max-nextcloud** [comment]
@juliushaertl I separated this from #585 so people can pick on of the two. Could you check if i got the description right?

**Comment by juliushaertl** [comment]
Sounds good, we may want to give some pointers on how to detect desktop vs. mobile, but I'm currently unsure what the best way would be there.

**Comment by juliushaertl** [comment]
We can actually check for the `window.DirectEditingMobileInterface` or `window.webkit.messageHandlers.DirectEditingMobileInterface` and redirect if neither of those are available:

https://github.com/nextcloud/text/blob/ba1bc2cb2eef697252fa98b89b8d8321beda91d4/src/views/DirectEditing.vue#L66-L80
