### ISSUE TITLE
Prevent loading spinner for link preview when `reference_opengraph` is false

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3824]
**Describe the bug**
It's possible to turn off the link preview by setting `reference_opengraph` to false. See https://github.com/nextcloud/text/issues/3588#issuecomment-1358355490.
When this is done text will still attempt to load link previews leading to an endless loading spinner.

**To Reproduce**
1. Set `reference_opengraph` to false in your server config.
2. Open a text file and insert a link.
3. See the spinning wheel that will never stop.

**Expected behavior**
If link preview is turned off text should neither attempt to fetch it nor include a loading spinner.

**Comment by wbob** [comment]
as a temp workaround for nginx users, early return a 404 to skip the spinning wheel
```
location = /ocs/v2.php/references/resolve {
  return 404;
}
```

**Comment by Mannshoch** [comment]
Currently every Link I put into a text apear a second time below 
![grafik](https://user-images.githubusercontent.com/7795891/234268232-ca9f654d-e519-4925-aa8e-f57c259c8899.png)
the first occurence is may OK, the second is for the trashbin.

Please change the behavior:

- Deactivate Linkpreview for cases wher no preview is possible, e.g. the website do not exist or the website need an authentication.
- Allow to global turn off (made it Opt-in) link preview in the Nextcoud settings. eg into `/index.php/settings/admin/security`
- Find a way to add an Opt-in tag to the Markdown Link e.g.:
  Add a signal Unicode-Icon to the Linktext. -> `[https://github.com/nextcloud/](/📸 Linnk_Text)` If this signal Icon is available use link preview.

**Comment by juliushaertl** [comment]
Pushed a fix to https://github.com/nextcloud/nextcloud-vue/pull/4036
