### ISSUE TITLE
Prevent duplicate loading of yjs when workspace and viewer open text

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#3825]
**Describe the bug**
When opening both the Readme.md in the workspace and a file in the viewer the following error shows up in the console:
> Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438

**To Reproduce**
1.Create a folder description.
2. Create a test file
3. Open console
4. See error message there

**Expected behavior**
We should only import Yjs once and avoid that error message.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/97337118/221192346-8aa26aad-b4d6-4e3d-90c4-f40d90253241.png)

**Comment by luka-nextcloud** [comment]
This is a reproducible bug.

**Comment by max-nextcloud** [comment]
I wonder if it is due to the dynamic loading of Editor.vue. Both the rich workspace and the viewer component load it dynamically with
Editor: () => import(/* webpackChunkName: "editor" */'./../components/Editor.vue'),
We will want to keep this i think because it reduces the size of the view component and rich workspace artifacts and they can share the editor.
But if normal imports would fix the duplicate loading it might be an idea to use normal imports for yjs and then inject the yjs doc ($ydoc) into the Editor either via props or with provide / inject.
