### ISSUE TITLE
Strange behaviour of background when direct editing on narrow screens

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/text#3844]
**Describe the bug**
When direct editing on a narrow screen (i.e. mobile), and typing a line that's longer than the screen width, the white background for the text editor is extended only around the longer lines, but keeps the screen width elsewhere. See screenshot below as it's easier to understand.

**To Reproduce**
1. Open a file through direct editing in a narrow screen (mobile, or just a resized desktop browser window)
2. Ensure there's some text lines that are wider than the viewport
3. Those lines will overflow to the right: scroll horizontally to the right to see the background mismatch

**Expected behavior**
I expected either:
a) the text to wrap around to the width of the viewport, or
b) The entire background expanding to the width of the text, to avoid this effect

Additional info: this does not happen in the company instance, the entire background is white there.

**Screenshots**

<details>

![Screen Shot 2023-02-27 at 16 29 29](https://user-images.githubusercontent.com/8677743/221607066-186e74ea-5682-41bb-a74e-d88627748f0c.png)

</details>

**Client details:**
 - OS: Linux, Android
 - Browser: Desktop Firefox, Android Chrome, Android Webview
 - Version: -
 - Device: -

<details>
<summary>Server details</summary>

**Text app version:** main

**Operating system:** debian bullseye

**Web server:** apache2

**Database:** SQLite

**PHP version:** 8.x

**Nextcloud version:** master (26.0.0 beta5)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log

</details>

**Comment by juliushaertl** [comment]
@AlvaroBrey Did you test that with #3839 in place already? Haven't tried yet but could fix this already

**Comment by luka-nextcloud** [comment]
It seems like it was fixed already.

![image](https://github.com/nextcloud/text/assets/89908051/4a10c090-247f-4532-b858-ed0438a20112)

**Comment by mejo-** [comment]
@luka-nextcloud did you intend to close the issue?

**Comment by juliushaertl** [comment]
Just looked into this with @luka-nextcloud and it is still reproduicable.

- Create a welcome.txt file in the web interface
- Have a long line without spaces e.g. `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
- Generate a direct editing link through the API
```
curl --request POST \
  --url 'http://admin:admin@nextcloud.local/ocs/v2.php/apps/files/api/v1/directEditing/open?editorId=text&creatorId=textdocument&format=json' \
  --header 'Content-Type: multipart/form-data' \
  --header 'OCS-APIRequest: true' \
  --form path=/welcome.txt | jq .ocs.data.url
```
- Open the link in a private browser window with small screen size
