### ISSUE TITLE
Opening non-image attachments is broken

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3849]
**Describe the bug**
Opening non-image attachments is broken in latest Text. I'd expect them to be opened in the Viewer, but instead a modal is displayed that tries to load them as image and displays them as broken image.

Probably related: https://github.com/nextcloud/text/pull/2924 @luka-nextcloud

**To Reproduce**
1. Open a Text file, upload a non-image attachment
2. Click on the attachment
3. See the modal showing a broken image

**Expected behavior**
The attachment should be opened in the viewer.

**Comment by mejo-** [comment]
After discussing this a bit more I'm not sure anymore whether we want the attachment to be opened in Viewer - because Text itself might already be open in Viewer. :thinking:

**Comment by mejo-** [comment]
https://github.com/nextcloud/text/blob/bf6c6bb8df03037dc9d95dc2f62550d2a61d84ed/src/nodes/ImageView.vue#L38 is the relevant part in code.

**Comment by luka-nextcloud** [comment]
@mejo- @juliushaertl 
I would suggest to show an icon based on the file type of attachments in the preview modal.
Or just a file icon for all non-image file, it may be a simple fix for now.

**Comment by mejo-** [comment]
>  I would suggest to show an icon based on the file type of attachments in the preview modal.

I'm not sure whether that's useful from a user perspective. How about opening non-image attachments in the files app in a new tab (`target="_blank"`) instead. That way the files app could take care of opening the attachment in viewer.

Maybe we would just make the whole non-image NodeView a link to the file view (`/f/<fileId>`) and let the default `linkHandler` do it's job. That way we could take care of opening it in Viewer from Collectives with its own `linkHandler` later on :thinking:

**Comment by luka-nextcloud** [comment]
@mejo- Sounds good to me, totally agree with you.

**Comment by hcaihao** [comment]
Does this issue sloved? How to update & test?
