### ISSUE TITLE
Editor loading enhancements

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#385]
- Add share token, ttl to session
- Move create http call out of the sync service
- initialize editor with session data

**Comment by mejo-** [comment]
@juliushaertl could you elaborate a bit on the background of these enhancements? Maybe we should split them into separate tickets?

**Comment by juliushaertl** [comment]
From the intention i remember 2/3 are kind of addressed with the y.js rewrite. For 1 i don't recall what this exactly was about, so let's close.
