### ISSUE TITLE
[BITV] 9.2.4.7/3.4 - Buttons in the "Add link / Link file" popup have poor visibility when focused with the keyboard. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/text#3874]
- [ ] Fix
- [ ] Backport

<img width="335" alt="c3d91894e456e78c64f95a4ce074cb9f" src="https://user-images.githubusercontent.com/1315170/222541413-e63f5936-2617-4141-bd6b-9f464ce02004.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-91f2646afa-v3-n4

</details>

- [ ] 9.2.4.7/10.4 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-91f2646afa-v10-n4

**Comment by juliushaertl** [comment]
We no longer have those buttons but they are in the toolbar.
