### ISSUE TITLE
Unexpected lists formatting override on document save

### ISSUE THREAD

**Issue by ovk** [nextcloud/text#390]
**Describe the bug**

Markdown list formatting is changed unexpectedly on document save.

**To Reproduce**

1. Create markdown file with the following content (not using Nextcloud Text editor):

```markdown
- One
- Two
  + Three
    * Four
```

2. Open this file in the Nextcloud Text editor. The formatting is correct and list properly indented.
3. Add new item to the list in the Nextcloud Text editor.
4. Open the file outside of the Nextcloud Text editor. Now list have been changed to:

```markdown
* One

* Two

  * Three

    * Four

    * Five

```

Notice two unexpected (and possibly unwanted) changes to the list formatting:

1. Every list item prefix has been replaced with `*` character.
2. List items are now separated with an empty line.

**Expected behavior**

The original formatting is preserved and not altered for existing list items.

**Details**

While this bug report may at first seem like nitpicking, the described behaviour can be really annoying in some cases:

1. In my case, markdown files live outside of the Nextcloud and are mounted into Nextcloud via external folders. Thus the files are also viewed/edited using other tools, and for some of them having all lists formatting changed may be undesirable.
2. If markdown files are under version control (popular for personal notetaking) then having unexpected changes to list formatting on document save makes VCS history not very useful.

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/text/issues/593 where we have more info
