### ISSUE TITLE
[PollingBackend:fetchSteps] Network error when fetching steps, retry 1

### ISSUE THREAD

**Issue by ovk** [nextcloud/text#391]
**Describe the bug**

Every time the editor is closed the following message appears in the browser console log:

```
[PollingBackend:fetchSteps] Network error when fetching steps, retry 1
```

**To Reproduce**

1. Open any markdown document.
2. Close the editor.
3. Observe the error message in the browser console.

**Expected behavior**

Error doesn't appear.

**Details**

It appears that the message originates from here: https://github.com/nextcloud/text/blob/e322c247a347c703bdab35f0ba423114bc898d49/src/services/PollingBackend.js#L151

This is the `e` object from the debugger if it helps:

```
e: TypeError
​​  columnNumber: 7943
​​  fileName: "/apps/text/js/editor.js"
​​  lineNumber: 172
​​  message: "this.currentSession is null"
​​  stack: "updateSessions@/apps/text/js/editor.js:172:7943
              initSession/this.syncService<@/apps/text/js/editor.js:172:5013
              value/<@/apps/text/js/editor.js:151:4076
              value@/apps/text/js/editor.js:151:4055
              value/<@/apps/text/js/editor.js:129:1561"
​​<prototype>:​​
  constructor:TypeError()
​​​  message: ""
​​​  name: "TypeError"
​​​  stack: ""
```

**Client details:**

 - OS: Ubuntu 18.04
 - Browser: Firefox 70.0

**Comment by mejo-** [comment]
@ovk sorry for not replying earlier. Are you still able to reproduce this issue? To my knowledge, this wasn't reported by somebody else so far and I didn't spot it in my tests either.

I'm going to close the issue for now. But please don't hesitate to tell us if you still experience the same issue and we'll reopen it straight away.
