### ISSUE TITLE
Embed Images as base64 embedded Image Content

### ISSUE THREAD

**Issue by enboig** [nextcloud/text#392]
And option to embed an image would make documents more portable. Maybe a checkbox when inserting image or a "right-click" option of already added images.

**Comment by mejo-** [comment]
Unfortunately, embedding base64 encoded images in markdown can have unexpected security implications. E.g. it might be a SVG with embedded scripts.

But we completely revamped the way how uploaded images are handled in Text recently. When you upload an image to a text document, it gets uploaded to an attachment folder that is automatically shared together with the markdown file and cleaned up once the markdown file gets removed. Would this solve your problem?

Closing the issue for now, but don't hesitate to comment and/or reopen if you still see a need to discuss this further.
