### ISSUE TITLE
Translate design feedback

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#3925]
From reviewing with @jancborchardt 

- Put full text into the input when nothing is selected
- Change layout to be more like google translate/deepl (side-by-side) – of both the dropdowns as well as the big textareas
- Add placeholder text to language selectors
- Small info text that selected text could be used (To translate individual parts of the text, select it before using the translate function.)
- Texareas should not be resizable
- Keep initial focus on the first input field

**Comment by thgoebel** [comment]
> Texareas should not be resizable

The text areas should automatically resize to fit its contents. The default 2.5 lines is not realistic imho, most texts are longer. It's super crammed:

![image](https://github.com/nextcloud/text/assets/33295590/93732845-1af3-41a0-bbeb-d28efa793cec)

**Comment by juliushaertl** [comment]
@luka-nextcloud Please check if the description makes sense so far or if you need further input from the design team. Also see if you manage to setup translations either with deepl https://github.com/juliushaertl/integration_deepl/ or https://github.com/nextcloud/translate. The first one might be easier in docker based envirnoments

**Comment by luka-nextcloud** [comment]
@juliushaertl 
- I was able to setup https://github.com/nextcloud/translate
- `Add placeholder text to language selectors` -> please provide placeholder values
- `Small info text that selected text could be used (To translate individual parts of the text, select it before using the translate function.)` -> I don't really get this point. I have checked translate functionality. It is already working as described (select a text then use translate function).
- `Textareas should not be resizable` -> what is the final decision?
- `Keep initial focus on the first input field` -> It's already done, right? (currently, first input field is always focused when opening the translate popup form)

**Comment by jancborchardt** [comment]
- Placeholder text should be "Select language" for both
- The fields should as said not be manually resizable, and as @thgoebel said use autosize (think we discussed that as well @juliushaertl). Note with the side-by-side layout, the height of the text boxes can also increase a bunch, to fill out the rest of the modal height.
- The suggested info text for below the heading is written in the original issue:
  > To translate individual parts of the text, select it before using the translate function.
