### ISSUE TITLE
Support more file extensions

### ISSUE THREAD

**Issue by The1AndMany** [nextcloud/text#394]
**Is your feature request related to a problem? Please describe.**
When I was using files_texteditor, it allowed me to open files with pretty much any file extension, so long as the data was stored in plaintext format. This was especially useful for editing my website's .html and .css files on the fly. Since upgrading to Nextcloud 17, this functionality seems to have been removed when the default text editor changed. This means I must have that file synced to my computer and open it locally, but there are some instances where I might be using a public computer at a library, so that wouldn't be an option.

**Describe the solution you'd like**
Ideally, if a file format stores its data in a plaintext-like format (.html, .css, .json, .xml, etc.), Text should be able to open it

**Describe alternatives you've considered**
Switch back to files_texteditor, but I'm not sure that's a possibility anymore

**Additional context**
The only other context I can think of is specifically stating that I keep my website saved to another folder on my server, which I connect to using local external storage.

**Comment by gt2416** [comment]
+1 for this, I used to be able to code my .cpp files on nextcloud for my school projects, now it just downloads the file.

**Comment by juliushaertl** [comment]
As a quick fix we can extend the list in https://github.com/nextcloud/text/blob/master/src/helpers/mime.js#L38 

Ideally the viewer should maybe also support wildcards just as the files apps file actions which also allows only matching for the mime part (`text`)

**Comment by FastBlit** [comment]
I would like to open asciidoc files without hiding the syntax.

**Comment by GottHeit** [comment]
> 
> 
> As a quick fix we can extend the list in https://github.com/nextcloud/text/blob/master/src/helpers/mime.js#L38
> 

I tried to add that fix as I would like do edit some files which are editable yet. But I don´t have that folder/file mentioned? Cannot find it, even with a search. Maybe you can give me a hint? (Not a nextcloud pro, so maybe too stupid ^^)

**Comment by juliushaertl** [comment]
> I tried to add that fix as I would like do edit some files which are not editable yet. But I don´t have that folder/file mentioned? Cannot find it, even with a search. Maybe you can give me a hint? (Not a nextcloud pro, so maybe too stupid ^^)

Those file are not available in the release bundle since we use webpack to bundle all files in the `src/` directory into javascript bundles. Checkout the development setup in our readme: https://github.com/nextcloud/text#-development-setup

**Comment by Torenga** [comment]
Please make this an opt-in/out feature. I want to click my HTML-files, start a download and open them directly in a new tab. No hosting, no editing.

At the moment I have removed the Text app because it freezes the tab when opening larger HTML-files (10mb+) in the editor beyond blocking my workflow.

**Comment by ParaplegicRacehorse** [comment]
I don't much care about programming syntax -- a separate code editor app might be better suited for that -- but I think support for more general-purpose markup languages would be a good thing.

++ org-mode
++ asciidoc

I know gitlab and github web editors both have some level of support for at least org-mode and asciidoc. Code could be borrowed.

**Comment by juliushaertl** [comment]
Pull requests are very welcome for that. As mentioned the mimetypes are listed in https://github.com/nextcloud/text/blob/master/src/helpers/mime.js#L38

**Comment by bzg** [comment]
I'm the maintainer of Org-mode, let me know if we can help about this.

**Comment by juliushaertl** [comment]
Is there a standardized mimetype for org files somewhere or should they be just considered as text/plain as it get it on my system:

```
$ file --mime-type test.org
test.org: text/plain
```

**Comment by bzg** [comment]
We have a _de facto_ mimetype `text/org` advertized on [our website](https://orgmode.org) but it is not registered yet, we are working toward registering it.  In the meantime, `text/plain` would be.

**Comment by JudicialDomicide** [comment]
Being able to edit **.org** and **.bib** files in nextcloud natively would be really useful rather than having to download to edit.

**Comment by ParaplegicRacehorse** [comment]
Nobody is asking for the full emacs org-mode interactive experience (it would be lovely, but way outside the scope of this issue). Simple recognition of file type, editability as any other plain text file, and display-rendering of the markup at least to the same level of sophistication that whichever flavor of markdown you recognize currently enjoys.

**Comment by Spartachetto** [comment]
@juliushaertl the request of the possibility to open other files formats with a text editor (either permanently or just in case you need it that time) has a long story.

Here are some references:
https://github.com/nextcloud/files_texteditor/issues/15
https://github.com/nextcloud/files_texteditor/issues/16

I'd add also this, as I think it is related:
https://github.com/nextcloud/server/issues/8105

**Comment by JudicialDomicide** [comment]
Why do we need to read ridiculous amounts of a long history chain just to get emacs .org text files viewable in the nextcloud text editor?

It’s ridiculous!

**Comment by Spartachetto** [comment]
@JudicialDomicide if you are disturbed by my comment, my purpose was:
- to let the developers know that this feature is asked since long time
- to help issue maintainers to close issues that could be no more useful 
- to link to interesting ideas like, for example, the possibility to provide both the ability to always open a specific file format with a text editor or to open it only if needed

So I ask to @juliushaertl to please tell me if i managed to reach at least some of these goals....

I'd also like to ask if @JudicialDomicide _nice_ words respect Nextcloud code of conduct...

**Comment by zzkt** [comment]
@bzg @JudicialDomicide (and others) as of Nextcloud 21 you can now view & edit .org files as text.

**Comment by JudicialDomicide** [comment]
Many thanks. Can we be cheeky and get .bib added as well (bibtex/biblatex)

**Comment by Thatoo** [comment]
I guess, this could be solved by these two old enhancement requests : https://github.com/nextcloud/server/issues/8105 and https://github.com/nextcloud/server/issues/9192

Thus, I invite people of this thread to +1 these two requests and close this issue to make things clearer to devs.

**Comment by bzg** [comment]
Thanks @Thatoo, I +1'ed the other two requests.

**Comment by juliushaertl** [comment]
I'm going to close this as this is a very wide ticket. In case you want to push forward additional file type support, this would need:

- The mime type needs to be known by Nextcloud server (see https://github.com/nextcloud/server/pull/24488 for how this can be added)
- Once that is there, please open a separate ticket for the individual types or a pull request to add them to https://github.com/nextcloud/text/blob/12df66ffdd3d71cc696438e2e4ec60fa17b89a64/src/helpers/mime.js#L35-L61
