### ISSUE TITLE
Handle frontend state reset after cleanup of document state

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/text#3963]
From brainstorming with @max-nextcloud 

- Disable sync after idle timeout (based on when cronjob might clean up)
- Handle sync after cleanup of document state
	- On close with invalid session
		- set readonly
		- allow to reconnect
		- reopen the full document from scratch
	- Add timestamp or etag for current base state of the document
		- Client can use this for validating that the current editor state can still be used
- JS logging for empty serialization during save with trace

**Comment by mejo-** [comment]
Is this still a thing @juliushaertl? In my tests, the frontend automatically reloads the document after a full reset of the document state using (`occ text:reset <fileId> -f`).

**Comment by juliushaertl** [comment]
Should be good then 👍
