### ISSUE TITLE
OCA\Text\Db\SessionMapper::deleteInactiveWithoutSteps lists more than 1000 expressions in a query

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/text#3989]
**Describe the bug**

```
Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.
#7 /var/www/cloud.domain.com/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(263): OC\DB\QueryBuilder\QueryBuilder::execute
#6 /text/lib/Db/SessionMapper.php(122): OCA\Text\Db\SessionMapper::deleteInactiveWithoutSteps
#5 /text/lib/Service/SessionService.php(151): OCA\Text\Service\SessionService::removeInactiveSessionsWithoutSteps
#4 /text/lib/Cron/Cleanup.php(76): OCA\Text\Cron\Cleanup::run
#3 /var/www/cloud.domain.com/nextcloud/lib/public/BackgroundJob/Job.php(78): OCP\BackgroundJob\Job::start
#2 /var/www/cloud.domain.com/nextcloud/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\TimedJob::start
#1 /var/www/cloud.domain.com/nextcloud/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob::execute
#0 /var/www/cloud.domain.com/nextcloud/cron.php(152): null
```

**To Reproduce**
1. ???

**Expected behavior**

No error

**Screenshots**

**Client details:**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by max-nextcloud** [comment]
Looks like more than 1k sessions are active at that very moment so the query has more than 1k expressions because of this:
```php
		$qb->andWhere($qb->expr()->notIn('id', $qb->createNamedParameter($activeSessions, IQueryBuilder::PARAM_INT_ARRAY)));
```

**Comment by max-nextcloud** [comment]
> Yeah we need to chunk and loop over those in PHP then.

Either that or we use a nested select statement. Not sure if that's possible with Oracle and the query builder though.

**Comment by juliushaertl** [comment]
Not sure about that, but we use a chunked loop in quite a lot of places so better be on the safe side there I'd say.

**Comment by juliushaertl** [comment]
Oh seems more tricky here since we are using a notIn to filter out active session.

**Comment by ChristophWurst** [comment]
> Either that or we use a nested select statement. Not sure if that's possible with Oracle and the query builder though.

https://github.com/nextcloud/server/blob/a1ed1db01b1e6cb798277baddfa41458631595c6/apps/dav/lib/CalDAV/CalDavBackend.php#L1897 I think it works

**Comment by juliushaertl** [comment]
I was looking into this and think we can optimize the`deleteInactiveWithoutSteps` method to just run one SQL query to perform the delete instead of a select and delete. Will check if I can push that later.
