### ISSUE TITLE
NC26: author tags are shown although no other user is in the file

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/text#4010]
**Describe the bug**
When I enter a md file, some author tags are shown of users who earlier edit this file.
After I wait for 30 seks the tags are gone

![grafik](https://user-images.githubusercontent.com/24530680/228915475-31f99fee-a6a9-475f-b965-034c6cddc827.png)

**Comment by fin444** [comment]
In my experience, this issue occurs because the editor displayed closed the tab directly via the browser instead of using the X in the top right. The tag will be left at the exact location that their cursor was at when they closed the tab, and will persist until the server restarts.

**Comment by jakobroehrl** [comment]
> 

Could be true, I think. 
But a server reboot does not delete this tags.
