### ISSUE TITLE
Add support to edit all kind of code files (java, html, etc)

### ISSUE THREAD

**Issue by Perflyst** [nextcloud/text#402]
**Is your feature request related to a problem? Please describe.**
The old text editor supports editing code files like .html and .java files. It also has syntax highlighting. 

**Describe the solution you'd like**
Text should be able to edit code files and should have syntax highlighting.
It should also make automatic code formatting if for example new `if { }` is written.

**Comment by juliushaertl** [comment]
Duplicate of #394
