### ISSUE TITLE
Detected link breaks mobile layout

### ISSUE THREAD

**Issue by stephanhoennekes** [nextcloud/text#4023]
**Describe the bug**
Once a link gets detected in text (and preview appears below) the text container seems to adapt to the size of --text-editor-max-width (670px) … even if the actual width is less than that (on mobile viewports for example). Text container’s width is bigger than the viewport.

**To Reproduce**
1. Paste hyperlink in mobile viewport.

**Expected behavior**
Responsive behavior of text container keeps the same as before (text breaks according to viewport width).

**Screenshots**

https://user-images.githubusercontent.com/26901419/229596802-e55f0fb5-7026-42ed-b4b0-c2326491f39b.mov

**Client details:**
 - OS: macOS, iOS
 - Browser: Chrome, Safari (iOS)
 - Version: current versions

**Text app version:** (see Nextcloud apps page)
3.7.2

**Nextcloud version:** (see Nextcloud admin page)
26.0

**Comment by luka-nextcloud** [comment]
@stephanhoennekes @juliushaertl Seems like the issue is caused by the width of url preview widget. So, how should be the url preview widget displayed in this case? totally hide or hide the overflow or something else?

**Comment by juliushaertl** [comment]
The link preview should automatically adjust, looking at the DOM layout it seems to be caused by the grid layout:

![Screenshot 2023-06-16 at 09 51 23](https://github.com/nextcloud/text/assets/3404133/328b895a-ed4b-4645-a6ca-8e2efd375a05)
