### ISSUE TITLE
Image description not editable after it has been set once

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4046]
**Describe the bug**
I should be able to edit an image description as often as I want, but it's not possible to do it after editing it for the first time.

**To Reproduce**
1. Paste an image
2. Edit the image description
3. Click somewhere else
4. Try to edit the description again by clicking on the field

**Expected behavior**
The image description field should be focussed and a cursor should appear that lets me edit the description, but nothing happens.

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 112
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.7.2

**Nextcloud version:** 26

</details>

**Comment by luka-nextcloud** [comment]
@provokateurin I am not able to reproduce the problem, please check the video.

https://user-images.githubusercontent.com/89908051/236118908-1a31ef2b-fc7f-4cb7-a67d-241fcca0e4a5.mov

**Comment by provokateurin** [comment]
I couldn't reproduce it in text, but in collectives it is broken (that's where I originally found it). So it seems to be a collectives specific bug?

**Comment by luka-nextcloud** [comment]
@provokateurin Could you please try to check on main branch if you can reproduce there?
https://github.com/nextcloud/text/pull/4071

**Comment by provokateurin** [comment]
I can try, although I don't see how the mentioned PR would fix the problem :thinking:

**Comment by provokateurin** [comment]
How can I use collectives with the latest main branch?

**Comment by juliushaertl** [comment]
This is a bit tricker since collectives is using a npm library that we build from text still, so it would require to run `npm run dev:package` on text and the use npm link to build collectives with it.

@mejo- maybe you can pair up with @luka-nextcloud on this one?

**Comment by provokateurin** [comment]
I think I was confused by two different problems:
1. The image description field was very short (has been fixed)
2. The cursor is always placed at the end of the image description field and there is no way to click somewhere else in the field to move it. Shall I open a new issue about that?

This lead me to not seeing the cursor when clicking into the image description field again when I wanted to edit the image description again.

**Comment by mejo-** [comment]
Thanks for clarification @provokateurin. I agree that your second point is a usability issue, so please file a new issue for it.
