### ISSUE TITLE
Can't show Chinese word corrlecty, Maybe it's because GB2312 and GBk encoding is not supported

### ISSUE THREAD

**Issue by Raven-L** [nextcloud/text#405]
![image](https://user-images.githubusercontent.com/47520028/68528643-7f766300-0330-11ea-84ad-7e2aaff0d181.png)

**Comment by juliushaertl** [comment]
Could you share an example file with me?

**Comment by Raven-L** [comment]
[软件说明.txt](https://github.com/nextcloud/text/files/3834517/default.txt)
OK,this is the example file.

**Comment by cly0514** [comment]
save problem

**Comment by xayane** [comment]
same problem

**Comment by caichao0519** [comment]
same problem

**Comment by juliushaertl** [comment]
So I was finally able to display the file on my development machine with the following PHP code:

```
<?php

$encodeList = 'UTF-8, GB2312';
$file = file_get_contents('default.txt');
$encoding = mb_detect_encoding($file, $encodeList);

echo $encoding;
echo PHP_EOL;
echo mb_convert_encoding($file, 'UTF-8', $encoding);
```

However I'm still not sure how to properly solve this as showing GB2312 file is a general issue as we are using UTF-8 encoding all over the place. We could of course check the encoding on open and convert the file to UTF-8 but not sure if that is the desired behavior. Needs more research on how other platforms handle such files.

**Comment by LL223851** [comment]
> [软件说明.txt](https://github.com/nextcloud/text/files/3834517/default.txt)
> OK,this is the example file.

这个我弄好了，反正都是中国人会遇到这个问题，就用中文来回答吧，没测试所有文件类型，不知道这样做会不会引发其他问题。
修改文件路径：/服务器路径/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php
第68行注销掉
修改为
            //$output->setOutput($this->file->getContent());
            $fileContents=$this->file->getContent();
            $encoding = mb_detect_encoding($fileContents . 'a', 'UTF-8,GB2312, GBK, WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII', true);
            if ($encoding === '') {
                $encoding = 'ISO-8859-15';
            }
            $fileContents = iconv($encoding, 'UTF-8', $fileContents);
            $output->setOutput($fileContents);

**Comment by juliushaertl** [comment]
Same issue for "windows-1250", see https://github.com/nextcloud/android/issues/6685#issuecomment-682554239 for an example file

**Comment by DogTorrent** [comment]
> 
> 
> > [软件说明.txt](https://github.com/nextcloud/text/files/3834517/default.txt)
> > OK,this is the example file.
> 
> 这个我弄好了，反正都是中国人会遇到这个问题，就用中文来回答吧，没测试所有文件类型，不知道这样做会不会引发其他问题。
> 修改文件路径：/服务器路径/nextcloud/apps/text/lib/Service/ApiService.php
> 第112行（line 112）修改为
> return new FileDisplayResponse($file);
> --->
> $fileContents=$file->getContent();
> $encoding = mb_detect_encoding($fileContents . 'a', 'UTF-8,GB2312, GBK, WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII', true);
> if ($encoding === '') {
> $encoding = 'ISO-8859-15';
> }
> $fileContents = iconv($encoding, 'UTF-8', $fileContents);
> $file->putContent($fileContents );
> return new FileDisplayResponse($file);

@LL223851 
Your code may cause some file broken such as avatar or image preview, cause you did not check if the file was text...
你没验证文件是否为纯文本，如果遇到缩略图也会将缩略图当成文本来更改编码，导致图片无法预览（小头像也是如此）
And this is the code I wrote that contains the code to check the file type:
``` php
$fileContents=$this->file->getContent();
$queryHeaders=$this->getHeaders();
if (array_key_exists("Content-Type",$headers) and $headers["Content-Type"] == "text/plain") {
	$encoding = mb_detect_encoding($fileContents . "a", "UTF-8, GB2312, GBK, WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII", true);
	if ($encoding !== false ) {
		//$encoding = "ISO-8859-15";
		$fileContents = iconv($encoding, "UTF-8", $fileContents);
	}
}
$output->setOutput($fileContents);
```
