### ISSUE TITLE
[Bug]: Maximum number of allowable file uploads has been exceeded at Unknown#0, only in .md files

### ISSUE THREAD

**Issue by Whoffie** [nextcloud/text#4052]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

To my knowledge, this is not a PHP or server issue. I am able to upload images and other documents to my main Nextcloud file system. The issue arises when an image is uploaded to a markdown document using Nextcloud's built-in markdown editor. When an image is uploaded, a simple "Upload error" appears in the top right corner of my screen. Upon further inspection of the logs, I see the following response:

Maximum number of allowable file uploads has been exceeded at Unknown#0

This _would_ lead me to believe that there is something wrong with my install / PHP settings specifically, but as I mentioned earlier, I am able to upload any number of documents and images to my Nextcloud file section.

I am currently on the latest version, Nextcloud Hub 4 (26.0.0)

### Steps to reproduce

1. Create a document in Markdown
2. Attempt to upload an image using the built-in WYSIWYG editor

### Expected behavior

An image is successfully inserted into the markdown document

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.159",
            "dontbestup.id"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/192.168.0.159\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        }
    }
}
```

**Comment by juliushaertl** [comment]
This error is issued by PHP so it looks like a setup issue. You might want to check the value of `max_file_uploads` in your php configuration.

**Comment by blizzz** [comment]
@Whoffie any updates on those questions?

**Comment by mejo-** [comment]
Let's close the issue for now. @Whoffie if you still experience the issue, please try to provide further details as asked in the questions above and don't hesitate to reopen.
