### ISSUE TITLE
 Footer is floating in the middle of the page in single file public link share

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/text#4064]
**Describe the bug**
In a public share on md file, the Nextcloud instance name and slogan are printed above the md file, hiding some content.
When scrolling the document, the name and content also scroll.

**To Reproduce**
1. Create a md file long enough to scroll it
2. Create a public share link
3. Open that public share link and scroll down
4. See the Nextcloud instance name and slogan scrolling

**Expected behavior**
Nextcloud instance  name and slogan should not hide content nor scroll.

**Screenshots**
![Uploading image.png…]()

**Client details:**
 - OS: [e.g. iOS] Windows 11
 - Browser: [e.g. chrome, safari] Firefox
 - Version: [e.g. 22] 110
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)
c.nc.c
**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This seems to be only an issue when talk is enabled (due to the talk sidebar that is injected and applying changes to the share page layout)

Quick fix like this seems to work but needs more testing with different scenarios:

![Screenshot 2023-04-26 at 18 45 54](https://user-images.githubusercontent.com/3404133/234646083-a4def545-ade7-4f9a-8eac-edcd97c81839.png)

**Comment by blizzz** [comment]
I can confirm or current main/master with Talk. Without Talk, the issue is not reproducible. I can also confirm the fix by Julius is working (on Firefox).
