### ISSUE TITLE
Jump to bottom button

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4086]
**Is your feature request related to a problem? Please describe.**
Annoying to scroll down in long documents or needing to open the outline

**Describe the solution you'd like**
Add a button to jump to the bottom of the document

**Comment by provokateurin** [comment]
I wasn't aware of that. Is there anything in the interface saying that those shortcuts work?

**Comment by provokateurin** [comment]
As far as I can tell my laptop doesn't have those home/end keys, so there is no way for me to jump to the bottom :/

**Comment by juliushaertl** [comment]
Let's get @nimishavijay and @jancborchardt here for some input ;)

**Comment by nimishavijay** [comment]
I would have to agree here,
- a scroll-to-bottom button is not present in any other similar software either (Google docs, dropbox Paper, etherpad)
- there are multiple ways to get to the bottom quickly, eg, using the End key as mentioned or by dragging the scrollbar 
- introducing a scroll-to-bottom may cause confusion while in a call with the editor open, as now that there is the feature to show a small video on the bottom right, which is also exactly where the scroll-to-bottom button would be

Perhaps the scrollbar could have a bit more visual prominence to give a nudge towards using dragging the scrollbar to the bottom as a quick way to scroll down :)

**Comment by provokateurin** [comment]
Yeah, the scrollbar is also good, but I have a hard time using it, because it's very very small.

**Comment by provokateurin** [comment]
Wouldn't little arrows at the top and bottom of the scrollbar also be an idea?

**Comment by nimishavijay** [comment]
> Yeah, the scrollbar is also good, but I have a hard time using it, because it's very very small.

I think there is already an open issue about this! I can't find it for the life of me though. It was a discussion about the scrollbar being too narrow, there was a suggestion to just make it the browser default, and I think that would already be much better without any buttons at all :)

**Comment by juliushaertl** [comment]
Should be https://github.com/nextcloud/server/issues/24619

Let's close this then and rather aim for more usable scroll bars :)
