### ISSUE TITLE
Text Viewer breaks Viewer's window's resize handling

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/text#4099]
**Describe the bug**

Viewer resizing is broken by a fixme for stable16. Still actual? 😅

https://github.com/nextcloud/text/blob/ff65bc4341b04d6d55c1d94ceeb16cd89c0ce1b7/src/components/ViewerComponent.vue#L71C1-L76

**To Reproduce**
1. Open viewer with a text
2. Change the window's size

**Expected behavior**

Viewer size is following the window's size (all without the sidebar).

**Actual behavior**

It is not.

Related: https://github.com/nextcloud/viewer/issues/1633

**Screenshots**

![Screnshot](https://user-images.githubusercontent.com/25978914/235260212-10b57a31-16cb-415d-a798-45994d8dbcee.png)

**Client details:**
 - OS: Windows 11
 - Browser: Vivaldi (Chromium-based)
 - Version: 27
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** current master

**Operating system:** Ubuntu 22
**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8

**Nextcloud version:** 27

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by max-nextcloud** [comment]
> @max-nextcloud Could you check that? Seems unnecessary to me these days

Sure. I'll take a look.
