### ISSUE TITLE
Image attachment not shown when title of markdown file contains '#'

### ISSUE THREAD

**Issue by jmechnich** [nextcloud/text#4156]
**Describe the bug**
When the name/title of a page contains a '#' character, image attachments cannot be loaded after saving.

**To Reproduce**
1. Create a new markdown file containing a '#' in its title/name
2. Attach an image, e.g. by pasting one from the clipboard
3. The image is displayed while still editing the file
4. Click the 'Done' button
5. The image is replaced by a 404 error box

**Expected behavior**
The image should be displayed all the time.

**Screenshots**

Create page containing '#' in name:
![image](https://user-images.githubusercontent.com/6206799/235304246-107c0b3e-78fa-4324-8a51-64f3269a1228.png)

View after saving image:
![image](https://user-images.githubusercontent.com/6206799/235304397-982eb7c0-c7fa-4c32-8422-dcb180e07e18.png)

View after replacing '#' with 'No.' and reloading/reselecting the page
![image](https://user-images.githubusercontent.com/6206799/235304461-f9c7ffd0-31d6-4551-b202-41c9efddb459.png)

From the developer tool in Firefox I gathered the following:
The Image loaded by collective-main.js contains an unescaped '#' character:
`[redacted]/Collectives/Instruments/Guitars/Heritage%2025th%20Anniversary%20C150%20#16%20(02-22-2010)/.attachments.460129/image.png
`

**Client details:**
 - OS: macOS 13.2
 - Browser: Firefox
 - Version: 112.0.2
 - Device: MacBook Air

<details>
<summary>Server details</summary>

**Collectives app version:** 2.4.0

**Operating system:** Debian bullseye

**Web server:** nginx

**Database:** mariadb

**PHP version:** 8.2

**Nextcloud version:** 26.0.1

</details>

I don't think that any further logs should be required but I am happy to deliver them in case they are.

**Comment by juliushaertl** [comment]
@mejo- Any futher pointers on why this goes wrong? Seems to be only an issue in the read only editor.

**Comment by mejo-** [comment]
As far as I tried to understand it, the problem is that with the readonly editor, we will request the file via DAV. And there, the `#` is not escaped in the filename when doing the request for some reason.
