### ISSUE TITLE
support checkboxes

### ISSUE THREAD

**Issue by CWempe** [nextcloud/text#416]
**Is your feature request related to a problem? Please describe.**
It looks like the current Version of Text does not support check boxes in lists.
I use lists with checkboxes very often and would like to use them with the new editor.

**Describe the solution you'd like**
`* [ ] foo` and `* [x] bar` should be displayed with (un)checked checkboxes.

**Describe alternatives you've considered**
Using another editor?

**Additional context**

It works here and in may other editors I use.

* [ ] foo
* [x] bar

**Comment by juliushaertl** [comment]
Duplicate of #93
