### ISSUE TITLE
Callout box with type `info` changes color with theme

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#4161]
**Describe the bug**
The border color of callout boxes with type `info` currently is set to `var(--color-primary-element)`. This variable can be changed in custom themes.

Instead, we should probably hardcode it to `#006aa3` for now and use `var(--color-info)` once it got introduced.

See https://github.com/nextcloud/nextcloud-vue/pull/4063#discussion_r1187741514.

**Comment by max-nextcloud** [comment]
I'd be tempted to just migrate to using Nextcloud vues note card and not backport this.

But maybe that's two steps indeed. A fix with a hard coded default that can be backported and then the migration.

**Comment by max-nextcloud** [comment]
We are using Nextcloud vue 7 since stable25. So maybe we could move to using the component right away to fix this and backport all the way to stable25 with minor version bumps of Nextcloud vue.
