### ISSUE TITLE
Outline state not in sync

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4176]
**Describe the bug**
The show/hide outline button is not in sync with the actual outline

**To Reproduce**
1. Click the "Show outline" button
2. Click the X on the outline to close it

**Expected behavior**
The button should be called "Show outline" but still shows "Hide outline" after the outline has been closed.

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 113
 - Device: Desktop

**Comment by luka-nextcloud** [comment]
It seems working fine on firefox v114.

**Comment by provokateurin** [comment]
Yep, I can't reproduce it on c.nc.c anymore. Probably was fixed in the meantime.
