### ISSUE TITLE
Footer is floating in the middle of the page in single file link share

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/text#4194]
**Describe the bug**
When opening a share link for a md file, the footer appear floating if the text is long enough to require scrolling

**Expected behavior**
No floating footer

**Screenshots**
![image](https://github.com/nextcloud/text/assets/14975046/8db108c8-472f-4ca8-8102-08b43da8e24d)

**Client details:**
 - OS: Arch btw
 - Browser: chrome
 - Version: 112
 - Device: desktop
 - Text app version: 3.7.2
 - Nextcloud version: 26

**Comment by juliushaertl** [comment]
closing as a duplicate of https://github.com/nextcloud/text/issues/4064

**Comment by skjnldsv** [comment]
Damn, I search for multiple keywords, didn't find it :see_no_evil:

**Comment by juliushaertl** [comment]
No worries, I adjusted the title with yours as it took me a bit to find as well 😁
