### ISSUE TITLE
.Txt Content deleted after restoring older Version an reopeninge with "Text"

### ISSUE THREAD

**Issue by StevenE009** [nextcloud/text#4205]
**Describe the bug**
Lines in .txt Document dissapear 

**To Reproduce**
1. create text Document test.txt with 3 Lines:
"Line1"
"Blank line with "enter key""
"Line2"
Upload via drag and drop

2. Open with Text, add two lines
"Blank Linke with enter key"
"Line3"
Click Save or autosave ... close Document

3. Go to File Details - > Version
Curren Version and Inital Version are available
Restore Inital Version

4. Open File again with text.
Verison with 3 Lines is displayed, click "use saved Version" (Die gespeicherte Version verwenden). I'M using german UI.
After Click "Line3" and also "Line2" are removed.
only "Line1" is keept.

So Content from Initial Version is removed.

**Expected behavior**
Original Content with "Line1" and "Line2" is displayed

**Client details:**
 - OS: Win10
 - Browser: tested on Firefox and Edge (113)

<details>
<summary>Server details</summary>

**Text app version:**  3.7.2

**Operating system:**
Ubuntu 22.04

**Web server:**
Apache

**Database:**
Art: sqlite3

**PHP version:**
Version: 8.1.2

**Nextcloud version:** (see Nextcloud admin page)
26.0.1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:



</details>

**Comment by kolAflash** [comment]
Sounds like the bug I described here at the bottom of this comment:  
https://github.com/nextcloud/text/issues/4100#issuecomment-1537097255

It also happened to me after restoring an older file version.  
And I'm pretty sure this didn't happen before Nextcloud-26.0. (regression)

**Comment by mejo-** [comment]
Would be interesting to know if this still happens with Nextcloud 26.0.2 (currently in RC state, about to be released on May 25th).

**Comment by StevenE009** [comment]
Hello mejo,

samen problem on 26.0.2 RC1

regards
Steven
