### ISSUE TITLE
auto save dose not working in Nextcloud

### ISSUE THREAD

**Issue by aihuanghe** [nextcloud/text#4210]
Auto save dose not working in Nextcloud;
Php8.0
nextcloud version:26
error info:
xception: OCA\Text\Db\StepMapper::getLatestVersion(): Return value must be of type ?int, string returned in file '/www/wwwroot/nextcloud/apps/text/lib/Db/StepMapper.php' line 69

After modifying the code, it can run normally:
public function getLatestVersion($documentId): ?int{
The modified code is:
public function getLatestVersion($documentId): ?string {

**Comment by juliushaertl** [comment]
Thanks for reporting. Can you post the full log message with the exception trace?

**Comment by mejo-** [comment]
Closing due to lack of information.
