### ISSUE TITLE
Menu dropdowns: Tooltip overlaps with first action and is sticky on mobile

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/text#4234]
**Describe the bug**

The tooltip "Remaining actions" is shown when clicking the ... to open the overflow menu.
It is sticky and does not disappear automatically, thus hiding the first menu item.

The same issue also applies to other dropdowns such as "Headings".

Both in the Files Android+iOS apps but also in the Nextcloud Notes Android+iOS apps.
I'm opening this here centrally, instead of creating 4 separate issues for (Files, Notes) x (Android, iOS). Feel free to move it.

In a mobile browser the tooltip is also sticky, but it is not a UX issue because there is space *above* for the tooltip (it only overlaps the title).

**Steps To Reproduce**

1. Open a document with the Rich Text editor in Files or Nextcloud Notes in the Android or iOS app.

**Expected behavior**

The tooltip should not automatically be shown, or at least disappear after 1-2 seconds?

**Screenshots**

Android Files app:
<img src=https://github.com/nextcloud/text/assets/33295590/af49c985-c25f-4194-a7d2-aba7773be6d8 width=35%>

iOS Files app:
<img src=https://github.com/nextcloud/text/assets/33295590/2d1296e9-f3e7-419c-a804-fa98397c2c00 width=35%>

iOS Notes app:
<img src=https://github.com/nextcloud/text/assets/33295590/9cc0337c-f2b9-45cd-872f-5b9665dca799 width=75%>

It is not an issue if I log in to Nextcloud in Firefox for Android and open the Rich Text editor there:

<img src=https://github.com/nextcloud/text/assets/33295590/f616e263-04e0-49cb-ae85-a7477218f881 width=35%>

**Client details:**

Device 1:
 - OS: iPadOS 16.5
 -  Device: iPad Pro 2020
 -  Files app: 4.8.0.5
 -  Notes app: 4.1.7

Device 2:
 -  OS: Android 13
 -  Device: OnePlus 5
 -  Files app: 3.24.1
 -  Notes app: 4.0.0

<details>
<summary>Server details</summary>

**Text app version:** 3.7.2

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 26.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
n/a
```

#### Browser log
```
n/a
```

</details>

**Comment by juliushaertl** [comment]
Has been fixed with #5174
