### ISSUE TITLE
Add button to disable all wysiwyg features

### ISSUE THREAD

**Issue by andynd** [nextcloud/text#424]
**Is your feature request related to a problem? Please describe.**
I can no longer copy/paste or write raw markdown without it getting escaped

**Describe the solution you'd like**
I do not want any wysiwyg functionality, I just want a plain texteditor. Some persons using the same instance *do* want wysiwyg features. Please give us an option to make both happen and settings to select a default.

**Describe alternatives you've considered**
Switching to another Plugin, but then I loss the option to switch on the fly or open files with a simple klick.

**Comment by pierreozoux** [comment]
I personnaly like the experience that [codiMD](https://demo.codimd.org/) provides. But I understand that it shouldn't be the default for most users.
I personally prefer raw MD too.

this is linked to https://github.com/nextcloud/text/issues/418

**Comment by edonnachie** [comment]
Given that the text addon is regarded as the default interface, the ability to turn off WYSIWYG would appear to be a basic requirement. Or at least prevent the interface from "correcting" quotes, brackets etc., thus breaking many markdown documents.

**Comment by juliushaertl** [comment]
Let's continue with https://github.com/nextcloud/text/issues/439 (which has some more discussion on that)
