### ISSUE TITLE
Ctrl+S doesn't work

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4244]
**Describe the bug**
Pressing Ctrl+S should save the document, but the browser save dialog opens instead.
https://github.com/nextcloud/text/issues/300

**To Reproduce**
1. Press Ctrl+S

**Expected behavior**
Pressing Ctrl+S should save the document, but the browser save dialog opens instead.

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 113
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.7.2

**Operating system:** Alpine Linux

**Web server:** Nginx

**Database:** Postgres

**PHP version:** 8.2

**Nextcloud version:** 26.0.2

</details>

**Comment by blizzz** [comment]
The save is actually triggered, but the browser's save behaviour is triggered just as well.

**Comment by luka-nextcloud** [comment]
After investigation, it seems like there is no way to prevent the browser's save action since the Ctrl+S is browser's hotkey.

**Comment by provokateurin** [comment]
But as far as I understood it once used to work?

**Comment by mejo-** [comment]
Also, in Collabora Online it somehow works. There, <kbd>Ctrl</kbd>-<kbd>S</kbd> only saves the file and doesn't open the browsers "Save file as" dialog.

**Comment by juliushaertl** [comment]
@provokateurin Can you tell if this only happens if the editor doesn't have a cursor focus in the document itself?

**Comment by juliushaertl** [comment]
Note for later:
- Maybe we need to also listen for ctrl+s in the editor wrapper component itself not just in tiptap:
  - https://github.com/nextcloud/text/blob/main/src/components/Editor.vue#L27C9-L27C9
  - https://github.com/nextcloud/text/blob/main/src/components/Editor.vue#L504-L508

**Comment by provokateurin** [comment]
I tested it with the cursor inside the editor and it didn't work. It always downloaded a file, regardless of where my cursor was.

I noticed that there are different behaviors:
In text the markdown file got downloaded.
In collectives an html file got downloaded that contains the whole website.
So in the normal text app it triggers a different handler (probably from the files app?).

**Comment by juliushaertl** [comment]
Might be https://github.com/nextcloud/viewer/blob/master/src/views/Viewer.vue#L845 for the markdown one then

**Comment by juliushaertl** [comment]
Let's try to tackle this the following way:
- Add a event listener for any key events to the `#editor-container` in https://github.com/nextcloud/text/blob/main/src/components/Editor.vue#L27C9-L27C9
- If the event listener is triggered by `Ctrl-S` or `Cmd-S` (for macOS) we run the syncService.save() method and preventDefault on the event to avoid triggering the native save dialog
