### ISSUE TITLE
在Android设备上，使用WebView打开，没有弹出账号密码输入框，提示Unauthoriaed

### ISSUE THREAD

**Issue by reverseAndroid** [nextcloud/text#4298]
在Android设备上，使用WebView打开nextcloud.com，会报错

Unauthoriaed
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials(e.g.,bad password),  or your browser doesn't understand how to supply the credentials required.
Apache/2.4.57(Debian) Server at nextcloud.fgms.dev.com Port 80。

但是同样的地址在Android设备的自带浏览器上打开，就会弹出账号密码输入框，输入账号密码后正常使用，但是在我自己的android app中，使用WebView打开nextcloud.com就会报错，也不会弹出账号密码输入框。现在我觉得是Android webview中没法调用出账号密码弹出框的问题导致报错，请问下这个问题，我该怎么解决？
`public class MainActivity extends AppCompatActivity {
    private WebView webView;

    @RequiresApi(api = Build.VERSION_CODES.O)
    @SuppressLint("SetJavaScriptEnabled")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        webView = findViewById(R.id.webView);
        webView.addJavascriptInterface(new WebAppInterface(this), "Android");
        webView.setWebViewClient(new WebViewClient());
        webView.setScrollBarStyle(View.SCROLLBARS_INSIDE_OVERLAY);
        webView.getSettings().setDomStorageEnabled(true);
        webView.getSettings().setAllowUniversalAccessFromFileURLs(true);
        webView.getSettings().getDatabaseEnabled();
        webView.setNetworkAvailable(true);

        webView.getSettings().setAppCacheEnabled(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.getSettings().setLoadWithOverviewMode(true);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.getSettings().setAllowContentAccess(true);
        webView.getSettings().getCacheMode();
        webView.getSettings().setUserAgentString("Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (XHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19");

        webView.getSettings().setUserAgentString("Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.14 (XHTML, like Gecko) Mobile/12F70");
        webView.setLayerType(View.LAYER_TYPE_HARDWARE, null);

        webView.getSettings().setBuiltInZoomControls(true);
        webView.clearHistory();
        webView.getSettings().setUserAgentString("Mozilla/5.0; Mobile/12F70");
        webView.clearCache(true);
        webView.getSettings().setDisplayZoomControls(true);
        webView.getSettings().setSupportZoom(true);
        webView.getSettings().setDefaultTextEncodingName("utf-8");
        webView.getSettings().setSupportZoom(true);
        webView.getSettings().setAllowUniversalAccessFromFileURLs(true);
        webView.getSettings().setSafeBrowsingEnabled(true);
        webView.getSettings().setJavaScriptCanOpenWindowsAutomatically(false);
        webView.getSettings().setAllowFileAccessFromFileURLs(true);
        webView.getSettings().setLoadWithOverviewMode(true);
        webView.getSettings().supportMultipleWindows();

        webView.loadUrl("http://nextcloud.fgms.dev.com");
        webView.setWebChromeClient(new WebChromeClient());

    }

    @Override
    public void onBackPressed() {
        if(webView.canGoBack()){
            webView.goBack();
        }
        else {
            super.onBackPressed();
        }
    }

    public static class WebAppInterface {
        Context mContext;

        /** Instantiate the interface and set the context */
        WebAppInterface(Context c) {
            mContext = c;
        }

        /** Show a toast from the web page */
        @JavascriptInterface
        public void showToast(String toast) {
            Toast.makeText(mContext, toast, Toast.LENGTH_SHORT).show();
        }
    }
}`
这个是在webView上打开。
![QQ截图20230615110027](https://github.com/nextcloud/text/assets/25810748/5212b1fd-5f3b-4aa7-8534-9d461a947681)

这个是在Android自带浏览器上打开
![image](https://github.com/nextcloud/text/assets/25810748/50271e90-6ac3-4279-8a2c-b6600d8c1e55)

**Comment by mejo-** [comment]
Dear @reverseAndroid, thanks for your report. To me It seems like an authentication issue though and not related to the Text app. Also the apache error in the first screenshot seems like something related to the deployment, not to the Nextcloud software itself. I'll close the issue for now, but don't hesitate to provide more information.
