### ISSUE TITLE
Can not use mouse to place cursor in image description field

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4399]
**Describe the bug**
When clicking into the image description field it is not possible to move the cursor by using the mouse. The cursor is always placed at the end and can only be moved by the arrow keys.

https://github.com/nextcloud/text/issues/4046

**To Reproduce**
1. Paste image
2. Write an image description and unfocus the field
3. Focus the field again and try clicking somewhere with the mouse

**Expected behavior**
The cursor should be set where I clicked into the field and be movable by the mouse.

**Server details:**
- Nextcloud version: 27.0.0
- PHP Version: 8.2
- Database: Postgres 14

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 114
 - Device: Desktop

**Comment by luka-nextcloud** [comment]
@provokateurin I am not able to reproduce on firefox 115, does it only happen on firefox 114?
[test.webm](https://github.com/nextcloud/text/assets/89908051/22590c58-e69b-482c-8cc6-d560d294b7ce)

**Comment by provokateurin** [comment]
In the video your cursor is not visible, but it doesn't look like you tried moving the cursor inside the image description field using the mouse? I can still reproduce it on Firefox 115.
