### ISSUE TITLE
Request: Show embedded images that are located in hidden folders

### ISSUE THREAD

**Issue by phiL0co** [nextcloud/text#440]
If I embed an image that's located inside a hidden folder inside my nextcloud (folder with a preceding "."), the image is not displayed.
When I did the same in the markdown editor, it worked, the images appeared.

I personally like to save the corresponding images in hidden folders on the same folder level as the markdown file because they are only relevant for the markdown file and not as files as such. 
In that way the file structure is not that cluttered with image folders.

Could this feature also be implemented in text?

**Comment by azul** [comment]
I don't think this is specific for hidden folders.
#504 should also fix this.
