### ISSUE TITLE
Copy and paste removes newline

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/text#4443]
**Describe the bug**
Copy and pasting text removes the newlines.

**To Reproduce**
1. Type some text with a newline in it
2. Copy the lines
3. Paste the lines
5. See that the newline is removed and the text is printed one just one line

**Expected behavior**
Pasted text should be shown the same way as the copied text.

**Screenshots**
[Screencast from 05-07-23 11:24:20.webm](https://github.com/nextcloud/collectives/assets/696839/a84c1539-5278-4e73-9edd-9b21f16ebe0d)

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox 114.0.2 and Chromium 114.0.5735.106
 - Device: laptop

<details>
<summary>Server details</summary>

**Collectives app version:** 2.6.0

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 26.0.3

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
This bug was introduced with the changes in #3906.

I think I found a better approach in #4452.
