### ISSUE TITLE
Footer scrolls with text when using public link

### ISSUE THREAD

**Issue by Uatschitchun** [nextcloud/text#4461]
**Describe the bug**
Sharing a .md file publically and open it results in the nextcloud's page-footer to scroll with the text

**To Reproduce**
1. Create .md file
2. share publically
3. open shared link in private tab & scroll down

**Expected behavior**
The page-footer should stay where it belongs, at the foot of the page

**Server details:**
- Nextcloud version: 27
- PHP Version: 8.2
- Database: MariaDB 10.5

**Client details:**
 - OS: Linux
 - Browser: Opera & Firefox

**Comment by juliushaertl** [comment]
Seems like a duplicate of https://github.com/nextcloud/text/issues/4064
