### ISSUE TITLE
Document status notice with connection issues is not sticky

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#4483]
**Describe the bug**
The document status notice that displays connection issues is not sticky anymore.

See https://github.com/nextcloud/text/pull/4474#issuecomment-1630971483 for a screenshot.

**To Reproduce**
1. Open a Text document with content long enough to scroll.
2. Open network tab of browser developer tools, block network.
3. Type something, see the notice about connection issues pop up.
4. See that the notice is not sticky.

**Comment by juliushaertl** [comment]
Recording from #5100

![Peek 2023-12-07 12-43](https://github.com/nextcloud/text/assets/7018928/4b6e24da-5e5b-443d-8672-2fe07bd1cb93)

**Comment by juliushaertl** [comment]
Once at it one could also address https://github.com/nextcloud/text/issues/4905

A possible fix needs careful testing of different ways that the text editor is embedded in scroll containers:
- Single file opened in the viewer as a logged in user
- Open a file on a public share link of that file
- Open a file on a publich share link of a folder
  - Make sure to test this with Talk enabled and disabled as talk registers a sidebar on the public share pages
- Collectives regular page and share links
- Notes
