### ISSUE TITLE
Workspace polishing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#452]
Some stuff brought up by @jospoortvliet 

- [x] Inserted images and attachments need some size adjustments
- [ ] ~images and attachments should be arranged in a row if possible~
- [x] Checklists work but you first have to make a list, THEN make it a checklist
- [x] code block doesn't work on a single word, only on the entire block (works in Text)

**Comment by dacoex** [comment]
Please add the issues w.r.t. Readme.md:
https://github.com/nextcloud/server/issues/19938

**Comment by juliushaertl** [comment]
Let's close this and track follow up stuff in individual issues.
