### ISSUE TITLE
Loading error after deleting rich workspaces readme.md

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/text#4525]
**Describe the bug**
See video

**To Reproduce**
See video

**Expected behavior**
* The folder description should disappear
* no error should raise, because it is expected that the deleted file can't be loaded

**Screenshots**

https://github.com/nextcloud/text/assets/26707476/9cd91a67-0f78-4c1d-9b99-70e2101a5ddf

**Server details:**
- Nextcloud version: 27.0.0
- PHP Version: 8.1
- Database: MariaDB 10.6

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Browser version: current
 - Device: desktop

I think it is reproducable, so no logs are necessary

**Comment by dartcafe** [comment]
possibly related to #3719

**Comment by juliushaertl** [comment]
With files to vue there should be an event that we can catch to hide the rich workspace accordingly

https://github.com/nextcloud/server/blob/7ee34a3fac802b1512fe3d12e9cc4d5b817a8ee1/apps/files/src/actions/deleteAction.ts#L52
