### ISSUE TITLE
CI: rely on cypress:default group rather than cypress summary

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#4535]
**Is your feature request related to a problem? Please describe.**

Recently i saw that the `cypress summary` failed while `cypress:default group` succeeded:

![grafik](https://github.com/nextcloud/text/assets/97337118/e2448541-cd0c-430e-817f-bdf05bff3b25)

The cause for this particular [run](https://github.com/nextcloud/text/actions/runs/5559640180/jobs/10156323362?pr=4528) was that one cypress runner failed to download cypress and thus could not start.

Cypress ran fine with the remaining 7 runners. The merge was still blocked on the failing `cypress summary`.

**Describe the solution you'd like**

The fact that cypress still succeeds even if one of the runners fails to start is a feature - not a bug. :)

* Check `cypress:default` for the branch protection instead of `cypress summary`
* Maybe drop `cypress summary` all together.

**Describe alternatives you've considered**
A rerun will fix this for this case. But it seems like something we could tweak.

**Comment by juliushaertl** [comment]
I’ve also seen cypress default group sometime just not getting reported, so I’d rather stick to the GitHub action where we can check the status and rerun
