### ISSUE TITLE
Printing (from browser) is broken (again) 

### ISSUE THREAD

**Issue by Uatschitchun** [nextcloud/text#4536]
**Describe the bug**
When printing a longer text, only the first page gets printed and is cropped 

**To Reproduce**
1. Have a longer text 
2. Use print from browser 
3. See error

**Expected behavior**
For to print or export to PDF using browsers print function, the text should print completely and well formatted. 

This was originally fixed and added (print CSS) and merged with PR: https://github.com/nextcloud/text/pull/2867

**_So this seems to be a regression_**. 

You can find screenshots in the PR. 

**Server details:**
- Nextcloud version: [27]
- PHP Version: [8.2]
- Database: [MariaDB 10.5]

**Client details:**
 - OS: [Linux]
 - Browser: [Opera (Chrome)]

**Comment by juliushaertl** [comment]
Can you provide a screenshot of the error? For me it works fine

**Comment by Uatschitchun** [comment]
> Can you provide a screenshot of the error? For me it works fine

Sure, here you are. This is the Readme.md from this repo. I tested on 2 different NC installations with same result.
![Screenshot_20230717_150702](https://github.com/nextcloud/text/assets/25088926/9cbc30fe-72a9-495a-872f-a66539c97ac8)
![Screenshot_20230717_150818](https://github.com/nextcloud/text/assets/25088926/ae7bbdb6-8c63-40d2-9d9e-f12c1f097826)

**Comment by sopvkore** [comment]
Observing the same. I suspect the issue is not around the print css but somewhere else. PR mentioned is still in (unchanged).
I'm wondering if it is perhaps install related issue - I'm running a couple of instances based on linuxserver docker images (versions 27+). 
Also, confirm it works on  a (public) nextcloud instance (murena.io) which is most likely v26.sth or even 25+. print.scss seems to be identical on all instances I could check.

**Comment by dertorsten** [comment]
Tested this with a galor of lore ipsum:
27.1.3 - Docker Nginx-FPM  PHP8.2 / fail
26.0.8 Nginx PHP 8.1 fail
25.0.12 Nginx PHP 8.1 works

**Comment by juliushaertl** [comment]
When we fix this we should also add a regression test if possible with something like this in cypress: https://stackoverflow.com/questions/65022756/testing-printing-a-page-from-a-webapp-cypress-jest-storybook

**Comment by AdamPS** [comment]
Broken for me on 27.1.3 PHP 8.1 Apache.

- Can I provide any extra diagnostics?
- Does anyone have any idea of a workaround yet please?

**Comment by AdamPS** [comment]
Great thanks
