### ISSUE TITLE
[UI] list items are too separated in a list 

### ISSUE THREAD

**Issue by 87113** [nextcloud/text#4547]
**Describe the bug**
The items are visually too separated in list  

**To Reproduce**
1. write a list with some items 

**Expected behavior**
The list items should be compact enough to help the user to see that is the same list. 

In the html the content of the `<li>` is inside a `<p>` and a `<div>` each of them with a pretty big `margin-bottom`. 
If this margin are disabled the space between list item is perfect. 

**Screenshots**

actual style 

![Capture d’écran du 2023-07-14 15-21-13](https://github.com/nextcloud/collectives/assets/102969362/dfe8b0be-7eb5-4dee-8127-b777c69c9794)

What I think is better

![Capture d’écran du 2023-07-14 15-21-44](https://github.com/nextcloud/collectives/assets/102969362/4039a6ba-b9db-4a19-a63d-da669874aa34)

**Comment by jancborchardt** [comment]
It actually seems like a bug? Currently the `padding-bottom: 1em;` from `p .paragraph-content` is taken, but the `li p { padding-bottom: 0.5em; }` is correct.

So yes, I’m fine with shortening this in lists to 0.5em, but make sure that it doesn’t break the case where 1em is wanted, like for paragraphs.
