### ISSUE TITLE
Pasting paragraphs sometimes adds unexpected linebreaks

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#4602]
**Describe the bug**
When pasting paragraphs to a document, sometimes unexpected linebreaks are added in between the paragraph. As soon as you do one change in the paragraph, all unexpected linebreaks get deleted at once.

As an example, paste the first 3-4 paragraphs of the [wikipedia article about Fairy Tales](https://en.wikipedia.org/wiki/Fairy_tale) into a document.

**To Reproduce**
1. Open a document, paste the example paragraph from above.
2. See unexpected linebreaks
3. Add one character anywhere in the paragraph
4. The the unexpected linebreaks disappearing.

**Comment by juliushaertl** [comment]
This seems to come from the `white-space: pre-wrap;` that is added to the paragraph. Might be coming from `@tiptap/vue-2/src/NodeViewContent.ts`

**Comment by mejo-** [comment]
Indeed, that's the reason for this behaviour. I wonder whether we should use our own implementation of `NodeViewContent` without `white-space: pre-wrap`? @juliushaertl and @max-nextcloud do you see any reason why we would need `white-space: pre-wrap` in `NodeViewContent`?

**Comment by juliushaertl** [comment]
This seems to come from the prosemirror stylesheet recommentations ad would also warn in https://github.com/ProseMirror/prosemirror-view/commit/b8b814c332f2bb51f07a4a397a074c7d0178434f, but i think it the original paragraph node doesn't have it we can also drop it here.

https://github.com/ProseMirror/prosemirror/issues/981 might give a bit of reasoning for what it is needed

**Comment by juliushaertl** [comment]
Worth to double check against this logic https://github.com/nextcloud/text/blob/b57faa02cd6ec6f38ffd26563a845a88cb3ef1dd/src/extensions/Markdown.js#L79-L104

**Comment by max-nextcloud** [comment]
### Experiments

#### replace the `preserveWhitespace: full` in `parseHtml` with `true`

This will fix the unexpected line breaks but at the same time also breaks the tests for preserving line breaks in markdown.


#### in addition to #4624 I also remove `whiteSpace` setting in `NodeViewWrapper`

Removing [this](https://github.com/ueberdosis/tiptap/blob/develop/packages/vue-2/src/NodeViewWrapper.ts#L27) broke the #4624 fix as now `whiteSpace` was inheriting `pre-wrap` again from the `.Prosemirror` tag.


### Conclusion

We actually have some conflicting interest here:
* preserve whitespace (in md files, when pasting lists of plaintext separate by empty lines)
* get rid of unexpected linebreaks when pasting html content.

However it's hard to destinguish pasting html from the initial load as we are also inserting html there.

**Comment by max-nextcloud** [comment]
Looks like prosemirror has a `transformPastedHtml` option that we could use to get rid of newlines outside of pre tags:

https://github.com/ProseMirror/prosemirror-view/blob/a93d102a121585d2244c7d23ba8383e277cf4aac/src/clipboard.ts#L64
