### ISSUE TITLE
Integrate text processing API

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4613]
Based on https://github.com/nextcloud/server/pull/38854 we will add options to process selected text.

This is the summary of what I discussed with @julien-nc during our meeting:

- Assistant app will provide a generic way across nextcloud in the menubar
  - Will trigger a dialog
- For text we will have some sort of action to trigger this dialog which gets prefilled with the selected text, processing task, app, identifier)
- As text processing is an async operation, we will need
  - a list of pending/finished tasks per document which could be rendered inline
  - the list provides a action to insert at cursor position
  - the list provides an option to dismiss the result
  - the list needs regular refreshing, could also get triggered by the notification from the assistant app

## Depends on 

- Server: Provide an OCS endpoint to list tasks for [app+identifier](https://github.com/nextcloud/server/pull/38854/files#diff-5e16b846a26a3d2e8efc3b1b628357d8bdd297ba325fd3f0b5b958f02a1557bfR76-R85)
- Assistant app: Provide a JS API to launch a modal, pseudo code API: 
```
openTextProcessingModal(appId, identifier,  task, inputText) 
    => new Promise((resolve, reject) => { resolve(ScheduledTask) })
```
- Assistant app: PHP event dispatched to trigger enhancing the notification with the link to the file to open in text
  - Task is finished -> assistant app prepares a notification -> emits an event -> text adds the file link (based on app+identifier) -> assistant app emits the notification

- UI questions to discuss
  - Where to put the processing options (menubar button, popover menu on select, menu next to the paragraph)?
  - How does the list look like (positioning, overflow, buttons, mobile)

**Comment by julien-nc** [comment]
LGTM!

**Comment by juliushaertl** [comment]
@nimishavijay This is the tracking issue for bringing support of https://github.com/nextcloud/server/issues/39478 to text. When discussing this with @julien-nc We were basically considering the following UI wise:

- Text offers a button to start the modal outlined in https://github.com/nextcloud/server/issues/39478 prefilled with the currently selected text
  - Question: Where should we put that button? It could be next to the already existing translate button in the menubar for example or would this be not visible enough? 
    <img width="1276" alt="Screenshot 2023-08-02 at 18 06 05" src="https://github.com/nextcloud/text/assets/3404133/d8760a5c-68da-457a-90c0-49133c3281a2">
- When the task is scheduled we will list all pending and succeeded tasks in the bottom of a text document
  - This can be used to get back to scheduled tasks once they are finished to insert the result into the document
  - Quick-and-dirty mockup:
    <img width="768" alt="Screenshot 2023-08-02 at 18 16 36" src="https://github.com/nextcloud/text/assets/3404133/aabf0e90-3f43-4c2c-9385-5d739decfbcb">

**Comment by nimishavijay** [comment]
> Question: Where should we put that button? It could be next to the already existing translate button in the menubar for example or would this be not visible enough?

So the original idea was that for Text it would be a floating button next to the line which has the cursor. That way the text fed into the TP widget would be the text in that line, or the text that has been selected. Would that be possible? It would look something like this:

![image](https://github.com/nextcloud/text/assets/52440189/577cedec-21d6-4591-8d69-f4ca8d24ab3f)

If not I would agree that it could go into the formatting bar. Since this is a feature we would like to market, I'd also agree that placing it near Translate is not visible enough. How about we place it as the last action before the remaining actions, and it is styled as a secondary icon-only button similar to the screenshot above. It would be great if the action menu with the subactions is there, but that is also something to be discussed with Julien :) What do you think?

> When the task is scheduled we will list all pending and succeeded tasks in the bottom of a text document 

That's a great idea! Indicating the progress would be different for each app, but this is a great solution for Text. The quick screenshot you pasted already is pretty close to how it would look ideally. I would only suggest that it be moved to the top right as in the bottom left there is a chance for it to overlap with the outline.

It would also be nice to be able to collapse it in case it gets in the way :)

**Comment by mejo-** [comment]
> So the original idea was that for Text it would be a floating button next to the line which has the cursor.

I just wanted to mention that we just got rid of the floating menu for links with Nextcloud 26 and that people were constantly annoyed by the floating menu. A button right to cursor position of the editor is less annoying, but still might be a bit too intrusive, given that it travels with your cursor all the time when typing/navigating in the document.

**Comment by juliushaertl** [comment]
Yes, definitely something to consider. @nimishavijay What do you think? Wouldn't the button changing position all the time be a bit too much when just working with the document?

**Comment by juliushaertl** [comment]
Another idea would be to just make the bottom overlay area a trigger for the popover menu.

**Comment by nimishavijay** [comment]
That's a good point. The reference I had in mind for that is something like Google Docs' comment indicator, which sort of follows your cursor. However that appears only on hovering over the right half of the screen. Would something like that be in scope? Hide the button while typing or while the mouse cursor is stationary for ~ 2 seconds, and show it if the mouse cursor is hovering over the text or the space on the right. 

If that is too complicated, no worries! We will likely have to show it on the formatting bar on mobile anyway, so we can just go with that for desktop as well :)

**Comment by jancborchardt** [comment]
I would say for this feature it is fine if it’s floating, as @nimishavijay said right of the current line, not next to the cursor. Google Docs does the exact same as said:
![image](https://github.com/nextcloud/text/assets/925062/c6a4d091-7310-4047-9571-030ebe3e518b)

And the currently processing tasks could show in the Assistant menu as a last entry "Ongoing tasks" (or "4 ongoing tasks" to actually list how many) and if you click it a submenu opens like we do in Mail for "More actions".
