### ISSUE TITLE
マルチバイト文字に対するエンコードの致命的なバグ

### ISSUE THREAD

**Issue by okamepowder** [nextcloud/text#4615]
マルチバイト文字に対するエンコードの致命的なバグ

mb_check_encoding によるエンコード判定はできない。mb_check_encodingをエンコード判定に使用してはいけない。
この関数は確定したエンコードに対する不正コードの検出関数である。

このコードは致命的なバグである。
a/apps/text/lib/Service/EncodingService.php
```
public function detectEncoding:
		foreach ($this->getEncodings() as $encoding) {
			if (mb_check_encoding($string, $encoding)) {
				return $encoding;
			}
		}
```

正しくは

step1: mb_detect_encoding による文字コードの確定
step2: mb_check_encoding によるstep1で確定した文字コードにおける不正文字のチェック
step3: 結果を返す

**Comment by mejo-** [comment]
Dear @okamepowder, could you please open a new report in english? Unfortunately none of us speaks japanese.
