### ISSUE TITLE
Make placeholder more useful

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4619]
We could advertise more features in the placeholder text, similar to google docs:

https://github.com/nextcloud/text/assets/3404133/63177a4d-72b8-4937-bc8f-0574e99ed566

Currently we only have a hard coded message:
- Add notes, lists or links ...

Examples from other products:
- Notion: Press 'space' for Al, '/' for commands.
- Talk: Write message, @ to mention someone ...

Topics we may advertise:
- Smart picker
- Mentions

Any thoughts about this @nextcloud/designers mabye also ideas of further features to advertise through this? I also thought about specific smart picker features depending on what is installed.

**Comment by jancborchardt** [comment]
> I also thought about specific smart picker features depending on what is installed.

Yeah, that seems good! Do you have an idea for a message you would like? I’m not sure the message switching around would be accessible, so it’s probably best to start with a single one.

> Start writing, or try '/' for the Smart Picker

**Comment by juliushaertl** [comment]
Adding another sample from @mejo- on notion:

| Screenshot |
| --- |
| ![2024-09-16T11:07:00,506168105+02:00](https://github.com/user-attachments/assets/ef37c258-638a-43b6-b317-1ada590c3c1e) |
