### ISSUE TITLE
Syntax highlightning for code blocks does not work very well

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#4676]
**Describe the bug**
When inserting a code block the latest version of Text seems to add syntax highlighting. However that approach has some severe problems:

1) Syntax is not determined by a given language name but somehow "detected". The correct way would be to treat all code blocks as plain text except when someone indicates the language to be used in the first line (like ```json to indicate that the following block is JSON) - also see https://www.markdownguide.org/extended-syntax/#syntax-highlighting about this.

2) The colours used are sometimes really hard to read - like light orange text on a grey background.

3) The "detection" of the code seems not to work properly in some cases and colors single characters like "no" in the Word "Arno" (see screenshot).

**To Reproduce**
1. Create a new text document
2. Insert a codeblock
3. Enter some text to the code block

**Expected behavior**
Code blocks without lanuage indication should be treated as plain text and not as code. It should be possible to define the language by entering it after the first ``` part or using some drop down above the block which offers all supported languages.

It would also be nice to have line numbers for code blocks so one can see what belongs to the same line, since the code blocks to word wrapping it is sometimes hard to recognize what text blongs to which line.

**Screenshots**

![image](https://github.com/nextcloud/text/assets/6613614/a914f790-8785-4101-a7b6-ef7a06145010)

**Server details:**
- Nextcloud version: 27.0.2
- PHP Version: 8.1
- Database: MariaDB

**Client details:**
 - OS: Windows
 - Browser: Vivaldi
 - Browser version: 6.1.3035.257 (Stable channel) (64-Bit) 
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
(not relevant)
```

#### Browser log
```
(not relevant)
```

</details>

**Comment by juliushaertl** [comment]
Thanks for the detailed bug report.

> Syntax is not determined by a given language name but somehow "detected". The correct way would be to treat all code blocks as plain text except when someone indicates the language to be used in the first line (like ```json to indicate that the following block is JSON) - also see [markdownguide.org/extended-syntax/#syntax-highlighting](https://www.markdownguide.org/extended-syntax/#syntax-highlighting) about this.

This should already be the case, do you have some markdown where this is the case?

> The colours used are sometimes really hard to read - like light orange text on a grey background.

Yes, this is definitely something we should fix.

> The "detection" of the code seems not to work properly in some cases and colors single characters like "no" in the Word "Arno" (see screenshot).

Did you provide a language on that code block or was it auto-detected?

**Comment by juliushaertl** [comment]
Sorry I mixed up some fixes there in my head and thought it was already released.

Apparently we have addressed this for the upcoming 27.1 release in https://github.com/nextcloud/text/pull/4614/commits/62f5d3e846b604a9e7576f5b9eae85bdd82fba1f#diff-2c9bf2121a3fd6e8e741c370dac3eaf7b84fa998365c3c3dc882cd81b5cf0ba3R93
