### ISSUE TITLE
Assistant synchronous task handling and polishing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4686]
from https://github.com/nextcloud/text/pull/4627

- [ ] Implement synchronous tasks 
- [ ] Smaller polishing
  - [ ] use notifications for triggering fetch instead of polling
  - [ ] FAB on mobile
  - [ ] How to handle markdown vs plain text
  - [ ] Dismiss notifications
  - [ ] merge translate to it and just move the actions to popover directly
  - [ ] Think about the making it show/hide depending on the mouse cursor (gdocs)

**Comment by julien-nc** [comment]
Additionally:
* [ ] Decide what to do when the assistant returns a completed task immediately (new [sync flow](https://github.com/nextcloud/assistant/pull/13)).

**Comment by jancborchardt** [comment]
If there are any design questions regarding this, @nimishavijay is the expert since she worked on the current implementation. :)

**Comment by luka-nextcloud** [comment]
> As discussed in the call
> 
> * Assistant will offer a flag to close the modal after a successful sync task
>   
>   * Can be used to directly insert and act with a sync result in text (e.g. when generating text on an empty line)
>   * If a task is switched from sync to async the promise resolves as usual with the task but the info about the scheduled task is shown no matter if the close modal flag is set or not
> * The main promise always resolves the task with its current status
> * There will be a list of action buttons that can be provided through the `openAssistantForm` parameters
>   
>   * Can be used in text to offer insert/replace actions on the result screen

@juliushaertl I have checked the repo [Assistant app](https://github.com/nextcloud/assistant) but seems like it still does not provide these functions:
- There is no event or public function `to close the modal after a successful sync task`
- There are no parameters for `a list of action buttons that can be provided through the openAssistantForm parameters`

**Comment by juliushaertl** [comment]
I linked the wrong PR but the main branch should have both https://github.com/nextcloud/assistant/blob/main/src/assistant.js#L37-L44

Reference PR https://github.com/nextcloud/assistant/pull/18
