### ISSUE TITLE
Add Word Count

### ISSUE THREAD

**Issue by TobiasPreiss** [nextcloud/text#470]
It would be nice if the app would have a function to count the number of words in the document text.

**Comment by juliushaertl** [comment]
We had that in the notes app as well at some point iirc but it is not present anymore. @jancborchardt is that something we want to have or should we keep the UI clean from additional details like that?

**Comment by jancborchardt** [comment]
Word count is indeed useful for writers. How it could be displayed is as the last item in the 3-dot-menu list, simply saying "14 words" or whichever number it is.

The entry doesn’t need an icon and would be inactive. As such the text should be grey via `var(--color-text-maxcontrast)`.

If there would be no 3-dot-icon, it’s fine if the word count is the only entry in the 3-dot-menu – so there would always be a menu. (We could also think about moving the modified date into there, but that’s a separate discussion.)

**Comment by elpraga** [comment]
Are there any news about this feature?

IMHO it could be displayed in the bottom or top corner in a similar way as the "last saved counter" - there is usually an abundance of space that is unused. (in case it is needed, it could disappear - the same way the counter does)

What do you think about this idea?

**Comment by elpraga** [comment]
What do you think about the idea @jancborchardt ? I am not a writer, I am an English teacher. I'd like to use **Text** app to emulate the computer based exams, hence my interest in the word count.

**Comment by jancborchardt** [comment]
No news and my design proposal in https://github.com/nextcloud/text/issues/470#issuecomment-577464003 still stands. If there is news, this issue will be updated. :)
