### ISSUE TITLE
Checkbox broken (shrinks horizontally) for long texts

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/text#4732]
**Describe the bug**
If a checkbox contains a long text, the checkbox deforms (shrinks horizontally).

**To Reproduce**
1. Create a markdown file
2. Click on checkbox 
3. Write a long text which spans over multiple lines.
4. See that checkbox shrinks horizontally

**Expected behavior**
Checkbox size should not change, even if a text is quite long.

**Screenshots**
![grafik](https://github.com/nextcloud/text/assets/4077683/5ea99269-5b73-477e-8d55-302c222e32d9)

**Server details:**
- Nextcloud version: 27.0.2
- PHP Version: 8.1
- Database: PGSQL

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Browser version: 116.0
 - Device: desktop

**Comment by pschopen** [comment]
I tried to fix it here: https://github.com/nextcloud/text/pull/4769
