### ISSUE TITLE
Make code type fields copyable

### ISSUE THREAD

**Issue by gbertolottiKS** [nextcloud/text#4750]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually copy the content of code blocks, especially when they are huge.

**Describe the solution you'd like**
A simple copy button in the top right corner of every code blocks

**Additional context**
That feature is already present in many sites/editors, like GitHub:

![immagine](https://github.com/nextcloud/text/assets/115481064/c9cef2ca-6bb4-4e10-968a-b9e635631da6)

**Comment by juliushaertl** [comment]
Nice idea :) Pull requests would be very welcome for this

**Comment by XueSheng-GIT** [comment]
With NC 28.0.2 copying code blocks got even more complicated. The whole markdown syntax is now copied (see https://github.com/nextcloud/text/pull/5212) so that you cannot just paste the command itself to the shell anymore.
