### ISSUE TITLE
Pasting and editing multi line text removes line breaks

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/text#4768]
**Describe the bug**

Pasted multi line text shows with line breaks until one of the lines is edited.

**To Reproduce**
1. Create a new text file
2. Copy-paste
```
Lorem
Ipsum
```
4. Add a *x* after *Lorem*

**Expected behavior**

```
Loremx
Ipsum
```

**Actual behavior**

```
Loremx Ipsum
```

**Screenshots**

**Server details:**
- Nextcloud version: 27.1
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by XueSheng-GIT** [comment]
The same happens if you create a markdown file locally with regular (single) line breaks and upload this file to nextcloud. Line breaks of the whole text are removed if you start editing in nextcloud. I assume this is the same issue.
Maybe related: https://github.com/nextcloud/text/pull/3568

**Comment by mejo-** [comment]
@ChristophWurst what you describe is already reported here, no? https://github.com/nextcloud/text/issues/4602

**Comment by ChristophWurst** [comment]
It sounds very similar but there are no unexpected linebreaks for me. I do expect the lines to break once and they do. If I modify the text there are no line breaks left at all
