### ISSUE TITLE
Left click+Ctrl does not open link

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#4781]
**Describe the bug**
Left click+Ctrl should open a clicked in link in a new tab, but instead the toolbar item for the link gets deactivated and the text of the link turns white (underline stays though).

**To Reproduce**
1. Create a link
2. Press left click+Ctrl on the link

**Expected behavior**
Left click+Ctrl should open a clicked in link in a new tab.

**Screenshots**

**Server details:**
- Nextcloud version: 27.0.1
- PHP Version: 8.2
- Database: Postgres

**Client details:**
 - OS: Arch Linux Wayland KDE
 - Browser: Firefox
 - Browser version: 117
 - Device: Desktop

**Comment by abhinaisai2002** [comment]
Can you provide any screenshot

**Comment by provokateurin** [comment]
I don't think that's useful since there is nothing to see with this bug?

**Comment by mejo-** [comment]
This should have been fixed with #5158.
