### ISSUE TITLE
smart picker can't set links for selected section of text / workflow for linking to resources

### ISSUE THREAD

**Issue by tatrapikao** [nextcloud/text#4783]
**Describe the bug**
If i mark a section of text i can set a link to a website whilst i can not do the same thing when i set a Link to a different Collectives Page via the Smartpicker. In that case the sected text is replaced by the string of the actual Link.

**Expected behavior**
I think the desirable behaviour for all tree kinds of linking(File/Website/Smart-Picker) would be dependent on the state of the text courser: If text is selected -> add the resource as a link to the selected section of text, if nothing is selected add the URL to the position of the courser, If nothing is selected and the courser is in an empty line with a line brake at the end and an empty line after it, or no line after it at all, a preview or if possible the resource itself should be rendered.

**Client details:**
 - Browser: [firefox]
 - Version: [116.0.2 (64-Bit)]
 - Device: [desktop]

**Collectives app version:** (2.7.0)

**Comment by JonasTrampe** [comment]
Is there any progress?

**Comment by enjeck** [comment]
@tatrapikao Sorry, I'm struggling to understand the problem here. If possible, please share an image or video?.

**Comment by tatrapikao** [comment]
![EvQGKrem1x](https://github.com/nextcloud/text/assets/77448960/4709303f-2992-45fd-bed6-a49ad286b9ca)
