### ISSUE TITLE
Support for Markdown in Text templates

### ISSUE THREAD

**Issue by fabricemous** [nextcloud/text#4784]
**Is your feature request related to a problem? Please describe.**
When using Text templates consisting of Markdown, the formatting is not parsed and thus the template is lacking formatting support. 

**Describe the solution you'd like**
I would like to see Text templates use the applied Markdown of the Text template. If no Markdown is used you can assume it is plain text. 

**Describe alternatives you've considered**
I am using a little text expander solution which uses a shortcut. But I prefer the use of Text templates. 

**Additional context**
I have no further context. Discussed this with @juliushaertl and he is aware of this request.

**Comment by juliushaertl** [comment]
Thinking more about it I'd say it is fine if we always consider smart picker output as markdown.

@luka-nextcloud Maybe you can check that to make sure that text inserted through the smart picker is always passed through markdownit? We do something similar already when pasting text in the Markdown tiptap extension.

https://github.com/nextcloud/text_templates is the app mentioned that can be useful for testing.
