### ISSUE TITLE
Opening a long markdown document scrolls the view to the bottom

### ISSUE THREAD

**Issue by Pointedstick** [nextcloud/text#4792]
**Describe the bug**
When opening a text document, the view is scrolled down to the bottom. This is annoying for frequently-updated documents where new content is prepended to the top, not appended to the bottom.

**To Reproduce**
1. Create a .md markdown document and enter a large amount of text into it, enough to make it scrollable
2. Close the document
3. Open it again

**Expected behavior**
The view is showing the beginning of the file.

**Server details:**
- Nextcloud version: 27

**Client details:**
 - OS: Fedora KDE 38
 - Browser: Firefox 
 - Browser version: 117.0
 - Device: Lenovo ThinkPad X1 Yoga laptop

**Comment by juliushaertl** [comment]
Which exact version are you running? This should have been fixed in the latest 27 release by https://github.com/nextcloud/text/pull/4544

**Comment by juliushaertl** [comment]
One additional thought, if you just paste the long text the cursor might be left at the end when closing the document so then it would still be restored to the very end.

**Comment by Pointedstick** [comment]
We are using version 27. Is it fixed in a bugfix release?

**Comment by juliushaertl** [comment]
Yes, it should be there since 27.0.1

**Comment by Pointedstick** [comment]
Indeed, we have just upgraded to that version and I can confirm the issue is resolved now. Thanks so much!
