### ISSUE TITLE
Broken table state

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4793]
Not sure how this was produced but the following table structure causes some issues:

```
**Info:** This is some test

## September 16th

- A list
- More list
  - More list entries

| **Name** | **Task** |
|------|------|
| XXXXX | XXX |
| XXXXX | XXX |
| XXXXX | XXX |

|
|
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |

## September 17th

- Anothe rlist
  - 2-3 PM 2 people interact with the audience; *1/2 accounted for*
  - 3-4 PM 2 people interact with the audience; *0/2 accounted for*

| **Name** | **Task** |
|------|------|
| XXXX | XXXX |
|  |  |
|  |  |
```

**Comment by max-nextcloud** [comment]
More ways of breaking tables:
* pasting an image
* entering `---` -> will insert `hr`
* when copying over some text outside the table and pasting this in the table it creates a cell within the table cell: 
  ![tableintable](https://github.com/nextcloud/text/assets/97337118/1bfc68da-56ab-4389-87ac-df4cfd928b86)

**Comment by provokateurin** [comment]
Also related: https://github.com/nextcloud/text/issues/4047
