### ISSUE TITLE
Text do not work on NC 18 beta

### ISSUE THREAD

**Issue by ralfi** [nextcloud/text#482]
**Describe the bug**
Cannot open or edit text files with latest nc 18 beta

**To Reproduce**
1. install app from store
2. open or create a file
3. text do not appear and cannot by edited
4. closing app works 

**Expected behavior**
text should be appears and could be edited

**Client details:**
 - OS: Linux
 - Browser: FF 71, Chrome 75
 - Device: desktop

**Text app version:** 1.2.3
**Operating system:** linux
**Web server:** apache
**Database:** maria
**PHP version:** 7.x
**Nextcloud version:** nc 18 beta latest docker image

Browser console tells this error:
Failed to load resource: the server responded with a status of 404 (Not found)
and the browser self tells me access denied with CSRF check failed

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/server/issues/18389

Fixed in beta3

**Comment by ralfi** [comment]
Thanks Julius

**Comment by warsix4** [comment]
Same issue, using **18.0.1 RC1**

**Comment by ralfi** [comment]
Fixed with docker image nc:18 / richtextdocuments app

**Comment by juliushaertl** [comment]
> Same issue, using 18.0.1 RC1

@warsix4 I cannot reproduce that. Please open a new issue and provide some details in the issue template like console and nextcloud log.
