### ISSUE TITLE
pasted text with newlines behaves strangely: cannot be reformatted, individually bulleted or numbered

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/text#4821]
**Describe the bug**
If I paste in text with newlines, the newlines are preserved, but when I try to then edit the text (say, hit `Delete` once) it loses all newlines and becomes one big paragraph. I am also unable to make it a bulleted, numbered, or task list.

**To Reproduce**
1. Create a new document called `test.md`, edit it the Text web app.
1. Paste in four lines of text from another app. I pasted `blah\nfoo\nbar\nbaz` from a console.
1. Try to delete one newline, or reformat as a bulleted or numbered list.

**Expected behavior**
Pasted list behaves more like the equivalent typed-in list and can be easily reformatted as desired using bullets, numbers, etc.

**Screenshots**
[Screencast from 09-23-2023 01:29:39 PM.webm](https://github.com/nextcloud/text/assets/50639/903160a6-9f56-4ee5-8221-52cb49e5b564)

**Server details:**
- Nextcloud version: 27.1.1 (installed via [community Docker image](https://github.com/nextcloud/docker/))
- PHP Version: 8.2.10
- Database: MariaDB 10.6.15

**Client details:**
 - OS: Ubuntu 22.04 LTS
 - Browser: both Firefox and Chromium
 - Browser version: Firefox latest (v117, installed via snap) and Chromium Version 117.0.5938.88 (Official Build) snap (64-bit)
 - Device: desktop

**Windows repro**
also repro's on Windows 11 using Notepad and Chrome

**macOS repro**
Does **not** repro on macOS Big Sur (v11.2.3) using TextEdit and Chrome. This is interesting. The list copied from TextEdit pastes in with *two* newlines at each EOL, that is: `blah\n\nfoo\n\nbar\n\nbaz`. This seems... better than what happens on Windows and Ubuntu. At least with this result it is easy to make it into a bulleted list.

**Suggested fix**
Make Ubuntu and Windows behave the same as macOS with respect to copying and pasting plain text with newlines into the web-based Text editor for Markdown files.

**Workaround 1:**
Edit the file locally (including copying and pasting) in your favorite text editor.

**Workaround 2:**
If you really prefer to copy and paste, you must copy from something that displays and stores rich text on your OS clipboard.

Example: create a plain text file with Markdown syntax (e.g. a bulleted list) on your desktop with your favorite editor. Convert the Markdown text to HTML (with something like pandoc), then paste the formatted HTML (with bullets or numbered lists) directly into a Markdown text file using the Nextcloud Text editor.

E.g. run `echo -e '* blah\n* foo\n* bar\n* baz' | pandoc -o out.html`, open `out.html` in a web browser, then copy the rendered HTML and paste it into Nextcloud Text.

**Other info**
If I open a new text file `test.md` in the Nextcloud Text web UI and manually type in

* `b` `l` `a` `h` <kbd>Shift</kbd><kbd>Enter</kbd>
* `f` `o` `o` <kbd>Shift</kbd><kbd>Enter</kbd>
* `b` `a` `r` <kbd>Shift</kbd><kbd>Enter</kbd>
* `b` `a` `z`

The resulting text file contains `blah  \nfoo  \nbar  \nbaz` (note the extra spaces). I can't manually delete the extra spaces in the Text web-based file editor, and it looks the same as if I'd pasted in the list of words per my example above. I'm not really suggesting a change here, just trying to understand how this web-based text editor goes about translating rich text in the browser to plain Markdown text stored in a file. And I'm doing this the lazy way (experimentation)... I'll just read some source code instead.

**Comment by max-nextcloud** [comment]
> **Other info** If I open a new text file `test.md` in the Nextcloud Text web UI and manually type in
> 
>     * `b` `l` `a` `h` ShiftEnter
> 
>     * `f` `o` `o` ShiftEnter
> 
>     * `b` `a` `r` ShiftEnter
> 
>     * `b` `a` `z`
> 
> 
> The resulting text file contains `blah \nfoo \nbar \nbaz` (note the extra spaces). I can't manually delete the extra spaces in the Text web-based file editor, and it looks the same as if I'd pasted in the list of words per my example above. I'm not really suggesting a change here, just trying to understand how this web-based text editor goes about translating rich text in the browser to plain Markdown text stored in a file. And I'm doing this the lazy way (experimentation)... I'll just read some source code instead.

I'm still looking into the main part of the issue. With respect to the two spaces... they are markdown syntax for line breaks:
https://www.markdownguide.org/basic-syntax/#line-breaks

**Comment by mejo-** [comment]
Probably the same as reported in #4768 and related to #4602.

**Comment by meonkeys** [comment]
> reported in #4768 and related to #4602.

Sure sounds like it, yes. Should we close this one?

**Comment by max-nextcloud** [comment]
> Sure sounds like it, yes. Should we close this one? Either way I'm happy to help test/QA.

Thanks! I'll close this one. Let's have the discussion in one place -> #4768
