### ISSUE TITLE
Undo goes beyond first change

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/text#4881]
**Describe the bug**
Multiple undo can delete document content

**To Reproduce**
1. Go to 'Collectives App' / configured with "Open Pages in View Mode"
2. open a page
3. enter edit mode
4. type text, eg. "abc"
5. type "ctrl+Z" multiple times
6. not only "abc" is deleted, but the content is deleted completely
7. type "ctrl+R" , this will reload the page in Firefox
8. 
   i. if document is opened from the files-app, an empty document is opened in edit mode
   ii. if document is opened in Collectives, the version from step 2. is shown. but changing to edit mode also shows empty document

**Expected behavior**
in step 5. only delete "abc" no matter how often "crtrl+z" is pressed

**Server details:**
- Nextcloud version: 27.1.2

**Client details:**
 - Browser: Firefox
 - Browser version: 115.3esr

**Comment by mejo-** [comment]
I can reproduce this. Probably the first step that sets the dav content is in the undo history.

@juliushaertl @max-nextcloud do you have good ideas how to solve this? Maybe we can set the dav content as a step that is not pushed to the undo history?

**Comment by juliushaertl** [comment]
- [ ] We should check if this is only for the user creating the session
- [ ] Check if the addToHistory meta data is actually passed along to prosemirror-history
  - https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/commands/setContent.ts
  - https://github.com/ProseMirror/prosemirror-history/blob/master/src/history.ts#L277C26-L277C38
  - https://github.com/nextcloud/text/blob/cc601a78b7bc224fe84088f8e377c2e8599821cd/src/mixins/setContent.js#L35
- https://github.com/nextcloud/text/commit/47e2f761bd3fc7bab7092edbaeed8f25abef2686 was supposed to fix exactly this issue
