### ISSUE TITLE
Link to file or folder links to the unsafe url instead of the files internal url.

### ISSUE THREAD

**Issue by small1** [nextcloud/text#4883]
**Describe the bug**
When using Link to file or folder it takes the url link in the url bar. If the markdown is shared and the file ends up somewhere else the link to that file is broken as that user has the file in a different location.

This means that files attached in collectives or shared documents will be broken.

**To Reproduce**
1. Open a new text document (or a new page in colectives)
2. go to where you want to have the link and choose link to file and folder. Select a file.
3. Check the url created. It will be the unsave url from the url field in the browsers and not the internal link to the file

**Expected behavior**
The internal link to the file should be in there. 

**Screenshots**

**Server details:**
- Nextcloud version: 27.0.2 and 27.1.2
- PHP Version:  8.1
- Database:  Mariadb

**Client details:**
 - OS: linux and windows
 - Browser: Chrome
 - Browser version: latest

**Comment by mejo-** [comment]
This is fixed by #5412
