### ISSUE TITLE
Cleanup potential duplicated index

### ISSUE THREAD

**Issue by blizzz** [nextcloud/text#4958]
In NC 27.0.1 RC2 we had an index which was colliding with one in the Talk app. This was fixed for 27.0.1 proper (#4553), nevertheless some people already ran into issues with the upgrade to 28.0.0 Beta 1, because a potentially existing index was not removed (cf. https://help.nextcloud.com/t/first-beta-of-nextcloud-28/173501/6 and https://help.nextcloud.com/t/first-beta-of-nextcloud-28/173501/12).

**Comment by kesselb** [comment]
Another report in server: https://github.com/nextcloud/server/issues/41253
