### ISSUE TITLE
Spellchecking support - Languagetool

### ISSUE THREAD

**Issue by conloos** [nextcloud/text#497]
Hello,

I already opened this feature request in tiptap's github. So far there has been no reaction and I do not know whether the featurequest is placed there correctly.

---
[https://github.com/scrumpy/tiptap/issues/542](https://github.com/scrumpy/tiptap/issues/542)
---

Hi ,

I often use Nextcloud - Text which is based on TipTap.

Is it possible to integrate support for the Langagetool spell checker? It would be good if the Langagetool server is set by defaut and can be replaced by its own.

Thanks Frank

**Comment by juliushaertl** [comment]
The chrome extension should work just fine with tiptap and text. The main issue I see with a direct integration is that we cannot ship the languagetool with the app itself, since it is java based.

**Comment by conloos** [comment]
Hi there,

Thanks for the answer.
The integration should take place on the basis of the HTTP API.
I suggest that the [Languagetool server] (http://wiki.languagetool.org/public-http-api) is set by default and can be replaced by your own.

The suggested Chrome / Firefox plug-in is good, but cannot be used everywhere. (No admin account)

Greetings Frank

**Comment by sereneinserenade** [comment]
Hi, maybe I'm too late to party, but I've made a Tiptap Extension that integrated spellchecking to Tiptap using ProseMirror decorations and Tiptap BubbleMenu.

Here's the Repository: https://github.com/sereneinserenade/tiptap-languagetool
Here's a demo: https://tiptap-languagetool.vercel.app/
