### ISSUE TITLE
Error view on inactive tabs

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#501]
For the rich workspaces, when you leave a tab inactive, sometimes this happens:
![Rich workspaces error view](https://user-images.githubusercontent.com/925062/71559660-877e9380-2a93-11ea-8b12-71d440cae8bb.png)

Instead it would be nice to just switch to the read-only view? It’s a rather technical error right in the UI, where everything else seems to be fine. cc @juliushaertl

**Comment by juliushaertl** [comment]
Did you upgrade your nextcloud instance in the meantime or had maintenance mode enabled? Makes sense to automatically reconnect in that case I'd say. Apart from that, do you have any suggestion to make the error less technical?

**Comment by jancborchardt** [comment]
Don't we have anything cached and could show that? Or as said, just show the read-only view?

Cause it's a bit strange, everything else is still shown even though it's all coming from a server. :)

As for making it less technical and scary:
- remove the red line
- Wording: "Rich workspace could not be loaded. Please check your internet connection."
- icon-info instead of icon-error
- spacing above so it is the same spacing as for the emptycontent message and the layout doesn't look broken
