### ISSUE TITLE
Rich workspaces takes too much screen estate when Readme.md is empty

### ISSUE THREAD

**Issue by blizzz** [nextcloud/text#5018]
**Describe the bug**

Rich workspaces takes too much screen estate(~30%) while Readme.md is being empty or not present.

Btw, Readme.md cannot be deleted.

**To Reproduce**
1. Go to Files
2. have ab empty Readme.md
3. A third of the screenspace is void. Especially when you have a lot of files, the space is not used well.

Also, the Readme.md cannot be deleted from the web interface due to it being locked.

**Expected behavior**

The rich workspaces placeholder is being shown

**Screenshots**
![the void](https://github.com/nextcloud/text/assets/2184312/917ff0ff-8ada-42d0-9b1b-a7f718b65de6)

**Server details:**
- Nextcloud version: 28 beta 4

**Client details:**
 - Browser: Firefox
 - Browser version: 119.0.1
 - Device: desktop

**Comment by juliushaertl** [comment]
Should be ok to just remove the minimum height now that we have the markdown content at rendering time and do not need to await the text session to start https://github.com/nextcloud/text/pull/4776
