### ISSUE TITLE
attach a pdf file to a markdown file

### ISSUE THREAD

**Issue by mherweg** [nextcloud/text#5030]
Steps to reproduce

    in NC web GUI create a "text"(.md) File
    use the attach button to attach a pdf file from server or from Computer
    close/save this "text" file
    open it again

Expected behaviour

when I click on the the pdf preview, the pdf file will open or offered for download
Actual behaviour

a "broken image" preview - it looks like the pdf is treated like a gif or jpg
Server configuration

I tried it on 3 different NC Servers, run by 3 different teams. all Linux/docker

NC Version: 27.0.2

Operating system:
Debian Linux

**Comment by juliushaertl** [comment]
There is some ongoing work on this done by @mejo- to make metadata of attachments easier accessible in the frontend to prepare for the fix of this, so maybe he could comment if there is anything to pair up with.

**Comment by mejo-** [comment]
Indeed, #5042 will fix this.

@GOWTHAM2K1 thanks for offering help here. If you like, a review and testing of this PR would be much appreciated!
