### ISSUE TITLE
Support for Chinese GB2312&GBK

### ISSUE THREAD

**Issue by LL223851** [nextcloud/text#506]
$nextcloud/apps/text/lib/Service/ApiService.php
line 112
$fileContents=$file->getContent();
$encoding = mb_detect_encoding($fileContents . 'a', 'UTF-8,GB2312, GBK, WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII', true);
if ($encoding === '') {
$encoding = 'ISO-8859-15';
}
if($encoding !== 'UTF-8')
{
$fileContents = iconv($encoding, 'UTF-8', $fileContents);
$file->putContent($fileContents );
}
return new FileDisplayResponse($file);

**Comment by juliushaertl** [comment]
Please propose a pull request if you want to suggest a change.
