### ISSUE TITLE
[BITV] 9.1.4.1/3.1 - Styling menubar - For many elements like "B" and "I", selected styles are visually marked by a pale blue background (1,2:1 to white) and remain below the contrast ratio of 3:1 that is needed to indicate the state visually. (2)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/text#5065]
![image](https://github.com/nextcloud/server/assets/6078378/077873d3-e753-41a5-866b-c8a9d5cc9d93)

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-45ae33ca9f-v3-n1

9.1.4.1/11.1 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-45ae33ca9f-v11-n1

**Comment by susnux** [comment]
Probably it would be enough to use the `pressed` property of NcButton which will enforce the contrast

**Comment by juliushaertl** [comment]
Original reference https://github.com/nextcloud/text/issues/3860#issuecomment-1645810660

@nextcloud/designers Can someone please have a look at https://github.com/nextcloud/text/issues/3860#issuecomment-1590774920 for that?

While I get the pressed state fixes the accessibility concern, i find that quite odd to have a kindof primary style for all those buttons.

**Comment by susnux** [comment]
See also this PR: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4344

**Comment by juliushaertl** [comment]
Ok, then let's go for the pressed button style.

**Comment by max-nextcloud** [comment]
I'll only backport to stable28 as this is quite a visible UI change and quite a bit of the ui changes with 28 while hardly any other ui changes will happen with 27 minor releases.
