### ISSUE TITLE
Examples for rich workspaces

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#507]
For their Spaces, Dropbox has a button "Show examples":
![signal-attachment-2019-12-31-150313_001](https://user-images.githubusercontent.com/925062/71614568-0207fa00-2bdf-11ea-8c4c-63e10b9fb151.png)

---------------------------------

That opens a modal with 3 examples, simply screenshots of what could be done with the feature. :)
![signal-attachment-2019-12-31-150313_002](https://user-images.githubusercontent.com/925062/71614566-0207fa00-2bdf-11ea-88cf-628b7ec130b1.png)

![signal-attachment-2019-12-31-150313_003](https://user-images.githubusercontent.com/925062/71614565-0207fa00-2bdf-11ea-89f3-322e0ba6fb59.png)

![signal-attachment-2019-12-31-150313_004](https://user-images.githubusercontent.com/925062/71614564-016f6380-2bdf-11ea-8a78-3defede2ff0c.png)

Might be nice to have the same to let people know what it can be used for. cc @juliushaertl @karlitschek @jospoortvliet

**Comment by karlitschek** [comment]
Very nice idea!  👍
