### ISSUE TITLE
Reconnect dialogue is hidden if page scrolled

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/text#5100]
**Summary**
When the Reconnect dialogue appears, it can inadvertently be hidden when scrolling a text document.

**Expected behavior**
The user would expect the dialogue to remain persistent, despite scrolling the document.

**Screenshots**
![Peek 2023-12-07 12-43](https://github.com/nextcloud/text/assets/7018928/4b6e24da-5e5b-443d-8672-2fe07bd1cb93)

**Server details:**
- Nextcloud version: 28.0.0 RC2
- PHP Version: [e.g. 8.2] 🤷‍♂️
- Database: [e.g. MariaDB 10.6] 🤷‍♂️

**Client details:**
 - OS: NixOS
 - Browser: Firefox
 - Browser version: 119.0.1
 - Device: laptop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Found a duplicate report https://github.com/nextcloud/text/issues/4483 will close this one as the other one is older.
