### ISSUE TITLE
File selector layout is defect

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#5125]
**Describe the bug**
When creating a link by selecting "link to file or folder" the popup with the file list seems to be defect - the table is way too small and does not fill the popup which makes selecting a file difficult.

**To Reproduce**
1. Open a collective page and edit it.
3. Klick the "link" icon and select "Link file or folder"
4. The file list in the popup will show with too small columns.

**Expected behavior**
The file list uses the available width of the popup.

I added the following CSS rules using the [CustomCSS](https://apps.nextcloud.com/apps/theming_customcss) app as a workaround for my live instance:

```
.file-picker__content table {
  width: 100%;
}

.file-picker__name-container {
  display: flex;
  gap: 4px;
}
```

It may also help if the popup would be wider (or resizable) and not just a small window inside the available viewport. Maybe 70-80% of the browser viewport - then you still see it as popup, but you also have enough space for longer file names in the table.

**Screenshots**

![image](https://github.com/nextcloud/collectives/assets/6613614/237ad1bf-4f43-4f71-a398-92ceea2fd798)

![image](https://github.com/nextcloud/collectives/assets/6613614/942cecf5-068e-4344-9b51-ac5769818eb6)

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 27.1.4
- PHP Version: 8.1
- Database: (not relevant)

**Client details:**

Happens with all tested browsers (Chrome, Firefox, Vivaldi)

**Comment by arnowelzel** [comment]
> Thanks for the bugreport @arnowelzel. In fact this issue exists in Text on Nextcloud 27.1.4. I'm transferring the issue to Text therefore.

Thanks - yes, it is Nextcloud 27.1.4 and not 27.4.1 - I just fixed this error in the issue.

**Comment by luka-nextcloud** [comment]
I have checked and noticed that this issue is fixed somehow on NC server v27.1.5.

![image](https://github.com/nextcloud/text/assets/89908051/0240f33c-9e43-4978-87b2-44874cef6805)

**Comment by juliushaertl** [comment]
All right let's close then

**Comment by arnowelzel** [comment]
Yes, I can confirm, that it is fixed in Nexcloud 28 as well.
