### ISSUE TITLE
Keyboard navigation in tables is broken

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#5156]
**Describe the bug**
When editing a table, you can navigate using the arrow keys on the keyboard. However when you move from one cell to the next, the cursor will end up being placed at the top corner of the cell instead of inside the cell. If you then try to type something, a new column will be created, before the text will be added to the cell. It can also happen, the the whole content will shift to the right as soon as you enter to the cell using arrow keys.

**To Reproduce**
1. Create a new text document.
2. Insert a table to the document and add some content to it
3. Klick inside a cell on the left
4. Use the arrow right key to navigate to the next cell right to it
5. See the cursor blinking as horizontal line on top of the cell instead of inside of it
6. Start typing, which creates a new cell instead of adding the text to the existing cell

**Expected behavior**
When moving with the arrow keys, the cursor will move the same way as using the [Tab] or [Shift]+[Tab].

**Screenshots**
This is, how it looks like when you move to the next cell with arrow right:

![image](https://github.com/nextcloud/text/assets/6613614/abcaee86-dec7-42fb-8f55-1de0f13b0f35)

And this happens when you then start typing - a new column will be created

![image](https://github.com/nextcloud/text/assets/6613614/7ce48e11-b84c-4360-bdca-f1a863d47ced)

In fact - the content will shift to the right, as soon as you enter the cell using the arrow keys and will shift back, when you leave the cell without typing any text:

![image](https://github.com/nextcloud/text/assets/6613614/128fc316-039d-4ed4-9d59-8ce876505775)

**Server details:**
- Nextcloud version: 28.0.0, 28.0.1
- PHP Version: 8.1
- Database: MariaDB 10.11

**Client details:**
 - OS: Windows
 - Browser: Chrome, Edge, Firefox
 - Browser version: the latest versions as of December 2023
 - Device: Desktop

**Comment by mejo-** [comment]
Thanks for your report @arnowelzel! This already got fixed with https://github.com/nextcloud/text/pull/5148 (and got backported to stable28). Will be shipped with the upcoming 28.0.2 release.
