### ISSUE TITLE
Scrollbar on shared text page.

### ISSUE THREAD

**Issue by simmstein** [nextcloud/text#521]
**Describe the bug**

Issue with a scrollbar on a shared file.

**To Reproduce**

* Create a file with long content
* Share the file using a link and browse it
* 1 useless scrollbar and 1 useful scrollbar are show

**Expected behavior**

* 1 useful scrollbar rather than 2

**Screenshots**

Video (gif): http://kim.deblan.fr/~simon/i3fffs-2020-01-06_17.08.54.gif

**Client details:**
 - OS: Debian 10 / Windows
 - Browser: Firefox / Chrome
 - Version: LTS
 - Device: desktop

**Comment by juliushaertl** [comment]
Which version of Nextcloud and Text are you running?

**Comment by simmstein** [comment]
* Nextcloud 17.0.2 (channel stable)
* Text  1.1.1

**Comment by simmstein** [comment]
Fixed on Nextcloud 18.x with text 2.x.
