### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by AdamPS** [nextcloud/text#5211]
**Describe the bug**
3 keyboard shortcuts aren't working in the text app: CS+2, CS+3, CA+C (heading 2, heading 3, code block). The related buttons work fine.

I am aware that the key could be stolen by the OS, the browser, a browser plug-in, or another program on the PC. However I can't find any such thing. Any advice would be appreciated.

**To Reproduce**
1. Open a file in notes
2. Type some text
3. Press CS+2
4. Nothing happens

**Expected behavior**
The shortcut would have its effect, e.g. change to heading 2.

**Screenshots**
None

**Server details:**
- Nextcloud version: 28.0.1
- PHP Version: 8.1
- Database: mysql 8.0.35

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox (Librewolf fork)
 - Browser version: 121.0-1
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Nothing in the log

#### Browser log
Nothing in the log

</details>

**Comment by mejo-** [comment]
Dear @AdamPS, thanks for your report. You're talking about the keyboard shortcuts to set heading style, i.e. <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<Number>, right?

All of them work for me, also on Linux and Firefox (124). My guess would be that some browser extension overwrites the shortcuts for you. Could you start your browser with all extensions disabled and see whether the problem persists?

**Comment by AdamPS** [comment]
Thanks @mejo-,
Since January I have upgraded my OpenOffice. Good news is that I've just tested again and it's all working fine. So I guess either a bug has been fixed or I had a problem on my computer that's been resolved.

**Comment by mejo-** [comment]
Thanks so much for reporting back @AdamPS. Glad this got sorted out for you.
