### ISSUE TITLE
View raw markup

### ISSUE THREAD

**Issue by hfiguiere** [nextcloud/text#5213]
**Is your feature request related to a problem? Please describe.**
I want to be able to copy the raw markdown, to paste it somewhere. The only way to do that currently is by downloading the file, which is a lot of friction.

**Describe the solution you'd like**
A view to show me the raw markdown. It can be read only.

**Describe alternatives you've considered**
Download file, and then copy from a local text editor. That's my current work around.

**Additional context**
See issue #3570 that could be a more feature full alternative (raw markdown editing)

**Comment by juliushaertl** [comment]
Copying would actually be something I just propsed a fix earlier with https://github.com/nextcloud/text/pull/5212

I'd assume this covers your main use case for that?

**Comment by hfiguiere** [comment]
This could work too.
