### ISSUE TITLE
Sidebar controls: bad UX

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/text#523]
At start there are 2 buttons:
- Open sidebar
- Close

After opening the sidebar, the _Open sidebar_ button still has the tooltip _Open sidebar_, even though the sidebar is already open. Clicking on the button does nothing.

In order to close the sidebar however, you don't have to click on the nearby _Close_ button, but on the _close_ button within the sidebar. (side note: Close ≠ close --> case sensitivity)

![Peek 2020-01-07 09-58](https://user-images.githubusercontent.com/1804221/71882256-66bdda00-3134-11ea-9d39-2aba146c2723.gif)

Here's my suggestion:
1. Turn the _Open sidebar_ button into a _Close sidebar_ button once the sidebar is opened
2. Make the icon consistent with the UX in richdocuments (Collabora): 
![image](https://user-images.githubusercontent.com/1804221/71882933-a507c900-3135-11ea-9168-9196a6c04066.png)
3. Keep the _Close_ button in the sidebar for the sake of consistency with other occasions' sidebar behavior
4. Rename the inner _Close_ button's tooltip to _Close document_

**Comment by juliushaertl** [comment]
cc @nextcloud/designers as right now we still use the viewer app. However I was already thinking if we should just take care of the modal display manually as the sidebar can now be triggered individually. This would also help a lot with #82

**Comment by skjnldsv** [comment]
@juliushaertl What is wrong with the sidebar being opened by the viewer?

**Comment by jancborchardt** [comment]
Very related to https://github.com/nextcloud/viewer/issues/328 in general.



> Here's my suggestion:
> 1. Turn the _Open sidebar_ button into a _Close sidebar_ button once the sidebar is opened

:+1:

> 2. Make the icon consistent with the UX in richdocuments (Collabora):
> ![image](https://user-images.githubusercontent.com/1804221/71882933-a507c900-3135-11ea-9168-9196a6c04066.png)

I’d say it should be the other way around, that icon should be adjusted.

> 3. Keep the _Close_ button in the sidebar for the sake of consistency with other occasions' sidebar behavior

Yep

> 4. Rename the inner _Close_ button's tooltip to _Close document_

:+1: 

------------

Additionally:
- Do not show the preview part in the sidebar because it makes no sense to have a preview for the document you have open right next to it.

**Comment by wiswedel** [comment]
Fully agree with @jancborchardt 's suggestions above

**Comment by skjnldsv** [comment]
> > 1. Turn the _Open sidebar_ button into a _Close sidebar_ button once the sidebar is opened

But the sidebar already have the close button, is hiding it good enough? :)

**Comment by wiswedel** [comment]
> > > 1. Turn the _Open sidebar_ button into a _Close sidebar_ button once the sidebar is opened
> 
> But the sidebar already have the close button, is hiding it good enough? :)

no, see 3.

**Comment by juliushaertl** [comment]
This is fixed these days in the viewer
