### ISSUE TITLE
Copy & paste of todo/task lists result in bulletpoints

### ISSUE THREAD

**Issue by Shadowstreik** [nextcloud/text#5237]
**Describe the bug**

Within Deck Cards, copy and pasting Numbered Lists and To-Do lists result in a bulletpoint list.

**To Reproduce**
1. Type text to create a Numbered List or To-Do List item.
2. Click on 'Ordered List' or 'To-Do List' icon in toolbar to create the list items. Hit 'Enter.' Repeat until there are, at least, two list items.
3. Highlight entire list and Copy (Ctrl+C or Right-click and elect Copy)
4. Go to an empty spot (hit Enter a couple of time) and Pate (Ctrl+V or Right-Click and select Paste).
* The Paste results in the Numbered List or To-Do list to become a Bulletpoint List. This should not happen.

**Expected behavior**
Pasting of Numbered Lists and To-Do lists should preserve their Numbered and/or To-Do formatting.

![Screenshot from 2024-01-05 15-32-53](https://github.com/nextcloud/deck/assets/126274824/b72c0e20-4bbb-42ee-99f1-31635931c960)

**Comment by Shadowstreik** [comment]
Confirmed, this behavior does not affect Numbered Lists, only To-Do.

**Comment by punkyard** [comment]
on apple ventura

a text edited in NC text and pasted in:

<img width="275" alt="Capture d’écran 2024-06-17 à 14 12 41" src="https://github.com/nextcloud/text/assets/59349105/76d5feb5-7f8d-45fe-a8b8-92e1e499db2b">

<img width="323" alt="Capture d’écran 2024-06-17 à 14 12 05" src="https://github.com/nextcloud/text/assets/59349105/4879d0bd-3c22-40bf-a73c-8f3e0c176fed">

<img width="268" alt="Capture d’écran 2024-06-17 à 14 12 27" src="https://github.com/nextcloud/text/assets/59349105/f624ff90-94de-457d-9c7a-c86e12045e7a">

this is a text pasted in NC text edited in: 

<img width="403" alt="Capture d’écran 2024-06-17 à 14 32 01" src="https://github.com/nextcloud/text/assets/59349105/b773255d-501a-4b22-9265-b28b97ec8d6e">

<img width="256" alt="Capture d’écran 2024-06-17 à 14 25 17" src="https://github.com/nextcloud/text/assets/59349105/54ebec7a-6c83-4fe7-a2d6-b062b6d641ec">

<img width="403" alt="Capture d’écran 2024-06-17 à 14 32 01" src="https://github.com/nextcloud/text/assets/59349105/d2f339fd-beeb-40d9-86aa-c8b852c5f9f5">

although this test shows a quite satisfying answer - it is not rare to have major formatting issues between 2 files in NC

**Comment by mejo-** [comment]
This is not reproducible in the upstream Tiptap demo editor, so likely a bug in our todo list implementation.
