### ISSUE TITLE
Nodes for embedding / previewing content

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#5270]
## Goal

When editing a markdown file
I want to be able to embed content from another app
either as a preview or editable

## Approach

- [ ] define a markdown syntax (preliminary)
- [ ] add parsing to markdown-it
- [ ] add a node type for previews
- [ ] render the previews when syntax is in the markdown
- [ ] ensure it serializes back to the same format
- [ ] allow removing a preview
- [ ] allow inserting a preview
- [ ] Revert https://github.com/nextcloud/text/pull/5313 and move the interactive flag to the new node type

**Describe alternatives you've considered**
Define all links in the form of a node that can either be a simple link or a preview. However normal links are inline and previews would be block content.

**Additional context**
* Part of https://github.com/nextcloud/server/issues/42550

**Comment by juliushaertl** [comment]
@max-nextcloud Added a checkbox to revert https://github.com/nextcloud/text/pull/5313 in your PR
