### ISSUE TITLE
Insert file via slash menu

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/text#5282]
**Describe the bug**
If you insert a file using the slash menu, the correct internal link is not generated. Instead ...%7BfileId%7D

**To Reproduce**
open Textfile
/ Slash
choose file

**Expected behavior**
internal link

**Server details:**
Nextcloud 27.1.5
Text 3.8.0

**Client details:**
Windows, Firefox

**Comment by juliushaertl** [comment]
I just tested and this should be fixed by the filepicker with the latest 27.1.6 release.
