### ISSUE TITLE
pure link, generated preview should cover url

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/text#5283]
**Is your feature request related to a problem? Please describe.**
When you type an URL a preview is generated in the next line

**Describe the solution you'd like**
the generated preview should cover the link. URLs can be long and ugly.
Workaround is to hide long URLs behind text.

**Describe alternatives you've considered**
alternatively reduce space between URL and preview, they cover a lot of space 

**Additional context**
The Document would be much nicer to view, if the URLs are not shown anymore.
Maybe hide URLin view mode and show in edit mode

![grafik](https://github.com/nextcloud/text/assets/66730800/4b6cb695-99b1-4d43-bcf5-ab6fae75ddca)
The red marked spacers are similar in height, so from first impression it is not clear, where preview belongs to.
Reduce space between URL and preview
Or even remove URL completely if link text is same as URL

**Comment by max-nextcloud** [comment]
@Solar-Simon I'm happy to tell you I'm working on this right now. It will be slightly different though. People will be able to choose:
* a plain link with a preview only opening on a click (#5158)
* a preview without the link like you described
* embedded content - at least if the link points to other resources on nextcloud.

#5270 is where i am tracking this.

**Comment by juliushaertl** [comment]
Thanks for the suggestion, as Max mentioned, let me close this one and use the others for tracking.
