### ISSUE TITLE
[BITV]: Not possible to reach action buttons in a table via keyboard *forwards* navigation

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/text#5314]
It is only possible to reach action buttons inside a table only via backwards navigation:

![Peek 2024-01-26 08-24](https://github.com/nextcloud/text/assets/6078378/f9ddbbb3-cf1c-4d44-884f-7a5f399d9356)

**Comment by juliushaertl** [comment]
Should already be addressed as part of https://github.com/nextcloud/text/pull/5281

![2024-01-26 08 48 09](https://github.com/nextcloud/text/assets/3404133/38c7987d-a03e-4443-89e9-0f33d7b79d59)

**Comment by JuliaKirschenheuter** [comment]
ok, closing issue https://github.com/nextcloud/text/issues/5314#issuecomment-1911621689

**Comment by szaimen** [comment]
This doesnt seem to work correclty yet on stable28:

https://github.com/nextcloud/text/assets/42591237/ec77c856-0c2b-41fc-a38e-96a322344db6

**Comment by juliushaertl** [comment]
I also consider this done.
