### ISSUE TITLE
Can no longer copy content from code blocks

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/text#5331]
**Describe the bug**
Ref https://github.com/nextcloud/text/pull/5212

**To Reproduce**
1. Have a collective page with a list and inside the list there is a code block:
```
* List item 1
* List item 2
    ```
    ### Workarounds
    
    
    
    * Disable app X
    * Change config setting Y
    * No workaround available
    ```
```

2. Copy bits inside the code block
3. Paste any where

**Expected behavior**
You paste:
```
### Workarounds

<!-- Remove not applicable sections -->

* Disable app X
* Change config setting Y
* No workaround available
```

**Actual behavior**
You paste with list item and code block wrap
![grafik](https://github.com/nextcloud/text/assets/213943/e97ba26d-56af-4ab8-9048-6462ba70e350)

**Screenshots**

**Comment by juliushaertl** [comment]
One further related topic I've noticed is that copying a link that was pasted earlier results in a link wrapped in brackets `<https://github.com/nextcloud/text/issues/5331>`

**Comment by juliushaertl** [comment]
@elzody Another suggestion from @susnux in https://github.com/nextcloud/text/pull/5212#issuecomment-1992150485 might also be interesting to check if that is feasible

**Comment by elzody** [comment]
Closing since a workaround was implemented via #5395

**Comment by susnux** [comment]
> Closing since a workaround was implemented via https://github.com/nextcloud/text/pull/5395.

I do not think this is a workaround, this is in most cases not usable, because often the code block contains multiple entries and you only want to copy one. E.g. email addresses, shell commands etc.

```shell
ls -ahlp
cat foo.bar
``` 

Copying `ls -ahlp` should not result in ```` ```ls -ahlp``` ```` you can not use that directly but again need an editor to paste and copy only the **selected** text.

**Comment by elzody** [comment]
> I do not think this is a workaround, this is in most cases not usable, because often the code block contains multiple entries and you only want to copy one. E.g. email addresses, shell commands etc.

Makes sense. I will reopen, we're trying to get #5487 merged as @max-nextcloud made some changes today and we can further iterate on it in the future. This specific issue and the one you described should be fixed once this happens.

Sorry for the confusion, just trying to get things a bit more organized around this
