### ISSUE TITLE
Image icon in toolbar missleading

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#5383]
**Describe the bug**
The icon for the "upload attachment" functionality in the toolbar is an image, which is a bit missleading. I just heard from another user that they didn't find their way to upload a PDF to a document because they didn't expect it behind the image icon.

I'm not sure which icon would be better. The paper clip icon (usually used for attachments) could be missleading when searching for an option to upload an image. Maybe there's some icon that represents media files in general? CC @nextcloud/designers for feedback.

**Comment by szaimen** [comment]
What about this icon?
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:note_add:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=add

**Comment by marcoambrosini** [comment]
I think we should go with the paperclip icon like in talk
https://pictogrammers.com/library/mdi/icon/paperclip/

**Comment by mejo-** [comment]
Fixed by https://github.com/nextcloud/text/pull/5929
