### ISSUE TITLE
Embedded images not loaded inside iOS Notes app

### ISSUE THREAD

**Issue by pjft** [nextcloud/text#5419]
**Describe the bug**
Attachments no longer opening on iOS app, with error 500.

**To Reproduce**
1. Open note with attachments.

**Expected behavior**
Attachments render as expected.

**Screenshots**
![unnamed (6)](https://github.com/nextcloud/text/assets/22025709/25425250-a356-4773-8757-050ae39ddc46)

**Server details:**
- Nextcloud version: 27.1.6
- PHP Version: 8.2.7
- Database: MySQL

**Client details:**
 - OS: iOS, NextCloud app 5.2.0.2
 - Device: iPhone 14

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
[index] Error: Exception: Call to a member function getUID() on null in file '/var/www/html/nextcloud/apps/text/lib/Service/AttachmentService.php' line 434 at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /var/www/html/nextcloud/lib/base.php line 1068
   OC\Route\Router->match()
3. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()

Caused by:

Error: Call to a member function getUID() on null at <<closure>>

0. /var/www/html/nextcloud/apps/text/lib/Service/AttachmentService.php line 226
   OCA\Text\Service\AttachmentService->getAttachmentDirectoryForFile()
1. /var/www/html/nextcloud/apps/text/lib/Controller/AttachmentController.php line 101
   OCA\Text\Service\AttachmentService->getAttachmentList()
2. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Text\Controller\AttachmentController->getAttachmentList()
3. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
4. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
6. /var/www/html/nextcloud/lib/base.php line 1068
   OC\Route\Router->match()
7. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()

POST /index.php/apps/text/attachments
</details>

Likely related to the changes from 3 months ago:
https://github.com/nextcloud/text/commits/main/lib/Service/AttachmentService.php

Unsure if client or server issue, [hence cross-posting the bug](https://github.com/nextcloud/ios/issues/2813). Apologies if incorrect.

Thanks.

**Comment by joshtrichards** [comment]
Fixed in 5707c21
