### ISSUE TITLE
Link URL disappearing while creating hyperlink

### ISSUE THREAD

**Issue by bentuna** [nextcloud/text#5437]
**Describe the bug**
When you try to add a hyperlink to a selected bit of text via "Link to website", the content of the input box for the link address is deleted after ~3 seconds.

**To Reproduce**
1. Select some text
2. Click on 'Insert link'
3. Start typing a URL into 'Link to website' input field
4. See the URL disappear after around 3 seconds

**Expected behavior**
The URL stays in there until I click the arrow button or hit enter, so the correct Link gets created

**Screenshots**
<img width="320" alt="Bildschirmfoto 2024-03-05 um 09 01 42" src="https://github.com/nextcloud/text/assets/7753747/6893f3a3-657e-408e-b2a4-5cd3897fa31a">

**Server details:**
- Nextcloud version: 28.0.2 and 28.0.3

**Comment by mejo-** [comment]
Dear  @bentuna, thanks for the report. This already got fixed with #5425 and will be released with the upcoming Nextcloud 28 and 27 point releases (scheduled for March 28th).
