### ISSUE TITLE
Escape character added when pasting version numbers copied from a document created with Text editor

### ISSUE THREAD

**Issue by estux** [nextcloud/text#5480]
**Describe the bug**
Write e.g. a version number inside Text editor, typing 28.0.3, and then copy it. 
When you paste it in another generic text editor (not Text module), e.g. in Windows Notepad or here in Github text field, the result is not the same, as you have an escape character added in the middle.
So the pasted result is: 28\\.0.3

This doesn't happen if I have a word or some text before the numbers, like "mysql 10.5.23".

**To Reproduce**
1. Open a Text editor document (e.g. an empty test.md or another existing document) from web interface
2. Write "28.0.3" or other similar version numbers (quotation marks excluded)
3. Copy "28.0.3"
4. Paste it in Windows Notepad or Github text field
5. Pasted text is: 28\\.0.3

**Expected behavior**
The pasted text should reflect what I copied, without added characters.

**Screenshots**
No

**Server details:**
- Nextcloud version: 28.0.3 - 28.0.3.2
- PHP Version: 8.2.14
- Database: mysql 10.5.23

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 122.0.1
 - Device: laptop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
I think this is related to the new way we fill the clipboard with markdown content. I also experienced issues with that, e.g. when copying content from Text to Signal, phpBB and Roundcube.

Also related to #5487 @elzody @juliushaertl.
