### ISSUE TITLE
Links can not be inserted using Markdown syntax

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#55]
This doesn’t work in [tiptap](https://tiptap.scrumpy.io/) either, but there’s a discussion at https://github.com/scrumpy/tiptap/issues/337
![writing link via markdown syntax does not work yet](https://user-images.githubusercontent.com/925062/59426564-c4758800-8dd8-11e9-9473-f057d20b1a89.png)

**Comment by RobinDev** [comment]
And maybe we could add the ability to use jump link ?

**Comment by juliushaertl** [comment]
> And maybe we could add the ability to use jump link ?

Not sure what you mean by that, can you clarify that a bit?

**Comment by RobinDev** [comment]
jump link or fragment link, eg : 

```
[item 1](#item1)

### Item 1 <a name=item1></a>
```

**Comment by jancborchardt** [comment]
@RobinDev could you open a separate issue for this? Also related: Outline view of headings #107

**Comment by juliushaertl** [comment]
https://github.com/ueberdosis/tiptap/discussions/1865 might be some good input for implementing this.
