### ISSUE TITLE
Toolbar missing

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/text#551]
**Describe the bug**
Editor toolbar appears to be missing. I can't be sure as I've never seen it like the [app screenshot](https://apps.nextcloud.com/apps/text), so this may be more of a question :) .

**To Reproduce**
1. Update Nextcloud to stable17 branch
2. Install text app
3. Note that it looks like this:

![Screenshot from 2020-01-12 15-42-14](https://user-images.githubusercontent.com/946674/72227506-3621da00-3552-11ea-8d37-08a39475efe4.png)

As opposed to what is expected given the [app screenshot](https://apps.nextcloud.com/apps/text):

![Screenshot from 2020-01-12 15-42-33](https://user-images.githubusercontent.com/946674/72227508-40dc6f00-3552-11ea-8543-1aee109db2cb.png)

Note in particular the missing editor toolbar.

**Expected behavior**
I expected it to look like the screenshot.

**Client details:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 72.0.1
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)

1.0.2

**Operating system:**

Ubuntu 18.04

**Web server:**

Apache2

**Database:**

Sqlite3

**PHP version:**

7.2

**Nextcloud version:** (see Nextcloud admin page)

stable17 branch, commit b1176aa9a8151c4b36244b344e9fdc733fafba35 .

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
(it's empty)
```

#### Browser log
```
15:57:40.345 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
15:57:40.660 JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
15:57:40.706 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. injectStylesIntoStyleTag.js:201:10
15:57:40.783 Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
files
15:57:40.841 New search handler registered search.js:67:12
15:57:40.845
Viewer app is not installed files.js:34:10
15:57:40.963 The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
15:57:41.040 The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
15:57:41.227 The humanFileSize library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:57:42.539 The escapeHTML library is deprecated! It will be removed in nextcloud 19. 3 globals.js:26:15
15:57:44.376 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:57:48.091 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:57:53.164 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:57:58.274 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:03.351 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:08.770 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:14.755 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:20.766 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:26.763 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:31.825 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
15:58:36.925 The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
15:58:42.001 The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15

​
```

</details>

**Comment by juliushaertl** [comment]
Rich editing is only available in `.md` files, I guess you are opening the `welcome.txt` ?

**Comment by kyrofa** [comment]
Oh wow, you're absolutely right. md files work perfectly fine, I feel silly. Thank you!
