### ISSUE TITLE
Link Preview: no way to edit link with preview toggled on

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#5517]
**Describe the bug**
With the new way to choose between text links and link previews, there's no way to edit a link when the preview is toggled on. It's impossible to select the link and the link bubble cannot be opened either.

**To Reproduce**
1. Add a link
2. Select 'Show link preview'
3. Try to somehow update the link URL

**Expected behavior**
I think there should be a way to alter the link without having to go back to 'Text only'.

**Comment by juliushaertl** [comment]
As discussed in the call, editing a link is probably not happening that often, but we should file a follow up ticket to discuss how to remove a link block node (or more generally any node) with a button with the designers.

@mejo- Can you take care of that?

**Comment by mejo-** [comment]
Sure, created a new issue now: https://github.com/nextcloud/text/issues/5524

Given the discussion yesterday I'm no longer confident that we need a solution for in-line editing of links in preview mode. If we have proper means to delete the link people will just delete and recreate links and that's fine. Let's close this one.
