### ISSUE TITLE
Link preview and link bubble broken in public shares (and with `reference_opengraph = false`)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#5520]
**Describe the bug**
In public shares we currently don't load previews (or other reference widgets). Same if `reference_opengraph` is disabled in server configuration. This leads to several issues:

- Links that are configured to be displayed as previews don't get displayed at all
- Links to other pages in the same collective don't get rerouted but instead get opened in a new tab

**To Reproduce**
- Open a public share of a text file with links configured as link previews

**Expected behavior**

Some thoughts:

- I wonder whether we should limit the effect of disabling `reference_opengraph` to disable previews of *external* pages and still load references to other objects from the same Nextcloud instance.
- In public shares (or with `reference_opengraph` disabled) we have to display links to external pages as text links no matter what.

**Comment by juliushaertl** [comment]
As discussed in the call:
- Text: Let's enable the fallback for link previews in the preview node type
- Server: File a enhancement request for previews on public shares

**Comment by mejo-** [comment]
This is fixed with upgrading to `@nextcloud/vue` 8.15.0
