### ISSUE TITLE
Link Preview: Add button to delete links in preview mode

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#5524]
**Describe the bug**
Currently there's no easily discoverable way to delete a link when it's displayed as preview. The <kbd>Backspace</kbd> key works, but it's not easily discoverable. You can also switch back to "Text only" and delete the link afterwards, but that's not very accessible either.

**Expected behavior**
We should expose a way to delete links that are displayed as previews somewhere in the API.

The best solution that comes to my mind is to add a "Delete" option to the three-dots-menu that allows to toggle between text/preview mode.

Another option would be an overlay "Delete" button like we have for images/attachments. But that would clutter the preview mode even more and is probably not a good idea.

@nextcloud/designers maybe you could give some input here?

**Screenshots**

| Link preview with three-dot-menu |
| --- |
| ![2024-03-19T09:43:18,042576387+01:00](https://github.com/nextcloud/text/assets/3582805/ff1ebabf-3de5-434c-ab89-3b51b069675d) |

**Comment by jancborchardt** [comment]
>  The best solution that comes to my mind is to add a "Delete" option to the three-dots-menu that allows to toggle between text/preview mode.

@mejo- yep, totally agree with this. On the bottom there can be a separator and then an entry "Delete link" with a trash/delete icon.
