### ISSUE TITLE
Interactive widgets are broken in text

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#5531]
Just noticed on current main branch that interactive widgets don't render in text, while they work in talk.

The custom rendering just stays empty:

<img width="877" alt="Screenshot 2024-03-19 at 16 03 33" src="https://github.com/nextcloud/text/assets/3404133/57ca4188-c5e1-4234-a3aa-63a9e7eb7d4d">

I've bisected and it seems to come from [ea8ed3c801800db3b1a0cd5721fcd1a9fce9742b] chore(dependencies): Bump @nextcloud/vue to 8.10.0

Likely https://github.com/nextcloud-libraries/nextcloud-vue/pull/5394

Putting a debugger in place it looks like updating the ref value in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5394/files#diff-08ec8752de5ca8ae39557deea144fd24e7fd409850c22adb3ea3b231afbb1730R69 does not trigger the [watcher of the isVisible value](https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcRichText/NcReferenceWidget.vue#L158).

Steps to reproduce:

- Copy an internal file link to an image
- Paste it into a new text document
- Switch the link type to preview
  <img width="304" alt="Screenshot 2024-03-19 at 15 58 34" src="https://github.com/nextcloud/text/assets/3404133/a3f9823e-5686-4c08-906d-f60aff423288">

I've tried building viewer+text with the same `@nextcloud/vue` version but that does not seem to make a difference.

@ShGKme @susnux I don have a real clue on how to debug that further, so any hint from you as the vue experts would be much appreciated.

**Comment by ShGKme** [comment]
Just in case, have you tested it only with `npm link` or it is on the current `main` of the text with its nextcloud/vue?

**Comment by ShGKme** [comment]
Likely the issue is the same that it was before in another place — text and viewer use different Vue. Changing of `ref` from one Vue is not reactive for another Vue.
