### ISSUE TITLE
New live preview/editing feature locks files forever

### ISSUE THREAD

**Issue by schiessle** [nextcloud/text#5532]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Share a markdown document to a chat room (I assume office documents have the same issue)
2. the chatroom will open a embedded text editor and show the file
3. look in the files app at the file listing and/or on the desktop if you use the sync client
4. the file is locked
5. even after all users who are in the chat are closing the chat windows -> file is still locked
6. delete the chat message with the file -> file is still locked

### Expected behaviour

I think we need to have a way to decide if someone really edits the embedded document. Maybe the document should be opened and displayed by default in a read-only mode and only if people click on "edit" the file gets locked. If the keyboard focus leaves the embedded editor, the lock should be removed and the chat view switches back to read-only.

### Actual behaviour

Once a file is shared to a room and showed with the embedded text editor, it seems to be locked forever. Even when the chat message was deleted again

## Talk app

tested on c.nc.com (Nc 29 beta3)

**Comment by juliushaertl** [comment]
In addition Joas mentioned that Christoph also had issues with text grabbing the focus.

Regarding locking this is nothing we can change short term, we have discussed approaches with only locking a file as soon as there are some actual edits, but this is a technically challenging implementation effort and not feasible.

@jancborchardt I would see making the text editor a read only by default with a button to start editing the only feasible option to have a reasonably good experience. We can work on individual issues then mid-term to at some point bring back editable by default interactive widgets, but this seems to be too heavy for now.

**Comment by schiessle** [comment]
Please also keep in mind that the same issue most likely also exists for Office documents. Just want to highlight it once more because the ticket is now now in the "text" repository.

**Comment by AndyScherzinger** [comment]
Good point, @juliushaertl can you "duplicate" the issue for richdocuments too please? Thanks in advance
