### ISSUE TITLE
Interactive widget takes focus away from Talk chat input

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/text#5542]
**Describe the bug**

The new interactive widget captures focus inside Talk. This has caused me to write into documents shared within a chat when I want to write a message to the chat.

**To Reproduce**
1. Open Talk
2. Share a link to a md file
3. Reload the page
4. See that the focus is on the Talk chat input
5. Type

**Expected behavior**

Focus is kept on the Talk input

**Screenshots**

**Server details:**
- Nextcloud version: [e.g. 26.0.1]
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
We'll address this with https://github.com/nextcloud/text/issues/5532#issuecomment-2007817093
