### ISSUE TITLE
No more preview on 28.0.3 from the smartpicker in text from internal link

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/text#5565]
**Describe the bug**
When you insert something from nextcloud => No preview
When you insert an URL from somewhere => Preview

**To Reproduce**
see above

**Expected behaviour**
Previews are nice :-)

**Screenshots**
![image](https://github.com/nextcloud/text/assets/53221471/660dc232-66e6-4870-a71c-fe8c6bf4d035)

**Server details:**
- Nextcloud version: 28.0.3
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Aveyron-RetD** [comment]
Confirmed on 28.0.4

**Comment by PatrickJosh** [comment]
![afbeelding](https://github.com/nextcloud/text/assets/32456639/0e008570-1b93-4a33-9651-6e9d2ab32bcc)

I can confirm this for version 28.0.5. As you can see in the screenshot, I only see thin grey lines instead of the previews.
Moreover, the previews work in the description of Deck cards.

**Comment by mejo-** [comment]
I tested again and was no longer able to reproduce the problem on Nextcloud 28. Closing the bug therefore.
