### ISSUE TITLE
Reduce size of headings relatively

### ISSUE THREAD

**Issue by pschopen** [nextcloud/text#5581]
**Is your feature request related to a problem? Please describe.**
Especially within Deck and Collectives H1 and H2 seem to be extremely large compared to the other parts of the UI.

**Describe the solution you'd like**
Reduce all sizes slightly. H1 could be 26px and then always -2px until H6 that than had 16px. Text is 15px.

**Describe alternatives you've considered**
Increase other parts of UI.

**Additional context**
This is how the suggested heading size would look.

![20240329_105548.png](https://github.com/nextcloud/text/assets/65334274/35979a03-8f2a-41bf-bf29-e68c4e04a28b)

**Comment by mejo-** [comment]
Thanks for your report @pschopen. This is already discussed in #5515, closing this one as duplicate therefore.
