### ISSUE TITLE
ctrl + click on link vanishes note container

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#559]
@juliushaertl 

as discussed

![image](https://user-images.githubusercontent.com/5836855/72269482-f3c8cd80-3623-11ea-92b5-2b1d99e6fcda.png)

**Comment by azul** [comment]
I guess this one can be closed.
But i don't dare to... :fearful: :wink: 
@tobiasKaminsky @juliushaertl

**Comment by juliushaertl** [comment]
@azul Feel free to do so next time, we can always reopen :wink:
