### ISSUE TITLE
Citavi Plugin messes with Nextcloud text app

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/text#562]
**Describe the bug**
I know that you probably cannot help with that as it is a bug of the Citavi Plugin but maybe it helps someone who stumbles into the same problem (I already described the error to Citavi).
The Citavi Picker Firefox plugin messes with files openend in text app of Nextcloud.
Tried this on two desktops.

**To Reproduce**
1. Install Firefox Citavi Picker Addon: [https://addons.mozilla.org/de/firefox/addon/citavi-picker/](https://addons.mozilla.org/de/firefox/addon/citavi-picker/)
2. Open in Browser a markdown file in Nextclouds text app which contains a (Springer) Link e.g. 
    `[https://link.springer.com/article/10.1007/s10291-019-0858-7 ](https://link.springer.com/article/10.1007/s10291-019-0858-7)`
3. Watch Citavi Picker messing with the file (inserting Links)

**Screenshots**
Screenshot of rendered file in browser:

![Screenshot from 2020-01-14 10-21-49](https://user-images.githubusercontent.com/20948931/72331832-c413d700-36b0-11ea-87df-57421d20200f.png)

<details>
<summary>Raw text that is added</summary>
4. Diskussion von neuen Veröffentlichungen 4.1. Flynn et al., GPS Sol, 2019, [https://link.springer.com/article/10.1007/s10291-019-0858-7 ](https://link.springer.com/article/10.1007/s10291-019-0858-7)[![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:) [![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAUlJREFUeNpiZEADV7XlEoBUPBA7oEkdAOKF2lcfLUAWZETSqACk1gOxgUBACAOvkzsDMy8fWO7v508Mn/ftZPiwYQ2IewGIA4EGPUC2VQGI398N9vj//frV/7gASA6kBqQWaiHcgPMgiT+fPsIVv1009/+DhLD/zzsa/v96+hguDlIDNeQ83M9AjGIzSDNIDIZvWOigGA5SC5VLYAIFGMjPHBpacBeB/IwMQPyPEP+DAUgtSA9IL8gAB1CAIQNeJzd4AMLAj5tX0dSA9TiADMBQDLJB/fhlBq0rDxmEYpPAYqxSsihqYHqYGAgAZl5+iAHSMljlmbD5GRl82LgabBvIW+jhAjPgACiRYAPPaooZfj99wiDV2ovhTaieA1ijEZZgQNH3fsNqrAkKFo1YE9KnvTv/P60uQklAOBMSpUmZ4szESGl2BggwAJR/ZVgK6XqqAAAAAElFTkSuQmCC "Titel anhand dieser DOI in Citavi-Projekt übernehmen")](javascript:)
</details>

**Client details:**
 - OS: Windows 10 & Ubuntu 19.10
 - Browser: Firefox 72.0.0 & Firefox 72.0.1
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:** 1.1.1

**Operating system:** Linux 4.15.0-74-generic

**Web server:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 10.1.43

**PHP version:** 7.2.24-0ubuntu0.18.04.1

**Nextcloud version:** 17.0.2 - 17.0.2.1

</details>

**Comment by biertz** [comment]
@q-wertz Do you have an answer from Citavi?

One of my users just had this issue (Nextcloud 21.0.3, Text 3.2.0).

**Comment by q-wertz** [comment]
They never replied...

**Comment by julien-nc** [comment]
Any news on this issue? Does it still happen with more recent versions of Text and the Citavi extension?

Closing this for now but feel free to reopen if needed.
