### ISSUE TITLE
Clarify relationship between link text and url

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#5651]
**Is your feature request related to a problem? Please describe.**
Urls are converted to links when inserted (pasted, typed, link picker). The link text stays the same as the url but changing it no longer has an effect on the url. This leads to a mismatch and is confusing.

[Bildschirmaufzeichnung vom 09.04.2024, 11:51:16.webm](https://github.com/nextcloud/text/assets/97337118/f09cfc2b-34bd-4dfc-b1a4-3b3ad14cf808)

**Describe the solution you'd like**
I see different options:

A) Indicate that link text and url are different by changing the link text in a meaningful way:
  * use linked page title when available
  * remove `https://` prefix
  * use ellipsis for long links

B) Keep the connection between the url and the link text when they are the same (but how would they become different then)

C) Introduce another type of link that has only a url - could be triggered in the preview menu on the side.

**Additional context**
Saw one incident where all links in a list had the same url but looked different. Probably due to using copy and paste to create the list and then editing the link description only.

**Comment by max-nextcloud** [comment]
@nextcloud/designers I'd be curious what you think about this.

**Comment by marcoambrosini** [comment]
I think it is a bit confusing, but it seems to be the default behavior in other editors (notion, google docs), so I guess it's ok if that's the convention?

**Comment by max-nextcloud** [comment]
Also checked with libreoffice and it's the same. I don't like it - but seems to not be urgent for now. So closing.
