### ISSUE TITLE
[stable28] Copied version number inside multiple paragraphs is escaped.

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#5660]
Worked in 29 and main and will be fixed by upgrading tiptap (#5435).

_Originally posted by @max-nextcloud in https://github.com/nextcloud/text/issues/5657#issuecomment-2049754409_

**Comment by mejo-** [comment]
I'd say let's skip this one as long as nobody else complains. Nextcloud 28 will be end of life in two months and upgrading Tiptap there involves work that is spent better elsewhere.
