### ISSUE TITLE
Links can't be seen, if admin sets global Nextcloud color to white (#FFFFFF)

### ISSUE THREAD

**Issue by laarisyko** [nextcloud/text#567]
If the admin sets global color of Nextcloud to #FFFFFF, than it is not possible to see links in the text editor. This cuts down the text editor capabilities quite a lot. Changing the global nextcloud color to something different is not a solution, due to corporate identity requirements. 

Maybe the link color could be set to stndard, if global nextcloud color is #FFFFFF?

**Comment by rogercreagh** [comment]
Better would be to have the link colour configurable. We have the global header colour set to yellow and the links look really naff. So we override them in css with the custom css app
```
#editor-wrapper div.ProseMirror a {
    color: #000080 !important;
}
```
Would make more sense to have links set to use a "standard" colour like some shade of blue and let people override it as required

**Comment by juliushaertl** [comment]
Seems to be fixed.
