### ISSUE TITLE
NotFoundException

### ISSUE THREAD

**Issue by melbruki** [nextcloud/text#5700]
hello im getting this error in my logs

NotFoundException
Text file with id=1218 and shareToken

running nextcloud 28.0.3

**Comment by joshtrichards** [comment]
Hi @melbruki - Thanks for reporting, but unfortunately you seem to have overlooked the entire bug report template.

We will need, at a minimum, the raw log entry (since it'll contain the trace).

Though I suspect you situation may be #6023

**Comment by mejo-** [comment]
Let's close this one due to lack of information.
