### ISSUE TITLE
Editing session has expired. Please reload the page.

### ISSUE THREAD

**Issue by KarlKeu00** [nextcloud/text#5828]
**Describe the bug**
Error when sharing folder with readme.md

**To Reproduce**
1. Create folder with readme
2. share (with password protection?)
3. open link

**Expected behavior**
Just show the text

**Server details:**
- Nextcloud version: Docker 28.0.5

**Client details:**
 - OS: Docker on Debian
 - Browser: Brave/Chrome
 - Device: Macbook

**Comment by mejo-** [comment]
Thanks for the report @KarlKeu00. This is already reported and discussed here: https://github.com/nextcloud/text/issues/5800
