### ISSUE TITLE
[Bug]: Folder Position Moves after Pageload

### ISSUE THREAD

**Issue by haldi4803** [nextcloud/text#5829]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you open a folder it loads everything, and moves everything down half a second later.
See Video:

https://github.com/nextcloud/server/assets/17104473/3984c2d5-f78a-43b5-8028-b1a336b0dd86

Happens on Firefox: 125.0.2 and Chrome 124.0.6367.78

### Steps to reproduce

1. Open a Folder.
2. Go back to Top Folder.
3. Folder Position changes after 0.5 seconds

### Expected behavior

Folder Position not changing after initial Load.

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Running TrueNAS Scale 24.04
App Version: 28.0.4
Chart Version: 1.6.59

**Comment by mejo-** [comment]
Let's close this due to missing information.
