### ISSUE TITLE
Display links inserted from smart picker as preview per default 

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#5838]
**Describe the bug**
Right now, inserting links inserts them as text links per default, which makes sense. When inserting via smart picker, we should change the default to display the link as preview though, as that's what people expect after seeing the preview in the smart picker already. Even more so for options in the smart picker where you can select between link and content preview (like for references to Nextcloud Tables).

This was originally suggested in issue https://github.com/nextcloud/collectives/issues/1298

@max-nextcloud @nextcloud/designers what do you think?

**Comment by Aveyron-RetD** [comment]
My 2 cents.
=> On a new line smart picker = preview automatically
=> inside a line = link 

Well this is what i do for formatting.
