### ISSUE TITLE
Unwanted Readme feature

### ISSUE THREAD

**Issue by alankeny** [nextcloud/text#586]
### Steps to reproduce
1. Enable the Text app
2. Let users behave like users

### Expected behaviour
Under no circumstances do I want a large clickable area at the top of every folder that creates an empty Readme.md file in any directory on my server.  The Text app should have left this feature to the Readme app for those that wanted it, or it should have provided an option to disable this feature.

### Actual behaviour
My organization doesn't use README files.  Nobody that uses my server has any idea what they're for or even why they exist.  As soon as any user clicks anywhere near the top of a folder listing, the Text app creates a Readme.md file in the current folder.  Even when the user had no intention of writing anything, the app still creates an empty file.  This is going to leave my server littered with empty Readme.md files.  Even for those that want this feature, I would think an app would delay creating the file until the user enters some text.  If all of the text is deleted, shouldn't the file be deleted too, so the app cleans up after itself?

In those rare instances when a user sees their mistake and tries to clean up the mess immediately, they will click on the three dots menu and select the "Delete file" option.  This results in the error, "Network connection error: Could not connect to the document".  No amount of clicking on the retry button gets the error to go away.  The user has to reload the page to clear the error and verify that the unwanted file was actually deleted.

I don't understand why this feature is in the Text app.  There was already an app called "Readme" for those that wanted it.  As a temporary workaround, I have hidden this functionality with the following custom CSS:

    #filelist-header #rich-workspace {
      display: none
    }

## Server configuration detail

**Operating system:** Linux 5.3.13-1-pve #1 SMP PVE 5.3.13-1 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.3.18

**PHP version:** 7.3.11-1~deb10u1

**Nextcloud version:** 18.0.0 RC2 - 18.0.0.9

**Comment by alankeny** [comment]
Thanks only to [this post](https://help.nextcloud.com/t/i-want-to-hide-the-add-notes-field-at-the-top-of-the-file-list-on-nc18/68574) on the support forum, I found the setting I was looking for.  While in the Files app, click on settings in the lower left corner, and uncheck the option **Show rich workspaces**.

The documentation probably needs to be updated.  This new feature was enabled by default, but it isn't mentioned in the CHANGELOG.md.  I never would have guessed that "rich workspaces" meant allowing users to create README.md files that are displayed at the top of folder listings.

My other feedback stands.  The file shouldn't be created until the user enters some text, and it should be deleted if there's no text remaining in the file.

**Comment by r2evans** [comment]
@alankeny have you seen the reference to `workspace_enabled`? I don't know how to disable a user-configuration like this (either per-user or globally). Any thoughts?

https://github.com/nextcloud/text/blob/d6d1badc1b89b929581fefcef534bf44bf0bd87c/src/views/FilesSettings.vue#L47-L60

https://github.com/nextcloud/text/blob/fc86a67cc3d17d838de687faf17b6d9bfb7e3223/lib/AppInfo/Application.php#L80-L88

https://github.com/nextcloud/text/blob/d6d1badc1b89b929581fefcef534bf44bf0bd87c/lib/Controller/SettingsController.php#L39-L47

https://github.com/nextcloud/text/blob/22589234991ad3249e8bf5530b6440eb3a432833/src/files.js#L31-L39

**Comment by alankeny** [comment]
As far as I can tell the `workspace_enabled` user setting is where the "show rich workspaces" option from the web interface is stored.  If this user setting is set to 1 either with the checkbox in the web interface or with the command line `occ user:setting <username> text workspace_enabled 1`, the rich workspace is shown in the main view for that user.  If it's set to any other value, the rich workspace is hidden.  If this user setting is deleted, the rich workspace is shown by default.

I tried to set a bunch of different values for the text app settings `workspace_available` and `workspace_enabled` to get the rich workspace to be disabled by default.  None of them worked to hide the rich workspace, even after I deleted the user setting.

Here are a few examples of the commands I tried:

    occ config:app:set text workspace_available --value=0
    occ config:app:set text workspace_available --value=false
    occ config:app:set text workspace_enabled --value=0
    occ config:app:set text workspace_enabled --value=false

At this point I'll probably put most of my effort into getting the original markdown editor working again, so I can remove this app.  I need an editor that doesn't modify and then break existing markdown so much, and I'd like a text editor that's good for editing code.  Collaboration and "rich workspaces" just aren't a priority for me.

**Comment by r2evans** [comment]
Thanks, I hadn't (yet) tried `occ user:setting ... text workspace_enabled 0`. Perhaps the fact that that step was ineffective can be explained by the `// FIXME: save to app config` comment?

I actually like the *premise* of the "Workspace", though the "always on, cannot disable" aspect is truly troublesome. And the windows client's inability to deal gracefully, https://github.com/nextcloud/desktop/issues/1755, is absolutely disabling for me. It would be better, in my opinion, if we could change the automatic filename used so that we could side-step the windows-case problem by not syncing it. In many environments, "readme.md" (whatever the case) is too common a filename to be globally excluding from client-sync.

**Comment by alankeny** [comment]
I can't tell from the code or that comment if the intention is to have an app level setting or not.  I would want to ensure that an app level setting to disable rich workspaces would override any user level setting.  If the administrator decides to disable the feature, users should not be able to override that decision.

I agree that the *premise* of workspaces is fine, if that's what you want.  Unfortunately this feature has very little to do with editing text and markdown files, so it really should have stayed in a separate app for those that wanted this feature specifically.

**Comment by juliushaertl** [comment]
Not being able to disable the rich workspaces globally was actually a bug in 18.0.0 and will be fixed in 18.0.1 with https://github.com/nextcloud/text/pull/597

Once that is releeased you can disable the feature by running: 
```
occ config:app:set text workspace_available --value=0
```

**Comment by My1** [comment]
is there a reason this is OCC only? not everyone (webhosting ftw) has acess to occ easily

**Comment by Baptistou** [comment]
> is there a reason this is OCC only? not everyone (webhosting ftw) has acess to occ easily

You can install and use the app "OCC Web" :
[How to use occ commands on a Shared Hosting without SSH access](https://help.nextcloud.com/t/how-to-use-occ-commands-on-a-shared-hosting-without-ssh-access/46133)

**Comment by alankeny** [comment]
I tend to agree with @fvdm.  It's really odd that this feature is installed with an editor.  Should someone using a web host that wants to edit files, but doesn't want rich workspaces, be required to load the OCC Web app just so they can disable a feature that doesn't really have anything to do with editing files?  It would have been much easier for everyone if Rich Workspaces had stayed in its own app.

**Comment by CyberneticCody** [comment]
Like @alankeny, I completely agree with @fvdm and I also agree with @My1 .
This should really be a toggle in settings that allows us to disable this globally. It is very confusing for my users and takes up a lot of space, thus ruining a nice clean UI.

> It would have been much easier for everyone if Rich Workspaces had stayed in its own app.
I fully agree with this. I had tried that app in the past with the same result as stated above: Confused users.

**Comment by ChrisB85** [comment]
I tried to run:

```occ config:app:set text workspace_available --value=0```

but all I get is:
```
Not enough arguments (missing: "app, name").
config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

So I tried also:
```
config:app:set --value=0 text workspace_available
```
and
```
config:app:set --value 0 text workspace_available
```

but the results are the same.

**Comment by kobuki** [comment]
> Not being able to disable the rich workspaces globally was actually a bug in 18.0.0 and will be fixed in 18.0.1 with #597
> 
> Once that is releeased you can disable the feature by running:
> 
> ```
> occ config:app:set text workspace_available --value=0
> ```

This does work, but we lose the functionality of `readme.md` altogether. Even if I intentionally add a `readme.md` to a directory, it's not displayed when the above setting is active. The `readme.md` functionality, as is, confusing and useless.

**Comment by chaosgrid** [comment]
@kobuki

But you can simply set it up in the configuration of that app so that the header file is actually readme.md (check the app settings in the admin area).

**Comment by kobuki** [comment]
Thank's I'll try that, but I think this issue will be fixed in the base sooner or later.

**Comment by pwnoobz** [comment]
It's a very unpleasant experience. It's odd that I have to occ it instead of ENABLE it instead. It's an unwanted feature. Please consider fixing this.

**Comment by r2evans** [comment]
@pwnoobz while I agree, I also recognize that this is a closed issue and the developers might not notice (or act on) the comment. Perhaps you should open a new issue as a "feature-request: default 'no' workspace"? It doesn't appear to be a current issue, including the "Workspace polishing" issue https://github.com/nextcloud/text/issues/452.

**Comment by kobuki** [comment]
Oh, it has been closed? So we will need to live with the fact that when the user clicks on the wrong place, the interface will be cluttered with a large empty space? If it has been fixed by some other issue or commit, someone in the know please mention it here.

**Comment by r2evans** [comment]
Yes, scroll up about half-way to the top and notice
![image](https://user-images.githubusercontent.com/5815808/82373622-b493fa00-99d2-11ea-8e66-5170937bd2f0.png)



Plus, at least in my display, I have a hanging-header:
![image](https://user-images.githubusercontent.com/5815808/82373646-b9f14480-99d2-11ea-8855-e5bc6a1529cd.png)

I think they are tweaking some portions of it. And while I admit I have not been tracking all dev recently, I've not seen any work on either (1) defaulting to "no", or (2) an ability to disable it within user- or system-settings UI.

**Comment by kobuki** [comment]
I now know it's closed, I just didn't notice it earlier. But closing an issue doesn't always mean it has been solved.

**Comment by dacoex** [comment]
@kobuki 
Thanks for coming in.
Please comment further on the still open issue:
https://github.com/nextcloud/server/issues/19938

**Comment by r2evans** [comment]
@kobuki , sorry, was not suggesting, I can see my last comment is framed poorly. Fully agree that `closed != solved`.
