### ISSUE TITLE
Opening a read only share locks the file

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#5862]
**Describe the bug**
When opening a document read only
* a session is created on the server
* the document is locked
* initial steps are pushed from the client but rejected by the server

**To Reproduce**
1. Create a markdown file and share it read only
2. Open the read only share without opening the file itself
3. Check the lock and open the file for editing in another tab.
4. See lock and failing initial load.

**Expected behavior**
Read only views should not lock the document or mess up the session state.

**Screenshots**
*will attach later*

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/text/pull/5863
