### ISSUE TITLE
Option to disable rich text editing mode

### ISSUE THREAD

**Issue by AtomToast** [nextcloud/text#5864]
**Is your feature request related to a problem? Please describe.**
I am used to just writing out markdown symbols like for example `[link](address)` for links. I mainly use the nextcloud editor to check or extend my notes when not on my own machine and the fact that I can't just simply edit the plain text in the file is frustrating. Having to learn those shortcuts or pressing the buttons is a lot less convenient than just typing everything out or being able to edit those symbols directly.

**Describe the solution you'd like**
Just have a toggle button or setting to switch to switch to a plain text mode, or even better an edit mode, similar to the one you can use in the notes app (which seems to use the same underlying editor?)

**Describe alternatives you've considered**
Move all my markdown files into notes so I can use their editor. Though then I have vastly reduced support for subfolders.

**Additional context**
Example of how the Notes 'edit mode' works
![image](https://github.com/nextcloud/text/assets/27757087/588580fa-2858-4191-ac90-8529d6cb2c33)

I also wanted to complain that expansion of markdown symbols in general didn't work for me but I must have done something wrong until now, since when I went to take a screenshot it actually just works now lol. Not sure what changed but I swear, right before this, typing \`code\` would result in \\\`code\\\` in the file. Or starting a line with `- ` or `##` would not result in a bullet point or heading. I even downloaded it to check when debugging this issue. But that definitely reduced friction and a big part of my issue now. Biggest annoyance left is really just links

**Comment by perennoe** [comment]
This is would be a really important feature, being able to see the markup in text. Some kind of sytax-highlighting/rendering the text accordingly is of course good feedback for the user, but it shouldn't hide the markup.
i would add: linenumbers in such a (hybrid/)plain text view. :)

**Comment by mejo-** [comment]
Dear @AtomToast, thanks for your feedback. Markdown editing is indeed a long requested feature. Unfortunately it's pretty complex to implement due to interference with the collaborative editing synchronisation.

The feature is already discussed at https://github.com/nextcloud/text/issues/3570, closing this one as duplicate.

**Comment by mejo-** [comment]
Regarding adding links with markdown syntax, there's also https://github.com/nextcloud/text/issues/55 to track it and it might come to Text soon: https://github.com/nextcloud/text/pull/5894
