### ISSUE TITLE
no "new" in creator capability

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#599]
Currently there is "new text document" in creators endpoint on text app.
Collabora only shown "presentation", "document", …

As clients might show it different, creator should only reflect to type, so that clients can choose what to show.

Server:
![image](https://user-images.githubusercontent.com/5836855/72802670-98629500-3c4c-11ea-98ea-2f6646a1a171.png)

Android:
![image](https://user-images.githubusercontent.com/5836855/72802759-c3e57f80-3c4c-11ea-8b79-17bd9a0d9773.png)

--> I would add "Create new" to every creator entry, once a new text version is released.

**Comment by tobiasKaminsky** [comment]
@juliushaertl ^

**Comment by juliushaertl** [comment]
Yes, lets do this for 18.0.1 then.

**Comment by tobiasKaminsky** [comment]
Isn't this "just" in Text?

**Comment by juliushaertl** [comment]
Yes, but text is not released in the app store but shipped with the release. That means at the moment we are unfortunately bound to the server release cycle.
