### ISSUE TITLE
Inline Code

### ISSUE THREAD

**Issue by JL710** [nextcloud/text#6014]
## Short summary of the issue
The editor is missing support for inline code or at least I could not figure out how to insert inline code. 

If uploaded in a markdown file, it is rendered correct and I can edit the content as well. But there is no method of creating a piece of inline code in the editor itself.

## Example markdown file
````markdown
this would be `inline code`
````

## Screenshot of the rendering in text
![Screenshot_20240708_170307](https://github.com/nextcloud/text/assets/76447362/078eee01-aa84-44b8-a419-78e00cdc4c5c)

## Details
- Nextcloud version: [Nextcloud Hub 8](https://nextcloud.com/) (29.0.3)

**Comment by juliushaertl** [comment]
You can just type the markdown syntax, however it makes sense to think about how we can make inserting easier. Probably we should reuse the code block icon and switch selected text to inline code if just a subset of a paragrpah is selected.

**Comment by rajmondburgaj** [comment]
@juliushaertl inserting single quotes manually does not render the text as code in collectives pages. I personally would expect it to work this way:

1. If I manually add single quotes everything inside should be rendered as code.
2. If code block button is clicked while having some code selected, it should treat it as inline (maybe check if not the whole paragraph is selected)

**Comment by JL710** [comment]
I updated my instance. Now I can input it as @juliushaertl described which is ok for my case.

But a button would be nice as well.

**Comment by rajmondburgaj** [comment]
hi @JL710 , not sure why this is closed, as I have stated this does not work in all cases. I understand that this works for you, but I guess the issue remains as long as there are other situations where this can be very easy replicated (using collectives pages for example).

**Comment by JL710** [comment]
I tested on windows today. On windows in firefox no solutions worked. So putting in inline code seems only to be possible on linux.

**Comment by JL710** [comment]
> Just to be sure, do you type the full inline code content and end it with an apostrophe? Just typing the apostophe doesn't start an inline code element. You have to type apostrophe - content - apostrophe, then it turns the part between the apostrophes into a code element.

Ups. That works.

**Comment by mejo-** [comment]
Let's close this for now. If someone still faces this problem, please record a screencast to get a better understanding of what you're doing :blush:
