### ISSUE TITLE
Tables button alignment is off on master

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#6027]
This is due to the design change coming with Nextcloud 30.

We probably need to adjust to use the css variables there as well:

<img width="694" alt="Screenshot 2024-07-11 at 12 54 15" src="https://github.com/nextcloud/text/assets/3404133/058d0c71-c416-42d5-bc53-eeacdaa00f6d">

**Comment by luka-nextcloud** [comment]
@juliushaertl Is there any instruction which css variables should be updated? Is it https://help.nextcloud.com/t/css-variable-change-and-probable-regressions-in-apps/196999?

**Comment by juliushaertl** [comment]
I'm not sure why the buttons are misaligned, but if there are any hardcoded height or margin/padding values it might be worth to adapt them to css variables. 

- height should probably be adapted to `--default-clickable-area`
- padding/margin either try to align more dynamically with flex layouts or use a multiple of `--default-grid-baseline`

Also see https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/css.html#css-variables for an overview on css variables and where to use them
