### ISSUE TITLE
Rich Workspaces / Folder Description not shown when using Favorites

### ISSUE THREAD

**Issue by bentuna** [nextcloud/text#6028]
**Describe the bug**
The Rich Workspaces (or now called Folder Description) is not shown, if you open a folder over the Favourites sidebar ("Favorites > Folder". It is, however, shown when you open the same folder via the normal way ("All Files > Folder").

**To Reproduce**
1. Open a Folder in Nextcloud Files that has a Readme.md.
2. Go to Files Settings and enable "Show folder description".
3. See how the content of the Readme.md is displayed above the files list/grid.
4. Add the said folder to your favorites and open it through clicking on the Favorites entry in the sidebar.
5. See how there is nothing displayed above the files list/grid.

**Expected behavior**
The Rich Workspaces (or now called Folder Description) is shown when opening a folder via Favorites.

**Server details:**
- Nextcloud version: 28.0.7

**Comment by juliushaertl** [comment]
@luka-nextcloud i remember you worked on something related recently, could you check that?

**Comment by juliushaertl** [comment]
@luka-nextcloud i remember you worked on something related recently, could you check that?

**Comment by luka-nextcloud** [comment]
This issue was already fixed on https://github.com/nextcloud/text/pull/5802
I will do backport to v28 and v29.

**Comment by luka-nextcloud** [comment]
https://github.com/nextcloud/text/pull/6029
https://github.com/nextcloud/text/pull/6030

**Comment by juliushaertl** [comment]
All merged
