### ISSUE TITLE
Enable Full-Width Display for Text Files in Nextcloud Text App

### ISSUE THREAD

**Issue by akang1798** [nextcloud/text#6049]
## Is your feature request related to a problem? Please describe.
Currently, the Nextcloud Text app displays text files in a fixed width layout, resembling a physical paper page. While this may be suitable for some use cases, it can be inconvenient for viewing and editing longer text files or those containing wide tables or code blocks.

## Describe the solution you'd like
Introduce an option to enable full-width display for text files in the Nextcloud Text app. This would allow users to maximize the available screen space and improve the overall reading and editing experience, especially for those working with extensive text content.
### Potential Implementation
**Custom CSS Approach:**
        Provide a configuration option in the Text app settings to enable/disable full-width display.
        Upon enabling the option, inject custom CSS rules to override the default max-width property for the text editor content area.

**Native Support:**
        Modify the underlying code of the Text app to incorporate a responsive layout mechanism that adapts the text editor's width to the available screen space.
        Consider introducing additional options for users to fine-tune the text wrapping and margins.

### Benefits
Enhanced readability and editing experience for longer text files Improved usability for viewing and working with wide tables or code blocks Better utilization of screen space, especially on larger monitors Increased flexibility for users to customize their preferred text editor layout.

## Describe alternatives you've considered
While full-width display may be beneficial for certain use cases, it's crucial to ensure that it doesn't compromise the overall layout and readability of the text content.
Implementing native full-width support might require more extensive code modifications compared to the custom CSS approach.
It's recommended to gather feedback from users regarding their preferences for text editor width and layout options.
We kindly request the Nextcloud development team to consider implementing full-width display functionality for text files in the Text app. This feature would significantly enhance the user experience for those who frequently work with extensive text content or require a more flexible text editor layout.

**Comment by mejo-** [comment]
Thanks for the report @akang1798. This is already reported and tracked in #4024. I'll close this one as duplicate.
