### ISSUE TITLE
Copying from code block adds backticks

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/text#6053]
**Describe the bug**
When copying text from a codeblock the clipboard content will be surrounded by 3 backticks at the start and end.
This is quite unexpected and annoying since I only copied the visual part which I intended to and not the rest.

**To Reproduce**
1. Create a code block
2. Enter some text
3. Select the text and copy it
4. Paste it somewhere else

**Expected behavior**
No backticks.

**Server details:**
- Nextcloud version: 28.0.4
- PHP Version: 8.2
- Database: Postgres 15

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 128
 - Device: Desktop

**Comment by mejo-** [comment]
This has been fixed in the meantime.
