### ISSUE TITLE
indent bullets

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/text#6055]
**Describe the bug**
I am trying to indent bullit points on my Android. My keyboard does not have a tab. Alternatively, it should be possible to indent a bullit point with two leading spaces. However, this starts a new list at the highest level.

**To Reproduce**
1. open an .md file with an editor
2. ...

**Expected behavior**
two spaces should cause an indented bullitpoint
There could also be a button for the “indent” command. 

**Screenshots**
![indent](https://github.com/user-attachments/assets/819232fc-9815-456a-b225-1b9da25ed19a)

**Server details:**

    Text app version: 3.9.1
    Nextcloud version: 28.0.4

**Client details:**

    OS: Android Lineage OS 21
    Browser: Firefox, Vivaldi

**Comment by juliushaertl** [comment]
Thanks for your suggestion, this is already tracked in https://github.com/nextcloud/text/issues/2438 so I'll close this as a duplicate
