### ISSUE TITLE
Emoji picker is secondary but should be tertiary like other buttons

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#6057]
As seen on daily:

<img width="717" alt="Screenshot 2024-07-17 at 17 01 07" src="https://github.com/user-attachments/assets/e100bc0e-ed9c-4f65-8b27-a33e588955af">

**Comment by juliushaertl** [comment]
I think this got fixed meanwhile with the library, cannot see this anymore on latest main

**Comment by mejo-** [comment]
Seem's like you're right :blush:
