### ISSUE TITLE
Header of collaborative text editor should not zoom

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#606]
- open up a markdown file with new text edit (collaborative)
- click to edit text
--> zooms and header is also zoomed
- try to close -> you cannot see the "x"

**Comment by juliushaertl** [comment]
Yes, thanks for the reminder. Moving to the text app repo

**Comment by juliushaertl** [comment]
was fixed with https://github.com/nextcloud/text/pull/608/commits/9bac30dfa6a32059ef20d5abec9f689bf9e518e4
