### ISSUE TITLE
Collaborative editing does not work in a clustered setup

### ISSUE THREAD

**Issue by lordcirth** [nextcloud/text#607]
**Describe the bug**
When running multiple Nextcloud servers behind HAProxy, if a user opens a file, users who are directed to other server backends cannot access the file.

**To Reproduce**

1. Have N>1 Nextcloud 17 servers behind a reverse proxy
2. Create an md file in browser 1
3. Attempt to open file in browser 2
4. Connection error.

**Expected behavior**
A normal collaborative editing session.

**Screenshots**
![NextcloudTextError](https://user-images.githubusercontent.com/2523446/73023743-2af46700-3dfa-11ea-99d4-4fcb43183772.png)

**Client details:**
 - OS: Xubuntu 18.04
 - Browser: Firefox 73.0b8 (64-bit)
 - Device: Desktop

**Text app version:** (see Nextcloud apps page)
1.1.1

**Operating system:**
Ubuntu 18.04

**Web server:**
Apache 

**Database:**
mysql 5.7

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
17.0.2

**Comment by DanScharon** [comment]
this is a showstopper for us

**Comment by lordcirth** [comment]
> I cannot see any issue with this on my test system. As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
> 
> If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

Could you share the setup of your test system? Perhaps there is some difference we could use to narrow it down. Are you using Apache and HAProxy like I am?
