### ISSUE TITLE
Copy & paste tasks (checkboxes) loses formatting

### ISSUE THREAD

**Issue by theroch** [nextcloud/text#6182]
Please make a clear and concise description of what the bug is.

## Steps to reproduce
1. Create a new note
2. Add "foo" and mark it as task
3. Select all and copy the text
4. Create a new note
5. paste the content

### Expected behaviour
The pasted content should retain the marker as a task.

### Actual behaviour
Marking as a task has been lost. The content is inserted as list item.

## Server
Please complete the following information.

- Notes app version: 4.8.1
- Nextcloud version:  27.0.2
- OS: Ubuntu
- Web server: Apache 
- PHP version: 8.1
- Database: MySQL

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by mejo-** [comment]
Thanks @theroch. This is already tracked in https://github.com/nextcloud/text/issues/5237, so closing this one as duplicate.
