### ISSUE TITLE
Bullets are not selected in the view when selecting the text

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/text#6183]
Bullets are not selected in the view mode when selecting the text if I want to copy and paste the whole text somewhere.

**Comment by mejo-** [comment]
@stefan-franz this should have been fixed in the meantime, je made quite some adjustments to copy & paste in Text. Please report back if you still experience this.

**Comment by stefan-franz** [comment]
Bullets from a list in the Notes Rich Text are not selectable. 
You can reproduse it: Make a list with 3 entrys and try to select the 3 entrys WITH the Bullets. Only the text is selectable. Not the bullets.
