### ISSUE TITLE
pressing UP on newline goes to line 1, not up one line

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/text#6185]
**Describe the bug**
When the cursor is on an empty line (i.e. newline), then the user pushes `up` arrow on the keyboard, the cursor jumps up to line 1 instead of the line immediately above.

**To Reproduce**
1. create new text document
2. create several newlines
3. Click on an empty line in your document - i.e. line 3, cursor must appear at character 1 position
4. press `up` to go to the line above

**Expected behavior**
cursor should move 1 line up

ACTUAL BEHAVIOR

cursor moves to line 1, regardless of which line it started on.

**Screenshots**
[Screencast_20240809_130421.webm](https://github.com/user-attachments/assets/71ef15e8-b5d8-42ff-9063-9f0ae5dbf030)

**Server details:**
- Nextcloud version: 30.0.0 beta 5
- PHP Version: 
- Database: 

**Client details:**
 - OS: linux / NixOS
 - Browser: Firefox
 - Browser version: 128.0.3
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by XueSheng-GIT** [comment]
Actually, I wanted to comment to this issue but did to another one by accident. Thus, now adding my intended comment as quote:

> Just tried this on Win11 with Firefox 129 and NC29.0.4. Following your steps, cursor does not jump to line 1, it doesn't move at all (it just stays at its position). I need to press left or use the mouse to move the cursor up again.
> Thus, there seems to be an issue with different symptoms.

I double checked with NC29.0.6 and Firefox 130 on Win11 and the behaviour is still the same (as quoted).

**Comment by mejo-** [comment]
Some more findings:

* Using the upstream `Paragraph` extension fixes this. So it's related to our custom `Paragraph` implementation.
* It's not reproducible in upsteams Tiptap example editors.
* Removing the `PreviewOptions` element from `ParagraphView` fixes it as well.
* Removing everything from `PreviewOptions` and making it a simple `<div />` doesn't fix it.
* Maybe somehow Tiptap doesn't like an extra element in the paragraph structure?

@max-nextcloud

**Comment by s-ailus2** [comment]
It'd be nice to have this either fixed or the application version reverted to ~ NC 28 time or something. This bug makes the application almost unusable.

**Comment by mejo-** [comment]
Apparently this bug only occurs on Firefox based cursors.
