### ISSUE TITLE
Unexpected end of array

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/text#6193]
**Describe the bug**
On daily opening the files app, this is shown:
<img width="485" alt="image" src="https://github.com/user-attachments/assets/b8a65a67-cad9-4501-a9ab-61bbfa5675c1">

The requests that might be of interest:
`workspace?path=/`:
<img width="410" alt="image" src="https://github.com/user-attachments/assets/ccccf508-ce75-4abf-a666-14d02a5907aa">

`create`:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/5d177748-447e-44af-8fcb-bee53569fe5f">

`attachments`:
<img width="150" alt="image" src="https://github.com/user-attachments/assets/9e913b99-4c65-4109-9da3-d93ab97c8960">

**Comment by mejo-** [comment]
So far I was unable to reproduce this on latest main/master branches. I copied the default Readme.md content from daily instance. On the daily instance, the error still occurs. I wonder whether this is really related to the Text app at all.

**Comment by juliushaertl** [comment]
I can also no longer reproduce this on daily. Let's close for now
