### ISSUE TITLE
Issues with Indenting Lists Using the TAB Key

### ISSUE THREAD

**Issue by 456634** [nextcloud/text#6198]
**Describe the bug**
Issues with Indenting Lists Using the TAB Key

**To Reproduce**
Indenting a list using the TAB key only works if, for example, a code block is present in the document. If this object is not present, the focus jumps to another element instead of indenting the list. Once the code block is reinserted, the list can be indented again. The position of the code block does not matter.

**Expected behavior**
Indenting a list using the TAB key works even without a code block in the document.

**Server details:**
- Nextcloud version: 29.0.4
- PHP Version: 8.2.21
- Database: 10.11.8-MariaDB

**Client details:**
 - OS: Linux
 - Browser: Firefox, Vivaldi
 - Browser version: 128.0, 6.8.3381.46

**Comment by XueSheng-GIT** [comment]
Just tried this on Win11 with Firefox 129 and NC29.0.4. Following your steps, cursor does not jump to line 1, it doesn't move at all (it just stays at its position). I need to press left or use the mouse to move the cursor up again.
Thus, there seems to be an issue with different symptoms.

**Comment by alexanderdd** [comment]
I can confirm that indenting a list entry with tab key doesn't work on NC 30.0.0 RC2 (c.nc.com - can't check App version).

I confirm that this still works as expected on NC 28.0.6 with Text App 3.9.1

**Comment by mejo-** [comment]
I cannot reproduce this any longer on instances running Nextcloud 29, 30 or main with Firefox 130 on Linux/Wayland.

@456634, @XueSheng-GIT can you still reproduce this issue on Nextcloud 29.0.6? And @alexanderdd is it reproducible for you still?

**Comment by XueSheng-GIT** [comment]
@mejo- Actually, having a look at my last comment, I believe that I answered to the wrong issue (at least my comment seems to be completely unrelated). Anyways, I followed the steps to reproduce on NC29.0.6 and Firefox 130 on Win11.

Indentation of unordered and ordered lists seem to work as long as items can be indented. If indentation is not possible (e.g. first item of a list), pressing the Tab key changes focus of item (e.g. to the three dot menu). This may not be the ideal behaviour but seems to be reasonable somehow. At least I would not expect that Tab changes the focus to another item within the context of text editing.

Indentation of check lists does not seem to work at all. At least in the past I used Tab to indent check lists.

Indentation in code blocks does work. But unindentation (SHIFT+TAB) does not seem to work inside code blocks (focus does change to another item).

At least the situation seems to be different compared to the initial post ;). Now the questions would be what the intended behaviour should look like ;).

**Comment by mejo-** [comment]
> Indentation of check lists does not seem to work at all. At least in the past I used Tab to indent check lists.

Interesting, this works well for me. Could you describe an exact reproducer? I tested on latest development branches and on Nextcloud 29.0.5, it worked on both: I created a new document, typed `* [ ] task` (created a first task list item), pressed <kbd>Enter</kbd> (created a second task list item) and then <kbd>Tab</kbd> (added indention of the item).

> Indentation in code blocks does work. But unindentation (SHIFT+TAB) does not seem to work inside code blocks (focus does change to another item).

I would say that's expected behaviour. The change of <kbd>Tab</kbd> behaviour should be as minimal as possible inside code blocks. Also using <kbd>Shift</kbd>+<kbd>Tab</kbd> in other editors doesn't lower indention either.

You can use <kbd>Backspace</kbd> to delete the tab that you just typed in a code block :wink:

**Comment by 456634** [comment]
> I cannot reproduce this any longer on instances running Nextcloud 29, 30 or main with Firefox 130 on Linux/Wayland.
> 
> @456634, @XueSheng-GIT can you still reproduce this issue on Nextcloud 29.0.6? And @alexanderdd is it reproducible for you still?

The behavior has not changed for me under 29.0.6. The only thing I have noticed is that adding a code block only helps sometimes. However, when I switch from the Big View to the Site View, everything seems to work as expected.

**Comment by mejo-** [comment]
@456634 what do you mean with switching from "big view" to "site view"? Do you mean the "full width" view in Nextcloud Collectives? maybe you can provide a screenshot of what you mean? Also, which operating system and browser to you use?

**Comment by 456634** [comment]
@mejo- 

Oh, sorry. I had tested it in Deck yesterday, not in Text. The issue does seem to be resolved in version 29.0.6. It's strange that it doesn't work in Deck, but that's not relevant here anymore
