### ISSUE TITLE
Public image upload fails with "Toastify is awesome" message

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/text#6206]
**Describe the bug**
If you try to upload a picture on a puplic shared collective, you only get a message "toastify is awesome"

**Server details:**
- Collectives app version: 2.13.0
- Nextcloud version: 29.0.3

**Client details:**
Tested with mozilla and mobile browser

**Comment by neuhaus** [comment]
Is this the same issue as issue #4153 ?

**Comment by juliushaertl** [comment]
Yes, sounds like the same
