### ISSUE TITLE
Search in text editor. 

### ISSUE THREAD

**Issue by Gatak** [nextcloud/text#623]
It would be nice with the ability to search for text in the text editor. Currently not possible in mobile browsers. Or rather, mobile browser can only search for visible text, and not the whole text file. 

Reference bug nextcloud/server#16047

**Comment by juliushaertl** [comment]
Your screenshots seem to refer to the old [files_texteditor](https://github.com/nextcloud/files_texteditor) app. Are you still on 16 and using that one?

**Comment by Gatak** [comment]
Hi. I recently moved to the new text/markdown editor now it handles plain text files properly (which wasn't the case in the beginning). The search works fine there. I suppose we can close this issue now?

**Comment by juliushaertl** [comment]
> Hi. I recently moved to the new text/markdown editor now it handles plain text files properly (which wasn't the case in the beginning). The search works fine there. I suppose we can close this issue now?

Yes, let's close it then :)
