### ISSUE TITLE
Pasting an image into a table cell does not align it inside the cell

### ISSUE THREAD

**Issue by rajmondburgaj** [nextcloud/text#6240]
When I have a table with some columns, and I try to paste one image inside one cell, instead of setting the image in the cell itself, it will split the table in half and upload the image in between which is not the desired behaviour.

![image](https://github.com/user-attachments/assets/0e77217d-5ca7-4790-b158-da48f4386423)

**Comment by juliushaertl** [comment]
Thanks for reporting. This is actually a bug in text, we already track it in https://github.com/nextcloud/text/issues/4047 so let me close this one here as a duplicate.
