### ISSUE TITLE
Embedded editor in preview mode via `NcReferenceWidget` doesn't support attachments

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#6267]
**Describe the bug**
The embedded editor in preview mode via `NcReferenceWidget` doesn't know about a `fileId` and therefore has not `AttachmentsResolver`. That results in attachments/images not being loaded.

**To Reproduce**
1. Create a Text document with an image
2. Add the internal link to this document to another Text document or a Talk conversation
3. If added to anoter Text document, turn the link into a preview
4. See error "Attachment source was not resolved"

**Expected behavior**

**Screenshots**

![grafik](https://github.com/user-attachments/assets/5933b19b-79e5-46ca-8a2a-9f5e3021456b)

**Server details:**
- Nextcloud version: 30.0.0rc2

**Comment by juliushaertl** [comment]
We should have the file id available as the file reference widget passes it to our viewer component 
https://github.com/nextcloud/server/blob/5b7dcc1427e996a3154761877d1e11463ed4bef4/apps/files/src/views/ReferenceFileWidget.vue#L149

So it might be just a matter of passing that along to the read only view in https://github.com/nextcloud/text/blob/3a9c4f6f7a0ce3e6d148314311730b35250e34fc/src/components/ViewerComponent.vue#L20

**Comment by mejo-** [comment]
Nice. We have to migrate from `RichTextReader` to `MarkdownContentEditor` in the `ViewerComponent`, but a quick text revealed it works. I'll open a PR.
