### ISSUE TITLE
Windows compatibiliy: upload a file with wrong filename

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#6269]
1. enable windows compatibility
2. upload a not-allowed file to an collectives page, e.g. CON.jpg
3. see 
![image](https://github.com/user-attachments/assets/15018b0f-ad63-4a99-8b85-a98adc7f542a)

**Comment by mejo-** [comment]
Transfered to Text as this is a Text issue.

What would be the expected behaviour here? Convert the filename to a compatible name? Is there APIs available in frontend and/or backend to sanitize the name?

**Comment by juliushaertl** [comment]
I think we should just provide a proper error message there to tell the user what was wrong.

Those would be some pointers around that:

https://github.com/nextcloud/files-clients/issues/58#issuecomment-2200130583
https://github.com/nextcloud/spreed/pull/12919/files
