### ISSUE TITLE
No translation - Add notes, lists or links …

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/text#627]
**Describe the bug**
No translation of the sentence "Add notes, lists or links ..." in file editing. Translation is in Trasifix.
code:
https://github.com/nextcloud/text/blob/b7322a0ed69169f9ba53ba3046d32f1a5aa50950/src/EditorFactory.js#L82

**To Reproduce**
1. Click on quick edit.

**Expected behavior**
Translated "Add notes, lists or links ..." text.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/47037905/73273699-b8fa9400-41e4-11ea-8b8b-b76b9dbf638f.png)

**Text app version:** (see Nextcloud apps page)
2.0.0

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Comment by KekcuHa** [comment]
Faced the same issue, NC 18.0.1
