### ISSUE TITLE
Markdown support for tables (regression?)

### ISSUE THREAD

**Issue by lispykid** [nextcloud/text#633]
Support for Markdown Tables doesn't work. In the Nextcloud Markdown app this used to work. Maybe my setup is broken? Is this feature planned?

Something like this isn't properly rendered:

|**AUFGABE**|**VERANTWORTLICH**|**BESCHREIBUNG**| |-|-|-| |**Vorstand Personal**|Name|| |**AGG**|Name|| ||Name|| ||Name|| ||Name|| |Sicherheitsbeauftragte|Name|| |Ansprechpartnerin  unter Kindern|Name|IsoFak nach §8a SGBVIII| |Hygienebeauftragter|Name|Durchführung von Gesundheitsbelehrungen für die Kochdienste| |||Gesundheitszeugnisse einsammeln und auf Vollständigkeit prüfen| |Personalsuche|Name|| |Betreuung Bewerber für's Team|Name|| |Bufdi-Koordination|Name|| |Patin für Name|Name|| |Paten für Putzfee|AG Putzwochenende|Name| |Team-Patin (Geschenke)|Name||

**Comment by ronaldscott** [comment]
https://github.com/nextcloud/text/issues/114

**Comment by juliushaertl** [comment]
Yes, closing as a duplicate of #114
