### ISSUE TITLE
Title bar uses wrong "dark" theme even in light mode

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#6386]
**Describe the bug**
When Nextcloud is using a "light" theme, the text editor uses a "dark" theme title bar which makes the elements very hard to see due to the light grey color.

In the HTML source you can also see the wrong theme `data-theme-dark` used:

```
<div data-v-1d602fb0="" data-theme-dark="" class="modal-header">
```

This would be the correct code:

```
<div data-v-1d602fb0="" data-theme-light="" class="modal-header">
```

**To Reproduce**
1. Make sure Nextcloud is using a "light" theme.
2. Open or create a text document.
3. See the title bar in light grey color instead of the expected dark color.

**Expected behavior**
The title bar uses the correct theme.

**Screenshots**

![image](https://github.com/user-attachments/assets/898c71b3-336e-4947-9486-e4497d23760c)

**Server details:**
- Nextcloud version: 30.0.0
- PHP Version: 8.3
- Database: MariaDB 10.6

**Client details:**
 - OS: Windows 11
 - Browser: Vivaldi, Chrome, Firefox
 - Browser version: latest versions as of 2024-09-15
 - Device: Desktop

**Comment by Rahul-2006** [comment]
Hi @arnowelzel 
If the theme is only the concern , i can adjust it and it can help me in growing my open source journey

**Comment by arnowelzel** [comment]
> Hi @arnowelzel If the theme is only the concern , i can adjust it and it can help me in growing my open source journey

Yes, only the attribute for the theme should match the current Nextcloud theme. Thanks for your help!

**Comment by Rahul-2006** [comment]
So can i get it assigned ?

**Comment by arnowelzel** [comment]
I am not a team member of Nextcloud, so I can not assign you. Maybe they can help. However you can always start working on that anyway and provide a pull request with your changes.

**Comment by Rahul-2006** [comment]
Ok I will start working on this  then...

**Comment by mejo-** [comment]
@Rahul-2006, before you start working on this, we already have a fix ready sorry. It was a rather complex fix in other components: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6083 and https://github.com/nextcloud/viewer/pull/2528

Thanks still for your interest in contributing. Feel free to pick another issue that you want to work on :blush:

**Comment by Rahul-2006** [comment]
Ok!!
Thank you
