### ISSUE TITLE
Headings menu appears but quickly closes, menu is lost

### ISSUE THREAD

**Issue by moviuro** [nextcloud/text#639]
**Describe the bug**
When editing Readme.md in a folder view, I can't select an adequate *Heading* because the menu closes abruptly.

**To Reproduce**
Steps to reproduce the behavior: see [video](https://sco.popho.be/s/ejcSyqJkpKtf6kL)
1. Go to whatever folder
2. Edit Readme.md at the top of the folder view
3. Try to add a Heading
4. The heading menu disappear before I have time to pick one

**Expected behavior**
The Heading drop down can be used

**Screenshots**
see [video](https://sco.popho.be/s/ejcSyqJkpKtf6kL)

**Client details:**
 - OS: Linux
 - Browser: Firefox and Chromium
 - Version: 72.0.2 and 79.0.3945.130 (Official Build) Arch Linux (64-bit)
 - Device: desktop

<details>
<summary>Server details</summary>

**Text app version:** 2.0.0

**Operating system:** FreeBSD 12.1

**Web server:** nginx

**Database:** postgre

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.0

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Most probably irrelevant - no errors
```

#### Browser log
```
I HAVE NO IDEA HOW TO GET THAT - NEED HELP/GUIDANCE
```

</details>

**Comment by julien-nc** [comment]
I can't reproduce this bug on stable24, stable25 or master.

Do you still face this issue? Feel free to reopen if so.

**Comment by moviuro** [comment]
Indeed, looks like it was fixed at a time since I reported the issue.
