### ISSUE TITLE
Changes stops being pushed after a while and data not saved. App can't be trusted.

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/text#6415]
**Describe the bug**
Since I updated my NC lately, every time I work on a text with the online editor, I'm losing some data which is not saved and can't even be saved. The app is then unusable. Never had this before.

Looking into the console, it seems that it stops pushing modification. But I couldn't find a way to reproduce it exactly. Only what I experience is that it happens after a while.

When it stops saving automatically, the save button is also disabled. There's no way to save changes. ⚠️ 

**To Reproduce**
1. Write some text
2. Keep doing it for a while
3. Change tab, change windows, go back. Have a regular behavior
4. At some point your changes won't be saved anymore and the save button is disabled

**Expected behavior**
Changes should be saved automatically. If there's an issue with push, user should see a warning and should be able to force save. Ultimately, changes should be saved locally in the brower in case of offline mode to avoid any loss of data.

**Screenshots**
![Capture d’écran 2024-09-17 à 17 31 14](https://github.com/user-attachments/assets/4fa375fc-4596-459a-8b23-d62fc6cb5aaf)

**Server details:**
- Nextcloud version: [Nextcloud Hub 8](https://nuage.pcfh.studio/) (29.0.5)
- Text app : 3.10.1

**Client details:**
 - OS: Mac 12.7.5
 - Firefox 130.0

Thanks for your help and this great piece of software ✨

**Comment by mejo-** [comment]
Dear @ImaCrea, thanks for your report. You mention Nextcloud version 29.0.5. Could you try to upgrade to the latest Nextcloud 29 release (29.0.7) and see whether the problem is still reproducible there?

**Comment by pablos891** [comment]
Hello, 
I've experinced the same issue, but after upgrading from 29.0.5 to 29.0.6 it starts working properly.

**Comment by ImaCrea** [comment]
Updated to 29.0.7 and not encountering this bug indeed. Thanks @mejo- !
