### ISSUE TITLE
Expose debugging information as global variables

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/text#6432]
This came up during the contributor week that it would be great to expose certain state of the text app as global variables in `OCA.Text` so we can inspect the yjs, document and sync state in case of issues.

@max-nextcloud Could you look into this so ideally we have something for the next release and can investigate further for the issues that are still there?

**Comment by juliushaertl** [comment]
I'd imagine we have some `OCA.Text.getDebugOutput()` to export as much as possible so we can just ask people with issues to run this one thing.

**Comment by juliusknorr** [comment]
Fixed by https://github.com/nextcloud/text/pull/6598
