### ISSUE TITLE
Comments on block elements

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#6478]
# Summary

![grafik](https://github.com/user-attachments/assets/257613b3-939b-44ca-be45-32746f58ba0b)
*Initial sketch with available comments indicated in text and a button to create a new comment on the current active section.*

Allow comments on block elements (paragraphs, headings, quotes, ...):
* Allow create comments.
* Display existing comments.
* Allow removing ones own comments.

# Motivation

Comments are useful in many situation. They allow adding information that directly relates to parts of the document without adding it directly to the document content.

Comments can be particularly helpful when drafting documents and during a review process.

Comments on block elements attach the comment to the relevant section on the document
while avoiding the complexity of in line comments such as overlapping comment ranges.

# Specification

Comments can be added to all block elements:
 * Paragraphs
 * Headings
 * Quotes
 * Callouts
 * Code blocks
 * Images
 * Link Previews
 * Tables
 * all types of Lists

# Alternatives

## Inline comments

This draft mainly came out of the discussion of in line comments in #185. 
In line comments allow commenting on a precise range of text, which is hard to represent in markdown.

## Footnotes

While footnotes could also be used to represent comments, they serve a different purpose.
#2142 discusses footnotes.

# User Interface Elements

* Button to add a comment to a block element
* Indicator that there are comments on an element
* List of comments on an element
* Button to remove ones own comment

# Implementation

* Comments will be serialized in markdown.
* They will be implemented using the standard way in text:
  * Markdown-it extension parses them to html.
  * Tiptap nodes represent them in the editor.
  * `toMarkdown` function to serialize them.
* Comments can contain multiple block nodes themselves.
 
# Out of scope for now (but maybe future)

* Edit my own comments.
* Reply to other comments.
* Suggest changes.
* Integrate with nextcloud comments system.
* Integrate with document chat (talk).
* Notify about comments.

**Comment by jancborchardt** [comment]
Looks super neat @nimishavijay! :) I think the comment indicator with avatar is very nice – also because even though the line is highlighted, if that’s the only indicator it’s not really clear it’s because of a comment. It could also just be formatting (of course not possible via Markdown but people don’t know that. :)

**Comment by juliusknorr** [comment]
Moved to https://github.com/nextcloud/text/issues/185
