### ISSUE TITLE
Fix failing cypress tests

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#6512]
### Assistent

needs assistent app locally and testing app enabled.

### Versioning

Looks like this might be a legit failure due to server changes.

**Comment by juliushaertl** [comment]
Versioning is a viewer/files bug: https://github.com/nextcloud/viewer/pull/2584

**Comment by juliushaertl** [comment]
Assistant one was a quick fix https://github.com/nextcloud/text/pull/6516
