### ISSUE TITLE
Do not auto-assign random vegetable names to guests

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/text#652]
It seems to have been plotted conjointly to auto-assign veggie names to guest editors (https://github.com/nextcloud/text/issues/52), but from an enterprise-grade software perspective, this is silly. Who wants to share a protocol with their bosses who eventually appear then as _Chinese Broccoli_ and _Spinach_?

Please take a minute to consider rolling back to the input field.

**Comment by juliushaertl** [comment]
cc @jancborchardt 

We basically have two options then, either we don't show the editor at all until the user has entered a name (this is how it is currently done with Collabora) or we just use something like "Anonymous user" as the default guest name.

**Comment by wiswedel** [comment]
+1 for enforced name entering:
1. It's usual across the web
2. you can still enter a pseudonym
3. Self-renaming of auto-anonymous-users is very likely to not happen in real-life

**Comment by kesselb** [comment]
Seems to be enterprise-grade enough for Google: https://support.google.com/docs/answer/2494888

**Comment by jancborchardt** [comment]
Yes – as @kesselb said Google does just the same, except with animal names.

Forced name entering doesn’t seem like much, but it’s an annoying hurdle when you just want to get editing. We literally had this before and it was bad: https://github.com/nextcloud/text/issues/52

Yes we can show the name input field more presently, but let’s not _require_ it. People just want to edit documents, not fill their names (or come up with pseudonyms).

**Comment by juliushaertl** [comment]
It might help a bit that google prefixes the animal names with "Anonymous". I also can imagine that a lot of people can easier get what animal names are about as they might apply some personification to those which is harder for vegetables. :wink:

**Comment by schiessle** [comment]
> +1 for enforced name entering:
> 
>     1. It's usual across the web
> 
>     2. you can still enter a pseudonym
> 
>     3. Self-renaming of auto-anonymous-users is very likely to not happen in real-life

FWIW, I agree with @wiswedel.

Looking at the initial issue which lead to the vegetable names I think there can be some middle ground.

1. If it is a read-only document we should skip the input field, as @jancborchardt said in one of the other issues, this classifies clearly as a bug.
2. It would be fine for me if the input field would be pre-filled with a fantasy name, so people who don't want to share their real name and don't want to be creative can just press enter.

I think this way we could solve both issues. I think asking more directly for a name is really important, because I strongly agree with point 3 of Sascha " Self-renaming of auto-anonymous-users is very likely to not happen in real-life". We see the same with Talk where guests most of the time don't care to set a useful name (completely off-topic, but there I would also love it if we would explicitly ask guests for a name before they join a room).

**Comment by wiswedel** [comment]
Cross-effect: Talk re-uses names from the browser storage if available (info via @nickvergessen).

Here's a scenario:

1. Get invited to a call
2. Get provided with a link to the meeting agenda/protocol
3. Have a look into that agenda first (opens in Text)
4. You get assigned a veggie name
5. You never find out about it because a) you don't get pointed at it in Text, b) you weren't asked if you care, c) you don't care
6. You join the Talk meeting and find yourself auto-renamed to something like _Chinese Broccoli_

I like the concept of sharing that stored name between the apps, but then the user should be completely in control about that display name of theirs.

**Comment by juliushaertl** [comment]
As discussed we'll we renaming anonymous users to "Anonymous guest" by default and give them a color to differentiate.

**Comment by wiswedel** [comment]
Just for the record, the above mentioned cross effect with Talk (https://github.com/nextcloud/text/issues/652#issuecomment-765562279) will then lead to a double-guest-naming:

![image](https://user-images.githubusercontent.com/1804221/105704855-b3c34880-5f0f-11eb-9b45-78a8d4531925.png)

**Comment by juliushaertl** [comment]
Ah thanks for the pointer, then it would probably make sense to rather call it "Anonymous" by default (@nickvergessen maybe also in talk) and add the guest part dynamically, as seeing that someone is a guest also makes sense if someone has a name set.

**Comment by nickvergessen** [comment]
In Talk they are called "Guests" as "Anonymous" is too good to translate and people could get scared when they think a hacker group just joined their call: https://en.wikipedia.org/wiki/Anonymous_(group)

![Bildschirmfoto von 2021-01-25 17-09-28](https://user-images.githubusercontent.com/213943/105731994-4d025700-5f30-11eb-9d3e-12b8e1c8969c.png)

1. Guest without a name
2. A guest with name "Guest with name"
