### ISSUE TITLE
Toolbar overlaid and not usable on small screens

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/text#6558]
**Describe the bug**

In Nextcloud 30, on small screens the toolbar is overlaid by the file header view, and thus not usable.

**To Reproduce**

1. Log in to Nextcloud in a mobile browser, e.g. Fennec
2. Open any .md file with Text

**Expected behavior**

The toolbar should be visible and usable.

**Screenshots**

<img src=https://github.com/user-attachments/assets/3584263a-1235-4792-bf68-c70817288161 width=300>

**Server details:**
- Nextcloud version: 30.0.1
- PHP Version: 8.2
- Database: MariaDB 10.11

**Client details:**
 - OS: Android 14 / LineageOS 21
 - Browser: Fennec F-Droid
 - Browser version: 129.0.2
 - Device: OnePlus 5

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
N/a
```

#### Browser log
```
n/a
```

</details>

**Comment by mejo-** [comment]
Thanks @thgoebel. This is already reported here: https://github.com/nextcloud/viewer/issues/2435. Would you mind adding a comment along with your screenshot over there?
