### ISSUE TITLE
No "move cursor one line upwards" possible after cutting out a line

### ISSUE THREAD

**Issue by ckoegler** [nextcloud/text#6568]
**Describe the bug**
After cutting out a line into the clipboard, its not possible to move one line upward using the Upward-arrow key immediately.

**To Reproduce**
1. Mark line e.g. with Pos1 key - Shift+End key
2. Cut out line into clipboard with Ctrl+X
3. Hit Arrow-up key

**Expected behavior**
cursor moves up one line

**Actual behavior**
cursor does not move

**Workaround**
Hit Arrow-down key and then twice Arrow-up or jump cursor with mouse click

**Screenshots**
-

**Server details:**
(hosted by Hetzner)
- Notes app version:  4.11.0
- Nextcloud version: 29.0.5 - 29.0.5.1
- OS server : Linux 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64
- Web server: nginx/1.25.3 (fpm-fcgi)
- PHP version: 8.2.22
- Database: mysql 10.5.26

**Client details:**
- OS: Win11 Home / 23H2
- Browser: Firefox 131.0.3

#### Nextcloud log (data/nextcloud.log)
Cannot access, as NC is hosted by Hetzner.

#### Browser log
-

**Comment by XueSheng-GIT** [comment]
I can reproduce on NC29.0.7. But not on NC30.0.1.
Maybe it's also fixed on NC29.0.8!?

**Comment by mejo-** [comment]
Thanks for your reports. This issue got fixed in the meantime, please update to Nextcloud 29.0.8.
