### ISSUE TITLE
Regression Mermaid diagramm text is not displayed

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/text#6572]
**Describe the bug**
![Image](https://github.com/user-attachments/assets/3dcd4850-2f66-4aa8-b537-92d120245f19)

**To Reproduce**
1. Have a mermaid diagram

**Expected behavior**
Text should be displayed

**Screenshots**

**Server details:**
- Nextcloud version: 30.0.1
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Aveyron-RetD** [comment]
Tried changing the mermaid theme but this does not work

**Comment by Aveyron-RetD** [comment]
here the code from the https://mermaid.js.org/config/theming.html to test

![Image](https://github.com/user-attachments/assets/ccb4212f-d4ef-4703-a05a-ad91a4d29986)

**Comment by mejo-** [comment]
Thanks for your report @Aveyron-RetD. I was able to reproduce on 30.0.1. Good thing is that this already got fixed - it's no longer reproducible on the stable30 development branch. So the release next week should fix this.
