### ISSUE TITLE
Inserted Images too small, not visible on mobile

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/text#662]
**Describe the bug**
Inserted images are getting resized...makes them nearly not visible
On mobile device the image isn't displayed, only a placeholder visible with "view image".
If you tab on it you get logged out.

**To Reproduce**
1. Create a text file
2. Insert image

**Expected behavior**
The image should keep it's size

**Screenshots**
![Bildschirmfoto_2020-02-07_14-57-26](https://user-images.githubusercontent.com/12480617/74035263-4181ed00-49ba-11ea-9f61-ddea95829c91.png)

**Client details:**
 - OS: [Linux Mint, arch, android 7.1.2]
 - Browser: [e.g. chrome, firefox]
 - Version: [recent]
 - Device: [desktop, mobile]

**Comment by eriteric** [comment]
It should be full width/size by default. That fits the majority of use cases.

For people looking for a workaround, you can right click the image and in your native browser context menu click on "open image in new tab". You can at least view it full size this way.

**Comment by eitzenbe** [comment]
This renders image insertion useless as the images are to small to recognize anything in them.

**Comment by rwagnon** [comment]
I agree.  Images are pretty much broken.

Interestingly, if I use the editor to make a markdown for a document folder, images work fine.  However, they don't work in a Text (.md) file.

**Comment by HappyClint** [comment]
I have the same problem,I used this plugin frequently and very like it.Wish the problem can be solved in next version.

**Comment by cenix102** [comment]
Hi everyone, I have a similar problem: #799 I also opened a issue. 
Did anyone find a good solution? (open in a new Tab is not a workaround for me.)
