### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/text#6649]
**Describe the bug**

For some reason the git repository of this app is massive.

![Image](https://github.com/user-attachments/assets/928c7333-cd38-4093-b39c-ef2a339f9e28)

**To Reproduce**
1. Clone the repo

**Expected behavior**

A .git directory much smaller

**Screenshots**

**Server details:**
- Nextcloud version: [e.g. 26.0.1]
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliusknorr** [comment]
That is all due to committed js assets (ours are large as we ship syntax highlight and mermaid diagram rendering libraries - not much we can do unless the release process changes

**Comment by juliusknorr** [comment]
Server is also 5.8GB these days 🙈

**Comment by juliusknorr** [comment]
Will raise this topic again, last time there were some ideas to move to different approaches but no actions taken

**Comment by juliusknorr** [comment]
Discussed with Andy last week, currently no further plans to change.
