### ISSUE TITLE
copy list -> clipboard contains broken markdown

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/text#6708]
**To Reproduce**
1. copy text including a unordered list from NC Text
2. insert into NC Mail
3. formatting is not preserved

**Expected behavior**
Formatting, e.g. lists should be preserved.

**Server details:**
- Nextcloud version: 30.0.2
- this is on c.nc.com. cannot check app version

**Client details:**
independent of client

**Details**
Original issue: https://github.com/nextcloud/mail/issues/9858
turns out that the problem is not in Mail, but in Text, as explained here https://github.com/nextcloud/mail/issues/9858#issuecomment-2499913979

**Comment by juliusknorr** [comment]
When inspecting the clipboard https://evercoder.github.io/clipboard-inspector/ with we properly pass in the markdown and html content including lists. Also testing https://ckeditor.com/ckeditor-5/demo/feature-rich/ it seems to work

**Comment by juliusknorr** [comment]
I expect this to be rather an issue in mail.

**Comment by juliusknorr** [comment]
Yep, let's close this for now. I'll subscribe to the mail issue also to see if there is anything needed from the text side.
