### ISSUE TITLE
Drag an drop of text

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/text#6724]
**Describe the bug**
When I drag and drop text, the background becomes gray. I don't see a reason for that, and it does not turn white again, till reload.

Further more the "#" of headlines is draggable. Same bug, the background becomes gray. 

**To Reproduce**
1. open any .md
2. mark text 
3. drag and drop

**Expected behavior**
drop the text, leave the background untouched

**Server details:**
- Nextcloud version: 29.0.8

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 132
 - Device: desktop

**Comment by mejo-** [comment]
Thanks for the report @Solar-Simon. I was able to reproduce, fix is in progress.
