### ISSUE TITLE
Spaces in file path make TextApp hangs

### ISSUE THREAD

**Issue by RTrave** [nextcloud/text#673]
If there is a space in filename or path folders name, we get the launch screen: black semi-tranparent, with only the 2 buttons right top, and the loading spin running.
No logs event, even in apache.

**To Reproduce**
1. Go to Files
2. Get a folder or a file containing spaces
3. If it's a folder without spaces, create a new text file containing space

**Expected behavior**
Text application must show the editor with file.

**Client details:**
 - OS: linux/debian
 - Browser: firefox
 - Version: 72.0.2
 - Device: linux & win10

<details>
<summary>Server details</summary>

**Text app version:** 2.0.0

**Operating system:** debian 9.11

**Web server:** apache 2.4.25

**Database:** mariadb 10.1.41

**PHP version:** php 7.3.12

**Nextcloud version:** 18.0.1rc1

</details>

**Comment by RTrave** [comment]
Just found this error in firefox dev bar:

> Error: "Request failed with status code 404"  in Viewer.vue:379
>     exports createError.js:16
>     exports settle.js:17
>     onreadystatechange xhr.js:61
> Viewer.vue:379
>     t Viewer.vue:379
>     c talk-files-sidebar.js:658
>     _invoke talk-files-sidebar.js:658
>     t talk-files-sidebar.js:658
>     q viewer.js:355
>     s viewer.js:355

**Comment by juliushaertl** [comment]
See https://github.com/nextcloud/viewer/issues/388
