### ISSUE TITLE
Editor takes only lower half of window for external users

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/text#674]
**Describe the bug**
When opening a markdown file in the text editor as external user (through a shared link), the editor takes only the lower half of the browser window. The editor is almost unsuable that way and I would say it's a rather weird user experience.

**To Reproduce**
1. Create a folder, share it with external users via link
2. Create a markdown file in this shared folder
3. Open the share link without being authenticated to Nextcloud
4. Open the markdown file from the shared folder
5. See the editor being opened only in the lower half of window

**Expected behavior**
The editor should take the full browser window just like it does for internal users.

**Screenshots**
![Nextcloud_Text_External_User](https://user-images.githubusercontent.com/25278864/74328421-21717580-4d8e-11ea-9688-102f299d1f2d.png)

**Client details:**
 - OS: Debian Buster
 - Browser: Firefox
 - Version: 72.0.2
 - Device: Desktop

<details>
<summary>Server details</summary>
**Text app version:** 2.0.0

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.11-1~deb10u1

**Nextcloud version:** 18.0.0.10
</details>

**Comment by novadeviator** [comment]
same situation here.

nextcloud 18.0.0 (Stable channel) on Ubuntu
Notes app 2.0.0

client: Firefox 72.0.2 or Chromium 79 on Ubuntu.

**Comment by Ecphrasis** [comment]
This bug has already been fixed, you can upgrade to 18.0.1 RC2, or you can wait the official release of 18.0.1 (I think it's tomorrow) ;)

**Comment by doobry-systemli** [comment]
Indeed, it's fixed in 18.0.1. Thanks a lot for the quick fix!
