### ISSUE TITLE
Option to insert images missing on nextcloud-android

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/text#675]
**Describe the bug**
In nextcloud-text there is an option to insert images
This option seems to be only available on nextcloud-server.
Option missing in nextcloud-android.
Seems to be the reason why inserted images are not visible on mobile #662

**Comment by julien-nc** [comment]
Is this still an issue nowadays?
Is the issue about not being able to insert images or not seeing them?

Feel free to reopen the issue if you answer :grin:.

**Comment by juliushaertl** [comment]
Still an issue but tracked in https://github.com/nextcloud/text/issues/1170 already
