### ISSUE TITLE
Error "GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.1" 404"

### ISSUE THREAD

**Issue by LHollyfeld** [nextcloud/text#676]
**Describe the bug**
In the apache2/access.log many errors:
GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.1" 404

**To Reproduce**
1. Go to Files (Datei) or a Filefolder
2. See error in apache2/access.log

**Client details:**
 - OS: WIN10 / IOS
 - Browser: Firefox, Edge, safari]
 - Version: Last
 - Device: iPhone8, desktop

**Web server:** apache2

**Database:**mysql

**PHP version:** 7.2.24

**Nextcloud version:** 18.0.1

**Comment by decole** [comment]
problems at the first visit to the page after authorization. the first window is just a blue screen, inside the HTML code, the browser hopes to find the video file

<video data-v-5283ac1f="" playsinline="" autoplay="autoplay" muted="muted"><source data-v-5283ac1f="" src="/apps/firstrunwizard/img/Nextcloud.webm" type="video/webm"> <source data-v-5283ac1f="" src="/apps/firstrunwizard/img/Nextcloud.mp4" type="video/mp4"></video>

**Comment by decole** [comment]
`<video data-v-5283ac1f="" playsinline="" autoplay="autoplay" muted="muted"><source data-v-5283ac1f="" src="/apps/firstrunwizard/img/Nextcloud.webm" type="video/webm"> <source data-v-5283ac1f="" src="/apps/firstrunwizard/img/Nextcloud.mp4" type="video/mp4"></video>`

**Comment by juliushaertl** [comment]
> GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.1" 404

The 404 is expected here, as when you don't have a rich workspace (README.md) file in your directory we return a 404 to tell that to the frontend.

**Comment by juliushaertl** [comment]
@decole This is not related at all to this issue, so please try to find an appropriate place next time. For this one check your webserver configuration if mp4 and webm can actually be served from the filesystem.

**Comment by HugoPresents** [comment]
or you can disable the "Text" app to avoid see that request

**Comment by jjasoncool** [comment]
> > GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.1" 404
> 
> The 404 is expected here, as when you don't have a rich workspace (README.md) file in your directory we return a 404 to tell that to the frontend.

Thank you.
