### ISSUE TITLE
New Element: link preview or bookmark

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/text#683]
It would be nice, if there is a preview of an inserted link

Current solution:
![grafik](https://user-images.githubusercontent.com/24530680/74832468-a6710780-5317-11ea-8727-ecaa54e3799f.png)

Possible idea:
![grafik](https://user-images.githubusercontent.com/24530680/74832483-b4bf2380-5317-11ea-8929-2fb8b9f430cb.png)

**Comment by juliushaertl** [comment]
I don't think we should have this as a redered replacement for the actual text, since links can also be inline in paragraphs, but we could consider showing a popover with the additional information.

**Comment by jakobroehrl** [comment]
@juliushaertl Is this hard to do? Maybe I could do it myself?

**Comment by julien-nc** [comment]
Good news: This has been implemented in Nextcloud 25 (https://github.com/nextcloud/text/pull/2977). This feature also works in Talk.
