### ISSUE TITLE
LaTeX in app

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/text#684]
Hi all,
My co-workers (maths teachers) would love to use Latex in the text app. There is an app for that, https://apps.nextcloud.com/apps/files_markdown, but she doesn't work any more since 18 version. Is it possible to have an official support for this ? Would be so great ! Thanks !

**Comment by pauleve** [comment]
I'm really interested in this feature. It looks like katex https://katex.org is the right JS lib to do that (as used by the files_markdown app if I'm not mistaken).
Is there any ongoing work for it? I'm considering an attempt of PR otherwise..

**Comment by julien-nc** [comment]
We are not working on such a feature. Feel free to reopen if you want to describe how this could work with katex so you or someone else can start a PR.

**Comment by meonkeys** [comment]
see #7957
