### ISSUE TITLE
No version for nextcloud 18 available in app store

### ISSUE THREAD

**Issue by azul** [nextcloud/text#696]
**Describe the bug**
There seems to be no version available for nextcloud 18.
The app store says 
> Diese App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
> Server version 17 or lower is required.

https://apps.nextcloud.com/apps/text also does not list a version for nc 18.

I can still install the app despite the warning but the workspace functionality is missing so i assume i am using an outdated version.

**To Reproduce**
1. Setup nextcloud-docker-dev
2. Login as admin
3. Visit apps page
4. Go to "Büro / Text"
5. Find "Text" app.
6. click on "Ungetestete App aktivieren" 
7. now it says "Herunterladen und aktivieren" ... click that.
8. Go to files,
9. Create "Readme.md" via :heavy_plus_sign: .
10. No workspace.

**Expected behavior**
in 6. i would expect to read "Herunterladen und aktivieren" like for the other apps.
in 9. I would expect to see a line that allows me to add a workspace Readme.md.
in 10. I would expect to see a workspace with the first lines of my Readme.md.

**Client details:**
 - OS: linux ubuntu 18.04
 - Browser: firefox
 - Version: 73.0.1 (64-Bit)
 - Device: thinkpad x230

**Comment by azul** [comment]
Cloning the app from github to the `apps` dir directly worked. Not sure if this is expected to be the only way.

Other apps could be installed throught the app store - so it feels strange to require the clone. But i also do not understand what dev setup is expected and how this behaves in production.

Feel free to close if i'm just confused.

**Comment by reswild** [comment]
I guess you don't see a version for Nextcloud 18 in the app store because this app is now distributed as a part of Nextcloud core, and you don't need to install it separately.

**Comment by juliushaertl** [comment]
Yep, was @reswild said:

> I guess you don't see a version for Nextcloud 18 in the app store because this app is now distributed as a part of Nextcloud core, and you don't need to install it separately.
