### ISSUE TITLE
Support plantuml

### ISSUE THREAD

**Issue by ccy** [nextcloud/text#705]
Many offline or online markdown editor support [plantuml ](https://plantuml.com/).  May consider adding the feature to this editor.

**Comment by juliushaertl** [comment]
Could you share some more details on how that is represented in markdown then?

An issue I see with the plantuml part is that it is Java and their Javascript integration uses their own servers for generating the images. Maybe mermaid chard support as described in #163 would also cover your use case there?

**Comment by hashworks** [comment]
In GitLab it's implemented like this:

The PlantUML Code is wrapped in Backticks like Code Blocks:
```
@startuml
C --> B: WorkDone
destroy C

B --> A: RequestCreated
deactivate B

A -> User: Done
deactivate A
@enduml
```

GitLab looks for `@startuml` and sends the Code Block to a PlantUML Server one has to configure - this can be a self hosted PlantUML instance or the public server. 

According to the [doc](https://plantuml.com/de/text-encoding) the code is deflated, basically encoded with base64 and attached to URL like this:

Http://www.plantuml.com/plantuml/png/SrRGrRLJSB9I2CylodR9pqlbIaajBYdAhrHmvk9o0aiwMYa4fHQM0eMTYr8JIr9JW4eIaqioou1i1ISkBaS5eABGujGYAmM80GXPHou0

Here is a PHP example: https://plantuml.com/de/code-php

I see no need for NextCloud to implement the PlantUML image generator, a configureable server would do just fine.

**Comment by voicevon** [comment]
You can install app draw.io , then refrence this link https://drawio-app.com/use-plantuml-in-draw-io/ , Wow , You got plantUML in nextcloud :)
