### ISSUE TITLE
Readme.md file editing in the header error - layout problems

### ISSUE THREAD

**Issue by rogercreagh** [nextcloud/text#707]
**Describe the bug**
Not sure if this is a Text problem or a Nextcloud problem.
A Readme.md file contents in a folder gets displayed in the header area above the files list and below the breadcrumbs.
Several issues:
1. There is a lot of whitespace between the breadcrumbs and the displayed text from the file. When you click on the file the Text toolbar appears here for editing. It is set to autohide when the text edit area is not focussed but it is just making it invisible rather than properly hiding it. (display:none;)
2. There seems to be a lot of confusion between the nest of divs about what heights are set and whether overflow scrollbars appear. Heights of 30vh and 50vh are both set on different divs. When you click on the text the height of the textarea changes causing the display below to jump around. Sometimes this means that if the user then clicks away to a file below the wrong file seems to get selected.
It would be better by far if the whole area was a fixed max-height so that the display below didn't jump around
3. The vertical scrollbar if the text overflows only appears when editing. This should also be present if the text is not being edited and the text is longer than the available space (max-height) so that the user can scroll to see more (eg mouse wheel) without actually going into edit mode.
4. Whilst the ability to edit the readme text in the place where it is displayed might seem nice it causes problems, particularly in shared folders and group folders, where naive users can inadvertently click on the text and edit it by mistake. A good feature would be the ability to disable this in-place editing option - either globally, or per group (eg Admins only). If it were disabled you can still edit the text by clicking on the file anyway (which seems more logical - there is no other part of the interface where clicking on text allows you to edit it
5. To ameliorate issue 4 perhaps putting a colour wash background on the display area would help to make it clear that it was something different. 
**To Reproduce**
Create a Readme.md in  folder and click on the text in the header area.

**Expected behavior**
A clear cue that the text is editable if clicked on
The ability to have a setting to disable in-place editing
No wasted white space above or below the display area
Consistent height to the text area whatever the mode (without overwriting the recommendations area on the home AllFiles page)(whether absolute or viewport percentages)
Scroll bars appearing if text from file is overflowing the available space whatever the mode.

**Client details:**
 - OS: [e.g. iOS] OSx
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22] latest stable
 - Device: [e.g. iPhone6, desktop] macbook

<details>
<summary>Server details</summary>

**Text app version:** (see Nextcloud apps page)

**Operating system:**
Linux Debian
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18.0.1
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by julien-nc** [comment]
Some of the issues described here are now solved in my opinion like the scrollbar now appears even when not editing.

@nextcloud/designers Any opinion on those recommendations?

**Comment by mejo-** [comment]
In my opinion this issue should either be closed or split into separate issues. While it's a nice feedback about the rich workspace UI, the feedback is pretty old by now, some raised issues got addressed already and rich workspaces is undergoing some redesign anyway (see #3209).

**Comment by rogercreagh** [comment]
Yes it is very old, I think we were on v18 when I raised it, and as you say it should be broken into separate issues. I'm not currently actively involved in a NC site so I'm not sure what is still relevant. #3209 will certainly help with the main annoyance. I'll close this one for now.

**Comment by mejo-** [comment]
Thanks a lot for your response @rogercreagh :heart:
