### ISSUE TITLE
Internal link opens the folder instead of the editor

### ISSUE THREAD

**Issue by biva** [nextcloud/text#715]
When I open an internal link to **notes.md**, the folder containing the file is opened: I have to click on the file to open the editor.

When I share a public link to this same file, it opens directly the editor. Is it a bug or a feature?

I'd like that when I open an internal link, it opens the editor directly.

**Config:**
NC 18
Firefox 74 (also tested on Chrome: same behaviour)

**Comment by almereyda** [comment]
Taking the way how we *write* Markdown within *text*, yet get rich text in the editor, internal links could be easily produced with Wiki notation `[[Title of the page]]` and transparently transformed into the internal Markdown notation '[Title of the page](title-of-the-page.md)', et voilà! we'd have a real-time wiki with indirect offline support (through the Nextcloud synchronisation clients - not speaking of Service Workers).

**Comment by juliushaertl** [comment]
This is something that the server or to be exactly the viewer app needs to handle. There is ongoing progress by @azul in https://github.com/nextcloud/server/issues/12470
