### ISSUE TITLE
From a shared folder the workspace (readme.md) is not displayed.

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/text#716]
### Problem
The new "workspace" (readme.md) will not be displayed for all users who only receive a public link and are not logged in.

### Steps to reproduce
1. Create folder with subfolders.
2. Fill the upper workspace for the folders with text.
3. Create a public link for the folder.
4. After the public link has been opened: You will see the file "Readme.md" but not automatically the content above the files/folders as it should be.

Note: The "rich workspace" in the settings is activated!
Note2: Tested with different browsers (Safari, Firefox, Chrome) on different systems (iOS, Mac, Win, Android) 

### Expected behaviour
Displayed the readme.md content above the files/folders as it should be – even if you are not logged in.

### Actual behaviour
The content of the readme.md is not displayed when you get a public link.

### Server configuration

**Nextcloud version:**
18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

http://example.com/index.php/settings/integrity/failed :
```
No errors have been found.
```

**Comment by the-matzup** [comment]
@juliushaertl 
Is it possible to include the bugfix in the next minor release? As a school we are currently using our Nextcloud intensively, while we suddenly have to teach all students from home during Corona time. The messages about the folders are very practical and would help us - if they work. 
(We work with the link shares because we are not allowed by law to create 1000 student accounts on foreign servers).

**Comment by jospoortvliet** [comment]
@the-matzup re: "foreign servers" -> you don't host in your own country? Finding a service provider that hosts locally should be doable with Nextcloud! In Germany/Europe there's IONOS for example.

**Comment by juliushaertl** [comment]
Once there is a fix for this, we will probably consider backporting it to 18 but no ETA yet.

**Comment by the-matzup** [comment]
@jospoortvliet 
We host in our country (Germany) and I know what IONOS offers. However, it is complicated for schools and the statements of our data protection supervisors are not consistent.

@juliushaertl  
I just saw in the weblog that in one week more than 58'000 incorrect accesses to the path "/ocs/v2.php/apps/text/public/workspace" have accumulated. And over 6'000 to the path "/ocs/v2.php/apps/text/workspace". 
This looks to me like it is related to the problem. Maybe the information will help.

**Comment by jospoortvliet** [comment]
> We host in our country (Germany) and I know what IONOS offers. However, it is complicated for schools and the statements of our data protection supervisors are not consistent

Yes, hosting on your own servers is best. Tnx for the debugging info, but please consider getting a proper support contract so we can provide you help in a more reasonable time!

**Comment by the-matzup** [comment]
(OT)

@jospoortvliet 
I do not intend to take advantage of your work and I do not expect anyone to work for free. Actually, I was just pointing out a bug. My asking if the fix is in the minor release should not be a pressure and this should not be interpreted as a demand. I thought it would be helpful to explain the background a bit. 

Anyway: By which way I can give you and your Nextcloud team an order, for example if we would like to have a plugin or a feature for our school. (This is currently not possible at Corona time, because the hiaric organization of our school system has no meetings right now, but for the future). And what are the "massive discounts for the education market"? If I know more about it, I can better argue for the decision makers.

**Comment by juliushaertl** [comment]
Fixed with #714
