### ISSUE TITLE
Dark mode editing for Android client

### ISSUE THREAD

**Issue by moviuro** [nextcloud/text#728]
**Is your feature request related to a problem? Please describe.**
The editor on the Android app defaults to using black text on white background even if the theme is dark. See https://sco.popho.be/s/Z2ANg6m22jTaRfX (link valid for 1 month); and initial discussion https://github.com/nextcloud/android/issues/5353#issuecomment-602581995

**Describe the solution you'd like**
The editor should use a dark theme. The one in use in the default view of markdown files could be very good (see https://sco.popho.be/s/PtDPt7d7E7ojEQt)

**Describe alternatives you've considered**
N/A

**Additional context**
Android client 3.11.0RC4, Nextcloud 18.0.2 on FreeBSD

**Comment by juliushaertl** [comment]
This is actually something that we should implement in the server with https://github.com/nextcloud/server/issues/12276, so once the server is able to pick up the dark mode automatically depending on the prefers-color-scheme text will support it without any further change.
