### ISSUE TITLE
Trouble opening XML files in web browser after upgrade to release 18

### ISSUE THREAD

**Issue by aleskomarek** [nextcloud/text#730]
Hello.

After upgrade NextCloud to release 18 we have trouble opening XML in webbrowser (tested in Firefox, GoogleChrome, IE in latest versions) in GUI of NextCloud file browser.
We can download XML files in web GUI or sync over NextCloud client without problems, but showing in GUI do nothing (circle rotating for evertime without showing any content of XML file).

Upgrading to 18.0.1, 18.0.2 or 18.0.3 does not solved this issue.
Tested on CentOs 7.7 with PHP 7.3.16 and also on Raspberry Pi 4B with latest release of Raspbian - same issue.
In version before 18 this was without problems.
No errors in webserver logfiles.

Thank You for Your response.
Best regards, Komarek.

**Comment by julien-nc** [comment]
Hi, I can't reproduce that with stable24, stable25 and master.

Feel free to reopen if this still happens to you.
