### ISSUE TITLE
ToDo list check boxes randomly vary in size

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/text#733]
**Describe the bug**
ToDo list check boxes randomly vary in size

**To Reproduce**
1. Create text doc
2. Add some ToDo items (UPDATE: including some items that are longer than one line)
3. Note they seem to randomly be different sizes
4. See screenshot

**Expected behavior**
I expect the check boxes to all be the same size

**Screenshots**
See attached.

**Client details:**
 - OS: Ubuntu 18.04
 - Browser: Firefox, Chromium
 - Version: latest
 - Device: Lenovo ThinkPad T510

Latest versions of Nextcloud and Text doc app.

![different_sized_checkboxes](https://user-images.githubusercontent.com/2113743/77766562-b7f4b000-7037-11ea-9e89-1e97e526810f.png)

**Comment by jdaviescoates** [comment]
Just to add, I've just noticed this only seems to happen when the todo item is longer than one line.

**Comment by juliushaertl** [comment]
Fixed with  #809
