### ISSUE TITLE
"Loading takes very long" on Android

### ISSUE THREAD

**Issue by Araly** [nextcloud/text#742]
**Describe the bug**
When I try to open a markdown file to edit, it loads forever and shows a message saying "Loading takes very long", with a message to go back.

**To Reproduce**
1. tap on a file to edit
2. wait
3. the message appears on the bottom

**Expected behavior**
some sort of editor appears

**Screenshots**
![Screenshot_20200329-230405_Nextcloud](https://user-images.githubusercontent.com/24990801/77862278-59cff480-7212-11ea-99c1-a6f998cfd83e.png)

**Client details:**
 - OS: Android
 - Browser: Android app
 - Version: 3.11.0 RC2
 - Device: Pocophone

**Comment by juliushaertl** [comment]
Are there any interesting things happening in your nextcloud or webserver access/error logs?

@tobiasKaminsky Do we have any way to debug this properly on the Android side?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Do we have any way to debug this properly on the Android side?

The only way might be to have a logcat running, or on RC/dev there are logs within settings.

**Comment by Araly** [comment]
[logs-2020-03-31-17-10-35.zip](https://github.com/nextcloud/text/files/4410248/logs-2020-03-31-17-10-35.zip)
Here are logs for "TextEditorWebView" but it doesn't seem very interesting

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Zkral** [comment]
Hi,

I had exactly the same issue. My Nextcloud setup was with a self-signed certificate directly on the IP address on the server (ie URL was https://192.168.x.y). Then I changed to use a domain name with a certificate from Let's Encrypt, and the issue disappeared right away (I simply removed and readded my account in the Android app to change the URL).

Note that I didn't change anything else, it is the same server and the same Nextcloud setup, I simply changed the overwrite.cli.url and trusted_domains variable in Nextcloud config file.

Hope this helps.

**Comment by lukket** [comment]
I had the same issue and can confirm that it's gone since I switched from a self-signed certificate to a certificate from Let's Encrypt. Thank you @Zkral for the "workaround".

**Comment by juliushaertl** [comment]
@tobiasKaminsky Could that be a case that is not catched in the android code part? I guess then the webview just fails to load and the postmessage never hits the app.

**Comment by tobiasKaminsky** [comment]
What case could it be?

**Comment by juliushaertl** [comment]
The webview not loading due to a self-signed certificate as written by https://github.com/nextcloud/text/issues/742#issuecomment-748188470

**Comment by matthijsbro** [comment]
Similarly, _some_ .md's don't load in Android for editing, others do. I tried removing links in them and copying them, but their copy also doesn't open for editing. They _can_ be viewed when chosen to store on the device. I have 'cpanel certificate'.

**Comment by tobiasKaminsky** [comment]
> The webview not loading due to a self-signed certificate as written by [#742 (comment)](https://github.com/nextcloud/text/issues/742#issuecomment-748188470)

I created a bug for this.

**Comment by matthijsbro** [comment]
self-signed... I have a cPanel-signed certificate and this problem occurs irregularly too.

**Comment by juliushaertl** [comment]
Ok, lets close this then in favor or https://github.com/nextcloud/android/issues/8322
