### ISSUE TITLE
txt file does not open

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#744]
**Describe the bug**
txt file does not open with community document server

**To Reproduce**
1. three dots on txt file
2. open in OO
3. see OO loading, but keeps hanging on "loading…"

**Expected behavior**
edit text

Ref: https://github.com/nextcloud/android/issues/5545

**Comment by wiswedel** [comment]
@tobiasKaminsky wrong repo? (OO <> Text)

**Comment by juliushaertl** [comment]
Should be fixed with https://github.com/nextcloud/text/pull/743/files

**Comment by juliushaertl** [comment]
Ah right, if this is about OO maybe open an issue at their repo.
