### ISSUE TITLE
Only one single txt-file opens once, afterwards time-out consistently

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/text#756]
This issue here is very similar to #744 but clearly is only related to .txt-files. Furthermore, there is a related [discussion on help.nextcloud.com](https://help.nextcloud.com/t/how-to-prevent-files-from-opening-without-downloading/73280/7) about the preview of .py-files.

### Steps to reproduce
1. De-activate Text
2. Re-activate Text
3. Go to Files
4. Click on a .txt-file
5. Check the preview is shown
6. Close preview window
7. Click on *another* .txt-file
8. Preview is not produced
9. Close preview window
10. Click on *first* .txt-file
11. Preview is not produced

### Expected behaviour
Preview of .txt-files should always show.

### Actual behaviour
Only the very first preview is shown

## Server configuration detail
**Operating system:** Ubuntu 18.04.4
**Webserver:** nginx/1.17.9 (fpm-fcgi)
**Database:** mysql 10.3.22

**PHP version:** 
7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, inotify, intl, json, exif, mysqli, OAuth, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.2
 - carnet: 0.20.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_inotify: 0.1.7
 - files_markdown: 2.2.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.4
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ownpad: 0.6.14
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 20.1.0
 - quota_warning: 1.7.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.7
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - unsplash: 1.1.5
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "lxcnextcloud.okunterhof5.ch",
        "lxcNextCloud",
        "nextcloud.url",
        "lxcnextcloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/lxcnextcloud.okunterhof5.ch",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "Europe\/Zurich",
    "loglevel": "2",
    "log_rotate_size": 10485760,
    "skeletondirectory": "",
    "share_folder": "\/Mit mir geteilt",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "force_language": "de",
    "trashbin_retention_obligation": "disabled",
    "versions_retention_obligation": "disabled",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "auth.bruteforce.protection.enabled": false,
    "maintenance": false,
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "theme": "",
    "app_install_overwrite": [
        "ownpad",
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Ubuntu 19.10

## Logs

<details><summary>Web server error log</summary>

```
No errors
```
</details>

<details><summary>Nextcloud log</summary>

```
No errors relative to this issue
```
</details>

<details><summary>Browser log</summary>

App Text deactivated:
no sign in conole

App Text activated, first .txt-file (successful), preview closed 14:28:20.000
14:27:53.851 Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/Documents/About.txt' }) viewer.js:377:761
14:27:53.853 Opening viewer for file  /Documents/About.txt viewer.js:355:3215
14:27:57.396 Fetching additional files... viewer.js:355:3779
14:28:01.523 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 2 main.js:1082:57
14:28:05.601 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
14:28:06.082 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3
Source-Map-Adresse: viewer.js.map
14:28:06.112 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/files_sharing/js/dist/files_sharing_tab.js?v=72123e2b-3
Source-Map-Adresse: files_sharing_tab.js.map
14:28:06.172 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/core/js/dist/main.js?v=72123e2b-3
Source-Map-Adresse: main.js.map
14:28:06.851 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/notifications/js/notifications.js?v=72123e2b-3
Source-Map-Adresse: notifications.js.map
14:28:07.190 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/files/js/dist/sidebar.js?v=72123e2b-3
Source-Map-Adresse: sidebar.js.map
14:28:07.284 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/groupfolders/build/3.js
Source-Map-Adresse: 3.js.map
14:28:07.601 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
14:28:09.601 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
14:28:15.602 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 2 main.js:1082:57
14:28:19.602 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
14:28:20.148 serialized document 
Object { file: "About Nextcloud\n\nWelcome to Nextcloud, your self-hosted file sync and share solution.\nNextcloud is the open source file sync and share software for everyone from individuals to large enterprises and service providers. Nextcloud provides a safe, secure and compliant file sync and share solution on servers you control.\nWith Nextcloud you can share one or more folders on your PC, and sync them with your Nextcloud server. Place files in your local shared directories, and those files are immediately synced to the server, and then to other PCs via the desktop client. Not near a desktop client? No problem, simply log in with the web client and manage your files there. The Android and iOS mobile apps allow you to browse, download and upload photos and videos.\nWhether using a mobile device, a workstation, or a web client, Nextcloud provides the ability to put the right files in the right hands at the right time on any device in one simple-to-use, secure, private and controlled solution.\n\n\nAll example pictures & music are licensed under Creative Commons Attribution." }
editor.js:108:4627
14:28:22.722 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.url/apps/text/js/editor.js?v=f37f6f59ed03e030d5f2
Source-Map-Adresse: editor.js.map?v=f37f6f59ed03e030d5f2

App Text activated, second .txt-file (fruitless), preview closed at 14:31:17.000:
14:31:02.899 Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/Documents/About.txt' }) viewer.js:377:761
14:31:02.900 Opening viewer for file  /Documents/About.txt viewer.js:355:3215
14:31:03.196 Fetching additional files... viewer.js:355:3779
14:31:04.032 TypeError: a.terminators is undefined vendors~editor~preview.js:32:66844
14:31:05.205 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
14:31:07.205 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 6 main.js:1082:57
14:31:17.906 TypeError: "this.editor is null"
    beforeDestroy https://nextcloud.url/apps/text/js/vendors~editor~preview.js?v=72b18a706c3726bc1ff0:7
    Gt https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    er https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    $destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    destroy https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    A https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    w https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    vi https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    _update https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    n https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    get https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    run https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    lr https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    ee https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
    Xt https://nextcloud.url/apps/viewer/js/viewer.js?v=72123e2b-3:14
viewer.js:14:11644

</details>

**Comment by luka-nextcloud** [comment]
When we click on a .txt file, the text app opens the file. Since it's not an md file, we can't access the actions bar.
@juliushaertl I think this is the right behavior right?

**Comment by sm8ps** [comment]
I cannot reproduce this issue on NC 24.0.7 anymore so I am closing it. Thanks for considering it though!

**Comment by juliushaertl** [comment]
Thanks for confirming that 👍
