### ISSUE TITLE
Hide rich workspace for talk folders

### ISSUE THREAD

**Issue by kesselb** [nextcloud/text#758]
**Describe the bug**

Might be related to #757.

**To Reproduce**

1. Be a guest user with access to talk
2. Join one or more rooms (not sure if that is relevant)
3. Ask a moderator to make you permanent in the room
4. I see shared folders for some rooms (for example "Lobby" for the Talk development chat)
5. Open "Lobby" in files app
6. Try to use rich workspace

**Expected behavior**

No rich workspace or a useable rich workspace.

**Screenshots**

![Peek 2020-04-06 17-02](https://user-images.githubusercontent.com/3902676/78573105-9a3dfc80-7828-11ea-9117-6d59973af3ae.gif)

**Comment by gary-kim** [comment]
Hehe, the true reason we were added was to find all the bugs with `guests`.

**Comment by kesselb** [comment]
That's what I was thinking. :rofl:

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore. For folders without write permission/quote the area is properly hidden. If the guest has write access, creating works fine as it would be expected, so I assume we fixed it somewhere in the meantime :D
