### ISSUE TITLE
Case-sensitivity causes sync issues on Windows clients

### ISSUE THREAD

**Issue by test-in-prod** [nextcloud/text#762]
**Describe the bug**
It seems that this app is causing sync issues with Windows nextcloud clients when server-side the app tries to create several files named "README.md", "readme.md", and "Readme.md".

![изображение](https://user-images.githubusercontent.com/1175100/79027073-bc44c100-7b3f-11ea-9871-e9b559800aa4.png)

The client then fails to sync further with error message (something like "file readme.md cannot be downloaded due to local naming conflict")

![изображение](https://user-images.githubusercontent.com/1175100/79027121-e6967e80-7b3f-11ea-9f26-e6ca6cab5a9f.png)

**To Reproduce**
1. On Windows 10 as client
2. On a Linux server as Nextcloud server with Text app enabled
3. [Nextcloud Web UI] Navigate to any directory in "Files"
4. [Nextcloud Web UI] Enter some text (e.g. "test") in to the field above file listing
5. [Nextcloud Web UI] Click outside of the field to save
6. Server-side it creates three files as listed in description
7. Client-side sync fails

**Expected behavior**
Only a single variation of a "readme.md" is created, or the app uses case-insensitive search for any pre-existing "readme.md" files

**Screenshots**
See attached above

**Client details:**
 - OS: Nextcloud Server: `Linux nextcloud-ng 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`; Client: `Windows 10 Build 1809 x64`
 - Browser: Firefox
 - Version: 74.0.1
 - Device: Windows Desktop
 - Nextcloud Sync app: 2.6.2stable-Win64 (build 20191224)

<details>
**Text app version:** 2.0

**Operating system:** Windows/Linux

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 18.0.3

</details>

------

Disabling the "Text" app for now resolves the sync issue. I don't use the app too much, but it does make things nice.

**Comment by juliushaertl** [comment]
Fix is in #834
