### ISSUE TITLE
How to edit code files (e.g., .py, .php, .html)

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/text#771]
I am trying to edit .py, .php, .html files with no success. I am running NC v18. I tried installing and enabling the Plain Text Editor (had to modify app.xml to have min version of 18 rather than 19). I also ahve the Text app and the Markdown Editor app. I cannot find any combination of these that works.

With the old “Plain Text Editor v2.11” app enabled and the Text app v2.0.0. disabled and Markdown Editor v.2.2.0 enabled), when I open one of these “code” files, I am getting the browser prompt asking what app to use (i.e. NC is not handling the file). So, with the new Text app, I get a wheel when trying to open code files and with the old Plain Text Editor, I get files being handed to the browser to open with a client app. Isn’t there a way to open these files in an editor in NC?

**Comment by astashov-andrey** [comment]
I confirm the problem with opening files.
On version 17, everything worked well. The extension "gradle" ("gradle": ["text / plain"]), "sql" and a few more are added to /config/mimetypemapping.json, a cache update through "occ" is done. But when you open gradle files through the web interface for editing, the editor window simply opens and the spinner spins. At the same time, on the "network" tab in the chrome console, you can see that the request "/apps/text/session/fetch" worked without errors and received the data. In the preview of the developer console, the data is visible. If you look at the "console" tab, you can see that at this moment there is such an error
```
Uncaught (in promise) TypeError: Cannot add property compiled, object is not extensible
    at e (core.js: 597)
    at core.js: 673
    at e (core.js: 647)
    at core.js: 589
    at S (core.js: 198)
    at i.x [as highlightAuto] (core.js: 82)
    at extensions.esm.js: 414
    at Array.forEach (<anonymous>)
    at Z (extensions.esm.js: 412)
    at _.init (extensions.esm.js: 440)

```
And after that, not a single file will open until you refresh the page.
Google chrome version: 80.0.3987.163 

Please tell me how you can fix it.
Thanks.
![bug](https://user-images.githubusercontent.com/54792374/79094639-fe594700-7d79-11ea-95de-20ce07169d4a.png)

**Comment by astashov-andrey** [comment]
I tried to update the viewer application (https://github.com/nextcloud/viewer) to version 1.3.0, it did not help. All the same, they do not open. The error is the same.

**Comment by 1ndeed** [comment]
Same issue.
I thought if I downgrade this and it will be fine. But I just tried nextcloud:17.0.5 and it didn't work. When I click the .py file, it just downloaded it. Did it use to work?
This thing hasn't been updated officially for 8 months. Why???

**Comment by ifuchs** [comment]
Well, I have had some success. I installed Plain Text Editor v2.10 and disabled Text app. I can now open and edit code files. My only problem with this is that the editor is using Ace and it is configured to add CR to each line. This is can be a problem on linux. I changed the config in Ace from "windows" to "auto" but either that doesn't work or it is not taking effect for some reason. So, the markdown editor is showing side-by-side view and code files are viewable/editable. Obviously it would be nice if this didn't require more effort than downloading and enabling in the web ui.

**Comment by 1ndeed** [comment]
> Well, I have had some success. I installed Plain Text Editor v2.10 and disabled Text app. I can now open and edit code files. My only problem with this is that the editor is using Ace and it is configured to add CR to each line. This is can be a problem on linux. I changed the config in Ace from "windows" to "auto" but either that doesn't work or it is not taking effect for some reason. So, the markdown editor is showing side-by-side view and code files are viewable/editable. Obviously it would be nice if this didn't require more effort than downloading and enabling in the web ui.

where did you download the `Plain Text Editor v2.10`? I can find it in the app store.

**Comment by ifuchs** [comment]
wget https://github.com/nextcloud/files_texteditor/archive/v18.0.0.tar.gz <https://github.com/nextcloud/files_texteditor/archive/v18.0.0.tar.gz>
tar -xzf v18.0.0.tar.gz
mv files_texteditor-18.0.0 files_texteditor
