### ISSUE TITLE
it doesn't work at all... ?

### ISSUE THREAD

**Issue by 1ndeed** [nextcloud/text#781]
I don't know if this is a bug or my problem. But when I click a .txt file it just download the file. Here's what I did:
```
mkdir backup
mv apps/text backup
cd custom_apps/
git clone 'https://github.com/nextcloud/text.git'
chown -Rh www-data:www-data text
```
Then I opened the nextcloud in my browser, made sure that text is enabled. Then I click a .txt file, it just got downloaded.

I even tried `make`, but it ended up with errors.
I also tried installing the viewer app, but nextcloud says it's not compatible.
nextcloud version: 18.0.3
Is this a bug?

**Comment by tcitworld** [comment]
Getting the app through git is for developers, and requires indeed prerequisites for the `make` command to run.
Why did you wanted to do that?

Also the viewer app was depreciated and is incompatible with Nextcloud 18 and above.

**Comment by 1ndeed** [comment]
> Getting the app through git is for developers, and requires indeed prerequisites for the `make` command to run.
> Why did you wanted to do that?
> 
> Also the viewer app was depreciated and is incompatible with Nextcloud 18 and above.

Then how can I, as a user, install it?
Through appstore? The version of text on appstore is only 1.0.2. And it doesn't support nextcloud 18. I can't even open a normal txt file with this.
...I am just so confused.

**Comment by tcitworld** [comment]
It should be bundled with any Nextcloud install starting from Nextcloud 17, you didn't have to install it manually.

**Comment by 1ndeed** [comment]
> It should be bundled with any Nextcloud install starting from Nextcloud 17, you didn't have to install it manually.

I understand, but a [bug](https://github.com/nextcloud/text/issues/771) has just been fixed, and I want to use the new version.

**Comment by tcitworld** [comment]
Either try to work your way out of the developer way or wait for the Nextcloud release.
Feel free to ask for support on https://help.nextcloud.com/
