### ISSUE TITLE
Excessive file update notifications

### ISSUE THREAD

**Issue by kostecke** [nextcloud/text#800]
**Describe the bug**

The text editor app auto-save behavior generates an update notification for **each** auto-save period during which a change is made to a file. This can result in an update notification e-mail containing upwards of twenty or more entries for the same file.

**To Reproduce**

1. Open a file in the text editor
2. Make a change
3. Wait for an auto-save
4. Make a change
5. Wait for an auto-save
6. repeat as desired ...
7. Wait to receive an update notification e-mail containing a long list of edits

**Expected behavior**

One update notification per file for each editing session during a notification period.

**Client details:**

n/a

<details>
<summary>Server details</summary>

**Text app version:** 2.7

**Operating system:** Debian 9.12

**Web server:** 2.4.25-3+deb9u9

**Database:** MySQL 5.8+1.0.2

**PHP version:** 7.0.22

**Nextcloud version:** 15.0.14

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
@nickvergessen Shouldn't multiple saves of the same file by the same user be grouped in the activity app?

**Comment by kostecke** [comment]
Unfortunately they're not.

**Comment by nickvergessen** [comment]
they are combined when showing them in the web.
In the emails I don't think they are.

**Comment by kostecke** [comment]
Here's an activity e-mail I received after creating a text file and then entering 5 sets of 3 characters with varying delays between sets. After each set I waited for the auto save indicator to display.

~~~

[ Message hamradio:47550 ]
Date:    Thu, 14 May 2020 19:30:12 -0000
To:      xxxxx <...@----.net>
From:    RRRA Groupware <...@----.org>
Subject: Activity notification for RRRA Groupware

Hello xxxxx

There was some activity at http://-----.----.---/

  * You created test.txt (Today at 1:20 PM)
  * You changed test.txt (Today at 1:20 PM)
  * You changed test.txt (Today at 1:20 PM)
  * You changed test.txt (Today at 1:21 PM)
  * You changed test.txt (Today at 1:21 PM)
  * You changed test.txt (Today at 1:22 PM)

-- 
RRRA Groupware - powered by Nextcloud
This is an automatically sent email, please do not reply.

~~~

[Screenshot of file changes in the Activities App](https://cloud.rrra.org/index.php/s/Bsg2SY7fBKsSpTo)

**Comment by juliushaertl** [comment]
Then this should be addressed in the activity app, since from the text app perspective there is nothing wrong with saving regularly in my oppinion. @kostecke Mind to open an issue for that in https://github.com/nextcloud/activity/ ?
