### ISSUE TITLE
Rich workspaces not working on latest master

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/text#801]
- I cannot see/edit rich workspaces on latest server and text master
- I cannot enable/disable rich workspaces, though you said it should work https://github.com/nextcloud/server/issues/19548#issuecomment-617888516

**Comment by juliushaertl** [comment]
@tobiasKaminsky I guess this was a configuration issue with 
occ config:app:set text workspace_available being set to `0` as we talked about that earlier this week?

**Comment by tobiasKaminsky** [comment]
Correct.
I just assumed that this was a UI setting in admin, so I was confused 🙈
