### ISSUE TITLE
Links with underscores are not well formatted

### ISSUE THREAD

**Issue by fflorent** [nextcloud/text#806]
**Describe the bug**
Using Nextcloud 18.0.2, links with underscores are not well formatted.

**To Reproduce**
1. Create some markdown text
2. Open it using the text application (if I am not wrong, the one which allows collaborative live edition)
3. Insert : https://foobar.com/path_with_underscores
4. You should see this:

![image](https://user-images.githubusercontent.com/371705/80941436-b8c0f480-8de2-11ea-91d7-9025aa0b28da.png)

**Expected behavior**
 - The link should be clickable on the whole URL, not only on https://foobar.com/path
 - `with` should be surrounded by plain `_` and not put in italic

<details>

**Client details:**
 - OS: Debian Sid
 - Browser: Firefox 77.0a1
 - Device: Desktop

**Text app version:** 2.0.0 (see Nextcloud apps page)

**Nextcloud version:** 18.0.2 (see Nextcloud admin page)

</details>

**Comment by mkindred** [comment]
I have this problem with underscores in general. The only ways I've found to include a pair of underscores without having them parsed as italic markdown are:

1. Edit the .md file on my local drive (via sync) and add a backslash before each underscore, or
2. Place the text into a code block.

It'd be nice to be able to have underscore pairs (e.g. in URLs, variable names, etc) without the hassle. Not sure what enhancement to suggest, though. I'd settle for being able to edit the raw text and add backslashes.

**Comment by darkdragon-001** [comment]
Should be fixed in v1.27.1 upstream (scrumpy/tiptap#258). At least for copy/paste.

**Comment by juliushaertl** [comment]
Thanks for the pointer, the package is already up to date on master. Let me see if we can bump to that then for the maintenance releases as well.

**Comment by juliushaertl** [comment]
Stable releases 20-22 are using 1.32.1 or higher already
