### ISSUE TITLE
Editing markdown source

### ISSUE THREAD

**Issue by pico40** [nextcloud/text#815]
**Is your feature request related to a problem? Please describe.**
I like to manipulate markdown code instead of just seeing the rendered result in a WYSIWYG editor.

**Describe the solution you'd like**
I would like to have a button or tabs (like on github) to switch between a source editor and a WYSIWYG editor.

**Describe alternatives you've considered**
An alternative would be two have two completely different editors.

**Comment by juliushaertl** [comment]
Duplicate of #123 

https://github.com/nextcloud/text/issues/123#issuecomment-508723049
