### ISSUE TITLE
Enhance checkbox behavior

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/text#819]
# Current behavior

One has to explicitely use the menu button to add checkboxes.

![text](https://user-images.githubusercontent.com/4741199/81563563-b2101f80-9396-11ea-8e3d-5af9b4cc0d9e.gif)

# Wanted behavior

This can be automated, so one can focus on *typing* and does not need to make a break to hit the menu button.

| Entered Key | Display |
| --- | --- |
| <kbd>-</kbd> | `-` |
| <kbd>Space</kbd> | `- ` |
| <kbd>[</kbd> | `- [` |
| <kbd>x</kbd> | `- [x` |
| <kbd>]</kbd> | `- [x]` |
| <kbd>Space</kbd> | :ballot_box_with_check:  |

After pressing backspace, the checkbox should disappear and the markdown displayed again

| Entered Key | Display |
| --- | --- |
|  | :ballot_box_with_check:  |
| <kbd>Backspace</kbd> | `- [x]` |

Valid combinations for checkboxes are of course with leading `-` as well as `*`, the value (within the brackets) can be ` `, `x`, `X`.

This is a video that demonstrates the wanted behavior (Nextcloud Notes app `3.3.0`)

![t7h37-kcjwy](https://user-images.githubusercontent.com/4741199/81562983-f5b65980-9395-11ea-870d-89e0b495d261.gif)

cc @korelstar since i know, that he aims to use Nextcloud Text in the future for the Notes app and cc @nextcloud/designers for a great UX :slightly_smiling_face:  :rocket:

**Comment by juliushaertl** [comment]
Work in progress at https://github.com/nextcloud/text/pull/901
