### ISSUE TITLE
Android client stuck on loading Ansi Latin 1 and UTF16 .md and .txt files with German umlauts

### ISSUE THREAD

**Issue by Sharky444** [nextcloud/text#824]
I have this text with the German umlaut Letter "Ü".

```
Über test 2

abc
```

I save this text into 3 text files as ASCII/Ansi Latin 1, as UTF8, and as UTF16.

Result in Nextcloud Android client:

The Ansi latin 1 version is stuck indefinitely on loading.
The UTF8 version can be opened and edited.
The UTF16 version is stuck indefinitely on loading.

Ansi Text is still widely used, both on Windows and Linux. Any German umlaut in such text files makes the file unloadable (even for display only) in the Android client.

Compare that to the web client, where all 3 text files can be opened and edited, although the ansi latin 1 will not display correctly (UTF8 and UTF16 will display correctly).

[Umlaut_AnsiLatin1.txt](https://github.com/nextcloud/android/files/4598693/Umlaut_AnsiLatin1.txt)
[Umlaut_UTF8.txt](https://github.com/nextcloud/android/files/4598696/Umlaut_UTF8.txt)
[Umlaut_UTF16.txt](https://github.com/nextcloud/android/files/4598697/Umlaut_UTF16.txt)

**Comment by Sharky444** [comment]
Today I had an issue where the file could not be displayed immediately even after downloading it. I wanted to already give up, but then it worked. What changed in the second before was that the preview images/thumbnails generation process has completed. This may be another issue altogether (the thumbnail process blocking display and being very slow because of the German Umlaut issue).

**Comment by Sharky444** [comment]
Unfortunately after 4 months this quite serious bug is still not fixed.

**Comment by juliushaertl** [comment]
@luka-nextcloud Wanted to close? This should be fixed by #2385 as linked above ;)
