### ISSUE TITLE
Feature: Add TOC funtionalbility

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/text#825]
**Is your feature request related to a problem? Please describe.**
Long documents get crowded, need table of contents.

**Describe the solution you'd like**
Add a button to add [[TOC]], also render [[TOC]].

Note: [[TOC]] is already rendered by readme-App.

**Comment by llucax** [comment]
Related to this, a sidebar with the TOC (independently of if `[[TOC]]` is used in the document or not) to navigate through the document and to see the document's structure might be really nice.

**Comment by jancborchardt** [comment]
Hi, this is a duplicate of https://github.com/nextcloud/text/issues/107 → let’s continue there. :)
