### ISSUE TITLE
Guest name input shown too presently

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#83]
The guest name input is still shown a bit too presently and also a bit confusing without context. :)

![Guest name input](https://user-images.githubusercontent.com/925062/59934577-26bf3000-944c-11e9-8c88-7604514058a4.png)

When someone sees that, the first thought would be "What’s Olive?" :D And what happens if you press the confirm button?

Better would be to have the input field in a popover when clicking on the avatar list, with a short label above it: "Your name:"
(And in the future simply show yourself in the list with the default name and an `icon-edit` next to it, with `aria-label="Edit name"` which then shows the input field inline just like for file rename.)

**Comment by juliushaertl** [comment]
This is fixed
