### ISSUE TITLE
Editing not possible in shared folders

### ISSUE THREAD

**Issue by mvscheven** [nextcloud/text#833]
**Describe the bug**
Opening a .md file in a shared folder (with full permissions) opens the text app, but the editing toolbar is not shown and editing is not possible.
When opening a .md file in the home directory everything works as expected.

**To Reproduce**
1. Go to a shared folder
2. Create a new .md file (+ button -> New text file)
3. text app is open on the new file, but toolbar is not shown, editing is not possible.

**Expected behavior**
Editing should also be possible in shared folders, if the permissions are set accordingly.

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Version: 76.0.1

**Text app version:**
2.0.0

**Nextcloud version:**
18.0.4

** php Version **
7.2.30

**Comment by juliushaertl** [comment]
Please fill out the complete issue template, especially:

**Comment by mvscheven** [comment]
Sorry, as there are no entries in the Nextcloud log related to this action, I did not include it.

**Browser log:**
`Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/Austausch/Test.md' }) viewer.js:369:761
Opening viewer for file  /Austausch/Test.md viewer.js:347:3143
Fetching additional files... viewer.js:347:3707
The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
The escapeHTML library is deprecated! It will be removed in nextcloud 19. main.js:1082:57
The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
GEThttps://cloud.evkirche-mf.de/index.php/core/preview?fileId=4996&x=2560&y=1440&a=true
[HTTP/2 404 Not Found 562ms]

moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
recommendations 
Array []
files_sharing_tab.js:1382:7192
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 2 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 2 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
`
Do you need any further logs from the browser?

**Comment by juliushaertl** [comment]
Same here, since this was reported with quite an old version I assume this has been fixed for quite some time, therefore I'm closing this. If you still see this happening on the latest version, feel free to reopen the issue again.
