### ISSUE TITLE
Default to current folder in "Insert an image" dialog, not home

### ISSUE THREAD

**Issue by jammon** [nextcloud/text#845]
**Problem:**
When I insert an image the dialog shows the home folder and I have to click through a (maybe large) folder tree to get to my picture. The next time I insert an image I have to start in the home folder again.

**Proposed solution:**
* The "Insert an image" dialog should default to the folder of the edited document when it is first called.
* The next time the dialog is opened it should show the folder it showed the last time it had been closed.

**Comment by juliushaertl** [comment]
Makes sense, yes. That should be pretty easy to do since the filepicker function already has a path parameter https://github.com/nextcloud/server/blob/2be21fab9a449abddaf5013272a92b54e7dc6d40/core/src/OC/dialogs.js#L225

**Comment by azul** [comment]
I think i can tackle this as part of #504
