### ISSUE TITLE
There is a blank area in RichWorkspace on the share folder page

### ISSUE THREAD

**Issue by XinRoom** [nextcloud/text#848]
### Steps to reproduce
1.  share folder page: https://***/s/PGY12234
2. When there is no readme file

### Expected behaviour
When there is no readme file, no display RichWorkspace blank area.

### Actual behaviour

There is a blank area in RichWorkspace on the share folder page:
![image](https://user-images.githubusercontent.com/32238570/83213568-08ea6700-a195-11ea-96ec-a9d56c2cf4d5.png)

### Nextcloud version: (see Nextcloud admin page)
Nextcloud 18.0.4

### Where did you install Nextcloud from:
Docker Image

### Describe the solution you'd like

The reason is that this line of code exists：

https://github.com/nextcloud/text/blob/8411bb1f3dd36c75c4b2cc21bdf54a29849c70b8/src/views/RichWorkspace.vue#L164

**If you remove this line of code：**

- When there is no readme file：

![image](https://user-images.githubusercontent.com/32238570/83213753-844c1880-a195-11ea-95f1-2252334c2694.png)

- When there is readme file：

![image](https://user-images.githubusercontent.com/32238570/83213773-8d3cea00-a195-11ea-9b86-d82cc68eeee2.png)

If you change the global code:
The area here will not show:
![image](https://user-images.githubusercontent.com/32238570/83215170-df333f00-a198-11ea-9fad-fe0e5f1433e4.png)

**So Please only for `text/js/public.js` file!**

**It makes sense.**
Please test more extensively

Maybe we shouldn't just remove the code. It should be displayed when it is not 404!
https://github.com/nextcloud/text/issues/820#issuecomment-627230118

**Comment by juliushaertl** [comment]
Yes, just removing is not going to work, also this is only an issue when the folder is shared read only. See #877 for the fix
