### ISSUE TITLE
Offer Shortcuts and make them accessible via hovering

### ISSUE THREAD

**Issue by fermiongithub** [nextcloud/text#859]
Actually there's no documentation about existing shortcuts like e.g. STRG+B on a PC or CMD+B on a Mac.

I would love to see a shortcut for every markuop command, made accessible via an information which is visible while hovering over the command in the GUI.

Independent of that: Thanks for all your work Julius. Your App is so useful for me!

**Comment by juliushaertl** [comment]
This is now already the case through tooltips and the formatting help dialog

**Comment by fermiongithub** [comment]
Thanks a lot Julius! : )
