### ISSUE TITLE
make file operations accessible from text editor

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/text#870]
The discussion in #6 lead me to realize that inclusion of file management features in the text app would improve usability in a number of ways.

Currently, the user may  access  some file  information in the sidebar, but not the basic operations, such as renaming, moving, or copying, that are normally accessed using the  ellipsis icon  in the file app. 

Changing the file name especially  would seem to be a common task that is more conveniently accessible without leaving the editor to return to the file view.

**Comment by juliushaertl** [comment]
This is something that once the viewer app has implemented it in https://github.com/nextcloud/viewer/pull/15 it will automatically become available in text.
