### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by themedleb** [nextcloud/text#883]
Please add markdown table support, that's the only major feature missing that I can see.
And for the solution, I'm sorry I don't have much experience in Markdown.

**Comment by themedleb** [comment]
I did have a look at the Tiptap project which this project (Text) is based on, and found out that Tables are supported https://tiptap.scrumpy.io/tables, so I think it should be easier than starting from scratch.

Thank you for the awesome efforts.

**Comment by juliushaertl** [comment]
Duplicate of #114

**Comment by themedleb** [comment]
Oh, sorry, thank you for letting me know.
