### ISSUE TITLE
Marking/Highlighting text (yellow background color)

### ISSUE THREAD

**Issue by themedleb** [nextcloud/text#885]
**Is your feature request related to a problem? Please describe.**
Marking/Highlighting text (usually with yellow color on the background) is not supported.

**Describe the solution you'd like**
Add a class called "highlighted" to the marked/highlighted text, then style that class with yellow background using CSS.

**Comment by juliushaertl** [comment]
There is no way we can represent such a marking in markdown though the commonmark standard (https://commonmark.org/), so while we could of course allow marking in the editor, it would never be persisted in the file.

**Comment by themedleb** [comment]
Oh I see, that's unfortunate.
