### ISSUE TITLE
Editing cursor

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#90]
It should be possible to see the other editing users curser in the document.

https://github.com/scrumpy/tiptap/compare/feature/collab-cursors is a wip implementation for tiptap

**Comment by juliushaertl** [comment]
Moving to next release

**Comment by jospoortvliet** [comment]
Got the request today, and indeed if you're in a doc with a bunch of people it is nice to have.

Looking at the [link](https://github.com/scrumpy/tiptap/compare/feature/collab-cursors) it makes the cursor red, so not user dependent? Still a good start of course :rocket:

**Comment by susnux** [comment]
easy to implement using https://tiptap.dev/api/extensions/collaboration-cursor

**Comment by szaimen** [comment]
I guess this is one of the last remaining features that I really miss for collaborative editing. Sorry for adding my own opinion here 😅

**Comment by juliushaertl** [comment]
Implemented with #2971

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉
