### ISSUE TITLE
ToDo list - Add checkboxes to all selected lines

### ISSUE THREAD

**Issue by themedleb** [nextcloud/text#903]
**Describe the bug**
As the title says, checkboxes should be added to all selected lines, not just one.

**To Reproduce**
![This is what happens](https://raw.githubusercontent.com/themedleb/Uploads/master/Actual.gif)

**Expected behavior**
![This is what should happen instead](https://raw.githubusercontent.com/themedleb/Uploads/master/Supposed.gif)

<details>
<summary>Server details</summary>

**Text app version:** 3.0.1

**Nextcloud version:** 19.0.0

</details>

**Comment by susnux** [comment]
Already fixed with #1973 (master and NC24)
