### ISSUE TITLE
Color annotations for author of text

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#91]
It should be possible to see who edited which part of the document, similar to etherpad where the text has different background colors.

Limitation: Since we only store markdown in files, editor information will be lost after save once all users have left the document

**Comment by ge-fa** [comment]
Any chance of getting this implemented? Is there a Bountysource or something similar available for this? This feature is pretty important IMHO, especially compared to Etherpad etc.

Thanks for your work on Nextcloud!

**Comment by varac** [comment]
I second this, imo it's the most missing feature which hold us back migrating from etherpad.

**Comment by juliushaertl** [comment]
While I appreciate the integration work, this is not related to the issue discussion, therefore marking as spam.

**Comment by hansimausisteffiwurstbrot** [comment]
> Any chance of getting this implemented? Is there a Bountysource or something similar available for this? This feature is pretty important IMHO, especially compared to Etherpad etc

I second the importance, we'd like to get rid of etherpad.

as bountysource shouldn't be used any more but we'd like to support this feature: please contact us if financial incentives help :)
it's not much but we could offer 200 € I guess.

**Comment by juliushaertl** [comment]
Implemented with #1296 to be available during collaborative editing sessions.

**Comment by hansimausisteffiwurstbrot** [comment]
Hey,
great to hear there is an implementation!

Just to get it clear: Due to the usage of markdown files it's not possible to save the colors?

I think it would be really usefule to achieve an implementation as in Pads (like Etherpad).

Cheers!

**Comment by juliushaertl** [comment]
> Just to get it clear: Due to the usage of markdown files it's not possible to save the colors?

Yes, we have some ideas how that could still work (#1296) but this is a next step and requires a lot more effort.
