### ISSUE TITLE
Is it normal to DDoS server for sync every 5 secs ?

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/text#911]
Allow open files app (main BTW) on 100500 computers and your server is down. 
Just because periodical poll `apps/text/session/sync` for "something"

Why not to "sync" when user need it - e,g, redacting. Not so fine but better then DDoS

**Comment by juliushaertl** [comment]
The 5 second poll is intended and required for the collaborative editing feature.

As for such a high amount of users this will of course not scale on a single Nextcloud instance, so this is rather a setup related issue and I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup and scalability from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
