### ISSUE TITLE
mimetypes markdown

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/text#913]
The capabilities for Text return the mimetypes supported, now for the markdown return text/markdown but should return text/x-markdown as well.

**Comment by susnux** [comment]
Is this still valid? As there is no mimetype mapping of `text/x-markdown` in `nextcloud/server ` https://github.com/nextcloud/server/blob/master/resources/config/mimetypemapping.dist.json

**Comment by juliushaertl** [comment]
@marinofaggiana Feel free to reopen with a bit more reasoning. if this is actually necessary, but let me close this for now since we stick to what server offers.

Also text/markdown is standardised as https://www.rfc-editor.org/rfc/rfc7763
