### ISSUE TITLE
Strikethrough non-conformity

### ISSUE THREAD

**Issue by dbolton** [nextcloud/text#942]
**Describe the bug**
Nextcloud Text misinterprets single tildes (~) as strikethrough. Also mis-parses tildes followed by a space. 

**To Reproduce**
1. Select and copy the following markdown text: 
    * "Should\~ not strikethrough\~. Should \~\~strikethrough\~\~ with no visible tildes. Should\~\~ not strikethrough\~\~."
2. Open a markdown file in Nextcloud
3. Paste
4. If you don't see any visible strikethroughs, paste the text again in a paragraph below the first.

**Actual behavior**
Text formatting alternates between one of the following: 
* "Should\~ not strikethrough\~. Should \~\~strikethrough\~\~ with no visible tildes. Should\~\~ not strikethrough\~\~."
* "Should\~ not strikethrough\~. Should \~\~strikethrough\~\~ with no visible tildes. Should\~~not strikethrough~\~."

**Expected behavior**
Text formatting should look like this:
* "Should\~ not strikethrough\~. Should ~~strikethrough~~ with no visible tildes. Should~~ not strikethrough~~."

Every reference to markdown strikethroughs mentions two tildes instead of the one tilde that Nextcloud Text currently assumes. 
* Markdown guide: https://www.markdownguide.org/extended-syntax
* Wikipedia: https://en.wikipedia.org/wiki/Markdown#Example
* Github: https://guides.github.com/features/mastering-markdown/

**Client details:**
 - OS: Windows
 - Browser: Firefox (developer edition)
 - Version: 79
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 2.0.0

**Operating system:** Ubuntu

**Web server:** Nginx

**Database:** mysql 

**PHP version:** 7.2.31

**Nextcloud version:** 18.0.7

</details>

**Comment by juliushaertl** [comment]
Works as expected for me here when opening the file with the content:

![image](https://user-images.githubusercontent.com/3404133/89010786-8ce4da80-d30f-11ea-9cd4-21b66e7b7d16.png)

Now pasting markdown is currently not supported but planned in https://github.com/nextcloud/text/issues/16 as an enhancement.
