### ISSUE TITLE
Manage ManuallyLockedException and disable editing on the buffer if file is locked.

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/text#943]
The FilesLock App returns [`OCP\Lock\ManuallyLockedException`](https://github.com/nextcloud/server/blob/master/lib/public/Lock/ManuallyLockedException.php) which extends `LockedException` when the file is locked and someone else tries to update or delete the file.

The `ManuallyLockedException` contains the owner of the lock and (_should also returns_) the time until the unlock.

The idea we talked about was to do some test on the file on opening to disable any edit on the buffer because, right now, any edit on the buffer made by the non-owner will be shared and saved by the owner of the file himself.

https://github.com/nextcloud/files_lock/blob/master/lib/Storage/LockWrapper.php#L94-L98

**Comment by juliushaertl** [comment]
This is handled now with #2248
