### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/text#962]
Please implemented an API func for the dark mode, under iOS  the cursor becomes white and the background is always white.

![88482350-f73cfa00-cf60-11ea-9273-d7e80783cc1f](https://user-images.githubusercontent.com/8616947/89387792-4de5c900-d703-11ea-8bd1-93020d94feff.PNG)

**Comment by juliushaertl** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/12276

Once the prefers-color-scheme is picked up by the server properly the dark mode will apply to text automatically.
