### ISSUE TITLE
iOs cannot edit text files

### ISSUE THREAD

**Issue by brunoschroeder** [nextcloud/text#978]
This version 2.0.0 stopped working in iOs.

This means we users lost the most important reason to have NextCloud, edit text files. A notes application that syncs with vim on the desktop.

This is also described in the iOs app, but it is reason enough to roll back bogus code, please!
https://github.com/nextcloud/ios/issues/1340

**Comment by marinofaggiana** [comment]
Install on Server the Text

**Comment by juliushaertl** [comment]
Please fill out the complete issue template. I assume you mainly updated from Nextcloud 17 to 18? Which nextcloud version are you using and do you have encryption enabled (as it is stated int he ios ticket)?

**Comment by CamZie** [comment]
@juliushaertl below are the answers to your questions (similar to the iOS ticket #1340)

<details>
<summary>Server details</summary>


**Text app version:** 2.0.0

Where did you install Nextcloud from: Nextcloud website

**Operating system:** Debian 9.13 (stretch)

**Web server:** nginx 1.10.3

**Database:** MariaDB 10.1.45

**PHP version:** 7.2

**Nextcloud version:** NC 18.0.6 (updated from an older version)

**Encryption enabled:** yes

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
PHP message: [owncloud][files][3] {"Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Stream/Encryption.php","line":507,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/Encryption.php","line":302,"function":"readCache","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[]},{"function":"stream_read","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[43]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":217,"function":"stream_get_contents","args":[null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":245,"function":"file_get_contents","class":"OC\\Files\\Storage\\Wrapper\\Encryption","t" while reading response header from upstream, client: ***removed***, server: ***removed***, request: "GET /apps/files/directEditing/pPSYtD6C5Wc5sWjrzaWQFEMjJwPZeYKroSEELGkRKPSBffGYWWWWH3TRKrSFKgdQ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "***removed***"
```

</details>

**Comment by juliushaertl** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/22423
